	.org 0x070000

cells:
; cell label: obj_id map_x map_y, render routine address
; MIND THE LITTLE-ENDIANESS IN THE COORDINATES!!!111
cell_000: dl 0x1D0000, rend_000
cell_001: dl 0x1D0001, rend_001
cell_002: dl 0x1D0002, rend_002
cell_003: dl 0x1D0003, rend_003
cell_004: dl 0x1D0004, rend_004
cell_005: dl 0x1D0005, rend_005
cell_006: dl 0x1D0006, rend_006
cell_007: dl 0x1D0007, rend_007
cell_008: dl 0x1D0008, rend_008
cell_009: dl 0x1D0009, rend_009
cell_010: dl 0x1D000A, rend_010
cell_011: dl 0x1D000B, rend_011
cell_012: dl 0x1D000C, rend_012
cell_013: dl 0x1D000D, rend_013
cell_014: dl 0x1D000E, rend_014
cell_015: dl 0x0A000F, rend_015
cell_016: dl 0x1D0100, rend_016
cell_017: dl 0x0A0101, rend_017
cell_018: dl 0x110102, rend_018
cell_019: dl 0x0A0103, rend_019
cell_020: dl 0x110104, rend_020
cell_021: dl 0x0A0105, rend_021
cell_022: dl 0x110106, rend_022
cell_023: dl 0x0A0107, rend_023
cell_024: dl 0x110108, rend_024
cell_025: dl 0x0A0109, rend_025
cell_026: dl 0x11010A, rend_026
cell_027: dl 0x1D010B, rend_027
cell_028: dl 0x1D010C, rend_028
cell_029: dl 0x1D010D, rend_029
cell_030: dl 0x1D010E, rend_030
cell_031: dl 0x0A010F, rend_031
cell_032: dl 0x1D0200, rend_032
cell_033: dl 0x110201, rend_033
cell_034: dl 0x1D0202, rend_034
cell_035: dl 0x1D0203, rend_035
cell_036: dl 0x1D0204, rend_036
cell_037: dl 0x1D0205, rend_037
cell_038: dl 0x1D0206, rend_038
cell_039: dl 0x1D0207, rend_039
cell_040: dl 0x1D0208, rend_040
cell_041: dl 0x1D0209, rend_041
cell_042: dl 0x0A020A, rend_042
cell_043: dl 0x1D020B, rend_043
cell_044: dl 0x1D020C, rend_044
cell_045: dl 0x1D020D, rend_045
cell_046: dl 0x1D020E, rend_046
cell_047: dl 0x0A020F, rend_047
cell_048: dl 0x1D0300, rend_048
cell_049: dl 0x390301, rend_049
cell_050: dl 0x1D0302, rend_050
cell_051: dl 0x1D0303, rend_051
cell_052: dl 0x1D0304, rend_052
cell_053: dl 0x1D0305, rend_053
cell_054: dl 0x1D0306, rend_054
cell_055: dl 0x1D0307, rend_055
cell_056: dl 0x1D0308, rend_056
cell_057: dl 0x1D0309, rend_057
cell_058: dl 0x11030A, rend_058
cell_059: dl 0x1D030B, rend_059
cell_060: dl 0x1D030C, rend_060
cell_061: dl 0x1D030D, rend_061
cell_062: dl 0x1D030E, rend_062
cell_063: dl 0x0A030F, rend_063
cell_064: dl 0x1D0400, rend_064
cell_065: dl 0x110401, rend_065
cell_066: dl 0x1D0402, rend_066
cell_067: dl 0x1D0403, rend_067
cell_068: dl 0x1D0404, rend_068
cell_069: dl 0x0C0405, rend_069
cell_070: dl 0x0A0406, rend_070
cell_071: dl 0x0F0407, rend_071
cell_072: dl 0x1D0408, rend_072
cell_073: dl 0x1D0409, rend_073
cell_074: dl 0x0A040A, rend_074
cell_075: dl 0x1D040B, rend_075
cell_076: dl 0x1D040C, rend_076
cell_077: dl 0x1D040D, rend_077
cell_078: dl 0x1D040E, rend_078
cell_079: dl 0x0A040F, rend_079
cell_080: dl 0x1D0500, rend_080
cell_081: dl 0x0A0501, rend_081
cell_082: dl 0x1D0502, rend_082
cell_083: dl 0x1D0503, rend_083
cell_084: dl 0x1D0504, rend_084
cell_085: dl 0x1D0505, rend_085
cell_086: dl 0x1D0506, rend_086
cell_087: dl 0x1D0507, rend_087
cell_088: dl 0x1D0508, rend_088
cell_089: dl 0x1D0509, rend_089
cell_090: dl 0x11050A, rend_090
cell_091: dl 0x1D050B, rend_091
cell_092: dl 0x1D050C, rend_092
cell_093: dl 0x1D050D, rend_093
cell_094: dl 0x1D050E, rend_094
cell_095: dl 0x0A050F, rend_095
cell_096: dl 0x1D0600, rend_096
cell_097: dl 0x110601, rend_097
cell_098: dl 0x1D0602, rend_098
cell_099: dl 0x1D0603, rend_099
cell_100: dl 0x1D0604, rend_100
cell_101: dl 0x1D0605, rend_101
cell_102: dl 0x1D0606, rend_102
cell_103: dl 0x1D0607, rend_103
cell_104: dl 0x1D0608, rend_104
cell_105: dl 0x1D0609, rend_105
cell_106: dl 0x0A060A, rend_106
cell_107: dl 0x1D060B, rend_107
cell_108: dl 0x1D060C, rend_108
cell_109: dl 0x1D060D, rend_109
cell_110: dl 0x1D060E, rend_110
cell_111: dl 0x0A060F, rend_111
cell_112: dl 0x1D0700, rend_112
cell_113: dl 0x0A0701, rend_113
cell_114: dl 0x1D0702, rend_114
cell_115: dl 0x1D0703, rend_115
cell_116: dl 0x110704, rend_116
cell_117: dl 0x0A0705, rend_117
cell_118: dl 0x110706, rend_118
cell_119: dl 0x390707, rend_119
cell_120: dl 0x110708, rend_120
cell_121: dl 0x0A0709, rend_121
cell_122: dl 0x11070A, rend_122
cell_123: dl 0x1D070B, rend_123
cell_124: dl 0x1D070C, rend_124
cell_125: dl 0x1D070D, rend_125
cell_126: dl 0x1D070E, rend_126
cell_127: dl 0x0A070F, rend_127
cell_128: dl 0x1D0800, rend_128
cell_129: dl 0x110801, rend_129
cell_130: dl 0x3B0802, rend_130
cell_131: dl 0x110803, rend_131
cell_132: dl 0x0A0804, rend_132
cell_133: dl 0x1D0805, rend_133
cell_134: dl 0x1D0806, rend_134
cell_135: dl 0x1D0807, rend_135
cell_136: dl 0x1D0808, rend_136
cell_137: dl 0x1D0809, rend_137
cell_138: dl 0x0A080A, rend_138
cell_139: dl 0x1D080B, rend_139
cell_140: dl 0x1D080C, rend_140
cell_141: dl 0x1D080D, rend_141
cell_142: dl 0x1D080E, rend_142
cell_143: dl 0x0A080F, rend_143
cell_144: dl 0x1D0900, rend_144
cell_145: dl 0x0E0901, rend_145
cell_146: dl 0x1D0902, rend_146
cell_147: dl 0x0E0903, rend_147
cell_148: dl 0x110904, rend_148
cell_149: dl 0x1D0905, rend_149
cell_150: dl 0x1D0906, rend_150
cell_151: dl 0x1D0907, rend_151
cell_152: dl 0x1D0908, rend_152
cell_153: dl 0x1D0909, rend_153
cell_154: dl 0x11090A, rend_154
cell_155: dl 0x1D090B, rend_155
cell_156: dl 0x1D090C, rend_156
cell_157: dl 0x1D090D, rend_157
cell_158: dl 0x1D090E, rend_158
cell_159: dl 0x0A090F, rend_159
cell_160: dl 0x1D0A00, rend_160
cell_161: dl 0x0E0A01, rend_161
cell_162: dl 0x1D0A02, rend_162
cell_163: dl 0x0E0A03, rend_163
cell_164: dl 0x100A04, rend_164
cell_165: dl 0x1D0A05, rend_165
cell_166: dl 0x1D0A06, rend_166
cell_167: dl 0x1D0A07, rend_167
cell_168: dl 0x1D0A08, rend_168
cell_169: dl 0x1D0A09, rend_169
cell_170: dl 0x0C0A0A, rend_170
cell_171: dl 0x110A0B, rend_171
cell_172: dl 0x0A0A0C, rend_172
cell_173: dl 0x110A0D, rend_173
cell_174: dl 0x0A0A0E, rend_174
cell_175: dl 0x0A0A0F, rend_175
cell_176: dl 0x1D0B00, rend_176
cell_177: dl 0x0E0B01, rend_177
cell_178: dl 0x3A0B02, rend_178
cell_179: dl 0x0E0B03, rend_179
cell_180: dl 0x110B04, rend_180
cell_181: dl 0x1D0B05, rend_181
cell_182: dl 0x1D0B06, rend_182
cell_183: dl 0x1D0B07, rend_183
cell_184: dl 0x1D0B08, rend_184
cell_185: dl 0x1D0B09, rend_185
cell_186: dl 0x110B0A, rend_186
cell_187: dl 0x0B0B0B, rend_187
cell_188: dl 0x0A0B0C, rend_188
cell_189: dl 0x0B0B0D, rend_189
cell_190: dl 0x0A0B0E, rend_190
cell_191: dl 0x0A0B0F, rend_191
cell_192: dl 0x1D0C00, rend_192
cell_193: dl 0x0E0C01, rend_193
cell_194: dl 0x0E0C02, rend_194
cell_195: dl 0x0E0C03, rend_195
cell_196: dl 0x0A0C04, rend_196
cell_197: dl 0x1D0C05, rend_197
cell_198: dl 0x1D0C06, rend_198
cell_199: dl 0x1D0C07, rend_199
cell_200: dl 0x1D0C08, rend_200
cell_201: dl 0x1D0C09, rend_201
cell_202: dl 0x390C0A, rend_202
cell_203: dl 0x1D0C0B, rend_203
cell_204: dl 0x1D0C0C, rend_204
cell_205: dl 0x1D0C0D, rend_205
cell_206: dl 0x1D0C0E, rend_206
cell_207: dl 0x0A0C0F, rend_207
cell_208: dl 0x1D0D00, rend_208
cell_209: dl 0x0D0D01, rend_209
cell_210: dl 0x110D02, rend_210
cell_211: dl 0x0D0D03, rend_211
cell_212: dl 0x110D04, rend_212
cell_213: dl 0x0A0D05, rend_213
cell_214: dl 0x110D06, rend_214
cell_215: dl 0x0F0D07, rend_215
cell_216: dl 0x110D08, rend_216
cell_217: dl 0x0A0D09, rend_217
cell_218: dl 0x110D0A, rend_218
cell_219: dl 0x1D0D0B, rend_219
cell_220: dl 0x1D0D0C, rend_220
cell_221: dl 0x1D0D0D, rend_221
cell_222: dl 0x1D0D0E, rend_222
cell_223: dl 0x0A0D0F, rend_223
cell_224: dl 0x1D0E00, rend_224
cell_225: dl 0x1D0E01, rend_225
cell_226: dl 0x1D0E02, rend_226
cell_227: dl 0x1D0E03, rend_227
cell_228: dl 0x1D0E04, rend_228
cell_229: dl 0x1D0E05, rend_229
cell_230: dl 0x1D0E06, rend_230
cell_231: dl 0x1D0E07, rend_231
cell_232: dl 0x1D0E08, rend_232
cell_233: dl 0x0A0E09, rend_233
cell_234: dl 0x0B0E0A, rend_234
cell_235: dl 0x1D0E0B, rend_235
cell_236: dl 0x1D0E0C, rend_236
cell_237: dl 0x1D0E0D, rend_237
cell_238: dl 0x1D0E0E, rend_238
cell_239: dl 0x0A0E0F, rend_239
cell_240: dl 0x0A0F00, rend_240
cell_241: dl 0x0A0F01, rend_241
cell_242: dl 0x0A0F02, rend_242
cell_243: dl 0x0A0F03, rend_243
cell_244: dl 0x0A0F04, rend_244
cell_245: dl 0x0A0F05, rend_245
cell_246: dl 0x0A0F06, rend_246
cell_247: dl 0x0A0F07, rend_247
cell_248: dl 0x0A0F08, rend_248
cell_249: dl 0x0A0F09, rend_249
cell_250: dl 0x0A0F0A, rend_250
cell_251: dl 0x0A0F0B, rend_251
cell_252: dl 0x0A0F0C, rend_252
cell_253: dl 0x0A0F0D, rend_253
cell_254: dl 0x0A0F0E, rend_254
cell_255: dl 0x0A0F0F, rend_255


rend_000: dl rend_000_0,rend_000_1,rend_000_2,rend_000_3
rend_000_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_000_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_000_2:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01D4 ; BUF_57_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_000_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_001: dl rend_001_0,rend_001_1,rend_001_2,rend_001_3
rend_001_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_001_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_001_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_001_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_002: dl rend_002_0,rend_002_1,rend_002_2,rend_002_3
rend_002_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_002_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_002_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_002_3:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_003: dl rend_003_0,rend_003_1,rend_003_2,rend_003_3
rend_003_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_003_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_003_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_003_3:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_004: dl rend_004_0,rend_004_1,rend_004_2,rend_004_3
rend_004_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_004_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_004_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_004_3:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_005: dl rend_005_0,rend_005_1,rend_005_2,rend_005_3
rend_005_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_005_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_005_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_005_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_006: dl rend_006_0,rend_006_1,rend_006_2,rend_006_3
rend_006_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_006_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_006_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_006_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_007: dl rend_007_0,rend_007_1,rend_007_2,rend_007_3
rend_007_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_007_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_007_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_007_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_008: dl rend_008_0,rend_008_1,rend_008_2,rend_008_3
rend_008_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_008_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_008_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_008_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_009: dl rend_009_0,rend_009_1,rend_009_2,rend_009_3
rend_009_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_009_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_009_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_009_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_010: dl rend_010_0,rend_010_1,rend_010_2,rend_010_3
rend_010_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_010_1:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x080100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_010_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_010_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_011: dl rend_011_0,rend_011_1,rend_011_2,rend_011_3
rend_011_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_011_1:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_011_2:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_011_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_012: dl rend_012_0,rend_012_1,rend_012_2,rend_012_3
rend_012_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_012_1:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_012_2:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_012_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_013: dl rend_013_0,rend_013_1,rend_013_2,rend_013_3
rend_013_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_013_1:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_013_2:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_013_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_014: dl rend_014_0,rend_014_1,rend_014_2,rend_014_3
rend_014_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_014_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_014_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_014_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_015: dl rend_015_0,rend_015_1,rend_015_2,rend_015_3
rend_015_0:
	jp render_scene_return
rend_015_1:
	jp render_scene_return
rend_015_2:
	jp render_scene_return
rend_015_3:
	jp render_scene_return

rend_016: dl rend_016_0,rend_016_1,rend_016_2,rend_016_3
rend_016_0:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_016_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_016_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_016_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_017: dl rend_017_0,rend_017_1,rend_017_2,rend_017_3
rend_017_0:
	jp render_scene_return
rend_017_1:
	jp render_scene_return
rend_017_2:
	jp render_scene_return
rend_017_3:
	jp render_scene_return

rend_018: dl rend_018_0,rend_018_1,rend_018_2,rend_018_3
rend_018_0:
	jp render_scene_return
rend_018_1:
	jp render_scene_return
rend_018_2:
	jp render_scene_return
rend_018_3:
	jp render_scene_return

rend_019: dl rend_019_0,rend_019_1,rend_019_2,rend_019_3
rend_019_0:
	jp render_scene_return
rend_019_1:
	jp render_scene_return
rend_019_2:
	jp render_scene_return
rend_019_3:
	jp render_scene_return

rend_020: dl rend_020_0,rend_020_1,rend_020_2,rend_020_3
rend_020_0:
	jp render_scene_return
rend_020_1:
	jp render_scene_return
rend_020_2:
	jp render_scene_return
rend_020_3:
	jp render_scene_return

rend_021: dl rend_021_0,rend_021_1,rend_021_2,rend_021_3
rend_021_0:
	jp render_scene_return
rend_021_1:
	jp render_scene_return
rend_021_2:
	jp render_scene_return
rend_021_3:
	jp render_scene_return

rend_022: dl rend_022_0,rend_022_1,rend_022_2,rend_022_3
rend_022_0:
	jp render_scene_return
rend_022_1:
	jp render_scene_return
rend_022_2:
	jp render_scene_return
rend_022_3:
	jp render_scene_return

rend_023: dl rend_023_0,rend_023_1,rend_023_2,rend_023_3
rend_023_0:
	jp render_scene_return
rend_023_1:
	jp render_scene_return
rend_023_2:
	jp render_scene_return
rend_023_3:
	jp render_scene_return

rend_024: dl rend_024_0,rend_024_1,rend_024_2,rend_024_3
rend_024_0:
	jp render_scene_return
rend_024_1:
	jp render_scene_return
rend_024_2:
	jp render_scene_return
rend_024_3:
	jp render_scene_return

rend_025: dl rend_025_0,rend_025_1,rend_025_2,rend_025_3
rend_025_0:
	jp render_scene_return
rend_025_1:
	jp render_scene_return
rend_025_2:
	jp render_scene_return
rend_025_3:
	jp render_scene_return

rend_026: dl rend_026_0,rend_026_1,rend_026_2,rend_026_3
rend_026_0:
	jp render_scene_return
rend_026_1:
	jp render_scene_return
rend_026_2:
	jp render_scene_return
rend_026_3:
	jp render_scene_return

rend_027: dl rend_027_0,rend_027_1,rend_027_2,rend_027_3
rend_027_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_027_1:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_027_2:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_027_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_028: dl rend_028_0,rend_028_1,rend_028_2,rend_028_3
rend_028_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_028_1:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_028_2:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_028_3:
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_029: dl rend_029_0,rend_029_1,rend_029_2,rend_029_3
rend_029_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_029_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_029_2:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_029_3:
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return

rend_030: dl rend_030_0,rend_030_1,rend_030_2,rend_030_3
rend_030_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_030_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_030_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1001B7 ; BUF_17_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_030_3:
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return

rend_031: dl rend_031_0,rend_031_1,rend_031_2,rend_031_3
rend_031_0:
	jp render_scene_return
rend_031_1:
	jp render_scene_return
rend_031_2:
	jp render_scene_return
rend_031_3:
	jp render_scene_return

rend_032: dl rend_032_0,rend_032_1,rend_032_2,rend_032_3
rend_032_0:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_032_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_032_2:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_032_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_033: dl rend_033_0,rend_033_1,rend_033_2,rend_033_3
rend_033_0:
	jp render_scene_return
rend_033_1:
	jp render_scene_return
rend_033_2:
	jp render_scene_return
rend_033_3:
	jp render_scene_return

rend_034: dl rend_034_0,rend_034_1,rend_034_2,rend_034_3
rend_034_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_034_1:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1C0140 ; BUF_12_028
	call render_panel
	ld hl,0x220142 ; BUF_12_032
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_034_2:
	ld hl,0x0001AF ; BUF_17_004
	call render_panel
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B01DF ; BUF_57_043
	call render_panel
	jp render_scene_return
rend_034_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_035: dl rend_035_0,rend_035_1,rend_035_2,rend_035_3
rend_035_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_035_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0E0183 ; BUF_15_014
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x260146 ; BUF_12_038
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_035_2:
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x230143 ; BUF_12_035
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_035_3:
	ld hl,0x2701DD ; BUF_57_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_036: dl rend_036_0,rend_036_1,rend_036_2,rend_036_3
rend_036_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_036_1:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1C018B ; BUF_15_028
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_036_2:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x240144 ; BUF_12_036
	call render_panel
	ld hl,0x270147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_036_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F01D8 ; BUF_57_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_037: dl rend_037_0,rend_037_1,rend_037_2,rend_037_3
rend_037_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_037_1:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x260191 ; BUF_15_038
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_037_2:
	ld hl,0x1001B7 ; BUF_17_016
	call render_panel
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_037_3:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x1301D1 ; BUF_57_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_038: dl rend_038_0,rend_038_1,rend_038_2,rend_038_3
rend_038_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_038_1:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_038_2:
	ld hl,0x270192 ; BUF_15_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_038_3:
	ld hl,0x0001AF ; BUF_17_004
	call render_panel
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x0301C8 ; BUF_57_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_039: dl rend_039_0,rend_039_1,rend_039_2,rend_039_3
rend_039_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_039_1:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_039_2:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x280192 ; BUF_15_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_039_3:
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x230143 ; BUF_12_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_040: dl rend_040_0,rend_040_1,rend_040_2,rend_040_3
rend_040_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_040_1:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_040_2:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0501C8 ; BUF_57_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x250190 ; BUF_15_037
	call render_panel
	ld hl,0x290192 ; BUF_15_040
	call render_panel
	jp render_scene_return
rend_040_3:
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x19013D ; BUF_12_025
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_041: dl rend_041_0,rend_041_1,rend_041_2,rend_041_3
rend_041_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_041_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_041_2:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0601C8 ; BUF_57_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x260191 ; BUF_15_038
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_041_3:
	ld hl,0x0B0135 ; BUF_12_011
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x23018E ; BUF_15_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_042: dl rend_042_0,rend_042_1,rend_042_2,rend_042_3
rend_042_0:
	jp render_scene_return
rend_042_1:
	jp render_scene_return
rend_042_2:
	jp render_scene_return
rend_042_3:
	jp render_scene_return

rend_043: dl rend_043_0,rend_043_1,rend_043_2,rend_043_3
rend_043_0:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_043_1:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	jp render_scene_return
rend_043_2:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_043_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_044: dl rend_044_0,rend_044_1,rend_044_2,rend_044_3
rend_044_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_044_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_044_2:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_044_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_045: dl rend_045_0,rend_045_1,rend_045_2,rend_045_3
rend_045_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_045_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_045_2:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_045_3:
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	jp render_scene_return

rend_046: dl rend_046_0,rend_046_1,rend_046_2,rend_046_3
rend_046_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_046_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_046_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_046_3:
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return

rend_047: dl rend_047_0,rend_047_1,rend_047_2,rend_047_3
rend_047_0:
	jp render_scene_return
rend_047_1:
	jp render_scene_return
rend_047_2:
	jp render_scene_return
rend_047_3:
	jp render_scene_return

rend_048: dl rend_048_0,rend_048_1,rend_048_2,rend_048_3
rend_048_0:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_048_1:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return
rend_048_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_048_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_049: dl rend_049_0,rend_049_1,rend_049_2,rend_049_3
rend_049_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_049_1:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0D0137 ; BUF_12_013
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x15013B ; BUF_12_020
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_049_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_049_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_050: dl rend_050_0,rend_050_1,rend_050_2,rend_050_3
rend_050_0:
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_050_1:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1001B7 ; BUF_17_016
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1B013F ; BUF_12_027
	call render_panel
	ld hl,0x210142 ; BUF_12_032
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_050_2:
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x0401FA ; BUF_59_004
	call render_panel
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_050_3:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return

rend_051: dl rend_051_0,rend_051_1,rend_051_2,rend_051_3
rend_051_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_051_1:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0D0182 ; BUF_15_013
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x250145 ; BUF_12_037
	call render_panel
	ld hl,0x290147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_051_2:
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0501FA ; BUF_59_004
	call render_panel
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_051_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801DD ; BUF_57_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_052: dl rend_052_0,rend_052_1,rend_052_2,rend_052_3
rend_052_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_052_1:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1B018A ; BUF_15_027
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0149 ; BUF_12_043
	call render_panel
	jp render_scene_return
rend_052_2:
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0601FA ; BUF_59_004
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x2A0148 ; BUF_12_042
	call render_panel
	jp render_scene_return
rend_052_3:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2001D8 ; BUF_57_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return

rend_053: dl rend_053_0,rend_053_1,rend_053_2,rend_053_3
rend_053_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_053_1:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x250190 ; BUF_15_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_053_2:
	ld hl,0x2C014A ; BUF_12_044
	call render_panel
	jp render_scene_return
rend_053_3:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1401D1 ; BUF_57_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return

rend_054: dl rend_054_0,rend_054_1,rend_054_2,rend_054_3
rend_054_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_054_1:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x2B0194 ; BUF_15_043
	call render_panel
	jp render_scene_return
rend_054_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_054_3:
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x0401C8 ; BUF_57_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	ld hl,0x2A0148 ; BUF_12_042
	call render_panel
	jp render_scene_return

rend_055: dl rend_055_0,rend_055_1,rend_055_2,rend_055_3
rend_055_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_055_1:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_055_2:
	ld hl,0x2C0195 ; BUF_15_044
	call render_panel
	jp render_scene_return
rend_055_3:
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x240144 ; BUF_12_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_056: dl rend_056_0,rend_056_1,rend_056_2,rend_056_3
rend_056_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_056_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_056_2:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1501D1 ; BUF_57_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x2B0194 ; BUF_15_043
	call render_panel
	jp render_scene_return
rend_056_3:
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x1A013E ; BUF_12_026
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	ld hl,0x2A0193 ; BUF_15_042
	call render_panel
	jp render_scene_return

rend_057: dl rend_057_0,rend_057_1,rend_057_2,rend_057_3
rend_057_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_057_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_057_2:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1601D1 ; BUF_57_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_057_3:
	ld hl,0x0C0136 ; BUF_12_012
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x24018F ; BUF_15_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x270192 ; BUF_15_040
	call render_panel
	jp render_scene_return

rend_058: dl rend_058_0,rend_058_1,rend_058_2,rend_058_3
rend_058_0:
	jp render_scene_return
rend_058_1:
	jp render_scene_return
rend_058_2:
	jp render_scene_return
rend_058_3:
	jp render_scene_return

rend_059: dl rend_059_0,rend_059_1,rend_059_2,rend_059_3
rend_059_0:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_059_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	jp render_scene_return
rend_059_2:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_059_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_060: dl rend_060_0,rend_060_1,rend_060_2,rend_060_3
rend_060_0:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_060_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_060_2:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_060_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_061: dl rend_061_0,rend_061_1,rend_061_2,rend_061_3
rend_061_0:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_061_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_061_2:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_061_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	jp render_scene_return

rend_062: dl rend_062_0,rend_062_1,rend_062_2,rend_062_3
rend_062_0:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_062_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_062_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1001B7 ; BUF_17_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_062_3:
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	jp render_scene_return

rend_063: dl rend_063_0,rend_063_1,rend_063_2,rend_063_3
rend_063_0:
	jp render_scene_return
rend_063_1:
	jp render_scene_return
rend_063_2:
	jp render_scene_return
rend_063_3:
	jp render_scene_return

rend_064: dl rend_064_0,rend_064_1,rend_064_2,rend_064_3
rend_064_0:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01DF ; BUF_57_043
	call render_panel
	jp render_scene_return
rend_064_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_064_2:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_064_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_065: dl rend_065_0,rend_065_1,rend_065_2,rend_065_3
rend_065_0:
	jp render_scene_return
rend_065_1:
	jp render_scene_return
rend_065_2:
	jp render_scene_return
rend_065_3:
	jp render_scene_return

rend_066: dl rend_066_0,rend_066_1,rend_066_2,rend_066_3
rend_066_0:
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	jp render_scene_return
rend_066_1:
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x200142 ; BUF_12_032
	call render_panel
	jp render_scene_return
rend_066_2:
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140203 ; BUF_59_020
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_066_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_067: dl rend_067_0,rend_067_1,rend_067_2,rend_067_3
rend_067_0:
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_067_1:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0F01CF ; BUF_57_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x280147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_067_2:
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150203 ; BUF_59_020
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_067_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901DD ; BUF_57_040
	call render_panel
	jp render_scene_return

rend_068: dl rend_068_0,rend_068_1,rend_068_2,rend_068_3
rend_068_0:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	jp render_scene_return
rend_068_1:
	ld hl,0x2C014A ; BUF_12_044
	call render_panel
	jp render_scene_return
rend_068_2:
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160203 ; BUF_59_020
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	jp render_scene_return
rend_068_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101D8 ; BUF_57_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	jp render_scene_return

rend_069: dl rend_069_0,rend_069_1,rend_069_2,rend_069_3
rend_069_0:
	jp render_scene_return
rend_069_1:
	jp render_scene_return
rend_069_2:
	jp render_scene_return
rend_069_3:
	jp render_scene_return

rend_070: dl rend_070_0,rend_070_1,rend_070_2,rend_070_3
rend_070_0:
	jp render_scene_return
rend_070_1:
	jp render_scene_return
rend_070_2:
	jp render_scene_return
rend_070_3:
	jp render_scene_return

rend_071: dl rend_071_0,rend_071_1,rend_071_2,rend_071_3
rend_071_0:
	jp render_scene_return
rend_071_1:
	jp render_scene_return
rend_071_2:
	jp render_scene_return
rend_071_3:
	jp render_scene_return

rend_072: dl rend_072_0,rend_072_1,rend_072_2,rend_072_3
rend_072_0:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_072_1:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_072_2:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101D8 ; BUF_57_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_072_3:
	ld hl,0x2C0195 ; BUF_15_044
	call render_panel
	jp render_scene_return

rend_073: dl rend_073_0,rend_073_1,rend_073_2,rend_073_3
rend_073_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_073_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_073_2:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201D8 ; BUF_57_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_073_3:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x280192 ; BUF_15_040
	call render_panel
	jp render_scene_return

rend_074: dl rend_074_0,rend_074_1,rend_074_2,rend_074_3
rend_074_0:
	jp render_scene_return
rend_074_1:
	jp render_scene_return
rend_074_2:
	jp render_scene_return
rend_074_3:
	jp render_scene_return

rend_075: dl rend_075_0,rend_075_1,rend_075_2,rend_075_3
rend_075_0:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_075_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	jp render_scene_return
rend_075_2:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_075_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_076: dl rend_076_0,rend_076_1,rend_076_2,rend_076_3
rend_076_0:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_076_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_076_2:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_076_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_077: dl rend_077_0,rend_077_1,rend_077_2,rend_077_3
rend_077_0:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_077_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_077_2:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_077_3:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return

rend_078: dl rend_078_0,rend_078_1,rend_078_2,rend_078_3
rend_078_0:
	ld hl,0x000100 ; BUF_10_004
	call render_panel
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_078_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_078_2:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_078_3:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	jp render_scene_return

rend_079: dl rend_079_0,rend_079_1,rend_079_2,rend_079_3
rend_079_0:
	jp render_scene_return
rend_079_1:
	jp render_scene_return
rend_079_2:
	jp render_scene_return
rend_079_3:
	jp render_scene_return

rend_080: dl rend_080_0,rend_080_1,rend_080_2,rend_080_3
rend_080_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501DB ; BUF_57_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_080_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_080_2:
	ld hl,0x0C0168 ; BUF_14_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_080_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_081: dl rend_081_0,rend_081_1,rend_081_2,rend_081_3
rend_081_0:
	jp render_scene_return
rend_081_1:
	jp render_scene_return
rend_081_2:
	jp render_scene_return
rend_081_3:
	jp render_scene_return

rend_082: dl rend_082_0,rend_082_1,rend_082_2,rend_082_3
rend_082_0:
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_082_1:
	ld hl,0x0901B0 ; BUF_17_009
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x1A013E ; BUF_12_026
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x1F0142 ; BUF_12_032
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_082_2:
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x20020A ; BUF_59_032
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_082_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_083: dl rend_083_0,rend_083_1,rend_083_2,rend_083_3
rend_083_0:
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x2301D9 ; BUF_57_035
	call render_panel
	jp render_scene_return
rend_083_1:
	ld hl,0x0C0181 ; BUF_15_012
	call render_panel
	ld hl,0x0E01CE ; BUF_57_014
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x240144 ; BUF_12_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x270147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_083_2:
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x21020A ; BUF_59_032
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_083_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_084: dl rend_084_0,rend_084_1,rend_084_2,rend_084_3
rend_084_0:
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x2B0149 ; BUF_12_043
	call render_panel
	jp render_scene_return
rend_084_1:
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x1A0189 ; BUF_15_026
	call render_panel
	ld hl,0x1C01D6 ; BUF_57_028
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	ld hl,0x2A0148 ; BUF_12_042
	call render_panel
	jp render_scene_return
rend_084_2:
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x22020A ; BUF_59_032
	call render_panel
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_084_3:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201D8 ; BUF_57_032
	call render_panel
	jp render_scene_return

rend_085: dl rend_085_0,rend_085_1,rend_085_2,rend_085_3
rend_085_0:
	ld hl,0x2C014A ; BUF_12_044
	call render_panel
	jp render_scene_return
rend_085_1:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x24018F ; BUF_15_036
	call render_panel
	ld hl,0x2601DC ; BUF_57_038
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_085_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_085_3:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1601D1 ; BUF_57_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x180204 ; BUF_59_024
	call render_panel
	jp render_scene_return

rend_086: dl rend_086_0,rend_086_1,rend_086_2,rend_086_3
rend_086_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_086_1:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	ld hl,0x2A0193 ; BUF_15_042
	call render_panel
	jp render_scene_return
rend_086_2:
	ld hl,0x2701DD ; BUF_57_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_086_3:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0A01FC ; BUF_59_010
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x2B0149 ; BUF_12_043
	call render_panel
	jp render_scene_return

rend_087: dl rend_087_0,rend_087_1,rend_087_2,rend_087_3
rend_087_0:
	ld hl,0x2C0195 ; BUF_15_044
	call render_panel
	jp render_scene_return
rend_087_1:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_087_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801DD ; BUF_57_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_087_3:
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x250145 ; BUF_12_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_088: dl rend_088_0,rend_088_1,rend_088_2,rend_088_3
rend_088_0:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	ld hl,0x2A0193 ; BUF_15_042
	call render_panel
	jp render_scene_return
rend_088_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_088_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901DD ; BUF_57_040
	call render_panel
	jp render_scene_return
rend_088_3:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1B013F ; BUF_12_027
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0194 ; BUF_15_043
	call render_panel
	jp render_scene_return

rend_089: dl rend_089_0,rend_089_1,rend_089_2,rend_089_3
rend_089_0:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_089_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_089_2:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_089_3:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0D0137 ; BUF_12_013
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2301D9 ; BUF_57_035
	call render_panel
	ld hl,0x250190 ; BUF_15_037
	call render_panel
	ld hl,0x290192 ; BUF_15_040
	call render_panel
	jp render_scene_return

rend_090: dl rend_090_0,rend_090_1,rend_090_2,rend_090_3
rend_090_0:
	jp render_scene_return
rend_090_1:
	jp render_scene_return
rend_090_2:
	jp render_scene_return
rend_090_3:
	jp render_scene_return

rend_091: dl rend_091_0,rend_091_1,rend_091_2,rend_091_3
rend_091_0:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_091_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	jp render_scene_return
rend_091_2:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_091_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_092: dl rend_092_0,rend_092_1,rend_092_2,rend_092_3
rend_092_0:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_092_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_092_2:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E01B5 ; BUF_17_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_092_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_093: dl rend_093_0,rend_093_1,rend_093_2,rend_093_3
rend_093_0:
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_093_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_093_2:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_093_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	jp render_scene_return

rend_094: dl rend_094_0,rend_094_1,rend_094_2,rend_094_3
rend_094_0:
	ld hl,0x0901B0 ; BUF_17_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_094_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_094_2:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1001B7 ; BUF_17_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_094_3:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	jp render_scene_return

rend_095: dl rend_095_0,rend_095_1,rend_095_2,rend_095_3
rend_095_0:
	jp render_scene_return
rend_095_1:
	jp render_scene_return
rend_095_2:
	jp render_scene_return
rend_095_3:
	jp render_scene_return

rend_096: dl rend_096_0,rend_096_1,rend_096_2,rend_096_3
rend_096_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01D5 ; BUF_57_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_096_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_096_2:
	ld hl,0x0C0168 ; BUF_14_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0170 ; BUF_14_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_096_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_097: dl rend_097_0,rend_097_1,rend_097_2,rend_097_3
rend_097_0:
	jp render_scene_return
rend_097_1:
	jp render_scene_return
rend_097_2:
	jp render_scene_return
rend_097_3:
	jp render_scene_return

rend_098: dl rend_098_0,rend_098_1,rend_098_2,rend_098_3
rend_098_0:
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x0801AF ; BUF_17_004
	call render_panel
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x1A01D4 ; BUF_57_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_098_1:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x19013D ; BUF_12_025
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x1E0142 ; BUF_12_032
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_098_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x28020F ; BUF_59_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_098_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_099: dl rend_099_0,rend_099_1,rend_099_2,rend_099_3
rend_099_0:
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x1901D3 ; BUF_57_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	ld hl,0x260146 ; BUF_12_038
	call render_panel
	jp render_scene_return
rend_099_1:
	ld hl,0x0B0180 ; BUF_15_011
	call render_panel
	ld hl,0x0D01CD ; BUF_57_013
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x230143 ; BUF_12_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_099_2:
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x29020F ; BUF_59_040
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_099_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_100: dl rend_100_0,rend_100_1,rend_100_2,rend_100_3
rend_100_0:
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x1801D2 ; BUF_57_024
	call render_panel
	ld hl,0x250145 ; BUF_12_037
	call render_panel
	ld hl,0x290147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_100_1:
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x190188 ; BUF_15_025
	call render_panel
	ld hl,0x1B01D5 ; BUF_57_027
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_100_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_100_3:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x23020B ; BUF_59_035
	call render_panel
	jp render_scene_return

rend_101: dl rend_101_0,rend_101_1,rend_101_2,rend_101_3
rend_101_0:
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0901B0 ; BUF_17_009
	call render_panel
	ld hl,0x280147 ; BUF_12_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_101_1:
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x23018E ; BUF_15_035
	call render_panel
	ld hl,0x2501DB ; BUF_57_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_101_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_101_3:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x1701D1 ; BUF_57_020
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_102: dl rend_102_0,rend_102_1,rend_102_2,rend_102_3
rend_102_0:
	ld hl,0x270147 ; BUF_12_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290192 ; BUF_15_040
	call render_panel
	jp render_scene_return
rend_102_1:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B01DF ; BUF_57_043
	call render_panel
	jp render_scene_return
rend_102_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_102_3:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x0701C8 ; BUF_57_004
	call render_panel
	ld hl,0x0801AF ; BUF_17_004
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_103: dl rend_103_0,rend_103_1,rend_103_2,rend_103_3
rend_103_0:
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280192 ; BUF_15_040
	call render_panel
	jp render_scene_return
rend_103_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_103_2:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return
rend_103_3:
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x260146 ; BUF_12_038
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_104: dl rend_104_0,rend_104_1,rend_104_2,rend_104_3
rend_104_0:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x24018F ; BUF_15_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x270192 ; BUF_15_040
	call render_panel
	jp render_scene_return
rend_104_1:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_104_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_104_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1C0140 ; BUF_12_028
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	jp render_scene_return

rend_105: dl rend_105_0,rend_105_1,rend_105_2,rend_105_3
rend_105_0:
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x23018E ; BUF_15_035
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_105_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_105_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_105_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0E0138 ; BUF_12_014
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x260191 ; BUF_15_038
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_106: dl rend_106_0,rend_106_1,rend_106_2,rend_106_3
rend_106_0:
	jp render_scene_return
rend_106_1:
	jp render_scene_return
rend_106_2:
	jp render_scene_return
rend_106_3:
	jp render_scene_return

rend_107: dl rend_107_0,rend_107_1,rend_107_2,rend_107_3
rend_107_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_107_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	jp render_scene_return
rend_107_2:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_107_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_108: dl rend_108_0,rend_108_1,rend_108_2,rend_108_3
rend_108_0:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_108_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_108_2:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_108_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_109: dl rend_109_0,rend_109_1,rend_109_2,rend_109_3
rend_109_0:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_109_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_109_2:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_109_3:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return

rend_110: dl rend_110_0,rend_110_1,rend_110_2,rend_110_3
rend_110_0:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_110_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_110_2:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_110_3:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	jp render_scene_return

rend_111: dl rend_111_0,rend_111_1,rend_111_2,rend_111_3
rend_111_0:
	jp render_scene_return
rend_111_1:
	jp render_scene_return
rend_111_2:
	jp render_scene_return
rend_111_3:
	jp render_scene_return

rend_112: dl rend_112_0,rend_112_1,rend_112_2,rend_112_3
rend_112_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01CD ; BUF_57_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_112_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_112_2:
	ld hl,0x0C0168 ; BUF_14_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0170 ; BUF_14_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240176 ; BUF_14_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_112_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_113: dl rend_113_0,rend_113_1,rend_113_2,rend_113_3
rend_113_0:
	jp render_scene_return
rend_113_1:
	jp render_scene_return
rend_113_2:
	jp render_scene_return
rend_113_3:
	jp render_scene_return

rend_114: dl rend_114_0,rend_114_1,rend_114_2,rend_114_3
rend_114_0:
	ld hl,0x0C01CC ; BUF_57_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1D0141 ; BUF_12_029
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_114_1:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x18013C ; BUF_12_024
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_114_2:
	ld hl,0x2C0212 ; BUF_59_044
	call render_panel
	jp render_scene_return
rend_114_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_115: dl rend_115_0,rend_115_1,rend_115_2,rend_115_3
rend_115_0:
	ld hl,0x0B01CB ; BUF_57_011
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1C0140 ; BUF_12_028
	call render_panel
	ld hl,0x220142 ; BUF_12_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_115_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_115_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_115_3:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0210 ; BUF_59_042
	call render_panel
	jp render_scene_return

rend_116: dl rend_116_0,rend_116_1,rend_116_2,rend_116_3
rend_116_0:
	jp render_scene_return
rend_116_1:
	jp render_scene_return
rend_116_2:
	jp render_scene_return
rend_116_3:
	jp render_scene_return

rend_117: dl rend_117_0,rend_117_1,rend_117_2,rend_117_3
rend_117_0:
	jp render_scene_return
rend_117_1:
	jp render_scene_return
rend_117_2:
	jp render_scene_return
rend_117_3:
	jp render_scene_return

rend_118: dl rend_118_0,rend_118_1,rend_118_2,rend_118_3
rend_118_0:
	jp render_scene_return
rend_118_1:
	jp render_scene_return
rend_118_2:
	jp render_scene_return
rend_118_3:
	jp render_scene_return

rend_119: dl rend_119_0,rend_119_1,rend_119_2,rend_119_3
rend_119_0:
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x1E0142 ; BUF_12_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x20018D ; BUF_15_032
	call render_panel
	jp render_scene_return
rend_119_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_119_2:
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x0F01B6 ; BUF_17_015
	call render_panel
	ld hl,0x18013C ; BUF_12_024
	call render_panel
	ld hl,0x1D01A5 ; BUF_16_029
	call render_panel
	jp render_scene_return
rend_119_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_120: dl rend_120_0,rend_120_1,rend_120_2,rend_120_3
rend_120_0:
	jp render_scene_return
rend_120_1:
	jp render_scene_return
rend_120_2:
	jp render_scene_return
rend_120_3:
	jp render_scene_return

rend_121: dl rend_121_0,rend_121_1,rend_121_2,rend_121_3
rend_121_0:
	jp render_scene_return
rend_121_1:
	jp render_scene_return
rend_121_2:
	jp render_scene_return
rend_121_3:
	jp render_scene_return

rend_122: dl rend_122_0,rend_122_1,rend_122_2,rend_122_3
rend_122_0:
	jp render_scene_return
rend_122_1:
	jp render_scene_return
rend_122_2:
	jp render_scene_return
rend_122_3:
	jp render_scene_return

rend_123: dl rend_123_0,rend_123_1,rend_123_2,rend_123_3
rend_123_0:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_123_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return
rend_123_2:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_123_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_124: dl rend_124_0,rend_124_1,rend_124_2,rend_124_3
rend_124_0:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_124_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_124_2:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_124_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_125: dl rend_125_0,rend_125_1,rend_125_2,rend_125_3
rend_125_0:
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_125_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_125_2:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_125_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	jp render_scene_return

rend_126: dl rend_126_0,rend_126_1,rend_126_2,rend_126_3
rend_126_0:
	ld hl,0x0901B0 ; BUF_17_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_126_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_126_2:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_126_3:
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	jp render_scene_return

rend_127: dl rend_127_0,rend_127_1,rend_127_2,rend_127_3
rend_127_0:
	jp render_scene_return
rend_127_1:
	jp render_scene_return
rend_127_2:
	jp render_scene_return
rend_127_3:
	jp render_scene_return

rend_128: dl rend_128_0,rend_128_1,rend_128_2,rend_128_3
rend_128_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_128_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_128_2:
	ld hl,0x0C0168 ; BUF_14_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0170 ; BUF_14_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240176 ; BUF_14_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_128_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_129: dl rend_129_0,rend_129_1,rend_129_2,rend_129_3
rend_129_0:
	jp render_scene_return
rend_129_1:
	jp render_scene_return
rend_129_2:
	jp render_scene_return
rend_129_3:
	jp render_scene_return

rend_130: dl rend_130_0,rend_130_1,rend_130_2,rend_130_3
rend_130_0:
	jp render_scene_return
rend_130_1:
	jp render_scene_return
rend_130_2:
	jp render_scene_return
rend_130_3:
	jp render_scene_return

rend_131: dl rend_131_0,rend_131_1,rend_131_2,rend_131_3
rend_131_0:
	jp render_scene_return
rend_131_1:
	jp render_scene_return
rend_131_2:
	jp render_scene_return
rend_131_3:
	jp render_scene_return

rend_132: dl rend_132_0,rend_132_1,rend_132_2,rend_132_3
rend_132_0:
	jp render_scene_return
rend_132_1:
	jp render_scene_return
rend_132_2:
	jp render_scene_return
rend_132_3:
	jp render_scene_return

rend_133: dl rend_133_0,rend_133_1,rend_133_2,rend_133_3
rend_133_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_133_1:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060132 ; BUF_12_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x0801C8 ; BUF_57_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_133_2:
	ld hl,0x000100 ; BUF_10_004
	call render_panel
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x02017D ; BUF_15_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x2501A9 ; BUF_16_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_133_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_134: dl rend_134_0,rend_134_1,rend_134_2,rend_134_3
rend_134_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_134_1:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x16013B ; BUF_12_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	jp render_scene_return
rend_134_2:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x03017D ; BUF_15_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0901C9 ; BUF_57_009
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x2601AA ; BUF_16_038
	call render_panel
	jp render_scene_return
rend_134_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_135: dl rend_135_0,rend_135_1,rend_135_2,rend_135_3
rend_135_0:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return
rend_135_1:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220142 ; BUF_12_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_135_2:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x04017D ; BUF_15_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0A01CA ; BUF_57_010
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	jp render_scene_return
rend_135_3:
	ld hl,0x1E01A6 ; BUF_16_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_136: dl rend_136_0,rend_136_1,rend_136_2,rend_136_3
rend_136_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_136_1:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_136_2:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x05017D ; BUF_15_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x0B01CB ; BUF_57_011
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230143 ; BUF_12_035
	call render_panel
	jp render_scene_return
rend_136_3:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x12019F ; BUF_16_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B01DF ; BUF_57_043
	call render_panel
	jp render_scene_return

rend_137: dl rend_137_0,rend_137_1,rend_137_2,rend_137_3
rend_137_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_137_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_137_2:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x06017D ; BUF_15_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x080100 ; BUF_10_004
	call render_panel
	ld hl,0x0C01CC ; BUF_57_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240144 ; BUF_12_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_137_3:
	ld hl,0x000100 ; BUF_10_004
	call render_panel
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020196 ; BUF_16_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x2501DB ; BUF_57_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_138: dl rend_138_0,rend_138_1,rend_138_2,rend_138_3
rend_138_0:
	jp render_scene_return
rend_138_1:
	jp render_scene_return
rend_138_2:
	jp render_scene_return
rend_138_3:
	jp render_scene_return

rend_139: dl rend_139_0,rend_139_1,rend_139_2,rend_139_3
rend_139_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_139_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_139_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_139_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_140: dl rend_140_0,rend_140_1,rend_140_2,rend_140_3
rend_140_0:
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_140_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_140_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_140_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_141: dl rend_141_0,rend_141_1,rend_141_2,rend_141_3
rend_141_0:
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_141_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_141_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_141_3:
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return

rend_142: dl rend_142_0,rend_142_1,rend_142_2,rend_142_3
rend_142_0:
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_142_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_142_2:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_142_3:
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return

rend_143: dl rend_143_0,rend_143_1,rend_143_2,rend_143_3
rend_143_0:
	jp render_scene_return
rend_143_1:
	jp render_scene_return
rend_143_2:
	jp render_scene_return
rend_143_3:
	jp render_scene_return

rend_144: dl rend_144_0,rend_144_1,rend_144_2,rend_144_3
rend_144_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_144_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_144_2:
	ld hl,0x0C014F ; BUF_13_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0170 ; BUF_14_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240176 ; BUF_14_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_144_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_145: dl rend_145_0,rend_145_1,rend_145_2,rend_145_3
rend_145_0:
	jp render_scene_return
rend_145_1:
	jp render_scene_return
rend_145_2:
	jp render_scene_return
rend_145_3:
	jp render_scene_return

rend_146: dl rend_146_0,rend_146_1,rend_146_2,rend_146_3
rend_146_0:
	ld hl,0x2C0212 ; BUF_59_044
	call render_panel
	jp render_scene_return
rend_146_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_146_2:
	ld hl,0x2801F6 ; BUF_58_040
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_146_3:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return

rend_147: dl rend_147_0,rend_147_1,rend_147_2,rend_147_3
rend_147_0:
	jp render_scene_return
rend_147_1:
	jp render_scene_return
rend_147_2:
	jp render_scene_return
rend_147_3:
	jp render_scene_return

rend_148: dl rend_148_0,rend_148_1,rend_148_2,rend_148_3
rend_148_0:
	jp render_scene_return
rend_148_1:
	jp render_scene_return
rend_148_2:
	jp render_scene_return
rend_148_3:
	jp render_scene_return

rend_149: dl rend_149_0,rend_149_1,rend_149_2,rend_149_3
rend_149_0:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_149_1:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050132 ; BUF_12_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x0701C8 ; BUF_57_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x2301D9 ; BUF_57_035
	call render_panel
	jp render_scene_return
rend_149_2:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x120186 ; BUF_15_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B01AD ; BUF_16_043
	call render_panel
	jp render_scene_return
rend_149_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_150: dl rend_150_0,rend_150_1,rend_150_2,rend_150_3
rend_150_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901DD ; BUF_57_040
	call render_panel
	jp render_scene_return
rend_150_1:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x15013B ; BUF_12_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x1701D1 ; BUF_57_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_150_2:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x130186 ; BUF_15_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_150_3:
	ld hl,0x2701AB ; BUF_16_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return

rend_151: dl rend_151_0,rend_151_1,rend_151_2,rend_151_3
rend_151_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801DD ; BUF_57_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_151_1:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210142 ; BUF_12_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_151_2:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140186 ; BUF_15_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1801D2 ; BUF_57_024
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return
rend_151_3:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F01A6 ; BUF_16_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return

rend_152: dl rend_152_0,rend_152_1,rend_152_2,rend_152_3
rend_152_0:
	ld hl,0x2701DD ; BUF_57_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_152_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290147 ; BUF_12_040
	call render_panel
	jp render_scene_return
rend_152_2:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150186 ; BUF_15_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x1901D3 ; BUF_57_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_152_3:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x13019F ; BUF_16_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return

rend_153: dl rend_153_0,rend_153_1,rend_153_2,rend_153_3
rend_153_0:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_153_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_153_2:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160186 ; BUF_15_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A01D4 ; BUF_57_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0148 ; BUF_12_042
	call render_panel
	jp render_scene_return
rend_153_3:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x030196 ; BUF_16_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x2601DC ; BUF_57_038
	call render_panel
	jp render_scene_return

rend_154: dl rend_154_0,rend_154_1,rend_154_2,rend_154_3
rend_154_0:
	jp render_scene_return
rend_154_1:
	jp render_scene_return
rend_154_2:
	jp render_scene_return
rend_154_3:
	jp render_scene_return

rend_155: dl rend_155_0,rend_155_1,rend_155_2,rend_155_3
rend_155_0:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_155_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_155_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_155_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_156: dl rend_156_0,rend_156_1,rend_156_2,rend_156_3
rend_156_0:
	ld hl,0x0B01B2 ; BUF_17_011
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_156_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_156_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_156_3:
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_157: dl rend_157_0,rend_157_1,rend_157_2,rend_157_3
rend_157_0:
	ld hl,0x0A01B1 ; BUF_17_010
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_157_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_157_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_157_3:
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_158: dl rend_158_0,rend_158_1,rend_158_2,rend_158_3
rend_158_0:
	ld hl,0x0901B0 ; BUF_17_009
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_158_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_158_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_158_3:
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_159: dl rend_159_0,rend_159_1,rend_159_2,rend_159_3
rend_159_0:
	jp render_scene_return
rend_159_1:
	jp render_scene_return
rend_159_2:
	jp render_scene_return
rend_159_3:
	jp render_scene_return

rend_160: dl rend_160_0,rend_160_1,rend_160_2,rend_160_3
rend_160_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_160_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_160_2:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0157 ; BUF_13_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240176 ; BUF_14_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_160_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_161: dl rend_161_0,rend_161_1,rend_161_2,rend_161_3
rend_161_0:
	jp render_scene_return
rend_161_1:
	jp render_scene_return
rend_161_2:
	jp render_scene_return
rend_161_3:
	jp render_scene_return

rend_162: dl rend_162_0,rend_162_1,rend_162_2,rend_162_3
rend_162_0:
	ld hl,0x28020F ; BUF_59_040
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_162_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_162_2:
	ld hl,0x2C01F9 ; BUF_58_044
	call render_panel
	jp render_scene_return
rend_162_3:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return

rend_163: dl rend_163_0,rend_163_1,rend_163_2,rend_163_3
rend_163_0:
	jp render_scene_return
rend_163_1:
	jp render_scene_return
rend_163_2:
	jp render_scene_return
rend_163_3:
	jp render_scene_return

rend_164: dl rend_164_0,rend_164_1,rend_164_2,rend_164_3
rend_164_0:
	jp render_scene_return
rend_164_1:
	jp render_scene_return
rend_164_2:
	jp render_scene_return
rend_164_3:
	jp render_scene_return

rend_165: dl rend_165_0,rend_165_1,rend_165_2,rend_165_3
rend_165_0:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201D8 ; BUF_57_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_165_1:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040132 ; BUF_12_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0601C8 ; BUF_57_004
	call render_panel
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	jp render_scene_return
rend_165_2:
	ld hl,0x1E018D ; BUF_15_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_165_3:
	ld hl,0x2C01AE ; BUF_16_044
	call render_panel
	jp render_scene_return

rend_166: dl rend_166_0,rend_166_1,rend_166_2,rend_166_3
rend_166_0:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101D8 ; BUF_57_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_166_1:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x14013B ; BUF_12_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1601D1 ; BUF_57_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return
rend_166_2:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F018D ; BUF_15_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_166_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801AB ; BUF_16_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return

rend_167: dl rend_167_0,rend_167_1,rend_167_2,rend_167_3
rend_167_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2001D8 ; BUF_57_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_167_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200142 ; BUF_12_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201D8 ; BUF_57_032
	call render_panel
	jp render_scene_return
rend_167_2:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x20018D ; BUF_15_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return
rend_167_3:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2001A6 ; BUF_16_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	jp render_scene_return

rend_168: dl rend_168_0,rend_168_1,rend_168_2,rend_168_3
rend_168_0:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F01D8 ; BUF_57_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_168_1:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280147 ; BUF_12_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_168_2:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x21018D ; BUF_15_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x2301D9 ; BUF_57_035
	call render_panel
	jp render_scene_return
rend_168_3:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x14019F ; BUF_16_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return

rend_169: dl rend_169_0,rend_169_1,rend_169_2,rend_169_3
rend_169_0:
	ld hl,0x1E01D8 ; BUF_57_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_169_1:
	ld hl,0x2C014A ; BUF_12_044
	call render_panel
	jp render_scene_return
rend_169_2:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x22018D ; BUF_15_032
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_169_3:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040196 ; BUF_16_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	jp render_scene_return

rend_170: dl rend_170_0,rend_170_1,rend_170_2,rend_170_3
rend_170_0:
	jp render_scene_return
rend_170_1:
	jp render_scene_return
rend_170_2:
	jp render_scene_return
rend_170_3:
	jp render_scene_return

rend_171: dl rend_171_0,rend_171_1,rend_171_2,rend_171_3
rend_171_0:
	jp render_scene_return
rend_171_1:
	jp render_scene_return
rend_171_2:
	jp render_scene_return
rend_171_3:
	jp render_scene_return

rend_172: dl rend_172_0,rend_172_1,rend_172_2,rend_172_3
rend_172_0:
	jp render_scene_return
rend_172_1:
	jp render_scene_return
rend_172_2:
	jp render_scene_return
rend_172_3:
	jp render_scene_return

rend_173: dl rend_173_0,rend_173_1,rend_173_2,rend_173_3
rend_173_0:
	jp render_scene_return
rend_173_1:
	jp render_scene_return
rend_173_2:
	jp render_scene_return
rend_173_3:
	jp render_scene_return

rend_174: dl rend_174_0,rend_174_1,rend_174_2,rend_174_3
rend_174_0:
	jp render_scene_return
rend_174_1:
	jp render_scene_return
rend_174_2:
	jp render_scene_return
rend_174_3:
	jp render_scene_return

rend_175: dl rend_175_0,rend_175_1,rend_175_2,rend_175_3
rend_175_0:
	jp render_scene_return
rend_175_1:
	jp render_scene_return
rend_175_2:
	jp render_scene_return
rend_175_3:
	jp render_scene_return

rend_176: dl rend_176_0,rend_176_1,rend_176_2,rend_176_3
rend_176_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250177 ; BUF_14_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_176_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_176_2:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x24015D ; BUF_13_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_176_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_177: dl rend_177_0,rend_177_1,rend_177_2,rend_177_3
rend_177_0:
	jp render_scene_return
rend_177_1:
	jp render_scene_return
rend_177_2:
	jp render_scene_return
rend_177_3:
	jp render_scene_return

rend_178: dl rend_178_0,rend_178_1,rend_178_2,rend_178_3
rend_178_0:
	ld hl,0x20020A ; BUF_59_032
	call render_panel
	ld hl,0x240176 ; BUF_14_036
	call render_panel
	ld hl,0x250177 ; BUF_14_037
	call render_panel
	ld hl,0x2A017A ; BUF_14_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_178_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_178_2:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_178_3:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return

rend_179: dl rend_179_0,rend_179_1,rend_179_2,rend_179_3
rend_179_0:
	jp render_scene_return
rend_179_1:
	jp render_scene_return
rend_179_2:
	jp render_scene_return
rend_179_3:
	jp render_scene_return

rend_180: dl rend_180_0,rend_180_1,rend_180_2,rend_180_3
rend_180_0:
	jp render_scene_return
rend_180_1:
	jp render_scene_return
rend_180_2:
	jp render_scene_return
rend_180_3:
	jp render_scene_return

rend_181: dl rend_181_0,rend_181_1,rend_181_2,rend_181_3
rend_181_0:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1601D1 ; BUF_57_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A01AC ; BUF_16_042
	call render_panel
	jp render_scene_return
rend_181_1:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x030132 ; BUF_12_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0501C8 ; BUF_57_004
	call render_panel
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260191 ; BUF_15_038
	call render_panel
	jp render_scene_return
rend_181_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_181_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_182: dl rend_182_0,rend_182_1,rend_182_2,rend_182_3
rend_182_0:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1501D1 ; BUF_57_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return
rend_182_1:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x13013B ; BUF_12_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1501D1 ; BUF_57_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_182_2:
	ld hl,0x270192 ; BUF_15_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_182_3:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901AB ; BUF_16_040
	call render_panel
	jp render_scene_return

rend_183: dl rend_183_0,rend_183_1,rend_183_2,rend_183_3
rend_183_0:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1401D1 ; BUF_57_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	jp render_scene_return
rend_183_1:
	ld hl,0x1E01BF ; BUF_17_032
	call render_panel
	ld hl,0x1F0142 ; BUF_12_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101D8 ; BUF_57_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_183_2:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x280192 ; BUF_15_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	jp render_scene_return
rend_183_3:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101A6 ; BUF_16_032
	call render_panel
	ld hl,0x2201BF ; BUF_17_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return

rend_184: dl rend_184_0,rend_184_1,rend_184_2,rend_184_3
rend_184_0:
	ld hl,0x110109 ; BUF_10_020
	call render_panel
	ld hl,0x1201B8 ; BUF_17_020
	call render_panel
	ld hl,0x1301D1 ; BUF_57_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x2601C3 ; BUF_17_038
	call render_panel
	jp render_scene_return
rend_184_1:
	ld hl,0x270147 ; BUF_12_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901DD ; BUF_57_040
	call render_panel
	jp render_scene_return
rend_184_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x290192 ; BUF_15_040
	call render_panel
	jp render_scene_return
rend_184_3:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x15019F ; BUF_16_020
	call render_panel
	ld hl,0x1601B8 ; BUF_17_020
	call render_panel
	ld hl,0x170109 ; BUF_10_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x2301C0 ; BUF_17_035
	call render_panel
	jp render_scene_return

rend_185: dl rend_185_0,rend_185_1,rend_185_2,rend_185_3
rend_185_0:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x1201D1 ; BUF_57_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0149 ; BUF_12_043
	call render_panel
	jp render_scene_return
rend_185_1:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_185_2:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	jp render_scene_return
rend_185_3:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050196 ; BUF_16_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x23018E ; BUF_15_035
	call render_panel
	jp render_scene_return

rend_186: dl rend_186_0,rend_186_1,rend_186_2,rend_186_3
rend_186_0:
	jp render_scene_return
rend_186_1:
	jp render_scene_return
rend_186_2:
	jp render_scene_return
rend_186_3:
	jp render_scene_return

rend_187: dl rend_187_0,rend_187_1,rend_187_2,rend_187_3
rend_187_0:
	jp render_scene_return
rend_187_1:
	jp render_scene_return
rend_187_2:
	jp render_scene_return
rend_187_3:
	jp render_scene_return

rend_188: dl rend_188_0,rend_188_1,rend_188_2,rend_188_3
rend_188_0:
	jp render_scene_return
rend_188_1:
	jp render_scene_return
rend_188_2:
	jp render_scene_return
rend_188_3:
	jp render_scene_return

rend_189: dl rend_189_0,rend_189_1,rend_189_2,rend_189_3
rend_189_0:
	jp render_scene_return
rend_189_1:
	jp render_scene_return
rend_189_2:
	jp render_scene_return
rend_189_3:
	jp render_scene_return

rend_190: dl rend_190_0,rend_190_1,rend_190_2,rend_190_3
rend_190_0:
	jp render_scene_return
rend_190_1:
	jp render_scene_return
rend_190_2:
	jp render_scene_return
rend_190_3:
	jp render_scene_return

rend_191: dl rend_191_0,rend_191_1,rend_191_2,rend_191_3
rend_191_0:
	jp render_scene_return
rend_191_1:
	jp render_scene_return
rend_191_2:
	jp render_scene_return
rend_191_3:
	jp render_scene_return

rend_192: dl rend_192_0,rend_192_1,rend_192_2,rend_192_3
rend_192_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B0171 ; BUF_14_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250177 ; BUF_14_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_192_1:
	ld hl,0x2C017C ; BUF_14_044
	call render_panel
	jp render_scene_return
rend_192_2:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0161 ; BUF_13_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_192_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_193: dl rend_193_0,rend_193_1,rend_193_2,rend_193_3
rend_193_0:
	jp render_scene_return
rend_193_1:
	jp render_scene_return
rend_193_2:
	jp render_scene_return
rend_193_3:
	jp render_scene_return

rend_194: dl rend_194_0,rend_194_1,rend_194_2,rend_194_3
rend_194_0:
	jp render_scene_return
rend_194_1:
	jp render_scene_return
rend_194_2:
	jp render_scene_return
rend_194_3:
	jp render_scene_return

rend_195: dl rend_195_0,rend_195_1,rend_195_2,rend_195_3
rend_195_0:
	jp render_scene_return
rend_195_1:
	jp render_scene_return
rend_195_2:
	jp render_scene_return
rend_195_3:
	jp render_scene_return

rend_196: dl rend_196_0,rend_196_1,rend_196_2,rend_196_3
rend_196_0:
	jp render_scene_return
rend_196_1:
	jp render_scene_return
rend_196_2:
	jp render_scene_return
rend_196_3:
	jp render_scene_return

rend_197: dl rend_197_0,rend_197_1,rend_197_2,rend_197_3
rend_197_0:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x0601C8 ; BUF_57_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x080100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x2401A8 ; BUF_16_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_197_1:
	ld hl,0x000100 ; BUF_10_004
	call render_panel
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x020132 ; BUF_12_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x0401C8 ; BUF_57_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250190 ; BUF_15_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_197_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_197_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_198: dl rend_198_0,rend_198_1,rend_198_2,rend_198_3
rend_198_0:
	ld hl,0x030100 ; BUF_10_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x0501C8 ; BUF_57_004
	call render_panel
	ld hl,0x0601AF ; BUF_17_004
	call render_panel
	ld hl,0x070100 ; BUF_10_004
	call render_panel
	ld hl,0x0B0103 ; BUF_10_011
	call render_panel
	ld hl,0x100108 ; BUF_10_016
	call render_panel
	ld hl,0x1901BA ; BUF_17_025
	call render_panel
	ld hl,0x2301A7 ; BUF_16_035
	call render_panel
	jp render_scene_return
rend_198_1:
	ld hl,0x1101B8 ; BUF_17_020
	call render_panel
	ld hl,0x12013B ; BUF_12_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1401D1 ; BUF_57_020
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2B0194 ; BUF_15_043
	call render_panel
	jp render_scene_return
rend_198_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_198_3:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_199: dl rend_199_0,rend_199_1,rend_199_2,rend_199_3
rend_199_0:
	ld hl,0x020100 ; BUF_10_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x0401C8 ; BUF_57_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0A0102 ; BUF_10_010
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1801B9 ; BUF_17_024
	call render_panel
	ld hl,0x1D01BE ; BUF_17_029
	call render_panel
	jp render_scene_return
rend_199_1:
	ld hl,0x1E0142 ; BUF_12_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2001D8 ; BUF_57_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_199_2:
	ld hl,0x2C0195 ; BUF_15_044
	call render_panel
	jp render_scene_return
rend_199_3:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201A6 ; BUF_16_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_200: dl rend_200_0,rend_200_1,rend_200_2,rend_200_3
rend_200_0:
	ld hl,0x010100 ; BUF_10_004
	call render_panel
	ld hl,0x0201AF ; BUF_17_004
	call render_panel
	ld hl,0x0301C8 ; BUF_57_004
	call render_panel
	ld hl,0x0401AF ; BUF_17_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x090101 ; BUF_10_009
	call render_panel
	ld hl,0x0E0106 ; BUF_10_014
	call render_panel
	ld hl,0x1C01BD ; BUF_17_028
	call render_panel
	ld hl,0x260146 ; BUF_12_038
	call render_panel
	jp render_scene_return
rend_200_1:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801DD ; BUF_57_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_200_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_200_3:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x16019F ; BUF_16_020
	call render_panel
	ld hl,0x1701B8 ; BUF_17_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0193 ; BUF_15_042
	call render_panel
	jp render_scene_return

rend_201: dl rend_201_0,rend_201_1,rend_201_2,rend_201_3
rend_201_0:
	ld hl,0x000100 ; BUF_10_004
	call render_panel
	ld hl,0x0101AF ; BUF_17_004
	call render_panel
	ld hl,0x0201C8 ; BUF_57_004
	call render_panel
	ld hl,0x0301AF ; BUF_17_004
	call render_panel
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x250145 ; BUF_12_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_201_1:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return
rend_201_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_201_3:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0501AF ; BUF_17_004
	call render_panel
	ld hl,0x060196 ; BUF_16_004
	call render_panel
	ld hl,0x0701AF ; BUF_17_004
	call render_panel
	ld hl,0x080100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x24018F ; BUF_15_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return

rend_202: dl rend_202_0,rend_202_1,rend_202_2,rend_202_3
rend_202_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_202_1:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x060100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0F0107 ; BUF_10_015
	call render_panel
	ld hl,0x1A0125 ; BUF_11_026
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A012F ; BUF_11_042
	call render_panel
	jp render_scene_return
rend_202_2:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_202_3:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x1A0189 ; BUF_15_026
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_203: dl rend_203_0,rend_203_1,rend_203_2,rend_203_3
rend_203_0:
	ld hl,0x2C0131 ; BUF_11_044
	call render_panel
	jp render_scene_return
rend_203_1:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x160109 ; BUF_10_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1D010F ; BUF_10_029
	call render_panel
	ld hl,0x24012B ; BUF_11_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_203_2:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x25012C ; BUF_11_037
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return
rend_203_3:
	ld hl,0x2C01E0 ; BUF_57_044
	call render_panel
	jp render_scene_return

rend_204: dl rend_204_0,rend_204_1,rend_204_2,rend_204_3
rend_204_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_204_1:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A012F ; BUF_11_042
	call render_panel
	jp render_scene_return
rend_204_2:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x26012D ; BUF_11_038
	call render_panel
	jp render_scene_return
rend_204_3:
	ld hl,0x2701C4 ; BUF_17_040
	call render_panel
	ld hl,0x2801DD ; BUF_57_040
	call render_panel
	ld hl,0x2B0130 ; BUF_11_043
	call render_panel
	jp render_scene_return

rend_205: dl rend_205_0,rend_205_1,rend_205_2,rend_205_3
rend_205_0:
	ld hl,0x2C0131 ; BUF_11_044
	call render_panel
	jp render_scene_return
rend_205_1:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_205_2:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	jp render_scene_return
rend_205_3:
	ld hl,0x1E0129 ; BUF_11_032
	call render_panel
	ld hl,0x1F01BF ; BUF_17_032
	call render_panel
	ld hl,0x2001D8 ; BUF_57_032
	call render_panel
	ld hl,0x25012C ; BUF_11_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_206: dl rend_206_0,rend_206_1,rend_206_2,rend_206_3
rend_206_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_206_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_206_2:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_206_3:
	ld hl,0x120122 ; BUF_11_020
	call render_panel
	ld hl,0x1301B8 ; BUF_17_020
	call render_panel
	ld hl,0x1401D1 ; BUF_57_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1B0126 ; BUF_11_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0130 ; BUF_11_043
	call render_panel
	jp render_scene_return

rend_207: dl rend_207_0,rend_207_1,rend_207_2,rend_207_3
rend_207_0:
	jp render_scene_return
rend_207_1:
	jp render_scene_return
rend_207_2:
	jp render_scene_return
rend_207_3:
	jp render_scene_return

rend_208: dl rend_208_0,rend_208_1,rend_208_2,rend_208_3
rend_208_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0169 ; BUF_14_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B0171 ; BUF_14_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250177 ; BUF_14_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B017B ; BUF_14_043
	call render_panel
	jp render_scene_return
rend_208_1:
	ld hl,0x2C0163 ; BUF_13_044
	call render_panel
	jp render_scene_return
rend_208_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_208_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_209: dl rend_209_0,rend_209_1,rend_209_2,rend_209_3
rend_209_0:
	jp render_scene_return
rend_209_1:
	jp render_scene_return
rend_209_2:
	jp render_scene_return
rend_209_3:
	jp render_scene_return

rend_210: dl rend_210_0,rend_210_1,rend_210_2,rend_210_3
rend_210_0:
	jp render_scene_return
rend_210_1:
	jp render_scene_return
rend_210_2:
	jp render_scene_return
rend_210_3:
	jp render_scene_return

rend_211: dl rend_211_0,rend_211_1,rend_211_2,rend_211_3
rend_211_0:
	jp render_scene_return
rend_211_1:
	jp render_scene_return
rend_211_2:
	jp render_scene_return
rend_211_3:
	jp render_scene_return

rend_212: dl rend_212_0,rend_212_1,rend_212_2,rend_212_3
rend_212_0:
	jp render_scene_return
rend_212_1:
	jp render_scene_return
rend_212_2:
	jp render_scene_return
rend_212_3:
	jp render_scene_return

rend_213: dl rend_213_0,rend_213_1,rend_213_2,rend_213_3
rend_213_0:
	jp render_scene_return
rend_213_1:
	jp render_scene_return
rend_213_2:
	jp render_scene_return
rend_213_3:
	jp render_scene_return

rend_214: dl rend_214_0,rend_214_1,rend_214_2,rend_214_3
rend_214_0:
	jp render_scene_return
rend_214_1:
	jp render_scene_return
rend_214_2:
	jp render_scene_return
rend_214_3:
	jp render_scene_return

rend_215: dl rend_215_0,rend_215_1,rend_215_2,rend_215_3
rend_215_0:
	jp render_scene_return
rend_215_1:
	jp render_scene_return
rend_215_2:
	jp render_scene_return
rend_215_3:
	jp render_scene_return

rend_216: dl rend_216_0,rend_216_1,rend_216_2,rend_216_3
rend_216_0:
	jp render_scene_return
rend_216_1:
	jp render_scene_return
rend_216_2:
	jp render_scene_return
rend_216_3:
	jp render_scene_return

rend_217: dl rend_217_0,rend_217_1,rend_217_2,rend_217_3
rend_217_0:
	jp render_scene_return
rend_217_1:
	jp render_scene_return
rend_217_2:
	jp render_scene_return
rend_217_3:
	jp render_scene_return

rend_218: dl rend_218_0,rend_218_1,rend_218_2,rend_218_3
rend_218_0:
	jp render_scene_return
rend_218_1:
	jp render_scene_return
rend_218_2:
	jp render_scene_return
rend_218_3:
	jp render_scene_return

rend_219: dl rend_219_0,rend_219_1,rend_219_2,rend_219_3
rend_219_0:
	ld hl,0x28012E ; BUF_11_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A01DE ; BUF_57_042
	call render_panel
	jp render_scene_return
rend_219_1:
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1C010E ; BUF_10_028
	call render_panel
	ld hl,0x23012A ; BUF_11_035
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_219_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0130 ; BUF_11_043
	call render_panel
	jp render_scene_return
rend_219_3:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return

rend_220: dl rend_220_0,rend_220_1,rend_220_2,rend_220_3
rend_220_0:
	ld hl,0x27012E ; BUF_11_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x29012E ; BUF_11_040
	call render_panel
	jp render_scene_return
rend_220_1:
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_220_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_220_3:
	ld hl,0x27012E ; BUF_11_040
	call render_panel
	ld hl,0x2801C4 ; BUF_17_040
	call render_panel
	ld hl,0x2901DD ; BUF_57_040
	call render_panel
	jp render_scene_return

rend_221: dl rend_221_0,rend_221_1,rend_221_2,rend_221_3
rend_221_0:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x28012E ; BUF_11_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_221_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_221_2:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	jp render_scene_return
rend_221_3:
	ld hl,0x1F0129 ; BUF_11_032
	call render_panel
	ld hl,0x2001BF ; BUF_17_032
	call render_panel
	ld hl,0x2101D8 ; BUF_57_032
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x26012D ; BUF_11_038
	call render_panel
	jp render_scene_return

rend_222: dl rend_222_0,rend_222_1,rend_222_2,rend_222_3
rend_222_0:
	ld hl,0x27012E ; BUF_11_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_222_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_222_2:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return
rend_222_3:
	ld hl,0x130122 ; BUF_11_020
	call render_panel
	ld hl,0x1401B8 ; BUF_17_020
	call render_panel
	ld hl,0x1501D1 ; BUF_57_020
	call render_panel
	ld hl,0x19010B ; BUF_10_025
	call render_panel
	ld hl,0x1C0127 ; BUF_11_028
	call render_panel
	ld hl,0x230111 ; BUF_10_035
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return

rend_223: dl rend_223_0,rend_223_1,rend_223_2,rend_223_3
rend_223_0:
	jp render_scene_return
rend_223_1:
	jp render_scene_return
rend_223_2:
	jp render_scene_return
rend_223_3:
	jp render_scene_return

rend_224: dl rend_224_0,rend_224_1,rend_224_2,rend_224_3
rend_224_0:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0169 ; BUF_14_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B0171 ; BUF_14_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250177 ; BUF_14_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0162 ; BUF_13_043
	call render_panel
	jp render_scene_return
rend_224_1:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0157 ; BUF_13_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0161 ; BUF_13_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_224_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_224_3:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return

rend_225: dl rend_225_0,rend_225_1,rend_225_2,rend_225_3
rend_225_0:
	ld hl,0x2C0163 ; BUF_13_044
	call render_panel
	jp render_scene_return
rend_225_1:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x24015D ; BUF_13_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_225_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_225_3:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x290115 ; BUF_10_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_226: dl rend_226_0,rend_226_1,rend_226_2,rend_226_3
rend_226_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_226_1:
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0161 ; BUF_13_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_226_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_226_3:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0162 ; BUF_13_043
	call render_panel
	jp render_scene_return

rend_227: dl rend_227_0,rend_227_1,rend_227_2,rend_227_3
rend_227_0:
	ld hl,0x2C0163 ; BUF_13_044
	call render_panel
	jp render_scene_return
rend_227_1:
	ld hl,0x0C0181 ; BUF_15_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_227_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_227_3:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x150109 ; BUF_10_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x25015E ; BUF_13_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_228: dl rend_228_0,rend_228_1,rend_228_2,rend_228_3
rend_228_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_228_1:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x0C01B3 ; BUF_17_012
	call render_panel
	ld hl,0x0D0105 ; BUF_10_013
	call render_panel
	ld hl,0x1A0189 ; BUF_15_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_228_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_228_3:
	ld hl,0x040100 ; BUF_10_004
	call render_panel
	ld hl,0x050100 ; BUF_10_004
	call render_panel
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B0158 ; BUF_13_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0162 ; BUF_13_043
	call render_panel
	jp render_scene_return

rend_229: dl rend_229_0,rend_229_1,rend_229_2,rend_229_3
rend_229_0:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_229_1:
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x1A01BB ; BUF_17_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x24018F ; BUF_15_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_229_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_229_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0150 ; BUF_13_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x25015E ; BUF_13_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_230: dl rend_230_0,rend_230_1,rend_230_2,rend_230_3
rend_230_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_230_1:
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x2401C1 ; BUF_17_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0193 ; BUF_15_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_230_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_230_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B0158 ; BUF_13_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return

rend_231: dl rend_231_0,rend_231_1,rend_231_2,rend_231_3
rend_231_0:
	ld hl,0x2C0195 ; BUF_15_044
	call render_panel
	jp render_scene_return
rend_231_1:
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_231_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_231_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D0150 ; BUF_13_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B01BC ; BUF_17_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B01C6 ; BUF_17_043
	call render_panel
	jp render_scene_return

rend_232: dl rend_232_0,rend_232_1,rend_232_2,rend_232_3
rend_232_0:
	ld hl,0x2C01C7 ; BUF_17_044
	call render_panel
	jp render_scene_return
rend_232_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_232_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_232_3:
	ld hl,0x0C0104 ; BUF_10_012
	call render_panel
	ld hl,0x0D01B4 ; BUF_17_013
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2501C2 ; BUF_17_037
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	ld hl,0x2B0194 ; BUF_15_043
	call render_panel
	jp render_scene_return

rend_233: dl rend_233_0,rend_233_1,rend_233_2,rend_233_3
rend_233_0:
	jp render_scene_return
rend_233_1:
	jp render_scene_return
rend_233_2:
	jp render_scene_return
rend_233_3:
	jp render_scene_return

rend_234: dl rend_234_0,rend_234_1,rend_234_2,rend_234_3
rend_234_0:
	jp render_scene_return
rend_234_1:
	jp render_scene_return
rend_234_2:
	jp render_scene_return
rend_234_3:
	jp render_scene_return

rend_235: dl rend_235_0,rend_235_1,rend_235_2,rend_235_3
rend_235_0:
	ld hl,0x200129 ; BUF_11_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x220129 ; BUF_11_032
	call render_panel
	ld hl,0x2401DA ; BUF_57_036
	call render_panel
	ld hl,0x2A01C5 ; BUF_17_042
	call render_panel
	jp render_scene_return
rend_235_1:
	ld hl,0x120109 ; BUF_10_020
	call render_panel
	ld hl,0x130109 ; BUF_10_020
	call render_panel
	ld hl,0x140109 ; BUF_10_020
	call render_panel
	ld hl,0x18010A ; BUF_10_024
	call render_panel
	ld hl,0x1B010D ; BUF_10_027
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_235_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_235_3:
	ld hl,0x2C0131 ; BUF_11_044
	call render_panel
	jp render_scene_return

rend_236: dl rend_236_0,rend_236_1,rend_236_2,rend_236_3
rend_236_0:
	ld hl,0x1F0129 ; BUF_11_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x210129 ; BUF_11_032
	call render_panel
	ld hl,0x220110 ; BUF_10_032
	call render_panel
	ld hl,0x2301D9 ; BUF_57_035
	call render_panel
	jp render_scene_return
rend_236_1:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_236_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_236_3:
	ld hl,0x28012E ; BUF_11_040
	call render_panel
	ld hl,0x2901C4 ; BUF_17_040
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_237: dl rend_237_0,rend_237_1,rend_237_2,rend_237_3
rend_237_0:
	ld hl,0x1E0129 ; BUF_11_032
	call render_panel
	ld hl,0x1F0110 ; BUF_10_032
	call render_panel
	ld hl,0x200129 ; BUF_11_032
	call render_panel
	ld hl,0x210110 ; BUF_10_032
	call render_panel
	ld hl,0x260114 ; BUF_10_038
	call render_panel
	jp render_scene_return
rend_237_1:
	ld hl,0x270115 ; BUF_10_040
	call render_panel
	ld hl,0x280115 ; BUF_10_040
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_237_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_237_3:
	ld hl,0x200129 ; BUF_11_032
	call render_panel
	ld hl,0x2101BF ; BUF_17_032
	call render_panel
	ld hl,0x2201D8 ; BUF_57_032
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_238: dl rend_238_0,rend_238_1,rend_238_2,rend_238_3
rend_238_0:
	ld hl,0x1E0110 ; BUF_10_032
	call render_panel
	ld hl,0x1F0129 ; BUF_11_032
	call render_panel
	ld hl,0x200110 ; BUF_10_032
	call render_panel
	ld hl,0x250113 ; BUF_10_037
	call render_panel
	ld hl,0x2B0117 ; BUF_10_043
	call render_panel
	jp render_scene_return
rend_238_1:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_238_2:
	ld hl,0x2C0118 ; BUF_10_044
	call render_panel
	jp render_scene_return
rend_238_3:
	ld hl,0x140122 ; BUF_11_020
	call render_panel
	ld hl,0x1501B8 ; BUF_17_020
	call render_panel
	ld hl,0x1601D1 ; BUF_57_020
	call render_panel
	ld hl,0x1A010C ; BUF_10_026
	call render_panel
	ld hl,0x1D0128 ; BUF_11_029
	call render_panel
	ld hl,0x240112 ; BUF_10_036
	call render_panel
	ld hl,0x2A0116 ; BUF_10_042
	call render_panel
	jp render_scene_return

rend_239: dl rend_239_0,rend_239_1,rend_239_2,rend_239_3
rend_239_0:
	jp render_scene_return
rend_239_1:
	jp render_scene_return
rend_239_2:
	jp render_scene_return
rend_239_3:
	jp render_scene_return

rend_240: dl rend_240_0,rend_240_1,rend_240_2,rend_240_3
rend_240_0:
	jp render_scene_return
rend_240_1:
	jp render_scene_return
rend_240_2:
	jp render_scene_return
rend_240_3:
	jp render_scene_return

rend_241: dl rend_241_0,rend_241_1,rend_241_2,rend_241_3
rend_241_0:
	jp render_scene_return
rend_241_1:
	jp render_scene_return
rend_241_2:
	jp render_scene_return
rend_241_3:
	jp render_scene_return

rend_242: dl rend_242_0,rend_242_1,rend_242_2,rend_242_3
rend_242_0:
	jp render_scene_return
rend_242_1:
	jp render_scene_return
rend_242_2:
	jp render_scene_return
rend_242_3:
	jp render_scene_return

rend_243: dl rend_243_0,rend_243_1,rend_243_2,rend_243_3
rend_243_0:
	jp render_scene_return
rend_243_1:
	jp render_scene_return
rend_243_2:
	jp render_scene_return
rend_243_3:
	jp render_scene_return

rend_244: dl rend_244_0,rend_244_1,rend_244_2,rend_244_3
rend_244_0:
	jp render_scene_return
rend_244_1:
	jp render_scene_return
rend_244_2:
	jp render_scene_return
rend_244_3:
	jp render_scene_return

rend_245: dl rend_245_0,rend_245_1,rend_245_2,rend_245_3
rend_245_0:
	jp render_scene_return
rend_245_1:
	jp render_scene_return
rend_245_2:
	jp render_scene_return
rend_245_3:
	jp render_scene_return

rend_246: dl rend_246_0,rend_246_1,rend_246_2,rend_246_3
rend_246_0:
	jp render_scene_return
rend_246_1:
	jp render_scene_return
rend_246_2:
	jp render_scene_return
rend_246_3:
	jp render_scene_return

rend_247: dl rend_247_0,rend_247_1,rend_247_2,rend_247_3
rend_247_0:
	jp render_scene_return
rend_247_1:
	jp render_scene_return
rend_247_2:
	jp render_scene_return
rend_247_3:
	jp render_scene_return

rend_248: dl rend_248_0,rend_248_1,rend_248_2,rend_248_3
rend_248_0:
	jp render_scene_return
rend_248_1:
	jp render_scene_return
rend_248_2:
	jp render_scene_return
rend_248_3:
	jp render_scene_return

rend_249: dl rend_249_0,rend_249_1,rend_249_2,rend_249_3
rend_249_0:
	jp render_scene_return
rend_249_1:
	jp render_scene_return
rend_249_2:
	jp render_scene_return
rend_249_3:
	jp render_scene_return

rend_250: dl rend_250_0,rend_250_1,rend_250_2,rend_250_3
rend_250_0:
	jp render_scene_return
rend_250_1:
	jp render_scene_return
rend_250_2:
	jp render_scene_return
rend_250_3:
	jp render_scene_return

rend_251: dl rend_251_0,rend_251_1,rend_251_2,rend_251_3
rend_251_0:
	jp render_scene_return
rend_251_1:
	jp render_scene_return
rend_251_2:
	jp render_scene_return
rend_251_3:
	jp render_scene_return

rend_252: dl rend_252_0,rend_252_1,rend_252_2,rend_252_3
rend_252_0:
	jp render_scene_return
rend_252_1:
	jp render_scene_return
rend_252_2:
	jp render_scene_return
rend_252_3:
	jp render_scene_return

rend_253: dl rend_253_0,rend_253_1,rend_253_2,rend_253_3
rend_253_0:
	jp render_scene_return
rend_253_1:
	jp render_scene_return
rend_253_2:
	jp render_scene_return
rend_253_3:
	jp render_scene_return

rend_254: dl rend_254_0,rend_254_1,rend_254_2,rend_254_3
rend_254_0:
	jp render_scene_return
rend_254_1:
	jp render_scene_return
rend_254_2:
	jp render_scene_return
rend_254_3:
	jp render_scene_return

rend_255: dl rend_255_0,rend_255_1,rend_255_2,rend_255_3
rend_255_0:
	jp render_scene_return
rend_255_1:
	jp render_scene_return
rend_255_2:
	jp render_scene_return
rend_255_3:
	jp render_scene_return
