cells:
; cell label: obj_id map_x map_y, render routine address
; MIND THE LITTLE-ENDIANESS IN THE COORDINATES!!!111
cell_000: dl 0x130000, rend_000
cell_001: dl 0x130001, rend_001
cell_002: dl 0x130002, rend_002
cell_003: dl 0x130003, rend_003
cell_004: dl 0x130004, rend_004
cell_005: dl 0x130005, rend_005
cell_006: dl 0x130006, rend_006
cell_007: dl 0x130007, rend_007
cell_008: dl 0x130008, rend_008
cell_009: dl 0x130009, rend_009
cell_010: dl 0x13000A, rend_010
cell_011: dl 0x13000B, rend_011
cell_012: dl 0x13000C, rend_012
cell_013: dl 0x13000D, rend_013
cell_014: dl 0x13000E, rend_014
cell_015: dl 0x130100, rend_015
cell_016: dl 0x130101, rend_016
cell_017: dl 0x130102, rend_017
cell_018: dl 0x130103, rend_018
cell_019: dl 0x130104, rend_019
cell_020: dl 0x130105, rend_020
cell_021: dl 0x130106, rend_021
cell_022: dl 0x130107, rend_022
cell_023: dl 0x130108, rend_023
cell_024: dl 0x130109, rend_024
cell_025: dl 0x13010A, rend_025
cell_026: dl 0x13010B, rend_026
cell_027: dl 0x13010C, rend_027
cell_028: dl 0x13010D, rend_028
cell_029: dl 0x13010E, rend_029
cell_030: dl 0x130200, rend_030
cell_031: dl 0x130201, rend_031
cell_032: dl 0x130202, rend_032
cell_033: dl 0x3B0203, rend_033
cell_034: dl 0x130204, rend_034
cell_035: dl 0x130205, rend_035
cell_036: dl 0x130206, rend_036
cell_037: dl 0x130207, rend_037
cell_038: dl 0x130208, rend_038
cell_039: dl 0x130209, rend_039
cell_040: dl 0x13020A, rend_040
cell_041: dl 0x13020B, rend_041
cell_042: dl 0x13020C, rend_042
cell_043: dl 0x13020D, rend_043
cell_044: dl 0x13020E, rend_044
cell_045: dl 0x130300, rend_045
cell_046: dl 0x130301, rend_046
cell_047: dl 0x0E0302, rend_047
cell_048: dl 0x1D0303, rend_048
cell_049: dl 0x0E0304, rend_049
cell_050: dl 0x130305, rend_050
cell_051: dl 0x130306, rend_051
cell_052: dl 0x130307, rend_052
cell_053: dl 0x130308, rend_053
cell_054: dl 0x130309, rend_054
cell_055: dl 0x13030A, rend_055
cell_056: dl 0x13030B, rend_056
cell_057: dl 0x13030C, rend_057
cell_058: dl 0x13030D, rend_058
cell_059: dl 0x13030E, rend_059
cell_060: dl 0x130400, rend_060
cell_061: dl 0x130401, rend_061
cell_062: dl 0x0E0402, rend_062
cell_063: dl 0x1D0403, rend_063
cell_064: dl 0x0E0404, rend_064
cell_065: dl 0x130405, rend_065
cell_066: dl 0x130406, rend_066
cell_067: dl 0x130407, rend_067
cell_068: dl 0x130408, rend_068
cell_069: dl 0x130409, rend_069
cell_070: dl 0x13040A, rend_070
cell_071: dl 0x13040B, rend_071
cell_072: dl 0x13040C, rend_072
cell_073: dl 0x13040D, rend_073
cell_074: dl 0x13040E, rend_074
cell_075: dl 0x130500, rend_075
cell_076: dl 0x130501, rend_076
cell_077: dl 0x130502, rend_077
cell_078: dl 0x3A0503, rend_078
cell_079: dl 0x130504, rend_079
cell_080: dl 0x130505, rend_080
cell_081: dl 0x130506, rend_081
cell_082: dl 0x130507, rend_082
cell_083: dl 0x130508, rend_083
cell_084: dl 0x130509, rend_084
cell_085: dl 0x13050A, rend_085
cell_086: dl 0x13050B, rend_086
cell_087: dl 0x13050C, rend_087
cell_088: dl 0x13050D, rend_088
cell_089: dl 0x13050E, rend_089
cell_090: dl 0x130600, rend_090
cell_091: dl 0x130601, rend_091
cell_092: dl 0x110602, rend_092
cell_093: dl 0x1D0603, rend_093
cell_094: dl 0x110604, rend_094
cell_095: dl 0x130605, rend_095
cell_096: dl 0x130606, rend_096
cell_097: dl 0x130607, rend_097
cell_098: dl 0x130608, rend_098
cell_099: dl 0x130609, rend_099
cell_100: dl 0x13060A, rend_100
cell_101: dl 0x13060B, rend_101
cell_102: dl 0x13060C, rend_102
cell_103: dl 0x13060D, rend_103
cell_104: dl 0x13060E, rend_104
cell_105: dl 0x130700, rend_105
cell_106: dl 0x130701, rend_106
cell_107: dl 0x0A0702, rend_107
cell_108: dl 0x1D0703, rend_108
cell_109: dl 0x0A0704, rend_109
cell_110: dl 0x130705, rend_110
cell_111: dl 0x130706, rend_111
cell_112: dl 0x130707, rend_112
cell_113: dl 0x130708, rend_113
cell_114: dl 0x130709, rend_114
cell_115: dl 0x13070A, rend_115
cell_116: dl 0x13070B, rend_116
cell_117: dl 0x13070C, rend_117
cell_118: dl 0x13070D, rend_118
cell_119: dl 0x13070E, rend_119
cell_120: dl 0x110800, rend_120
cell_121: dl 0x0A0801, rend_121
cell_122: dl 0x110802, rend_122
cell_123: dl 0x390803, rend_123
cell_124: dl 0x110804, rend_124
cell_125: dl 0x130805, rend_125
cell_126: dl 0x130806, rend_126
cell_127: dl 0x130807, rend_127
cell_128: dl 0x130808, rend_128
cell_129: dl 0x130809, rend_129
cell_130: dl 0x13080A, rend_130
cell_131: dl 0x13080B, rend_131
cell_132: dl 0x13080C, rend_132
cell_133: dl 0x13080D, rend_133
cell_134: dl 0x13080E, rend_134
cell_135: dl 0x1D0900, rend_135
cell_136: dl 0x1D0901, rend_136
cell_137: dl 0x1D0902, rend_137
cell_138: dl 0x1D0903, rend_138
cell_139: dl 0x1D0904, rend_139
cell_140: dl 0x110905, rend_140
cell_141: dl 0x130906, rend_141
cell_142: dl 0x130907, rend_142
cell_143: dl 0x130908, rend_143
cell_144: dl 0x130909, rend_144
cell_145: dl 0x13090A, rend_145
cell_146: dl 0x13090B, rend_146
cell_147: dl 0x13090C, rend_147
cell_148: dl 0x13090D, rend_148
cell_149: dl 0x13090E, rend_149
cell_150: dl 0x1D0A00, rend_150
cell_151: dl 0x1D0A01, rend_151
cell_152: dl 0x1D0A02, rend_152
cell_153: dl 0x1D0A03, rend_153
cell_154: dl 0x1D0A04, rend_154
cell_155: dl 0x0A0A05, rend_155
cell_156: dl 0x130A06, rend_156
cell_157: dl 0x130A07, rend_157
cell_158: dl 0x130A08, rend_158
cell_159: dl 0x130A09, rend_159
cell_160: dl 0x130A0A, rend_160
cell_161: dl 0x130A0B, rend_161
cell_162: dl 0x130A0C, rend_162
cell_163: dl 0x130A0D, rend_163
cell_164: dl 0x130A0E, rend_164
cell_165: dl 0x1D0B00, rend_165
cell_166: dl 0x1D0B01, rend_166
cell_167: dl 0x1D0B02, rend_167
cell_168: dl 0x1D0B03, rend_168
cell_169: dl 0x1D0B04, rend_169
cell_170: dl 0x110B05, rend_170
cell_171: dl 0x130B06, rend_171
cell_172: dl 0x130B07, rend_172
cell_173: dl 0x130B08, rend_173
cell_174: dl 0x130B09, rend_174
cell_175: dl 0x130B0A, rend_175
cell_176: dl 0x130B0B, rend_176
cell_177: dl 0x130B0C, rend_177
cell_178: dl 0x130B0D, rend_178
cell_179: dl 0x130B0E, rend_179
cell_180: dl 0x1D0C00, rend_180
cell_181: dl 0x1D0C01, rend_181
cell_182: dl 0x1D0C02, rend_182
cell_183: dl 0x1D0C03, rend_183
cell_184: dl 0x1D0C04, rend_184
cell_185: dl 0x0A0C05, rend_185
cell_186: dl 0x130C06, rend_186
cell_187: dl 0x130C07, rend_187
cell_188: dl 0x130C08, rend_188
cell_189: dl 0x130C09, rend_189
cell_190: dl 0x130C0A, rend_190
cell_191: dl 0x130C0B, rend_191
cell_192: dl 0x130C0C, rend_192
cell_193: dl 0x130C0D, rend_193
cell_194: dl 0x130C0E, rend_194
cell_195: dl 0x1D0D00, rend_195
cell_196: dl 0x1D0D01, rend_196
cell_197: dl 0x1D0D02, rend_197
cell_198: dl 0x1D0D03, rend_198
cell_199: dl 0x1D0D04, rend_199
cell_200: dl 0x110D05, rend_200
cell_201: dl 0x130D06, rend_201
cell_202: dl 0x130D07, rend_202
cell_203: dl 0x130D08, rend_203
cell_204: dl 0x130D09, rend_204
cell_205: dl 0x130D0A, rend_205
cell_206: dl 0x130D0B, rend_206
cell_207: dl 0x130D0C, rend_207
cell_208: dl 0x130D0D, rend_208
cell_209: dl 0x130D0E, rend_209
cell_210: dl 0x0A0E00, rend_210
cell_211: dl 0x1E0E01, rend_211
cell_212: dl 0x0A0E02, rend_212
cell_213: dl 0x110E03, rend_213
cell_214: dl 0x0A0E04, rend_214
cell_215: dl 0x130E05, rend_215
cell_216: dl 0x130E06, rend_216
cell_217: dl 0x130E07, rend_217
cell_218: dl 0x130E08, rend_218
cell_219: dl 0x130E09, rend_219
cell_220: dl 0x130E0A, rend_220
cell_221: dl 0x130E0B, rend_221
cell_222: dl 0x130E0C, rend_222
cell_223: dl 0x130E0D, rend_223
cell_224: dl 0x130E0E, rend_224
; cell_id:0 map_x/y:0,0 tile_name: NULL CELL 
rend_000:
; cell_id:1 map_x/y:1,0 tile_name: NULL CELL 
rend_001:
; cell_id:2 map_x/y:2,0 tile_name: NULL CELL 
rend_002:
; cell_id:3 map_x/y:3,0 tile_name: NULL CELL 
rend_003:
; cell_id:4 map_x/y:4,0 tile_name: NULL CELL 
rend_004:
; cell_id:5 map_x/y:5,0 tile_name: NULL CELL 
rend_005:
; cell_id:6 map_x/y:6,0 tile_name: NULL CELL 
rend_006:
; cell_id:7 map_x/y:7,0 tile_name: NULL CELL 
rend_007:
; cell_id:8 map_x/y:8,0 tile_name: NULL CELL 
rend_008:
; cell_id:9 map_x/y:9,0 tile_name: NULL CELL 
rend_009:
; cell_id:10 map_x/y:10,0 tile_name: NULL CELL 
rend_010:
; cell_id:11 map_x/y:11,0 tile_name: NULL CELL 
rend_011:
; cell_id:12 map_x/y:12,0 tile_name: NULL CELL 
rend_012:
; cell_id:13 map_x/y:13,0 tile_name: NULL CELL 
rend_013:
; cell_id:14 map_x/y:14,0 tile_name: NULL CELL 
rend_014:
; cell_id:15 map_x/y:0,1 tile_name: NULL CELL 
rend_015:
; cell_id:16 map_x/y:1,1 tile_name: NULL CELL 
rend_016:
; cell_id:17 map_x/y:2,1 tile_name: NULL CELL 
rend_017:
; cell_id:18 map_x/y:3,1 tile_name: NULL CELL 
rend_018:
; cell_id:19 map_x/y:4,1 tile_name: NULL CELL 
rend_019:
; cell_id:20 map_x/y:5,1 tile_name: NULL CELL 
rend_020:
; cell_id:21 map_x/y:6,1 tile_name: NULL CELL 
rend_021:
; cell_id:22 map_x/y:7,1 tile_name: NULL CELL 
rend_022:
; cell_id:23 map_x/y:8,1 tile_name: NULL CELL 
rend_023:
; cell_id:24 map_x/y:9,1 tile_name: NULL CELL 
rend_024:
; cell_id:25 map_x/y:10,1 tile_name: NULL CELL 
rend_025:
; cell_id:26 map_x/y:11,1 tile_name: NULL CELL 
rend_026:
; cell_id:27 map_x/y:12,1 tile_name: NULL CELL 
rend_027:
; cell_id:28 map_x/y:13,1 tile_name: NULL CELL 
rend_028:
; cell_id:29 map_x/y:14,1 tile_name: NULL CELL 
rend_029:
; cell_id:30 map_x/y:0,2 tile_name: NULL CELL 
rend_030:
; cell_id:31 map_x/y:1,2 tile_name: NULL CELL 
rend_031:
; cell_id:32 map_x/y:2,2 tile_name: NULL CELL 
rend_032:
; cell_id:33 map_x/y:3,2 tile_name: ELEVATOR SWITCH 
rend_033:
; cell_id:34 map_x/y:4,2 tile_name: NULL CELL 
rend_034:
; cell_id:35 map_x/y:5,2 tile_name: NULL CELL 
rend_035:
; cell_id:36 map_x/y:6,2 tile_name: NULL CELL 
rend_036:
; cell_id:37 map_x/y:7,2 tile_name: NULL CELL 
rend_037:
; cell_id:38 map_x/y:8,2 tile_name: NULL CELL 
rend_038:
; cell_id:39 map_x/y:9,2 tile_name: NULL CELL 
rend_039:
; cell_id:40 map_x/y:10,2 tile_name: NULL CELL 
rend_040:
; cell_id:41 map_x/y:11,2 tile_name: NULL CELL 
rend_041:
; cell_id:42 map_x/y:12,2 tile_name: NULL CELL 
rend_042:
; cell_id:43 map_x/y:13,2 tile_name: NULL CELL 
rend_043:
; cell_id:44 map_x/y:14,2 tile_name: NULL CELL 
rend_044:
; cell_id:45 map_x/y:0,3 tile_name: NULL CELL 
rend_045:
; cell_id:46 map_x/y:1,3 tile_name: NULL CELL 
rend_046:
; cell_id:47 map_x/y:2,3 tile_name: WOOD WALL 
rend_047:
; cell_id:48 map_x/y:3,3 tile_name: GREY FLOOR 
rend_048: dl rend_048_0,rend_048_1,rend_048_2,rend_048_3
rend_048_0:
	ld hl, 0x360282 ; BUF_59_054 ELEVATOR SWITCH
	call render_panel
	jp render_scene_return
rend_048_1:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return
rend_048_2:
	ld hl, 0x31027F ; BUF_58_049 ELEVATOR DOOR
	call render_panel
	ld hl, 0x3401AB ; BUF_14_052 WOOD WALL
	call render_panel
	ld hl, 0x3501AC ; BUF_14_053 WOOD WALL
	call render_panel
	jp render_scene_return
rend_048_3:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:49 map_x/y:4,3 tile_name: WOOD WALL 
rend_049:
; cell_id:50 map_x/y:5,3 tile_name: NULL CELL 
rend_050:
; cell_id:51 map_x/y:6,3 tile_name: NULL CELL 
rend_051:
; cell_id:52 map_x/y:7,3 tile_name: NULL CELL 
rend_052:
; cell_id:53 map_x/y:8,3 tile_name: NULL CELL 
rend_053:
; cell_id:54 map_x/y:9,3 tile_name: NULL CELL 
rend_054:
; cell_id:55 map_x/y:10,3 tile_name: NULL CELL 
rend_055:
; cell_id:56 map_x/y:11,3 tile_name: NULL CELL 
rend_056:
; cell_id:57 map_x/y:12,3 tile_name: NULL CELL 
rend_057:
; cell_id:58 map_x/y:13,3 tile_name: NULL CELL 
rend_058:
; cell_id:59 map_x/y:14,3 tile_name: NULL CELL 
rend_059:
; cell_id:60 map_x/y:0,4 tile_name: NULL CELL 
rend_060:
; cell_id:61 map_x/y:1,4 tile_name: NULL CELL 
rend_061:
; cell_id:62 map_x/y:2,4 tile_name: WOOD WALL 
rend_062:
; cell_id:63 map_x/y:3,4 tile_name: GREY FLOOR 
rend_063: dl rend_063_0,rend_063_1,rend_063_2,rend_063_3
rend_063_0:
	ld hl, 0x310281 ; BUF_59_049 ELEVATOR SWITCH
	call render_panel
	ld hl, 0x3401AB ; BUF_14_052 WOOD WALL
	call render_panel
	ld hl, 0x3501AC ; BUF_14_053 WOOD WALL
	call render_panel
	jp render_scene_return
rend_063_1:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return
rend_063_2:
	ld hl, 0x360280 ; BUF_58_054 ELEVATOR DOOR
	call render_panel
	jp render_scene_return
rend_063_3:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:64 map_x/y:4,4 tile_name: WOOD WALL 
rend_064:
; cell_id:65 map_x/y:5,4 tile_name: NULL CELL 
rend_065:
; cell_id:66 map_x/y:6,4 tile_name: NULL CELL 
rend_066:
; cell_id:67 map_x/y:7,4 tile_name: NULL CELL 
rend_067:
; cell_id:68 map_x/y:8,4 tile_name: NULL CELL 
rend_068:
; cell_id:69 map_x/y:9,4 tile_name: NULL CELL 
rend_069:
; cell_id:70 map_x/y:10,4 tile_name: NULL CELL 
rend_070:
; cell_id:71 map_x/y:11,4 tile_name: NULL CELL 
rend_071:
; cell_id:72 map_x/y:12,4 tile_name: NULL CELL 
rend_072:
; cell_id:73 map_x/y:13,4 tile_name: NULL CELL 
rend_073:
; cell_id:74 map_x/y:14,4 tile_name: NULL CELL 
rend_074:
; cell_id:75 map_x/y:0,5 tile_name: NULL CELL 
rend_075:
; cell_id:76 map_x/y:1,5 tile_name: NULL CELL 
rend_076:
; cell_id:77 map_x/y:2,5 tile_name: NULL CELL 
rend_077:
; cell_id:78 map_x/y:3,5 tile_name: ELEVATOR DOOR 
rend_078:
; cell_id:79 map_x/y:4,5 tile_name: NULL CELL 
rend_079:
; cell_id:80 map_x/y:5,5 tile_name: NULL CELL 
rend_080:
; cell_id:81 map_x/y:6,5 tile_name: NULL CELL 
rend_081:
; cell_id:82 map_x/y:7,5 tile_name: NULL CELL 
rend_082:
; cell_id:83 map_x/y:8,5 tile_name: NULL CELL 
rend_083:
; cell_id:84 map_x/y:9,5 tile_name: NULL CELL 
rend_084:
; cell_id:85 map_x/y:10,5 tile_name: NULL CELL 
rend_085:
; cell_id:86 map_x/y:11,5 tile_name: NULL CELL 
rend_086:
; cell_id:87 map_x/y:12,5 tile_name: NULL CELL 
rend_087:
; cell_id:88 map_x/y:13,5 tile_name: NULL CELL 
rend_088:
; cell_id:89 map_x/y:14,5 tile_name: NULL CELL 
rend_089:
; cell_id:90 map_x/y:0,6 tile_name: NULL CELL 
rend_090:
; cell_id:91 map_x/y:1,6 tile_name: NULL CELL 
rend_091:
; cell_id:92 map_x/y:2,6 tile_name: BLUE WALL 
rend_092:
; cell_id:93 map_x/y:3,6 tile_name: GREY FLOOR 
rend_093: dl rend_093_0,rend_093_1,rend_093_2,rend_093_3
rend_093_0:
	ld hl, 0x360280 ; BUF_58_054 ELEVATOR DOOR
	call render_panel
	jp render_scene_return
rend_093_1:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_093_2:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_093_3:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:94 map_x/y:4,6 tile_name: BLUE WALL 
rend_094:
; cell_id:95 map_x/y:5,6 tile_name: NULL CELL 
rend_095:
; cell_id:96 map_x/y:6,6 tile_name: NULL CELL 
rend_096:
; cell_id:97 map_x/y:7,6 tile_name: NULL CELL 
rend_097:
; cell_id:98 map_x/y:8,6 tile_name: NULL CELL 
rend_098:
; cell_id:99 map_x/y:9,6 tile_name: NULL CELL 
rend_099:
; cell_id:100 map_x/y:10,6 tile_name: NULL CELL 
rend_100:
; cell_id:101 map_x/y:11,6 tile_name: NULL CELL 
rend_101:
; cell_id:102 map_x/y:12,6 tile_name: NULL CELL 
rend_102:
; cell_id:103 map_x/y:13,6 tile_name: NULL CELL 
rend_103:
; cell_id:104 map_x/y:14,6 tile_name: NULL CELL 
rend_104:
; cell_id:105 map_x/y:0,7 tile_name: NULL CELL 
rend_105:
; cell_id:106 map_x/y:1,7 tile_name: NULL CELL 
rend_106:
; cell_id:107 map_x/y:2,7 tile_name: LIGHT GREY WALL 
rend_107:
; cell_id:108 map_x/y:3,7 tile_name: GREY FLOOR 
rend_108: dl rend_108_0,rend_108_1,rend_108_2,rend_108_3
rend_108_0:
	ld hl, 0x31027F ; BUF_58_049 ELEVATOR DOOR
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_108_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_108_2:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_108_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:109 map_x/y:4,7 tile_name: LIGHT GREY WALL 
rend_109:
; cell_id:110 map_x/y:5,7 tile_name: NULL CELL 
rend_110:
; cell_id:111 map_x/y:6,7 tile_name: NULL CELL 
rend_111:
; cell_id:112 map_x/y:7,7 tile_name: NULL CELL 
rend_112:
; cell_id:113 map_x/y:8,7 tile_name: NULL CELL 
rend_113:
; cell_id:114 map_x/y:9,7 tile_name: NULL CELL 
rend_114:
; cell_id:115 map_x/y:10,7 tile_name: NULL CELL 
rend_115:
; cell_id:116 map_x/y:11,7 tile_name: NULL CELL 
rend_116:
; cell_id:117 map_x/y:12,7 tile_name: NULL CELL 
rend_117:
; cell_id:118 map_x/y:13,7 tile_name: NULL CELL 
rend_118:
; cell_id:119 map_x/y:14,7 tile_name: NULL CELL 
rend_119:
; cell_id:120 map_x/y:0,8 tile_name: BLUE WALL 
rend_120:
; cell_id:121 map_x/y:1,8 tile_name: LIGHT GREY WALL 
rend_121:
; cell_id:122 map_x/y:2,8 tile_name: BLUE WALL 
rend_122:
; cell_id:123 map_x/y:3,8 tile_name: REGULAR DOOR 
rend_123:
; cell_id:124 map_x/y:4,8 tile_name: BLUE WALL 
rend_124:
; cell_id:125 map_x/y:5,8 tile_name: NULL CELL 
rend_125:
; cell_id:126 map_x/y:6,8 tile_name: NULL CELL 
rend_126:
; cell_id:127 map_x/y:7,8 tile_name: NULL CELL 
rend_127:
; cell_id:128 map_x/y:8,8 tile_name: NULL CELL 
rend_128:
; cell_id:129 map_x/y:9,8 tile_name: NULL CELL 
rend_129:
; cell_id:130 map_x/y:10,8 tile_name: NULL CELL 
rend_130:
; cell_id:131 map_x/y:11,8 tile_name: NULL CELL 
rend_131:
; cell_id:132 map_x/y:12,8 tile_name: NULL CELL 
rend_132:
; cell_id:133 map_x/y:13,8 tile_name: NULL CELL 
rend_133:
; cell_id:134 map_x/y:14,8 tile_name: NULL CELL 
rend_134:
; cell_id:135 map_x/y:0,9 tile_name: GREY FLOOR 
rend_135: dl rend_135_0,rend_135_1,rend_135_2,rend_135_3
rend_135_0:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_135_1:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x120207 ; BUF_17_018 BLUE WALL
	call render_panel
	ld hl, 0x130208 ; BUF_17_019 BLUE WALL
	call render_panel
	ld hl, 0x22026A ; BUF_57_034 REGULAR DOOR
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_135_2:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B025D ; BUF_57_011 REGULAR DOOR
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0204 ; BUF_17_015 BLUE WALL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_135_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:136 map_x/y:1,9 tile_name: GREY FLOOR 
rend_136: dl rend_136_0,rend_136_1,rend_136_2,rend_136_3
rend_136_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_136_1:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x220217 ; BUF_17_034 BLUE WALL
	call render_panel
	ld hl, 0x2D0275 ; BUF_57_045 REGULAR DOOR
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_136_2:
	ld hl, 0x0A025C ; BUF_57_010 REGULAR DOOR
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x19020E ; BUF_17_025 BLUE WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_136_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:137 map_x/y:2,9 tile_name: GREY FLOOR 
rend_137: dl rend_137_0,rend_137_1,rend_137_2,rend_137_3
rend_137_0:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_137_1:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x34027C ; BUF_57_052 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_137_2:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C025E ; BUF_57_012 REGULAR DOOR
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17020C ; BUF_17_023 BLUE WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_137_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:138 map_x/y:3,9 tile_name: GREY FLOOR 
rend_138: dl rend_138_0,rend_138_1,rend_138_2,rend_138_3
rend_138_0:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_138_1:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_138_2:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0260 ; BUF_57_014 REGULAR DOOR
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x15020A ; BUF_17_021 BLUE WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_138_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x230218 ; BUF_17_035 BLUE WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:139 map_x/y:4,9 tile_name: GREY FLOOR 
rend_139: dl rend_139_0,rend_139_1,rend_139_2,rend_139_3
rend_139_0:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_139_1:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_139_2:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100262 ; BUF_57_016 REGULAR DOOR
	call render_panel
	ld hl, 0x12010A ; BUF_10_018 LIGHT GREY WALL
	call render_panel
	ld hl, 0x130208 ; BUF_17_019 BLUE WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_139_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x140209 ; BUF_17_020 BLUE WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35027D ; BUF_57_053 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:140 map_x/y:5,9 tile_name: BLUE WALL 
rend_140:
; cell_id:141 map_x/y:6,9 tile_name: NULL CELL 
rend_141:
; cell_id:142 map_x/y:7,9 tile_name: NULL CELL 
rend_142:
; cell_id:143 map_x/y:8,9 tile_name: NULL CELL 
rend_143:
; cell_id:144 map_x/y:9,9 tile_name: NULL CELL 
rend_144:
; cell_id:145 map_x/y:10,9 tile_name: NULL CELL 
rend_145:
; cell_id:146 map_x/y:11,9 tile_name: NULL CELL 
rend_146:
; cell_id:147 map_x/y:12,9 tile_name: NULL CELL 
rend_147:
; cell_id:148 map_x/y:13,9 tile_name: NULL CELL 
rend_148:
; cell_id:149 map_x/y:14,9 tile_name: NULL CELL 
rend_149:
; cell_id:150 map_x/y:0,10 tile_name: GREY FLOOR 
rend_150: dl rend_150_0,rend_150_1,rend_150_2,rend_150_3
rend_150_0:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_150_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100205 ; BUF_17_016 BLUE WALL
	call render_panel
	ld hl, 0x15020A ; BUF_17_021 BLUE WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x24026C ; BUF_57_036 REGULAR DOOR
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_150_2:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0264 ; BUF_57_028 REGULAR DOOR
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200215 ; BUF_17_032 BLUE WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_150_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:151 map_x/y:1,10 tile_name: GREY FLOOR 
rend_151: dl rend_151_0,rend_151_1,rend_151_2,rend_151_3
rend_151_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return
rend_151_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210216 ; BUF_17_033 BLUE WALL
	call render_panel
	ld hl, 0x240219 ; BUF_17_036 BLUE WALL
	call render_panel
	ld hl, 0x2F0277 ; BUF_57_047 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_151_2:
	ld hl, 0x1B0263 ; BUF_57_027 REGULAR DOOR
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_151_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:152 map_x/y:2,10 tile_name: GREY FLOOR 
rend_152: dl rend_152_0,rend_152_1,rend_152_2,rend_152_3
rend_152_0:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33027B ; BUF_57_051 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_152_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_152_2:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0265 ; BUF_57_029 REGULAR DOOR
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26021B ; BUF_17_038 BLUE WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_152_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:153 map_x/y:3,10 tile_name: GREY FLOOR 
rend_153: dl rend_153_0,rend_153_1,rend_153_2,rend_153_3
rend_153_0:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return
rend_153_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return
rend_153_2:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0267 ; BUF_57_031 REGULAR DOOR
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x240219 ; BUF_17_036 BLUE WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_153_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25021A ; BUF_17_037 BLUE WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:154 map_x/y:4,10 tile_name: GREY FLOOR 
rend_154: dl rend_154_0,rend_154_1,rend_154_2,rend_154_3
rend_154_0:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32027A ; BUF_57_050 REGULAR DOOR
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_154_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_154_2:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210269 ; BUF_57_033 REGULAR DOOR
	call render_panel
	ld hl, 0x220217 ; BUF_17_034 BLUE WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_154_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16020B ; BUF_17_022 BLUE WALL
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:155 map_x/y:5,10 tile_name: LIGHT GREY WALL 
rend_155:
; cell_id:156 map_x/y:6,10 tile_name: NULL CELL 
rend_156:
; cell_id:157 map_x/y:7,10 tile_name: NULL CELL 
rend_157:
; cell_id:158 map_x/y:8,10 tile_name: NULL CELL 
rend_158:
; cell_id:159 map_x/y:9,10 tile_name: NULL CELL 
rend_159:
; cell_id:160 map_x/y:10,10 tile_name: NULL CELL 
rend_160:
; cell_id:161 map_x/y:11,10 tile_name: NULL CELL 
rend_161:
; cell_id:162 map_x/y:12,10 tile_name: NULL CELL 
rend_162:
; cell_id:163 map_x/y:13,10 tile_name: NULL CELL 
rend_163:
; cell_id:164 map_x/y:14,10 tile_name: NULL CELL 
rend_164:
; cell_id:165 map_x/y:0,11 tile_name: GREY FLOOR 
rend_165: dl rend_165_0,rend_165_1,rend_165_2,rend_165_3
rend_165_0:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_165_1:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x17020C ; BUF_17_023 BLUE WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26026E ; BUF_57_038 REGULAR DOOR
	call render_panel
	ld hl, 0x27021C ; BUF_17_039 BLUE WALL
	call render_panel
	jp render_scene_return
rend_165_2:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290271 ; BUF_57_041 REGULAR DOOR
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_165_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:166 map_x/y:1,11 tile_name: GREY FLOOR 
rend_166: dl rend_166_0,rend_166_1,rend_166_2,rend_166_3
rend_166_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2C0274 ; BUF_57_044 REGULAR DOOR
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_166_1:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x26021B ; BUF_17_038 BLUE WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_166_2:
	ld hl, 0x280270 ; BUF_57_040 REGULAR DOOR
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_166_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:167 map_x/y:2,11 tile_name: GREY FLOOR 
rend_167: dl rend_167_0,rend_167_1,rend_167_2,rend_167_3
rend_167_0:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0272 ; BUF_57_042 REGULAR DOOR
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	jp render_scene_return
rend_167_1:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	jp render_scene_return
rend_167_2:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A0272 ; BUF_57_042 REGULAR DOOR
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_167_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:168 map_x/y:3,11 tile_name: GREY FLOOR 
rend_168: dl rend_168_0,rend_168_1,rend_168_2,rend_168_3
rend_168_0:
	ld hl, 0x280270 ; BUF_57_040 REGULAR DOOR
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return
rend_168_1:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_168_2:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0274 ; BUF_57_044 REGULAR DOOR
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_168_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27021C ; BUF_17_039 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:169 map_x/y:4,11 tile_name: GREY FLOOR 
rend_169: dl rend_169_0,rend_169_1,rend_169_2,rend_169_3
rend_169_0:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290271 ; BUF_57_041 REGULAR DOOR
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_169_1:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_169_2:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_169_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x18020D ; BUF_17_024 BLUE WALL
	call render_panel
	ld hl, 0x26026E ; BUF_57_038 REGULAR DOOR
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:170 map_x/y:5,11 tile_name: BLUE WALL 
rend_170:
; cell_id:171 map_x/y:6,11 tile_name: NULL CELL 
rend_171:
; cell_id:172 map_x/y:7,11 tile_name: NULL CELL 
rend_172:
; cell_id:173 map_x/y:8,11 tile_name: NULL CELL 
rend_173:
; cell_id:174 map_x/y:9,11 tile_name: NULL CELL 
rend_174:
; cell_id:175 map_x/y:10,11 tile_name: NULL CELL 
rend_175:
; cell_id:176 map_x/y:11,11 tile_name: NULL CELL 
rend_176:
; cell_id:177 map_x/y:12,11 tile_name: NULL CELL 
rend_177:
; cell_id:178 map_x/y:13,11 tile_name: NULL CELL 
rend_178:
; cell_id:179 map_x/y:14,11 tile_name: NULL CELL 
rend_179:
; cell_id:180 map_x/y:0,12 tile_name: GREY FLOOR 
rend_180: dl rend_180_0,rend_180_1,rend_180_2,rend_180_3
rend_180_0:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x210269 ; BUF_57_033 REGULAR DOOR
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_180_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0204 ; BUF_17_015 BLUE WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x19020E ; BUF_17_025 BLUE WALL
	call render_panel
	ld hl, 0x25021A ; BUF_17_037 BLUE WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_180_2:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32027A ; BUF_57_050 REGULAR DOOR
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_180_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:181 map_x/y:1,12 tile_name: GREY FLOOR 
rend_181: dl rend_181_0,rend_181_1,rend_181_2,rend_181_3
rend_181_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0267 ; BUF_57_031 REGULAR DOOR
	call render_panel
	ld hl, 0x210216 ; BUF_17_033 BLUE WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_181_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200215 ; BUF_17_032 BLUE WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return
rend_181_2:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_181_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:182 map_x/y:2,12 tile_name: GREY FLOOR 
rend_182: dl rend_182_0,rend_182_1,rend_182_2,rend_182_3
rend_182_0:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0265 ; BUF_57_029 REGULAR DOOR
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27021C ; BUF_17_039 BLUE WALL
	call render_panel
	jp render_scene_return
rend_182_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_182_2:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x33027B ; BUF_57_051 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_182_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:183 map_x/y:3,12 tile_name: GREY FLOOR 
rend_183: dl rend_183_0,rend_183_1,rend_183_2,rend_183_3
rend_183_0:
	ld hl, 0x1B0263 ; BUF_57_027 REGULAR DOOR
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200215 ; BUF_17_032 BLUE WALL
	call render_panel
	ld hl, 0x25021A ; BUF_17_037 BLUE WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_183_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return
rend_183_2:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_183_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0277 ; BUF_57_047 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:184 map_x/y:4,12 tile_name: GREY FLOOR 
rend_184: dl rend_184_0,rend_184_1,rend_184_2,rend_184_3
rend_184_0:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0264 ; BUF_57_028 REGULAR DOOR
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x230218 ; BUF_17_035 BLUE WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_184_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_184_2:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_184_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A020F ; BUF_17_026 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24026C ; BUF_57_036 REGULAR DOOR
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:185 map_x/y:5,12 tile_name: LIGHT GREY WALL 
rend_185:
; cell_id:186 map_x/y:6,12 tile_name: NULL CELL 
rend_186:
; cell_id:187 map_x/y:7,12 tile_name: NULL CELL 
rend_187:
; cell_id:188 map_x/y:8,12 tile_name: NULL CELL 
rend_188:
; cell_id:189 map_x/y:9,12 tile_name: NULL CELL 
rend_189:
; cell_id:190 map_x/y:10,12 tile_name: NULL CELL 
rend_190:
; cell_id:191 map_x/y:11,12 tile_name: NULL CELL 
rend_191:
; cell_id:192 map_x/y:12,12 tile_name: NULL CELL 
rend_192:
; cell_id:193 map_x/y:13,12 tile_name: NULL CELL 
rend_193:
; cell_id:194 map_x/y:14,12 tile_name: NULL CELL 
rend_194:
; cell_id:195 map_x/y:0,13 tile_name: GREY FLOOR 
rend_195: dl rend_195_0,rend_195_1,rend_195_2,rend_195_3
rend_195_0:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x100262 ; BUF_57_016 REGULAR DOOR
	call render_panel
	ld hl, 0x120207 ; BUF_17_018 BLUE WALL
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_195_1:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110206 ; BUF_17_017 BLUE WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x230218 ; BUF_17_035 BLUE WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35027D ; BUF_57_053 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_195_2:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_195_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:196 map_x/y:1,13 tile_name: GREY FLOOR 
rend_196: dl rend_196_0,rend_196_1,rend_196_2,rend_196_3
rend_196_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0E0260 ; BUF_57_014 REGULAR DOOR
	call render_panel
	ld hl, 0x100205 ; BUF_17_016 BLUE WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A020F ; BUF_17_026 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_196_1:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_196_2:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_196_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:197 map_x/y:2,13 tile_name: GREY FLOOR 
rend_197: dl rend_197_0,rend_197_1,rend_197_2,rend_197_3
rend_197_0:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C025E ; BUF_57_012 REGULAR DOOR
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x18020D ; BUF_17_024 BLUE WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_197_1:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_197_2:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_197_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34027C ; BUF_57_052 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:198 map_x/y:3,13 tile_name: GREY FLOOR 
rend_198: dl rend_198_0,rend_198_1,rend_198_2,rend_198_3
rend_198_0:
	ld hl, 0x0A025C ; BUF_57_010 REGULAR DOOR
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0204 ; BUF_17_015 BLUE WALL
	call render_panel
	ld hl, 0x16020B ; BUF_17_022 BLUE WALL
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return
rend_198_1:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_198_2:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_198_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0275 ; BUF_57_045 REGULAR DOOR
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:199 map_x/y:4,13 tile_name: GREY FLOOR 
rend_199: dl rend_199_0,rend_199_1,rend_199_2,rend_199_3
rend_199_0:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B025D ; BUF_57_011 REGULAR DOOR
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110206 ; BUF_17_017 BLUE WALL
	call render_panel
	ld hl, 0x140209 ; BUF_17_020 BLUE WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_199_1:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_199_2:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_199_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x12010A ; BUF_10_018 LIGHT GREY WALL
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22026A ; BUF_57_034 REGULAR DOOR
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:200 map_x/y:5,13 tile_name: BLUE WALL 
rend_200:
; cell_id:201 map_x/y:6,13 tile_name: NULL CELL 
rend_201:
; cell_id:202 map_x/y:7,13 tile_name: NULL CELL 
rend_202:
; cell_id:203 map_x/y:8,13 tile_name: NULL CELL 
rend_203:
; cell_id:204 map_x/y:9,13 tile_name: NULL CELL 
rend_204:
; cell_id:205 map_x/y:10,13 tile_name: NULL CELL 
rend_205:
; cell_id:206 map_x/y:11,13 tile_name: NULL CELL 
rend_206:
; cell_id:207 map_x/y:12,13 tile_name: NULL CELL 
rend_207:
; cell_id:208 map_x/y:13,13 tile_name: NULL CELL 
rend_208:
; cell_id:209 map_x/y:14,13 tile_name: NULL CELL 
rend_209:
; cell_id:210 map_x/y:0,14 tile_name: LIGHT GREY WALL 
rend_210:
; cell_id:211 map_x/y:1,14 tile_name: DOOR TO ROOM 0 
rend_211: dl rend_211_0,rend_211_1,rend_211_2,rend_211_3
rend_211_0:
	ld hl, 0x020100 ; BUF_10_002 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0701FE ; BUF_17_007 BLUE WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_2:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:212 map_x/y:2,14 tile_name: LIGHT GREY WALL 
rend_212:
; cell_id:213 map_x/y:3,14 tile_name: BLUE WALL 
rend_213:
; cell_id:214 map_x/y:4,14 tile_name: LIGHT GREY WALL 
rend_214:
; cell_id:215 map_x/y:5,14 tile_name: NULL CELL 
rend_215:
; cell_id:216 map_x/y:6,14 tile_name: NULL CELL 
rend_216:
; cell_id:217 map_x/y:7,14 tile_name: NULL CELL 
rend_217:
; cell_id:218 map_x/y:8,14 tile_name: NULL CELL 
rend_218:
; cell_id:219 map_x/y:9,14 tile_name: NULL CELL 
rend_219:
; cell_id:220 map_x/y:10,14 tile_name: NULL CELL 
rend_220:
; cell_id:221 map_x/y:11,14 tile_name: NULL CELL 
rend_221:
; cell_id:222 map_x/y:12,14 tile_name: NULL CELL 
rend_222:
; cell_id:223 map_x/y:13,14 tile_name: NULL CELL 
rend_223:
; cell_id:224 map_x/y:14,14 tile_name: NULL CELL 
rend_224:
