cells:
; cell label: obj_id map_x map_y, render routine address
; MIND THE LITTLE-ENDIANESS IN THE COORDINATES!!!111
cell_000: dl 0x130000, rend_000
cell_001: dl 0x130100, rend_001
cell_002: dl 0x130200, rend_002
cell_003: dl 0x130300, rend_003
cell_004: dl 0x130400, rend_004
cell_005: dl 0x130500, rend_005
cell_006: dl 0x130600, rend_006
cell_007: dl 0x130700, rend_007
cell_008: dl 0x130800, rend_008
cell_009: dl 0x130900, rend_009
cell_010: dl 0x130A00, rend_010
cell_011: dl 0x130B00, rend_011
cell_012: dl 0x130C00, rend_012
cell_013: dl 0x130D00, rend_013
cell_014: dl 0x130E00, rend_014
cell_015: dl 0x130001, rend_015
cell_016: dl 0x130101, rend_016
cell_017: dl 0x130201, rend_017
cell_018: dl 0x130301, rend_018
cell_019: dl 0x130401, rend_019
cell_020: dl 0x130501, rend_020
cell_021: dl 0x130601, rend_021
cell_022: dl 0x130701, rend_022
cell_023: dl 0x130801, rend_023
cell_024: dl 0x130901, rend_024
cell_025: dl 0x130A01, rend_025
cell_026: dl 0x130B01, rend_026
cell_027: dl 0x130C01, rend_027
cell_028: dl 0x130D01, rend_028
cell_029: dl 0x130E01, rend_029
cell_030: dl 0x130002, rend_030
cell_031: dl 0x130102, rend_031
cell_032: dl 0x130202, rend_032
cell_033: dl 0x130302, rend_033
cell_034: dl 0x130402, rend_034
cell_035: dl 0x130502, rend_035
cell_036: dl 0x130602, rend_036
cell_037: dl 0x130702, rend_037
cell_038: dl 0x130802, rend_038
cell_039: dl 0x130902, rend_039
cell_040: dl 0x130A02, rend_040
cell_041: dl 0x130B02, rend_041
cell_042: dl 0x130C02, rend_042
cell_043: dl 0x130D02, rend_043
cell_044: dl 0x130E02, rend_044
cell_045: dl 0x0C0003, rend_045
cell_046: dl 0x0F0103, rend_046
cell_047: dl 0x1F0203, rend_047
cell_048: dl 0x100303, rend_048
cell_049: dl 0x0E0403, rend_049
cell_050: dl 0x130503, rend_050
cell_051: dl 0x130603, rend_051
cell_052: dl 0x130703, rend_052
cell_053: dl 0x130803, rend_053
cell_054: dl 0x130903, rend_054
cell_055: dl 0x130A03, rend_055
cell_056: dl 0x130B03, rend_056
cell_057: dl 0x130C03, rend_057
cell_058: dl 0x130D03, rend_058
cell_059: dl 0x130E03, rend_059
cell_060: dl 0x1D0004, rend_060
cell_061: dl 0x1D0104, rend_061
cell_062: dl 0x1D0204, rend_062
cell_063: dl 0x1D0304, rend_063
cell_064: dl 0x150404, rend_064
cell_065: dl 0x0E0504, rend_065
cell_066: dl 0x130604, rend_066
cell_067: dl 0x130704, rend_067
cell_068: dl 0x130804, rend_068
cell_069: dl 0x130904, rend_069
cell_070: dl 0x130A04, rend_070
cell_071: dl 0x130B04, rend_071
cell_072: dl 0x130C04, rend_072
cell_073: dl 0x130D04, rend_073
cell_074: dl 0x130E04, rend_074
cell_075: dl 0x1D0005, rend_075
cell_076: dl 0x290105, rend_076
cell_077: dl 0x1D0205, rend_077
cell_078: dl 0x280305, rend_078
cell_079: dl 0x180405, rend_079
cell_080: dl 0x0E0505, rend_080
cell_081: dl 0x130605, rend_081
cell_082: dl 0x130705, rend_082
cell_083: dl 0x130805, rend_083
cell_084: dl 0x130905, rend_084
cell_085: dl 0x130A05, rend_085
cell_086: dl 0x130B05, rend_086
cell_087: dl 0x130C05, rend_087
cell_088: dl 0x130D05, rend_088
cell_089: dl 0x130E05, rend_089
cell_090: dl 0x1D0006, rend_090
cell_091: dl 0x1D0106, rend_091
cell_092: dl 0x170206, rend_092
cell_093: dl 0x1D0306, rend_093
cell_094: dl 0x1D0406, rend_094
cell_095: dl 0x100506, rend_095
cell_096: dl 0x130606, rend_096
cell_097: dl 0x130706, rend_097
cell_098: dl 0x130806, rend_098
cell_099: dl 0x130906, rend_099
cell_100: dl 0x130A06, rend_100
cell_101: dl 0x130B06, rend_101
cell_102: dl 0x130C06, rend_102
cell_103: dl 0x130D06, rend_103
cell_104: dl 0x130E06, rend_104
cell_105: dl 0x1D0007, rend_105
cell_106: dl 0x2A0107, rend_106
cell_107: dl 0x1D0207, rend_107
cell_108: dl 0x2B0307, rend_108
cell_109: dl 0x1D0407, rend_109
cell_110: dl 0x0F0507, rend_110
cell_111: dl 0x130607, rend_111
cell_112: dl 0x130707, rend_112
cell_113: dl 0x130807, rend_113
cell_114: dl 0x130907, rend_114
cell_115: dl 0x130A07, rend_115
cell_116: dl 0x130B07, rend_116
cell_117: dl 0x130C07, rend_117
cell_118: dl 0x130D07, rend_118
cell_119: dl 0x130E07, rend_119
cell_120: dl 0x1D0008, rend_120
cell_121: dl 0x1D0108, rend_121
cell_122: dl 0x1D0208, rend_122
cell_123: dl 0x1D0308, rend_123
cell_124: dl 0x1D0408, rend_124
cell_125: dl 0x0E0508, rend_125
cell_126: dl 0x130608, rend_126
cell_127: dl 0x130708, rend_127
cell_128: dl 0x130808, rend_128
cell_129: dl 0x130908, rend_129
cell_130: dl 0x130A08, rend_130
cell_131: dl 0x130B08, rend_131
cell_132: dl 0x130C08, rend_132
cell_133: dl 0x130D08, rend_133
cell_134: dl 0x130E08, rend_134
cell_135: dl 0x0A0009, rend_135
cell_136: dl 0x390109, rend_136
cell_137: dl 0x110209, rend_137
cell_138: dl 0x100309, rend_138
cell_139: dl 0x0F0409, rend_139
cell_140: dl 0x130509, rend_140
cell_141: dl 0x130609, rend_141
cell_142: dl 0x130709, rend_142
cell_143: dl 0x130809, rend_143
cell_144: dl 0x130909, rend_144
cell_145: dl 0x130A09, rend_145
cell_146: dl 0x130B09, rend_146
cell_147: dl 0x130C09, rend_147
cell_148: dl 0x130D09, rend_148
cell_149: dl 0x130E09, rend_149
cell_150: dl 0x1D000A, rend_150
cell_151: dl 0x1D010A, rend_151
cell_152: dl 0x1D020A, rend_152
cell_153: dl 0x1D030A, rend_153
cell_154: dl 0x30040A, rend_154
cell_155: dl 0x0E050A, rend_155
cell_156: dl 0x13060A, rend_156
cell_157: dl 0x13070A, rend_157
cell_158: dl 0x13080A, rend_158
cell_159: dl 0x13090A, rend_159
cell_160: dl 0x130A0A, rend_160
cell_161: dl 0x130B0A, rend_161
cell_162: dl 0x130C0A, rend_162
cell_163: dl 0x130D0A, rend_163
cell_164: dl 0x130E0A, rend_164
cell_165: dl 0x1D000B, rend_165
cell_166: dl 0x2D010B, rend_166
cell_167: dl 0x1D020B, rend_167
cell_168: dl 0x2C030B, rend_168
cell_169: dl 0x31040B, rend_169
cell_170: dl 0x0D050B, rend_170
cell_171: dl 0x13060B, rend_171
cell_172: dl 0x13070B, rend_172
cell_173: dl 0x13080B, rend_173
cell_174: dl 0x13090B, rend_174
cell_175: dl 0x130A0B, rend_175
cell_176: dl 0x130B0B, rend_176
cell_177: dl 0x130C0B, rend_177
cell_178: dl 0x130D0B, rend_178
cell_179: dl 0x130E0B, rend_179
cell_180: dl 0x1D000C, rend_180
cell_181: dl 0x1D010C, rend_181
cell_182: dl 0x14020C, rend_182
cell_183: dl 0x1D030C, rend_183
cell_184: dl 0x1D040C, rend_184
cell_185: dl 0x0C050C, rend_185
cell_186: dl 0x13060C, rend_186
cell_187: dl 0x13070C, rend_187
cell_188: dl 0x13080C, rend_188
cell_189: dl 0x13090C, rend_189
cell_190: dl 0x130A0C, rend_190
cell_191: dl 0x130B0C, rend_191
cell_192: dl 0x130C0C, rend_192
cell_193: dl 0x130D0C, rend_193
cell_194: dl 0x130E0C, rend_194
cell_195: dl 0x1D000D, rend_195
cell_196: dl 0x2E010D, rend_196
cell_197: dl 0x1D020D, rend_197
cell_198: dl 0x2F030D, rend_198
cell_199: dl 0x1D040D, rend_199
cell_200: dl 0x0B050D, rend_200
cell_201: dl 0x13060D, rend_201
cell_202: dl 0x13070D, rend_202
cell_203: dl 0x13080D, rend_203
cell_204: dl 0x13090D, rend_204
cell_205: dl 0x130A0D, rend_205
cell_206: dl 0x130B0D, rend_206
cell_207: dl 0x130C0D, rend_207
cell_208: dl 0x130D0D, rend_208
cell_209: dl 0x130E0D, rend_209
cell_210: dl 0x1C000E, rend_210
cell_211: dl 0x1D010E, rend_211
cell_212: dl 0x1D020E, rend_212
cell_213: dl 0x1D030E, rend_213
cell_214: dl 0x1D040E, rend_214
cell_215: dl 0x0A050E, rend_215
cell_216: dl 0x13060E, rend_216
cell_217: dl 0x13070E, rend_217
cell_218: dl 0x13080E, rend_218
cell_219: dl 0x13090E, rend_219
cell_220: dl 0x130A0E, rend_220
cell_221: dl 0x130B0E, rend_221
cell_222: dl 0x130C0E, rend_222
cell_223: dl 0x130D0E, rend_223
cell_224: dl 0x130E0E, rend_224
; cell_id:0 map_x/y:0,0 tile_name: NULL CELL 
rend_000:
; cell_id:1 map_x/y:0,1 tile_name: NULL CELL 
rend_001:
; cell_id:2 map_x/y:0,2 tile_name: NULL CELL 
rend_002:
; cell_id:3 map_x/y:0,3 tile_name: NULL CELL 
rend_003:
; cell_id:4 map_x/y:0,4 tile_name: NULL CELL 
rend_004:
; cell_id:5 map_x/y:0,5 tile_name: NULL CELL 
rend_005:
; cell_id:6 map_x/y:0,6 tile_name: NULL CELL 
rend_006:
; cell_id:7 map_x/y:0,7 tile_name: NULL CELL 
rend_007:
; cell_id:8 map_x/y:0,8 tile_name: NULL CELL 
rend_008:
; cell_id:9 map_x/y:0,9 tile_name: NULL CELL 
rend_009:
; cell_id:10 map_x/y:0,10 tile_name: NULL CELL 
rend_010:
; cell_id:11 map_x/y:0,11 tile_name: NULL CELL 
rend_011:
; cell_id:12 map_x/y:0,12 tile_name: NULL CELL 
rend_012:
; cell_id:13 map_x/y:0,13 tile_name: NULL CELL 
rend_013:
; cell_id:14 map_x/y:0,14 tile_name: NULL CELL 
rend_014:
; cell_id:15 map_x/y:1,0 tile_name: NULL CELL 
rend_015:
; cell_id:16 map_x/y:1,1 tile_name: NULL CELL 
rend_016:
; cell_id:17 map_x/y:1,2 tile_name: NULL CELL 
rend_017:
; cell_id:18 map_x/y:1,3 tile_name: NULL CELL 
rend_018:
; cell_id:19 map_x/y:1,4 tile_name: NULL CELL 
rend_019:
; cell_id:20 map_x/y:1,5 tile_name: NULL CELL 
rend_020:
; cell_id:21 map_x/y:1,6 tile_name: NULL CELL 
rend_021:
; cell_id:22 map_x/y:1,7 tile_name: NULL CELL 
rend_022:
; cell_id:23 map_x/y:1,8 tile_name: NULL CELL 
rend_023:
; cell_id:24 map_x/y:1,9 tile_name: NULL CELL 
rend_024:
; cell_id:25 map_x/y:1,10 tile_name: NULL CELL 
rend_025:
; cell_id:26 map_x/y:1,11 tile_name: NULL CELL 
rend_026:
; cell_id:27 map_x/y:1,12 tile_name: NULL CELL 
rend_027:
; cell_id:28 map_x/y:1,13 tile_name: NULL CELL 
rend_028:
; cell_id:29 map_x/y:1,14 tile_name: NULL CELL 
rend_029:
; cell_id:30 map_x/y:2,0 tile_name: NULL CELL 
rend_030:
; cell_id:31 map_x/y:2,1 tile_name: NULL CELL 
rend_031:
; cell_id:32 map_x/y:2,2 tile_name: NULL CELL 
rend_032:
; cell_id:33 map_x/y:2,3 tile_name: NULL CELL 
rend_033:
; cell_id:34 map_x/y:2,4 tile_name: NULL CELL 
rend_034:
; cell_id:35 map_x/y:2,5 tile_name: NULL CELL 
rend_035:
; cell_id:36 map_x/y:2,6 tile_name: NULL CELL 
rend_036:
; cell_id:37 map_x/y:2,7 tile_name: NULL CELL 
rend_037:
; cell_id:38 map_x/y:2,8 tile_name: NULL CELL 
rend_038:
; cell_id:39 map_x/y:2,9 tile_name: NULL CELL 
rend_039:
; cell_id:40 map_x/y:2,10 tile_name: NULL CELL 
rend_040:
; cell_id:41 map_x/y:2,11 tile_name: NULL CELL 
rend_041:
; cell_id:42 map_x/y:2,12 tile_name: NULL CELL 
rend_042:
; cell_id:43 map_x/y:2,13 tile_name: NULL CELL 
rend_043:
; cell_id:44 map_x/y:2,14 tile_name: NULL CELL 
rend_044:
; cell_id:45 map_x/y:3,0 tile_name: STONE ARCH BIRD 
rend_045:
; cell_id:46 map_x/y:3,1 tile_name: HANGING FLAG 
rend_046:
; cell_id:47 map_x/y:3,2 tile_name: DOOR TO ROOM 1 
rend_047: dl rend_047_0,rend_047_1,rend_047_2,rend_047_3
rend_047_0:
	ld hl, 0x3601DA ; BUF_15_054 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_047_1:
	ld hl, 0x040101 ; BUF_10_004 LIGHT GREY WALL
	call render_panel
	ld hl, 0x050180 ; BUF_14_005 WOOD WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1801BC ; BUF_15_024 HANGING FLAG
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2701EE ; BUF_16_039 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_047_2:
	ld hl, 0x3601FD ; BUF_16_054 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_047_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:48 map_x/y:3,3 tile_name: WOOD EAGLE 
rend_048:
; cell_id:49 map_x/y:3,4 tile_name: WOOD WALL 
rend_049:
; cell_id:50 map_x/y:3,5 tile_name: NULL CELL 
rend_050:
; cell_id:51 map_x/y:3,6 tile_name: NULL CELL 
rend_051:
; cell_id:52 map_x/y:3,7 tile_name: NULL CELL 
rend_052:
; cell_id:53 map_x/y:3,8 tile_name: NULL CELL 
rend_053:
; cell_id:54 map_x/y:3,9 tile_name: NULL CELL 
rend_054:
; cell_id:55 map_x/y:3,10 tile_name: NULL CELL 
rend_055:
; cell_id:56 map_x/y:3,11 tile_name: NULL CELL 
rend_056:
; cell_id:57 map_x/y:3,12 tile_name: NULL CELL 
rend_057:
; cell_id:58 map_x/y:3,13 tile_name: NULL CELL 
rend_058:
; cell_id:59 map_x/y:3,14 tile_name: NULL CELL 
rend_059:
; cell_id:60 map_x/y:4,0 tile_name: GREY FLOOR 
rend_060: dl rend_060_0,rend_060_1,rend_060_2,rend_060_3
rend_060_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_060_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C025E ; BUF_57_012 REGULAR DOOR
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x1001E1 ; BUF_16_016 WOOD EAGLE
	call render_panel
	ld hl, 0x1201B6 ; BUF_15_018 HANGING FLAG
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_060_2:
	ld hl, 0x0A0181 ; BUF_14_010 WOOD WALL
	call render_panel
	ld hl, 0x0B0182 ; BUF_14_011 WOOD WALL
	call render_panel
	ld hl, 0x0D01DE ; BUF_16_013 WOOD EAGLE
	call render_panel
	ld hl, 0x0F01B3 ; BUF_15_015 HANGING FLAG
	call render_panel
	ld hl, 0x110188 ; BUF_14_017 WOOD WALL
	call render_panel
	ld hl, 0x14018B ; BUF_14_020 WOOD WALL
	call render_panel
	ld hl, 0x2301EA ; BUF_16_035 WOOD EAGLE
	call render_panel
	ld hl, 0x2E0276 ; BUF_57_046 REGULAR DOOR
	call render_panel
	ld hl, 0x3501D9 ; BUF_15_053 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_060_3:
	ld hl, 0x360167 ; BUF_12_054 STONE ARCH BIRD
	call render_panel
	jp render_scene_return

; cell_id:61 map_x/y:4,1 tile_name: GREY FLOOR 
rend_061: dl rend_061_0,rend_061_1,rend_061_2,rend_061_3
rend_061_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x340165 ; BUF_12_052 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_061_1:
	ld hl, 0x0A025C ; BUF_57_010 REGULAR DOOR
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0E01DF ; BUF_16_014 WOOD EAGLE
	call render_panel
	ld hl, 0x1001B4 ; BUF_15_016 HANGING FLAG
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A0191 ; BUF_14_026 WOOD WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_061_2:
	ld hl, 0x1B0192 ; BUF_14_027 WOOD WALL
	call render_panel
	ld hl, 0x1C0193 ; BUF_14_028 WOOD WALL
	call render_panel
	ld hl, 0x1E01E5 ; BUF_16_030 WOOD EAGLE
	call render_panel
	ld hl, 0x2001C4 ; BUF_15_032 HANGING FLAG
	call render_panel
	ld hl, 0x23019A ; BUF_14_035 WOOD WALL
	call render_panel
	ld hl, 0x2E01F5 ; BUF_16_046 WOOD EAGLE
	call render_panel
	ld hl, 0x35027D ; BUF_57_053 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_061_3:
	ld hl, 0x3601DA ; BUF_15_054 HANGING FLAG
	call render_panel
	jp render_scene_return

; cell_id:62 map_x/y:4,2 tile_name: GREY FLOOR 
rend_062: dl rend_062_0,rend_062_1,rend_062_2,rend_062_3
rend_062_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D015E ; BUF_12_045 STONE ARCH BIRD
	call render_panel
	ld hl, 0x3401D8 ; BUF_15_052 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_062_1:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B025D ; BUF_57_011 REGULAR DOOR
	call render_panel
	ld hl, 0x0C01DD ; BUF_16_012 WOOD EAGLE
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E01B2 ; BUF_15_014 HANGING FLAG
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x18018F ; BUF_14_024 WOOD WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2701CB ; BUF_15_039 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_062_2:
	ld hl, 0x28019F ; BUF_14_040 WOOD WALL
	call render_panel
	ld hl, 0x2901A0 ; BUF_14_041 WOOD WALL
	call render_panel
	ld hl, 0x2B01F2 ; BUF_16_043 WOOD EAGLE
	call render_panel
	ld hl, 0x2E01A5 ; BUF_14_046 WOOD WALL
	call render_panel
	ld hl, 0x3501FC ; BUF_16_053 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_062_3:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:63 map_x/y:4,3 tile_name: GREY FLOOR 
rend_063: dl rend_063_0,rend_063_1,rend_063_2,rend_063_3
rend_063_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x220156 ; BUF_12_034 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2D01D1 ; BUF_15_045 HANGING FLAG
	call render_panel
	ld hl, 0x34027C ; BUF_57_052 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_063_1:
	ld hl, 0x0A01DB ; BUF_16_010 WOOD EAGLE
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C01B0 ; BUF_15_012 HANGING FLAG
	call render_panel
	ld hl, 0x0D025F ; BUF_57_013 REGULAR DOOR
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16018D ; BUF_14_022 WOOD WALL
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2501C9 ; BUF_15_037 HANGING FLAG
	call render_panel
	ld hl, 0x3001F7 ; BUF_16_048 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_063_2:
	ld hl, 0x3101A8 ; BUF_14_049 WOOD WALL
	call render_panel
	ld hl, 0x3201A9 ; BUF_14_050 WOOD WALL
	call render_panel
	ld hl, 0x3501AC ; BUF_14_053 WOOD WALL
	call render_panel
	jp render_scene_return
rend_063_3:
	ld hl, 0x3601FD ; BUF_16_054 WOOD EAGLE
	call render_panel
	jp render_scene_return

; cell_id:64 map_x/y:4,4 tile_name: BARREL 
rend_064:
; cell_id:65 map_x/y:4,5 tile_name: WOOD WALL 
rend_065:
; cell_id:66 map_x/y:4,6 tile_name: NULL CELL 
rend_066:
; cell_id:67 map_x/y:4,7 tile_name: NULL CELL 
rend_067:
; cell_id:68 map_x/y:4,8 tile_name: NULL CELL 
rend_068:
; cell_id:69 map_x/y:4,9 tile_name: NULL CELL 
rend_069:
; cell_id:70 map_x/y:4,10 tile_name: NULL CELL 
rend_070:
; cell_id:71 map_x/y:4,11 tile_name: NULL CELL 
rend_071:
; cell_id:72 map_x/y:4,12 tile_name: NULL CELL 
rend_072:
; cell_id:73 map_x/y:4,13 tile_name: NULL CELL 
rend_073:
; cell_id:74 map_x/y:4,14 tile_name: NULL CELL 
rend_074:
; cell_id:75 map_x/y:5,0 tile_name: GREY FLOOR 
rend_075: dl rend_075_0,rend_075_1,rend_075_2,rend_075_3
rend_075_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_075_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0265 ; BUF_57_029 REGULAR DOOR
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x2101E8 ; BUF_16_033 WOOD EAGLE
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_075_2:
	ld hl, 0x0A0181 ; BUF_14_010 WOOD WALL
	call render_panel
	ld hl, 0x0B01DC ; BUF_16_011 WOOD EAGLE
	call render_panel
	ld hl, 0x0C0183 ; BUF_14_012 WOOD WALL
	call render_panel
	ld hl, 0x0D01B1 ; BUF_15_013 HANGING FLAG
	call render_panel
	ld hl, 0x0F0186 ; BUF_14_015 WOOD WALL
	call render_panel
	ld hl, 0x16018D ; BUF_14_022 WOOD WALL
	call render_panel
	ld hl, 0x1901BD ; BUF_15_025 HANGING FLAG
	call render_panel
	ld hl, 0x2501EC ; BUF_16_037 WOOD EAGLE
	call render_panel
	ld hl, 0x300278 ; BUF_57_048 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_075_3:
	ld hl, 0x310162 ; BUF_12_049 STONE ARCH BIRD
	call render_panel
	ld hl, 0x3201D6 ; BUF_15_050 HANGING FLAG
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:76 map_x/y:5,1 tile_name: GOLD CHALISE 
rend_076: dl rend_076_0,rend_076_1,rend_076_2,rend_076_3
rend_076_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_076_1:
	ld hl, 0x1B0263 ; BUF_57_027 REGULAR DOOR
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F01E6 ; BUF_16_031 WOOD EAGLE
	call render_panel
	ld hl, 0x2101C5 ; BUF_15_033 HANGING FLAG
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_076_2:
	ld hl, 0x1B0192 ; BUF_14_027 WOOD WALL
	call render_panel
	ld hl, 0x1C01E3 ; BUF_16_028 WOOD EAGLE
	call render_panel
	ld hl, 0x1D0194 ; BUF_14_029 WOOD WALL
	call render_panel
	ld hl, 0x1E01C2 ; BUF_15_030 HANGING FLAG
	call render_panel
	ld hl, 0x200197 ; BUF_14_032 WOOD WALL
	call render_panel
	ld hl, 0x25019C ; BUF_14_037 WOOD WALL
	call render_panel
	ld hl, 0x3001F7 ; BUF_16_048 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_076_3:
	ld hl, 0x3101D5 ; BUF_15_049 HANGING FLAG
	call render_panel
	ld hl, 0x32027A ; BUF_57_050 REGULAR DOOR
	call render_panel
	ld hl, 0x330164 ; BUF_12_051 STONE ARCH BIRD
	call render_panel
	jp render_scene_return

; cell_id:77 map_x/y:5,2 tile_name: GREY FLOOR 
rend_077: dl rend_077_0,rend_077_1,rend_077_2,rend_077_3
rend_077_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0160 ; BUF_12_047 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_077_1:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C0264 ; BUF_57_028 REGULAR DOOR
	call render_panel
	ld hl, 0x1D01E4 ; BUF_16_029 WOOD EAGLE
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F01C3 ; BUF_15_031 HANGING FLAG
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27019E ; BUF_14_039 WOOD WALL
	call render_panel
	jp render_scene_return
rend_077_2:
	ld hl, 0x28019F ; BUF_14_040 WOOD WALL
	call render_panel
	ld hl, 0x2901F0 ; BUF_16_041 WOOD EAGLE
	call render_panel
	ld hl, 0x2A01A1 ; BUF_14_042 WOOD WALL
	call render_panel
	ld hl, 0x2B01CF ; BUF_15_043 HANGING FLAG
	call render_panel
	ld hl, 0x3001A7 ; BUF_14_048 WOOD WALL
	call render_panel
	jp render_scene_return
rend_077_3:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x3201F9 ; BUF_16_050 WOOD EAGLE
	call render_panel
	ld hl, 0x3301D7 ; BUF_15_051 HANGING FLAG
	call render_panel
	jp render_scene_return

; cell_id:78 map_x/y:5,3 tile_name: HEALTH PACK 
rend_078: dl rend_078_0,rend_078_1,rend_078_2,rend_078_3
rend_078_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x240157 ; BUF_12_036 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2F01D3 ; BUF_15_047 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_078_1:
	ld hl, 0x1B01E2 ; BUF_16_027 WOOD EAGLE
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D01C1 ; BUF_15_029 HANGING FLAG
	call render_panel
	ld hl, 0x1E0266 ; BUF_57_030 REGULAR DOOR
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25019C ; BUF_14_037 WOOD WALL
	call render_panel
	ld hl, 0x3001D4 ; BUF_15_048 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_078_2:
	ld hl, 0x3101A8 ; BUF_14_049 WOOD WALL
	call render_panel
	ld hl, 0x3201F9 ; BUF_16_050 WOOD EAGLE
	call render_panel
	ld hl, 0x3301AA ; BUF_14_051 WOOD WALL
	call render_panel
	jp render_scene_return
rend_078_3:
	ld hl, 0x3101F8 ; BUF_16_049 WOOD EAGLE
	call render_panel
	ld hl, 0x3201A9 ; BUF_14_050 WOOD WALL
	call render_panel
	ld hl, 0x33027B ; BUF_57_051 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:79 map_x/y:5,4 tile_name: RADIOACTIVE BARREL 
rend_079:
; cell_id:80 map_x/y:5,5 tile_name: WOOD WALL 
rend_080:
; cell_id:81 map_x/y:5,6 tile_name: NULL CELL 
rend_081:
; cell_id:82 map_x/y:5,7 tile_name: NULL CELL 
rend_082:
; cell_id:83 map_x/y:5,8 tile_name: NULL CELL 
rend_083:
; cell_id:84 map_x/y:5,9 tile_name: NULL CELL 
rend_084:
; cell_id:85 map_x/y:5,10 tile_name: NULL CELL 
rend_085:
; cell_id:86 map_x/y:5,11 tile_name: NULL CELL 
rend_086:
; cell_id:87 map_x/y:5,12 tile_name: NULL CELL 
rend_087:
; cell_id:88 map_x/y:5,13 tile_name: NULL CELL 
rend_088:
; cell_id:89 map_x/y:5,14 tile_name: NULL CELL 
rend_089:
; cell_id:90 map_x/y:6,0 tile_name: GREY FLOOR 
rend_090: dl rend_090_0,rend_090_1,rend_090_2,rend_090_3
rend_090_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_090_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0272 ; BUF_57_042 REGULAR DOOR
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_090_2:
	ld hl, 0x0A01DB ; BUF_16_010 WOOD EAGLE
	call render_panel
	ld hl, 0x0B01AF ; BUF_15_011 HANGING FLAG
	call render_panel
	ld hl, 0x0C0183 ; BUF_14_012 WOOD WALL
	call render_panel
	ld hl, 0x0D0184 ; BUF_14_013 WOOD WALL
	call render_panel
	ld hl, 0x0E0185 ; BUF_14_014 WOOD WALL
	call render_panel
	ld hl, 0x1701BB ; BUF_15_023 HANGING FLAG
	call render_panel
	ld hl, 0x18018F ; BUF_14_024 WOOD WALL
	call render_panel
	ld hl, 0x2601ED ; BUF_16_038 WOOD EAGLE
	call render_panel
	ld hl, 0x2701EE ; BUF_16_039 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_090_3:
	ld hl, 0x280159 ; BUF_12_040 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2901CD ; BUF_15_041 HANGING FLAG
	call render_panel
	ld hl, 0x2B0273 ; BUF_57_043 REGULAR DOOR
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:91 map_x/y:6,1 tile_name: GREY FLOOR 
rend_091: dl rend_091_0,rend_091_1,rend_091_2,rend_091_3
rend_091_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_091_1:
	ld hl, 0x280270 ; BUF_57_040 REGULAR DOOR
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2C01F3 ; BUF_16_044 WOOD EAGLE
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_091_2:
	ld hl, 0x1B01E2 ; BUF_16_027 WOOD EAGLE
	call render_panel
	ld hl, 0x1C01C0 ; BUF_15_028 HANGING FLAG
	call render_panel
	ld hl, 0x1D0194 ; BUF_14_029 WOOD WALL
	call render_panel
	ld hl, 0x1E0195 ; BUF_14_030 WOOD WALL
	call render_panel
	ld hl, 0x1F0196 ; BUF_14_031 WOOD WALL
	call render_panel
	ld hl, 0x2601CA ; BUF_15_038 HANGING FLAG
	call render_panel
	ld hl, 0x27019E ; BUF_14_039 WOOD WALL
	call render_panel
	jp render_scene_return
rend_091_3:
	ld hl, 0x2801CC ; BUF_15_040 HANGING FLAG
	call render_panel
	ld hl, 0x290271 ; BUF_57_041 REGULAR DOOR
	call render_panel
	ld hl, 0x2A015B ; BUF_12_042 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2B01F2 ; BUF_16_043 WOOD EAGLE
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:92 map_x/y:6,2 tile_name: OVERHEAD LIGHT 
rend_092: dl rend_092_0,rend_092_1,rend_092_2,rend_092_3
rend_092_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_092_1:
	ld hl, 0x28021D ; BUF_17_040 BLUE WALL
	call render_panel
	ld hl, 0x290271 ; BUF_57_041 REGULAR DOOR
	call render_panel
	ld hl, 0x2A01F1 ; BUF_16_042 WOOD EAGLE
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C01D0 ; BUF_15_044 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_092_2:
	ld hl, 0x2801EF ; BUF_16_040 WOOD EAGLE
	call render_panel
	ld hl, 0x2901CD ; BUF_15_041 HANGING FLAG
	call render_panel
	ld hl, 0x2A01A1 ; BUF_14_042 WOOD WALL
	call render_panel
	ld hl, 0x2B01A2 ; BUF_14_043 WOOD WALL
	call render_panel
	ld hl, 0x2C01A3 ; BUF_14_044 WOOD WALL
	call render_panel
	jp render_scene_return
rend_092_3:
	ld hl, 0x280270 ; BUF_57_040 REGULAR DOOR
	call render_panel
	ld hl, 0x2901F0 ; BUF_16_041 WOOD EAGLE
	call render_panel
	ld hl, 0x2A01CE ; BUF_15_042 HANGING FLAG
	call render_panel
	ld hl, 0x2B01A2 ; BUF_14_043 WOOD WALL
	call render_panel
	ld hl, 0x2C015D ; BUF_12_044 STONE ARCH BIRD
	call render_panel
	jp render_scene_return

; cell_id:93 map_x/y:6,3 tile_name: GREY FLOOR 
rend_093: dl rend_093_0,rend_093_1,rend_093_2,rend_093_3
rend_093_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x260158 ; BUF_12_038 STONE ARCH BIRD
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_093_1:
	ld hl, 0x2801EF ; BUF_16_040 WOOD EAGLE
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A01CE ; BUF_15_042 HANGING FLAG
	call render_panel
	ld hl, 0x2B0273 ; BUF_57_043 REGULAR DOOR
	call render_panel
	ld hl, 0x3001A7 ; BUF_14_048 WOOD WALL
	call render_panel
	jp render_scene_return
rend_093_2:
	ld hl, 0x3101F8 ; BUF_16_049 WOOD EAGLE
	call render_panel
	ld hl, 0x3201D6 ; BUF_15_050 HANGING FLAG
	call render_panel
	ld hl, 0x3301AA ; BUF_14_051 WOOD WALL
	call render_panel
	jp render_scene_return
rend_093_3:
	ld hl, 0x2801EF ; BUF_16_040 WOOD EAGLE
	call render_panel
	ld hl, 0x2901A0 ; BUF_14_041 WOOD WALL
	call render_panel
	ld hl, 0x2A0272 ; BUF_57_042 REGULAR DOOR
	call render_panel
	ld hl, 0x2C01D0 ; BUF_15_044 HANGING FLAG
	call render_panel
	ld hl, 0x2F01A6 ; BUF_14_047 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:94 map_x/y:6,4 tile_name: GREY FLOOR 
rend_094: dl rend_094_0,rend_094_1,rend_094_2,rend_094_3
rend_094_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17014E ; BUF_12_023 STONE ARCH BIRD
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2601CA ; BUF_15_038 HANGING FLAG
	call render_panel
	ld hl, 0x27026F ; BUF_57_039 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_094_1:
	ld hl, 0x2801CC ; BUF_15_040 HANGING FLAG
	call render_panel
	ld hl, 0x2901F0 ; BUF_16_041 WOOD EAGLE
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2E01A5 ; BUF_14_046 WOOD WALL
	call render_panel
	ld hl, 0x3501D9 ; BUF_15_053 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_094_2:
	ld hl, 0x3601FD ; BUF_16_054 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_094_3:
	ld hl, 0x28019F ; BUF_14_040 WOOD WALL
	call render_panel
	ld hl, 0x2A01F1 ; BUF_16_042 WOOD EAGLE
	call render_panel
	ld hl, 0x2C0274 ; BUF_57_044 REGULAR DOOR
	call render_panel
	ld hl, 0x2D01A4 ; BUF_14_045 WOOD WALL
	call render_panel
	ld hl, 0x3401AB ; BUF_14_052 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:95 map_x/y:6,5 tile_name: WOOD EAGLE 
rend_095:
; cell_id:96 map_x/y:6,6 tile_name: NULL CELL 
rend_096:
; cell_id:97 map_x/y:6,7 tile_name: NULL CELL 
rend_097:
; cell_id:98 map_x/y:6,8 tile_name: NULL CELL 
rend_098:
; cell_id:99 map_x/y:6,9 tile_name: NULL CELL 
rend_099:
; cell_id:100 map_x/y:6,10 tile_name: NULL CELL 
rend_100:
; cell_id:101 map_x/y:6,11 tile_name: NULL CELL 
rend_101:
; cell_id:102 map_x/y:6,12 tile_name: NULL CELL 
rend_102:
; cell_id:103 map_x/y:6,13 tile_name: NULL CELL 
rend_103:
; cell_id:104 map_x/y:6,14 tile_name: NULL CELL 
rend_104:
; cell_id:105 map_x/y:7,0 tile_name: GREY FLOOR 
rend_105: dl rend_105_0,rend_105_1,rend_105_2,rend_105_3
rend_105_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_105_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33027B ; BUF_57_051 REGULAR DOOR
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_105_2:
	ld hl, 0x0A01AE ; BUF_15_010 HANGING FLAG
	call render_panel
	ld hl, 0x0B0182 ; BUF_14_011 WOOD WALL
	call render_panel
	ld hl, 0x0C01DD ; BUF_16_012 WOOD EAGLE
	call render_panel
	ld hl, 0x0E0185 ; BUF_14_014 WOOD WALL
	call render_panel
	ld hl, 0x100187 ; BUF_14_016 WOOD WALL
	call render_panel
	ld hl, 0x1501B9 ; BUF_15_021 HANGING FLAG
	call render_panel
	ld hl, 0x1A0191 ; BUF_14_026 WOOD WALL
	call render_panel
	ld hl, 0x1E01C2 ; BUF_15_030 HANGING FLAG
	call render_panel
	ld hl, 0x2401EB ; BUF_16_036 WOOD EAGLE
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_105_3:
	ld hl, 0x1B0150 ; BUF_12_027 STONE ARCH BIRD
	call render_panel
	ld hl, 0x1C01C0 ; BUF_15_028 HANGING FLAG
	call render_panel
	ld hl, 0x1E0266 ; BUF_57_030 REGULAR DOOR
	call render_panel
	ld hl, 0x2001E7 ; BUF_16_032 WOOD EAGLE
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:106 map_x/y:7,1 tile_name: GOLD CROSS 
rend_106: dl rend_106_0,rend_106_1,rend_106_2,rend_106_3
rend_106_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_106_1:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return
rend_106_2:
	ld hl, 0x1B01BF ; BUF_15_027 HANGING FLAG
	call render_panel
	ld hl, 0x1C0193 ; BUF_14_028 WOOD WALL
	call render_panel
	ld hl, 0x1D01E4 ; BUF_16_029 WOOD EAGLE
	call render_panel
	ld hl, 0x1F0196 ; BUF_14_031 WOOD WALL
	call render_panel
	ld hl, 0x210198 ; BUF_14_033 WOOD WALL
	call render_panel
	ld hl, 0x2401C8 ; BUF_15_036 HANGING FLAG
	call render_panel
	ld hl, 0x2F01F6 ; BUF_16_047 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_106_3:
	ld hl, 0x1B01BF ; BUF_15_027 HANGING FLAG
	call render_panel
	ld hl, 0x1C0264 ; BUF_57_028 REGULAR DOOR
	call render_panel
	ld hl, 0x1D0152 ; BUF_12_029 STONE ARCH BIRD
	call render_panel
	ld hl, 0x1E01E5 ; BUF_16_030 WOOD EAGLE
	call render_panel
	ld hl, 0x200197 ; BUF_14_032 WOOD WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:107 map_x/y:7,2 tile_name: GREY FLOOR 
rend_107: dl rend_107_0,rend_107_1,rend_107_2,rend_107_3
rend_107_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_107_1:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x32027A ; BUF_57_050 REGULAR DOOR
	call render_panel
	ld hl, 0x3301FA ; BUF_16_051 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_107_2:
	ld hl, 0x2801CC ; BUF_15_040 HANGING FLAG
	call render_panel
	ld hl, 0x2901A0 ; BUF_14_041 WOOD WALL
	call render_panel
	ld hl, 0x2A01F1 ; BUF_16_042 WOOD EAGLE
	call render_panel
	ld hl, 0x2C01A3 ; BUF_14_044 WOOD WALL
	call render_panel
	ld hl, 0x2F01D3 ; BUF_15_047 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_107_3:
	ld hl, 0x1B0263 ; BUF_57_027 REGULAR DOOR
	call render_panel
	ld hl, 0x1C01E3 ; BUF_16_028 WOOD EAGLE
	call render_panel
	ld hl, 0x1D01C1 ; BUF_15_029 HANGING FLAG
	call render_panel
	ld hl, 0x1E0195 ; BUF_14_030 WOOD WALL
	call render_panel
	ld hl, 0x1F0154 ; BUF_12_031 STONE ARCH BIRD
	call render_panel
	ld hl, 0x26019D ; BUF_14_038 WOOD WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:108 map_x/y:7,3 tile_name: PLATE OF FOOD 
rend_108: dl rend_108_0,rend_108_1,rend_108_2,rend_108_3
rend_108_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300278 ; BUF_57_048 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_108_1:
	ld hl, 0x3101F8 ; BUF_16_049 WOOD EAGLE
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x3301D7 ; BUF_15_051 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_108_2:
	ld hl, 0x3101D5 ; BUF_15_049 HANGING FLAG
	call render_panel
	ld hl, 0x3201A9 ; BUF_14_050 WOOD WALL
	call render_panel
	ld hl, 0x3301FA ; BUF_16_051 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_108_3:
	ld hl, 0x1B01E2 ; BUF_16_027 WOOD EAGLE
	call render_panel
	ld hl, 0x1C0193 ; BUF_14_028 WOOD WALL
	call render_panel
	ld hl, 0x1D0265 ; BUF_57_029 REGULAR DOOR
	call render_panel
	ld hl, 0x1F01C3 ; BUF_15_031 HANGING FLAG
	call render_panel
	ld hl, 0x210155 ; BUF_12_033 STONE ARCH BIRD
	call render_panel
	ld hl, 0x24019B ; BUF_14_036 WOOD WALL
	call render_panel
	ld hl, 0x2F01A6 ; BUF_14_047 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:109 map_x/y:7,4 tile_name: GREY FLOOR 
rend_109: dl rend_109_0,rend_109_1,rend_109_2,rend_109_3
rend_109_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x19014F ; BUF_12_025 STONE ARCH BIRD
	call render_panel
	ld hl, 0x25026D ; BUF_57_037 REGULAR DOOR
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return
rend_109_1:
	ld hl, 0x3101D5 ; BUF_15_049 HANGING FLAG
	call render_panel
	ld hl, 0x3201F9 ; BUF_16_050 WOOD EAGLE
	call render_panel
	ld hl, 0x3501AC ; BUF_14_053 WOOD WALL
	call render_panel
	jp render_scene_return
rend_109_2:
	ld hl, 0x3601DA ; BUF_15_054 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_109_3:
	ld hl, 0x1B0192 ; BUF_14_027 WOOD WALL
	call render_panel
	ld hl, 0x1D01E4 ; BUF_16_029 WOOD EAGLE
	call render_panel
	ld hl, 0x1F0267 ; BUF_57_031 REGULAR DOOR
	call render_panel
	ld hl, 0x2101C5 ; BUF_15_033 HANGING FLAG
	call render_panel
	ld hl, 0x220199 ; BUF_14_034 WOOD WALL
	call render_panel
	ld hl, 0x2D01A4 ; BUF_14_045 WOOD WALL
	call render_panel
	ld hl, 0x3401FB ; BUF_16_052 WOOD EAGLE
	call render_panel
	jp render_scene_return

; cell_id:110 map_x/y:7,5 tile_name: HANGING FLAG 
rend_110:
; cell_id:111 map_x/y:7,6 tile_name: NULL CELL 
rend_111:
; cell_id:112 map_x/y:7,7 tile_name: NULL CELL 
rend_112:
; cell_id:113 map_x/y:7,8 tile_name: NULL CELL 
rend_113:
; cell_id:114 map_x/y:7,9 tile_name: NULL CELL 
rend_114:
; cell_id:115 map_x/y:7,10 tile_name: NULL CELL 
rend_115:
; cell_id:116 map_x/y:7,11 tile_name: NULL CELL 
rend_116:
; cell_id:117 map_x/y:7,12 tile_name: NULL CELL 
rend_117:
; cell_id:118 map_x/y:7,13 tile_name: NULL CELL 
rend_118:
; cell_id:119 map_x/y:7,14 tile_name: NULL CELL 
rend_119:
; cell_id:120 map_x/y:8,0 tile_name: GREY FLOOR 
rend_120: dl rend_120_0,rend_120_1,rend_120_2,rend_120_3
rend_120_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_120_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_120_2:
	ld hl, 0x0A0181 ; BUF_14_010 WOOD WALL
	call render_panel
	ld hl, 0x0C01B0 ; BUF_15_012 HANGING FLAG
	call render_panel
	ld hl, 0x0E01DF ; BUF_16_014 WOOD EAGLE
	call render_panel
	ld hl, 0x100187 ; BUF_14_016 WOOD WALL
	call render_panel
	ld hl, 0x120189 ; BUF_14_018 WOOD WALL
	call render_panel
	ld hl, 0x1301B7 ; BUF_15_019 HANGING FLAG
	call render_panel
	ld hl, 0x2201E9 ; BUF_16_034 WOOD EAGLE
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x34027C ; BUF_57_052 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_120_3:
	ld hl, 0x0A0147 ; BUF_12_010 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0B01AF ; BUF_15_011 HANGING FLAG
	call render_panel
	ld hl, 0x0D025F ; BUF_57_013 REGULAR DOOR
	call render_panel
	ld hl, 0x0F01E0 ; BUF_16_015 WOOD EAGLE
	call render_panel
	ld hl, 0x110188 ; BUF_14_017 WOOD WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:121 map_x/y:8,1 tile_name: GREY FLOOR 
rend_121: dl rend_121_0,rend_121_1,rend_121_2,rend_121_3
rend_121_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_121_1:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_121_2:
	ld hl, 0x1B0192 ; BUF_14_027 WOOD WALL
	call render_panel
	ld hl, 0x1D01C1 ; BUF_15_029 HANGING FLAG
	call render_panel
	ld hl, 0x1F01E6 ; BUF_16_031 WOOD EAGLE
	call render_panel
	ld hl, 0x210198 ; BUF_14_033 WOOD WALL
	call render_panel
	ld hl, 0x2201C6 ; BUF_15_034 HANGING FLAG
	call render_panel
	ld hl, 0x2D01F4 ; BUF_16_045 WOOD EAGLE
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_121_3:
	ld hl, 0x0A01AE ; BUF_15_010 HANGING FLAG
	call render_panel
	ld hl, 0x0B025D ; BUF_57_011 REGULAR DOOR
	call render_panel
	ld hl, 0x0C0149 ; BUF_12_012 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0D01DE ; BUF_16_013 WOOD EAGLE
	call render_panel
	ld hl, 0x0F0186 ; BUF_14_015 WOOD WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x190190 ; BUF_14_025 WOOD WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:122 map_x/y:8,2 tile_name: GREY FLOOR 
rend_122: dl rend_122_0,rend_122_1,rend_122_2,rend_122_3
rend_122_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35027D ; BUF_57_053 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_122_1:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return
rend_122_2:
	ld hl, 0x28019F ; BUF_14_040 WOOD WALL
	call render_panel
	ld hl, 0x2A01CE ; BUF_15_042 HANGING FLAG
	call render_panel
	ld hl, 0x2C01F3 ; BUF_16_044 WOOD EAGLE
	call render_panel
	ld hl, 0x2D01D1 ; BUF_15_045 HANGING FLAG
	call render_panel
	ld hl, 0x3401FB ; BUF_16_052 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_122_3:
	ld hl, 0x0A025C ; BUF_57_010 REGULAR DOOR
	call render_panel
	ld hl, 0x0B01DC ; BUF_16_011 WOOD EAGLE
	call render_panel
	ld hl, 0x0C01B0 ; BUF_15_012 HANGING FLAG
	call render_panel
	ld hl, 0x0D0184 ; BUF_14_013 WOOD WALL
	call render_panel
	ld hl, 0x0E014B ; BUF_12_014 STONE ARCH BIRD
	call render_panel
	ld hl, 0x17018E ; BUF_14_023 WOOD WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26019D ; BUF_14_038 WOOD WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:123 map_x/y:8,3 tile_name: GREY FLOOR 
rend_123: dl rend_123_0,rend_123_1,rend_123_2,rend_123_3
rend_123_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0276 ; BUF_57_046 REGULAR DOOR
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_123_1:
	ld hl, 0x3601FD ; BUF_16_054 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_123_2:
	ld hl, 0x3101A8 ; BUF_14_049 WOOD WALL
	call render_panel
	ld hl, 0x3301D7 ; BUF_15_051 HANGING FLAG
	call render_panel
	ld hl, 0x3401D8 ; BUF_15_052 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_123_3:
	ld hl, 0x0A01DB ; BUF_16_010 WOOD EAGLE
	call render_panel
	ld hl, 0x0B0182 ; BUF_14_011 WOOD WALL
	call render_panel
	ld hl, 0x0C025E ; BUF_57_012 REGULAR DOOR
	call render_panel
	ld hl, 0x0E01B2 ; BUF_15_014 HANGING FLAG
	call render_panel
	ld hl, 0x10014C ; BUF_12_016 STONE ARCH BIRD
	call render_panel
	ld hl, 0x15018C ; BUF_14_021 WOOD WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0195 ; BUF_14_030 WOOD WALL
	call render_panel
	ld hl, 0x24019B ; BUF_14_036 WOOD WALL
	call render_panel
	ld hl, 0x2F01F6 ; BUF_16_047 WOOD EAGLE
	call render_panel
	jp render_scene_return

; cell_id:124 map_x/y:8,4 tile_name: GREY FLOOR 
rend_124: dl rend_124_0,rend_124_1,rend_124_2,rend_124_3
rend_124_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23026B ; BUF_57_035 REGULAR DOOR
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x3501FC ; BUF_16_053 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_124_1:
	ld hl, 0x3601DA ; BUF_15_054 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_124_2:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return
rend_124_3:
	ld hl, 0x0A0181 ; BUF_14_010 WOOD WALL
	call render_panel
	ld hl, 0x0C01DD ; BUF_16_012 WOOD EAGLE
	call render_panel
	ld hl, 0x0E0260 ; BUF_57_014 REGULAR DOOR
	call render_panel
	ld hl, 0x1001B4 ; BUF_15_016 HANGING FLAG
	call render_panel
	ld hl, 0x12014D ; BUF_12_018 STONE ARCH BIRD
	call render_panel
	ld hl, 0x13018A ; BUF_14_019 WOOD WALL
	call render_panel
	ld hl, 0x220199 ; BUF_14_034 WOOD WALL
	call render_panel
	ld hl, 0x2D01F4 ; BUF_16_045 WOOD EAGLE
	call render_panel
	ld hl, 0x3401D8 ; BUF_15_052 HANGING FLAG
	call render_panel
	jp render_scene_return

; cell_id:125 map_x/y:8,5 tile_name: WOOD WALL 
rend_125:
; cell_id:126 map_x/y:8,6 tile_name: NULL CELL 
rend_126:
; cell_id:127 map_x/y:8,7 tile_name: NULL CELL 
rend_127:
; cell_id:128 map_x/y:8,8 tile_name: NULL CELL 
rend_128:
; cell_id:129 map_x/y:8,9 tile_name: NULL CELL 
rend_129:
; cell_id:130 map_x/y:8,10 tile_name: NULL CELL 
rend_130:
; cell_id:131 map_x/y:8,11 tile_name: NULL CELL 
rend_131:
; cell_id:132 map_x/y:8,12 tile_name: NULL CELL 
rend_132:
; cell_id:133 map_x/y:8,13 tile_name: NULL CELL 
rend_133:
; cell_id:134 map_x/y:8,14 tile_name: NULL CELL 
rend_134:
; cell_id:135 map_x/y:9,0 tile_name: LIGHT GREY WALL 
rend_135:
; cell_id:136 map_x/y:9,1 tile_name: REGULAR DOOR 
rend_136:
; cell_id:137 map_x/y:9,2 tile_name: BLUE WALL 
rend_137:
; cell_id:138 map_x/y:9,3 tile_name: WOOD EAGLE 
rend_138:
; cell_id:139 map_x/y:9,4 tile_name: HANGING FLAG 
rend_139:
; cell_id:140 map_x/y:9,5 tile_name: NULL CELL 
rend_140:
; cell_id:141 map_x/y:9,6 tile_name: NULL CELL 
rend_141:
; cell_id:142 map_x/y:9,7 tile_name: NULL CELL 
rend_142:
; cell_id:143 map_x/y:9,8 tile_name: NULL CELL 
rend_143:
; cell_id:144 map_x/y:9,9 tile_name: NULL CELL 
rend_144:
; cell_id:145 map_x/y:9,10 tile_name: NULL CELL 
rend_145:
; cell_id:146 map_x/y:9,11 tile_name: NULL CELL 
rend_146:
; cell_id:147 map_x/y:9,12 tile_name: NULL CELL 
rend_147:
; cell_id:148 map_x/y:9,13 tile_name: NULL CELL 
rend_148:
; cell_id:149 map_x/y:9,14 tile_name: NULL CELL 
rend_149:
; cell_id:150 map_x/y:10,0 tile_name: GREY FLOOR 
rend_150: dl rend_150_0,rend_150_1,rend_150_2,rend_150_3
rend_150_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_150_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x12010A ; BUF_10_018 LIGHT GREY WALL
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_150_2:
	ld hl, 0x0A0181 ; BUF_14_010 WOOD WALL
	call render_panel
	ld hl, 0x0B0169 ; BUF_13_011 DARK GREY WALL
	call render_panel
	ld hl, 0x0D014A ; BUF_12_013 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0F0133 ; BUF_11_015 CELL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1401B8 ; BUF_15_020 HANGING FLAG
	call render_panel
	ld hl, 0x2301EA ; BUF_16_035 WOOD EAGLE
	call render_panel
	ld hl, 0x2E0223 ; BUF_17_046 BLUE WALL
	call render_panel
	ld hl, 0x35027D ; BUF_57_053 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_150_3:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:151 map_x/y:10,1 tile_name: GREY FLOOR 
rend_151: dl rend_151_0,rend_151_1,rend_151_2,rend_151_3
rend_151_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_151_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_151_2:
	ld hl, 0x1B0192 ; BUF_14_027 WOOD WALL
	call render_panel
	ld hl, 0x1C016E ; BUF_13_028 DARK GREY WALL
	call render_panel
	ld hl, 0x1E0153 ; BUF_12_030 STONE ARCH BIRD
	call render_panel
	ld hl, 0x200138 ; BUF_11_032 CELL
	call render_panel
	ld hl, 0x2301C7 ; BUF_15_035 HANGING FLAG
	call render_panel
	ld hl, 0x2E01F5 ; BUF_16_046 WOOD EAGLE
	call render_panel
	ld hl, 0x35022A ; BUF_17_053 BLUE WALL
	call render_panel
	jp render_scene_return
rend_151_3:
	ld hl, 0x36027E ; BUF_57_054 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:152 map_x/y:10,2 tile_name: GREY FLOOR 
rend_152: dl rend_152_0,rend_152_1,rend_152_2,rend_152_3
rend_152_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34027C ; BUF_57_052 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_152_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27013B ; BUF_11_039 CELL
	call render_panel
	jp render_scene_return
rend_152_2:
	ld hl, 0x28019F ; BUF_14_040 WOOD WALL
	call render_panel
	ld hl, 0x290176 ; BUF_13_041 DARK GREY WALL
	call render_panel
	ld hl, 0x2B015C ; BUF_12_043 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2E01D2 ; BUF_15_046 HANGING FLAG
	call render_panel
	ld hl, 0x3501FC ; BUF_16_053 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_152_3:
	ld hl, 0x36022B ; BUF_17_054 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:153 map_x/y:10,3 tile_name: GREY FLOOR 
rend_153: dl rend_153_0,rend_153_1,rend_153_2,rend_153_3
rend_153_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0275 ; BUF_57_045 REGULAR DOOR
	call render_panel
	ld hl, 0x340229 ; BUF_17_052 BLUE WALL
	call render_panel
	jp render_scene_return
rend_153_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25013A ; BUF_11_037 CELL
	call render_panel
	ld hl, 0x300161 ; BUF_12_048 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_153_2:
	ld hl, 0x3101A8 ; BUF_14_049 WOOD WALL
	call render_panel
	ld hl, 0x32017B ; BUF_13_050 DARK GREY WALL
	call render_panel
	ld hl, 0x3501D9 ; BUF_15_053 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_153_3:
	ld hl, 0x3601FD ; BUF_16_054 WOOD EAGLE
	call render_panel
	jp render_scene_return

; cell_id:154 map_x/y:10,4 tile_name: DOG FOOD 
rend_154: dl rend_154_0,rend_154_1,rend_154_2,rend_154_3
rend_154_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x12010A ; BUF_10_018 LIGHT GREY WALL
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22026A ; BUF_57_034 REGULAR DOOR
	call render_panel
	ld hl, 0x2D0222 ; BUF_17_045 BLUE WALL
	call render_panel
	ld hl, 0x3401FB ; BUF_16_052 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_154_1:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x230139 ; BUF_11_035 CELL
	call render_panel
	ld hl, 0x2E015F ; BUF_12_046 STONE ARCH BIRD
	call render_panel
	ld hl, 0x35017E ; BUF_13_053 DARK GREY WALL
	call render_panel
	jp render_scene_return
rend_154_2:
	ld hl, 0x3601AD ; BUF_14_054 WOOD WALL
	call render_panel
	jp render_scene_return
rend_154_3:
	ld hl, 0x3601DA ; BUF_15_054 HANGING FLAG
	call render_panel
	jp render_scene_return

; cell_id:155 map_x/y:10,5 tile_name: WOOD WALL 
rend_155:
; cell_id:156 map_x/y:10,6 tile_name: NULL CELL 
rend_156:
; cell_id:157 map_x/y:10,7 tile_name: NULL CELL 
rend_157:
; cell_id:158 map_x/y:10,8 tile_name: NULL CELL 
rend_158:
; cell_id:159 map_x/y:10,9 tile_name: NULL CELL 
rend_159:
; cell_id:160 map_x/y:10,10 tile_name: NULL CELL 
rend_160:
; cell_id:161 map_x/y:10,11 tile_name: NULL CELL 
rend_161:
; cell_id:162 map_x/y:10,12 tile_name: NULL CELL 
rend_162:
; cell_id:163 map_x/y:10,13 tile_name: NULL CELL 
rend_163:
; cell_id:164 map_x/y:10,14 tile_name: NULL CELL 
rend_164:
; cell_id:165 map_x/y:11,0 tile_name: GREY FLOOR 
rend_165: dl rend_165_0,rend_165_1,rend_165_2,rend_165_3
rend_165_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_165_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_165_2:
	ld hl, 0x0A0168 ; BUF_13_010 DARK GREY WALL
	call render_panel
	ld hl, 0x0B0148 ; BUF_12_011 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0C0183 ; BUF_14_012 WOOD WALL
	call render_panel
	ld hl, 0x0D0132 ; BUF_11_013 CELL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1601BA ; BUF_15_022 HANGING FLAG
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2501EC ; BUF_16_037 WOOD EAGLE
	call render_panel
	ld hl, 0x300225 ; BUF_17_048 BLUE WALL
	call render_panel
	jp render_scene_return
rend_165_3:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32027A ; BUF_57_050 REGULAR DOOR
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:166 map_x/y:11,1 tile_name: GOLD CHEST 
rend_166: dl rend_166_0,rend_166_1,rend_166_2,rend_166_3
rend_166_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_166_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_166_2:
	ld hl, 0x1B016D ; BUF_13_027 DARK GREY WALL
	call render_panel
	ld hl, 0x1C0151 ; BUF_12_028 STONE ARCH BIRD
	call render_panel
	ld hl, 0x1D0194 ; BUF_14_029 WOOD WALL
	call render_panel
	ld hl, 0x1E0137 ; BUF_11_030 CELL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2501C9 ; BUF_15_037 HANGING FLAG
	call render_panel
	ld hl, 0x3001F7 ; BUF_16_048 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_166_3:
	ld hl, 0x310279 ; BUF_57_049 REGULAR DOOR
	call render_panel
	ld hl, 0x320227 ; BUF_17_050 BLUE WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:167 map_x/y:11,2 tile_name: GREY FLOOR 
rend_167: dl rend_167_0,rend_167_1,rend_167_2,rend_167_3
rend_167_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_167_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_167_2:
	ld hl, 0x280175 ; BUF_13_040 DARK GREY WALL
	call render_panel
	ld hl, 0x29015A ; BUF_12_041 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2A01A1 ; BUF_14_042 WOOD WALL
	call render_panel
	ld hl, 0x2B013E ; BUF_11_043 CELL
	call render_panel
	ld hl, 0x3001D4 ; BUF_15_048 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_167_3:
	ld hl, 0x310226 ; BUF_17_049 BLUE WALL
	call render_panel
	ld hl, 0x3201F9 ; BUF_16_050 WOOD EAGLE
	call render_panel
	ld hl, 0x33027B ; BUF_57_051 REGULAR DOOR
	call render_panel
	jp render_scene_return

; cell_id:168 map_x/y:11,3 tile_name: KEYCARD 
rend_168: dl rend_168_0,rend_168_1,rend_168_2,rend_168_3
rend_168_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0277 ; BUF_57_047 REGULAR DOOR
	call render_panel
	jp render_scene_return
rend_168_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300140 ; BUF_11_048 CELL
	call render_panel
	jp render_scene_return
rend_168_2:
	ld hl, 0x31017A ; BUF_13_049 DARK GREY WALL
	call render_panel
	ld hl, 0x320163 ; BUF_12_050 STONE ARCH BIRD
	call render_panel
	ld hl, 0x3301AA ; BUF_14_051 WOOD WALL
	call render_panel
	jp render_scene_return
rend_168_3:
	ld hl, 0x3101F8 ; BUF_16_049 WOOD EAGLE
	call render_panel
	ld hl, 0x3201D6 ; BUF_15_050 HANGING FLAG
	call render_panel
	ld hl, 0x330228 ; BUF_17_051 BLUE WALL
	call render_panel
	jp render_scene_return

; cell_id:169 map_x/y:11,4 tile_name: GOLD KEY 
rend_169: dl rend_169_0,rend_169_1,rend_169_2,rend_169_3
rend_169_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24026C ; BUF_57_036 REGULAR DOOR
	call render_panel
	ld hl, 0x2F0224 ; BUF_17_047 BLUE WALL
	call render_panel
	jp render_scene_return
rend_169_1:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E013F ; BUF_11_046 CELL
	call render_panel
	ld hl, 0x350166 ; BUF_12_053 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_169_2:
	ld hl, 0x36017F ; BUF_13_054 DARK GREY WALL
	call render_panel
	jp render_scene_return
rend_169_3:
	ld hl, 0x3101D5 ; BUF_15_049 HANGING FLAG
	call render_panel
	ld hl, 0x3301FA ; BUF_16_051 WOOD EAGLE
	call render_panel
	ld hl, 0x3401AB ; BUF_14_052 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:170 map_x/y:11,5 tile_name: DARK GREY WALL 
rend_170:
; cell_id:171 map_x/y:11,6 tile_name: NULL CELL 
rend_171:
; cell_id:172 map_x/y:11,7 tile_name: NULL CELL 
rend_172:
; cell_id:173 map_x/y:11,8 tile_name: NULL CELL 
rend_173:
; cell_id:174 map_x/y:11,9 tile_name: NULL CELL 
rend_174:
; cell_id:175 map_x/y:11,10 tile_name: NULL CELL 
rend_175:
; cell_id:176 map_x/y:11,11 tile_name: NULL CELL 
rend_176:
; cell_id:177 map_x/y:11,12 tile_name: NULL CELL 
rend_177:
; cell_id:178 map_x/y:11,13 tile_name: NULL CELL 
rend_178:
; cell_id:179 map_x/y:11,14 tile_name: NULL CELL 
rend_179:
; cell_id:180 map_x/y:12,0 tile_name: GREY FLOOR 
rend_180: dl rend_180_0,rend_180_1,rend_180_2,rend_180_3
rend_180_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_180_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_180_2:
	ld hl, 0x0A0147 ; BUF_12_010 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0B0130 ; BUF_11_011 CELL
	call render_panel
	ld hl, 0x0C016A ; BUF_13_012 DARK GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0185 ; BUF_14_014 WOOD WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1801BC ; BUF_15_024 HANGING FLAG
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2701EE ; BUF_16_039 WOOD EAGLE
	call render_panel
	jp render_scene_return
rend_180_3:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290271 ; BUF_57_041 REGULAR DOOR
	call render_panel
	ld hl, 0x2B0220 ; BUF_17_043 BLUE WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:181 map_x/y:12,1 tile_name: GREY FLOOR 
rend_181: dl rend_181_0,rend_181_1,rend_181_2,rend_181_3
rend_181_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_181_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2C0124 ; BUF_10_044 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_181_2:
	ld hl, 0x1B0150 ; BUF_12_027 STONE ARCH BIRD
	call render_panel
	ld hl, 0x1C0135 ; BUF_11_028 CELL
	call render_panel
	ld hl, 0x1D016F ; BUF_13_029 DARK GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0196 ; BUF_14_031 WOOD WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2701CB ; BUF_15_039 HANGING FLAG
	call render_panel
	jp render_scene_return
rend_181_3:
	ld hl, 0x280270 ; BUF_57_040 REGULAR DOOR
	call render_panel
	ld hl, 0x29021E ; BUF_17_041 BLUE WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B01F2 ; BUF_16_043 WOOD EAGLE
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:182 map_x/y:12,2 tile_name: LAMP 
rend_182:
; cell_id:183 map_x/y:12,3 tile_name: GREY FLOOR 
rend_183: dl rend_183_0,rend_183_1,rend_183_2,rend_183_3
rend_183_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26011E ; BUF_10_038 LIGHT GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_183_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_183_2:
	ld hl, 0x310162 ; BUF_12_049 STONE ARCH BIRD
	call render_panel
	ld hl, 0x320142 ; BUF_11_050 CELL
	call render_panel
	ld hl, 0x33017C ; BUF_13_051 DARK GREY WALL
	call render_panel
	jp render_scene_return
rend_183_3:
	ld hl, 0x2801EF ; BUF_16_040 WOOD EAGLE
	call render_panel
	ld hl, 0x2901CD ; BUF_15_041 HANGING FLAG
	call render_panel
	ld hl, 0x2A021F ; BUF_17_042 BLUE WALL
	call render_panel
	ld hl, 0x2C0274 ; BUF_57_044 REGULAR DOOR
	call render_panel
	ld hl, 0x2F01A6 ; BUF_14_047 WOOD WALL
	call render_panel
	jp render_scene_return

; cell_id:184 map_x/y:12,4 tile_name: GREY FLOOR 
rend_184: dl rend_184_0,rend_184_1,rend_184_2,rend_184_3
rend_184_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17010F ; BUF_10_023 LIGHT GREY WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26026E ; BUF_57_038 REGULAR DOOR
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_184_1:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x350145 ; BUF_11_053 CELL
	call render_panel
	jp render_scene_return
rend_184_2:
	ld hl, 0x360167 ; BUF_12_054 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_184_3:
	ld hl, 0x2801CC ; BUF_15_040 HANGING FLAG
	call render_panel
	ld hl, 0x2A01F1 ; BUF_16_042 WOOD EAGLE
	call render_panel
	ld hl, 0x2C0221 ; BUF_17_044 BLUE WALL
	call render_panel
	ld hl, 0x2D01A4 ; BUF_14_045 WOOD WALL
	call render_panel
	ld hl, 0x34017D ; BUF_13_052 DARK GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:185 map_x/y:12,5 tile_name: STONE ARCH BIRD 
rend_185:
; cell_id:186 map_x/y:12,6 tile_name: NULL CELL 
rend_186:
; cell_id:187 map_x/y:12,7 tile_name: NULL CELL 
rend_187:
; cell_id:188 map_x/y:12,8 tile_name: NULL CELL 
rend_188:
; cell_id:189 map_x/y:12,9 tile_name: NULL CELL 
rend_189:
; cell_id:190 map_x/y:12,10 tile_name: NULL CELL 
rend_190:
; cell_id:191 map_x/y:12,11 tile_name: NULL CELL 
rend_191:
; cell_id:192 map_x/y:12,12 tile_name: NULL CELL 
rend_192:
; cell_id:193 map_x/y:12,13 tile_name: NULL CELL 
rend_193:
; cell_id:194 map_x/y:12,14 tile_name: NULL CELL 
rend_194:
; cell_id:195 map_x/y:13,0 tile_name: GREY FLOOR 
rend_195: dl rend_195_0,rend_195_1,rend_195_2,rend_195_3
rend_195_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_195_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_195_2:
	ld hl, 0x0A012F ; BUF_11_010 CELL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0149 ; BUF_12_012 STONE ARCH BIRD
	call render_panel
	ld hl, 0x0E016B ; BUF_13_014 DARK GREY WALL
	call render_panel
	ld hl, 0x100187 ; BUF_14_016 WOOD WALL
	call render_panel
	ld hl, 0x15010D ; BUF_10_021 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1A01BE ; BUF_15_026 HANGING FLAG
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_195_3:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0264 ; BUF_57_028 REGULAR DOOR
	call render_panel
	ld hl, 0x1E0213 ; BUF_17_030 BLUE WALL
	call render_panel
	ld hl, 0x2001E7 ; BUF_16_032 WOOD EAGLE
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:196 map_x/y:13,1 tile_name: MACHINE GUN 
rend_196: dl rend_196_0,rend_196_1,rend_196_2,rend_196_3
rend_196_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_196_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_196_2:
	ld hl, 0x1B0134 ; BUF_11_027 CELL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0152 ; BUF_12_029 STONE ARCH BIRD
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1F0170 ; BUF_13_031 DARK GREY WALL
	call render_panel
	ld hl, 0x210198 ; BUF_14_033 WOOD WALL
	call render_panel
	ld hl, 0x24011C ; BUF_10_036 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_196_3:
	ld hl, 0x1B0263 ; BUF_57_027 REGULAR DOOR
	call render_panel
	ld hl, 0x1C0211 ; BUF_17_028 BLUE WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E01E5 ; BUF_16_030 WOOD EAGLE
	call render_panel
	ld hl, 0x2001C4 ; BUF_15_032 HANGING FLAG
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:197 map_x/y:13,2 tile_name: GREY FLOOR 
rend_197: dl rend_197_0,rend_197_1,rend_197_2,rend_197_3
rend_197_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A0122 ; BUF_10_042 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_197_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_197_2:
	ld hl, 0x28013C ; BUF_11_040 CELL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A015B ; BUF_12_042 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2C0177 ; BUF_13_044 DARK GREY WALL
	call render_panel
	ld hl, 0x2F0127 ; BUF_10_047 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_197_3:
	ld hl, 0x1B0210 ; BUF_17_027 BLUE WALL
	call render_panel
	ld hl, 0x1C01E3 ; BUF_16_028 WOOD EAGLE
	call render_panel
	ld hl, 0x1D0265 ; BUF_57_029 REGULAR DOOR
	call render_panel
	ld hl, 0x1E01C2 ; BUF_15_030 HANGING FLAG
	call render_panel
	ld hl, 0x1F0117 ; BUF_10_031 LIGHT GREY WALL
	call render_panel
	ld hl, 0x26019D ; BUF_14_038 WOOD WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:198 map_x/y:13,3 tile_name: GATLING GUN 
rend_198: dl rend_198_0,rend_198_1,rend_198_2,rend_198_3
rend_198_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0115 ; BUF_10_029 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_198_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x33012B ; BUF_10_051 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_198_2:
	ld hl, 0x310141 ; BUF_11_049 CELL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x330164 ; BUF_12_051 STONE ARCH BIRD
	call render_panel
	jp render_scene_return
rend_198_3:
	ld hl, 0x1B01E2 ; BUF_16_027 WOOD EAGLE
	call render_panel
	ld hl, 0x1C01C0 ; BUF_15_028 HANGING FLAG
	call render_panel
	ld hl, 0x1D0212 ; BUF_17_029 BLUE WALL
	call render_panel
	ld hl, 0x1F0267 ; BUF_57_031 REGULAR DOOR
	call render_panel
	ld hl, 0x210119 ; BUF_10_033 LIGHT GREY WALL
	call render_panel
	ld hl, 0x24019B ; BUF_14_036 WOOD WALL
	call render_panel
	ld hl, 0x2F0179 ; BUF_13_047 DARK GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:199 map_x/y:13,4 tile_name: GREY FLOOR 
rend_199: dl rend_199_0,rend_199_1,rend_199_2,rend_199_3
rend_199_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x190111 ; BUF_10_025 LIGHT GREY WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_199_1:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_199_2:
	ld hl, 0x360146 ; BUF_11_054 CELL
	call render_panel
	jp render_scene_return
rend_199_3:
	ld hl, 0x1B01BF ; BUF_15_027 HANGING FLAG
	call render_panel
	ld hl, 0x1D01E4 ; BUF_16_029 WOOD EAGLE
	call render_panel
	ld hl, 0x1F0214 ; BUF_17_031 BLUE WALL
	call render_panel
	ld hl, 0x210269 ; BUF_57_033 REGULAR DOOR
	call render_panel
	ld hl, 0x220199 ; BUF_14_034 WOOD WALL
	call render_panel
	ld hl, 0x2D0178 ; BUF_13_045 DARK GREY WALL
	call render_panel
	ld hl, 0x340165 ; BUF_12_052 STONE ARCH BIRD
	call render_panel
	jp render_scene_return

; cell_id:200 map_x/y:13,5 tile_name: CELL 
rend_200:
; cell_id:201 map_x/y:13,6 tile_name: NULL CELL 
rend_201:
; cell_id:202 map_x/y:13,7 tile_name: NULL CELL 
rend_202:
; cell_id:203 map_x/y:13,8 tile_name: NULL CELL 
rend_203:
; cell_id:204 map_x/y:13,9 tile_name: NULL CELL 
rend_204:
; cell_id:205 map_x/y:13,10 tile_name: NULL CELL 
rend_205:
; cell_id:206 map_x/y:13,11 tile_name: NULL CELL 
rend_206:
; cell_id:207 map_x/y:13,12 tile_name: NULL CELL 
rend_207:
; cell_id:208 map_x/y:13,13 tile_name: NULL CELL 
rend_208:
; cell_id:209 map_x/y:13,14 tile_name: NULL CELL 
rend_209:
; cell_id:210 map_x/y:14,0 tile_name: BJ 100%/ START POSITION 
rend_210: dl rend_210_0,rend_210_1,rend_210_2,rend_210_3
rend_210_0:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_210_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_210_2:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0C0131 ; BUF_11_012 CELL
	call render_panel
	ld hl, 0x0E014B ; BUF_12_014 STONE ARCH BIRD
	call render_panel
	ld hl, 0x10016C ; BUF_13_016 DARK GREY WALL
	call render_panel
	ld hl, 0x120189 ; BUF_14_018 WOOD WALL
	call render_panel
	ld hl, 0x13010B ; BUF_10_019 LIGHT GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_210_3:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B025D ; BUF_57_011 REGULAR DOOR
	call render_panel
	ld hl, 0x0D0202 ; BUF_17_013 BLUE WALL
	call render_panel
	ld hl, 0x0F01E0 ; BUF_16_015 WOOD EAGLE
	call render_panel
	ld hl, 0x1101B5 ; BUF_15_017 HANGING FLAG
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:211 map_x/y:14,1 tile_name: GREY FLOOR 
rend_211: dl rend_211_0,rend_211_1,rend_211_2,rend_211_3
rend_211_0:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x32012A ; BUF_10_050 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_2:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1D0136 ; BUF_11_029 CELL
	call render_panel
	ld hl, 0x1F0154 ; BUF_12_031 STONE ARCH BIRD
	call render_panel
	ld hl, 0x210171 ; BUF_13_033 DARK GREY WALL
	call render_panel
	ld hl, 0x22011A ; BUF_10_034 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_211_3:
	ld hl, 0x0A025C ; BUF_57_010 REGULAR DOOR
	call render_panel
	ld hl, 0x0B0200 ; BUF_17_011 BLUE WALL
	call render_panel
	ld hl, 0x0C0104 ; BUF_10_012 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D01DE ; BUF_16_013 WOOD EAGLE
	call render_panel
	ld hl, 0x0F01B3 ; BUF_15_015 HANGING FLAG
	call render_panel
	ld hl, 0x16010E ; BUF_10_022 LIGHT GREY WALL
	call render_panel
	ld hl, 0x190190 ; BUF_14_025 WOOD WALL
	call render_panel
	ld hl, 0x25011D ; BUF_10_037 LIGHT GREY WALL
	call render_panel
	ld hl, 0x300128 ; BUF_10_048 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:212 map_x/y:14,2 tile_name: GREY FLOOR 
rend_212: dl rend_212_0,rend_212_1,rend_212_2,rend_212_3
rend_212_0:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x290121 ; BUF_10_041 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2B0123 ; BUF_10_043 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_212_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_212_2:
	ld hl, 0x280120 ; BUF_10_040 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2A013D ; BUF_11_042 CELL
	call render_panel
	ld hl, 0x2C015D ; BUF_12_044 STONE ARCH BIRD
	call render_panel
	ld hl, 0x2D0125 ; BUF_10_045 LIGHT GREY WALL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_212_3:
	ld hl, 0x0A01FF ; BUF_17_010 BLUE WALL
	call render_panel
	ld hl, 0x0B01DC ; BUF_16_011 WOOD EAGLE
	call render_panel
	ld hl, 0x0C025E ; BUF_57_012 REGULAR DOOR
	call render_panel
	ld hl, 0x0D01B1 ; BUF_15_013 HANGING FLAG
	call render_panel
	ld hl, 0x0E0106 ; BUF_10_014 LIGHT GREY WALL
	call render_panel
	ld hl, 0x17018E ; BUF_14_023 WOOD WALL
	call render_panel
	ld hl, 0x180110 ; BUF_10_024 LIGHT GREY WALL
	call render_panel
	ld hl, 0x260174 ; BUF_13_038 DARK GREY WALL
	call render_panel
	ld hl, 0x27011F ; BUF_10_039 LIGHT GREY WALL
	call render_panel
	jp render_scene_return

; cell_id:213 map_x/y:14,3 tile_name: GREY FLOOR 
rend_213: dl rend_213_0,rend_213_1,rend_213_2,rend_213_3
rend_213_0:
	ld hl, 0x1B0113 ; BUF_10_027 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1C0114 ; BUF_10_028 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0116 ; BUF_10_030 LIGHT GREY WALL
	call render_panel
	ld hl, 0x200118 ; BUF_10_032 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_213_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_213_2:
	ld hl, 0x310129 ; BUF_10_049 LIGHT GREY WALL
	call render_panel
	ld hl, 0x330143 ; BUF_11_051 CELL
	call render_panel
	ld hl, 0x34012C ; BUF_10_052 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_213_3:
	ld hl, 0x0A01DB ; BUF_16_010 WOOD EAGLE
	call render_panel
	ld hl, 0x0B01AF ; BUF_15_011 HANGING FLAG
	call render_panel
	ld hl, 0x0C0201 ; BUF_17_012 BLUE WALL
	call render_panel
	ld hl, 0x0E0260 ; BUF_57_014 REGULAR DOOR
	call render_panel
	ld hl, 0x100108 ; BUF_10_016 LIGHT GREY WALL
	call render_panel
	ld hl, 0x15018C ; BUF_14_021 WOOD WALL
	call render_panel
	ld hl, 0x1A0112 ; BUF_10_026 LIGHT GREY WALL
	call render_panel
	ld hl, 0x1E0195 ; BUF_14_030 WOOD WALL
	call render_panel
	ld hl, 0x240173 ; BUF_13_036 DARK GREY WALL
	call render_panel
	ld hl, 0x2F0160 ; BUF_12_047 STONE ARCH BIRD
	call render_panel
	jp render_scene_return

; cell_id:214 map_x/y:14,4 tile_name: GREY FLOOR 
rend_214: dl rend_214_0,rend_214_1,rend_214_2,rend_214_3
rend_214_0:
	ld hl, 0x0A0102 ; BUF_10_010 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0B0103 ; BUF_10_011 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0D0105 ; BUF_10_013 LIGHT GREY WALL
	call render_panel
	ld hl, 0x0F0107 ; BUF_10_015 LIGHT GREY WALL
	call render_panel
	ld hl, 0x110109 ; BUF_10_017 LIGHT GREY WALL
	call render_panel
	ld hl, 0x14010C ; BUF_10_020 LIGHT GREY WALL
	call render_panel
	ld hl, 0x23011B ; BUF_10_035 LIGHT GREY WALL
	call render_panel
	ld hl, 0x2E0126 ; BUF_10_046 LIGHT GREY WALL
	call render_panel
	ld hl, 0x35012D ; BUF_10_053 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_214_1:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_214_2:
	ld hl, 0x36012E ; BUF_10_054 LIGHT GREY WALL
	call render_panel
	jp render_scene_return
rend_214_3:
	ld hl, 0x0A01AE ; BUF_15_010 HANGING FLAG
	call render_panel
	ld hl, 0x0C01DD ; BUF_16_012 WOOD EAGLE
	call render_panel
	ld hl, 0x0E0203 ; BUF_17_014 BLUE WALL
	call render_panel
	ld hl, 0x100262 ; BUF_57_016 REGULAR DOOR
	call render_panel
	ld hl, 0x12010A ; BUF_10_018 LIGHT GREY WALL
	call render_panel
	ld hl, 0x13018A ; BUF_14_019 WOOD WALL
	call render_panel
	ld hl, 0x220172 ; BUF_13_034 DARK GREY WALL
	call render_panel
	ld hl, 0x2D015E ; BUF_12_045 STONE ARCH BIRD
	call render_panel
	ld hl, 0x340144 ; BUF_11_052 CELL
	call render_panel
	jp render_scene_return

; cell_id:215 map_x/y:14,5 tile_name: LIGHT GREY WALL 
rend_215:
; cell_id:216 map_x/y:14,6 tile_name: NULL CELL 
rend_216:
; cell_id:217 map_x/y:14,7 tile_name: NULL CELL 
rend_217:
; cell_id:218 map_x/y:14,8 tile_name: NULL CELL 
rend_218:
; cell_id:219 map_x/y:14,9 tile_name: NULL CELL 
rend_219:
; cell_id:220 map_x/y:14,10 tile_name: NULL CELL 
rend_220:
; cell_id:221 map_x/y:14,11 tile_name: NULL CELL 
rend_221:
; cell_id:222 map_x/y:14,12 tile_name: NULL CELL 
rend_222:
; cell_id:223 map_x/y:14,13 tile_name: NULL CELL 
rend_223:
; cell_id:224 map_x/y:14,14 tile_name: NULL CELL 
rend_224:
