; Bitmap indices:
BUF_10_003: equ 0x0100
BUF_10_004: equ 0x0101
BUF_10_010: equ 0x0102
BUF_10_011: equ 0x0103
BUF_10_012: equ 0x0104
BUF_10_013: equ 0x0105
BUF_10_014: equ 0x0106
BUF_10_015: equ 0x0107
BUF_10_016: equ 0x0108
BUF_10_017: equ 0x0109
BUF_10_018: equ 0x010A
BUF_10_019: equ 0x010B
BUF_10_020: equ 0x010C
BUF_10_021: equ 0x010D
BUF_10_022: equ 0x010E
BUF_10_023: equ 0x010F
BUF_10_024: equ 0x0110
BUF_10_025: equ 0x0111
BUF_10_026: equ 0x0112
BUF_10_027: equ 0x0113
BUF_10_028: equ 0x0114
BUF_10_029: equ 0x0115
BUF_10_030: equ 0x0116
BUF_10_031: equ 0x0117
BUF_10_032: equ 0x0118
BUF_10_033: equ 0x0119
BUF_10_034: equ 0x011A
BUF_10_035: equ 0x011B
BUF_10_036: equ 0x011C
BUF_10_037: equ 0x011D
BUF_10_038: equ 0x011E
BUF_10_039: equ 0x011F
BUF_10_040: equ 0x0120
BUF_10_041: equ 0x0121
BUF_10_042: equ 0x0122
BUF_10_043: equ 0x0123
BUF_10_044: equ 0x0124
BUF_10_045: equ 0x0125
BUF_10_046: equ 0x0126
BUF_10_047: equ 0x0127
BUF_10_048: equ 0x0128
BUF_10_049: equ 0x0129
BUF_10_050: equ 0x012A
BUF_10_051: equ 0x012B
BUF_10_052: equ 0x012C
BUF_10_053: equ 0x012D
BUF_10_054: equ 0x012E
BUF_11_010: equ 0x012F
BUF_11_011: equ 0x0130
BUF_11_012: equ 0x0131
BUF_11_013: equ 0x0132
BUF_11_015: equ 0x0133
BUF_11_027: equ 0x0134
BUF_11_028: equ 0x0135
BUF_11_029: equ 0x0136
BUF_11_030: equ 0x0137
BUF_11_032: equ 0x0138
BUF_11_035: equ 0x0139
BUF_11_037: equ 0x013A
BUF_11_039: equ 0x013B
BUF_11_040: equ 0x013C
BUF_11_042: equ 0x013D
BUF_11_043: equ 0x013E
BUF_11_046: equ 0x013F
BUF_11_048: equ 0x0140
BUF_11_049: equ 0x0141
BUF_11_050: equ 0x0142
BUF_11_051: equ 0x0143
BUF_11_052: equ 0x0144
BUF_11_053: equ 0x0145
BUF_11_054: equ 0x0146
BUF_12_010: equ 0x0147
BUF_12_011: equ 0x0148
BUF_12_012: equ 0x0149
BUF_12_013: equ 0x014A
BUF_12_014: equ 0x014B
BUF_12_016: equ 0x014C
BUF_12_018: equ 0x014D
BUF_12_023: equ 0x014E
BUF_12_025: equ 0x014F
BUF_12_027: equ 0x0150
BUF_12_028: equ 0x0151
BUF_12_029: equ 0x0152
BUF_12_030: equ 0x0153
BUF_12_031: equ 0x0154
BUF_12_033: equ 0x0155
BUF_12_034: equ 0x0156
BUF_12_036: equ 0x0157
BUF_12_038: equ 0x0158
BUF_12_040: equ 0x0159
BUF_12_041: equ 0x015A
BUF_12_042: equ 0x015B
BUF_12_043: equ 0x015C
BUF_12_044: equ 0x015D
BUF_12_045: equ 0x015E
BUF_12_046: equ 0x015F
BUF_12_047: equ 0x0160
BUF_12_048: equ 0x0161
BUF_12_049: equ 0x0162
BUF_12_050: equ 0x0163
BUF_12_051: equ 0x0164
BUF_12_052: equ 0x0165
BUF_12_053: equ 0x0166
BUF_12_054: equ 0x0167
BUF_13_010: equ 0x0168
BUF_13_011: equ 0x0169
BUF_13_012: equ 0x016A
BUF_13_014: equ 0x016B
BUF_13_016: equ 0x016C
BUF_13_027: equ 0x016D
BUF_13_028: equ 0x016E
BUF_13_029: equ 0x016F
BUF_13_031: equ 0x0170
BUF_13_033: equ 0x0171
BUF_13_034: equ 0x0172
BUF_13_036: equ 0x0173
BUF_13_038: equ 0x0174
BUF_13_040: equ 0x0175
BUF_13_041: equ 0x0176
BUF_13_044: equ 0x0177
BUF_13_045: equ 0x0178
BUF_13_047: equ 0x0179
BUF_13_049: equ 0x017A
BUF_13_050: equ 0x017B
BUF_13_051: equ 0x017C
BUF_13_052: equ 0x017D
BUF_13_053: equ 0x017E
BUF_13_054: equ 0x017F
BUF_14_005: equ 0x0180
BUF_14_010: equ 0x0181
BUF_14_011: equ 0x0182
BUF_14_012: equ 0x0183
BUF_14_013: equ 0x0184
BUF_14_014: equ 0x0185
BUF_14_015: equ 0x0186
BUF_14_016: equ 0x0187
BUF_14_017: equ 0x0188
BUF_14_018: equ 0x0189
BUF_14_019: equ 0x018A
BUF_14_020: equ 0x018B
BUF_14_021: equ 0x018C
BUF_14_022: equ 0x018D
BUF_14_023: equ 0x018E
BUF_14_024: equ 0x018F
BUF_14_025: equ 0x0190
BUF_14_026: equ 0x0191
BUF_14_027: equ 0x0192
BUF_14_028: equ 0x0193
BUF_14_029: equ 0x0194
BUF_14_030: equ 0x0195
BUF_14_031: equ 0x0196
BUF_14_032: equ 0x0197
BUF_14_033: equ 0x0198
BUF_14_034: equ 0x0199
BUF_14_035: equ 0x019A
BUF_14_036: equ 0x019B
BUF_14_037: equ 0x019C
BUF_14_038: equ 0x019D
BUF_14_039: equ 0x019E
BUF_14_040: equ 0x019F
BUF_14_041: equ 0x01A0
BUF_14_042: equ 0x01A1
BUF_14_043: equ 0x01A2
BUF_14_044: equ 0x01A3
BUF_14_045: equ 0x01A4
BUF_14_046: equ 0x01A5
BUF_14_047: equ 0x01A6
BUF_14_048: equ 0x01A7
BUF_14_049: equ 0x01A8
BUF_14_050: equ 0x01A9
BUF_14_051: equ 0x01AA
BUF_14_052: equ 0x01AB
BUF_14_053: equ 0x01AC
BUF_14_054: equ 0x01AD
BUF_15_010: equ 0x01AE
BUF_15_011: equ 0x01AF
BUF_15_012: equ 0x01B0
BUF_15_013: equ 0x01B1
BUF_15_014: equ 0x01B2
BUF_15_015: equ 0x01B3
BUF_15_016: equ 0x01B4
BUF_15_017: equ 0x01B5
BUF_15_018: equ 0x01B6
BUF_15_019: equ 0x01B7
BUF_15_020: equ 0x01B8
BUF_15_021: equ 0x01B9
BUF_15_022: equ 0x01BA
BUF_15_023: equ 0x01BB
BUF_15_024: equ 0x01BC
BUF_15_025: equ 0x01BD
BUF_15_026: equ 0x01BE
BUF_15_027: equ 0x01BF
BUF_15_028: equ 0x01C0
BUF_15_029: equ 0x01C1
BUF_15_030: equ 0x01C2
BUF_15_031: equ 0x01C3
BUF_15_032: equ 0x01C4
BUF_15_033: equ 0x01C5
BUF_15_034: equ 0x01C6
BUF_15_035: equ 0x01C7
BUF_15_036: equ 0x01C8
BUF_15_037: equ 0x01C9
BUF_15_038: equ 0x01CA
BUF_15_039: equ 0x01CB
BUF_15_040: equ 0x01CC
BUF_15_041: equ 0x01CD
BUF_15_042: equ 0x01CE
BUF_15_043: equ 0x01CF
BUF_15_044: equ 0x01D0
BUF_15_045: equ 0x01D1
BUF_15_046: equ 0x01D2
BUF_15_047: equ 0x01D3
BUF_15_048: equ 0x01D4
BUF_15_049: equ 0x01D5
BUF_15_050: equ 0x01D6
BUF_15_051: equ 0x01D7
BUF_15_052: equ 0x01D8
BUF_15_053: equ 0x01D9
BUF_15_054: equ 0x01DA
BUF_16_010: equ 0x01DB
BUF_16_011: equ 0x01DC
BUF_16_012: equ 0x01DD
BUF_16_013: equ 0x01DE
BUF_16_014: equ 0x01DF
BUF_16_015: equ 0x01E0
BUF_16_016: equ 0x01E1
BUF_16_027: equ 0x01E2
BUF_16_028: equ 0x01E3
BUF_16_029: equ 0x01E4
BUF_16_030: equ 0x01E5
BUF_16_031: equ 0x01E6
BUF_16_032: equ 0x01E7
BUF_16_033: equ 0x01E8
BUF_16_034: equ 0x01E9
BUF_16_035: equ 0x01EA
BUF_16_036: equ 0x01EB
BUF_16_037: equ 0x01EC
BUF_16_038: equ 0x01ED
BUF_16_039: equ 0x01EE
BUF_16_040: equ 0x01EF
BUF_16_041: equ 0x01F0
BUF_16_042: equ 0x01F1
BUF_16_043: equ 0x01F2
BUF_16_044: equ 0x01F3
BUF_16_045: equ 0x01F4
BUF_16_046: equ 0x01F5
BUF_16_047: equ 0x01F6
BUF_16_048: equ 0x01F7
BUF_16_049: equ 0x01F8
BUF_16_050: equ 0x01F9
BUF_16_051: equ 0x01FA
BUF_16_052: equ 0x01FB
BUF_16_053: equ 0x01FC
BUF_16_054: equ 0x01FD
BUF_17_006: equ 0x01FE
BUF_17_010: equ 0x01FF
BUF_17_011: equ 0x0200
BUF_17_012: equ 0x0201
BUF_17_013: equ 0x0202
BUF_17_014: equ 0x0203
BUF_17_015: equ 0x0204
BUF_17_016: equ 0x0205
BUF_17_017: equ 0x0206
BUF_17_018: equ 0x0207
BUF_17_019: equ 0x0208
BUF_17_020: equ 0x0209
BUF_17_021: equ 0x020A
BUF_17_022: equ 0x020B
BUF_17_023: equ 0x020C
BUF_17_024: equ 0x020D
BUF_17_025: equ 0x020E
BUF_17_026: equ 0x020F
BUF_17_027: equ 0x0210
BUF_17_028: equ 0x0211
BUF_17_029: equ 0x0212
BUF_17_030: equ 0x0213
BUF_17_031: equ 0x0214
BUF_17_032: equ 0x0215
BUF_17_033: equ 0x0216
BUF_17_034: equ 0x0217
BUF_17_035: equ 0x0218
BUF_17_036: equ 0x0219
BUF_17_037: equ 0x021A
BUF_17_038: equ 0x021B
BUF_17_039: equ 0x021C
BUF_17_040: equ 0x021D
BUF_17_041: equ 0x021E
BUF_17_042: equ 0x021F
BUF_17_043: equ 0x0220
BUF_17_044: equ 0x0221
BUF_17_045: equ 0x0222
BUF_17_046: equ 0x0223
BUF_17_047: equ 0x0224
BUF_17_048: equ 0x0225
BUF_17_049: equ 0x0226
BUF_17_050: equ 0x0227
BUF_17_051: equ 0x0228
BUF_17_052: equ 0x0229
BUF_17_053: equ 0x022A
BUF_17_054: equ 0x022B
BUF_30_010: equ 0x022C
BUF_30_011: equ 0x022D
BUF_30_012: equ 0x022E
BUF_30_013: equ 0x022F
BUF_30_015: equ 0x0230
BUF_30_027: equ 0x0231
BUF_30_028: equ 0x0232
BUF_30_029: equ 0x0233
BUF_30_030: equ 0x0234
BUF_30_032: equ 0x0235
BUF_30_035: equ 0x0236
BUF_30_037: equ 0x0237
BUF_30_039: equ 0x0238
BUF_30_040: equ 0x0239
BUF_30_041: equ 0x023A
BUF_30_042: equ 0x023B
BUF_30_043: equ 0x023C
BUF_30_046: equ 0x023D
BUF_30_048: equ 0x023E
BUF_30_049: equ 0x023F
BUF_30_050: equ 0x0240
BUF_30_051: equ 0x0241
BUF_30_052: equ 0x0242
BUF_30_053: equ 0x0243
BUF_30_054: equ 0x0244
BUF_31_010: equ 0x0245
BUF_31_011: equ 0x0246
BUF_31_012: equ 0x0247
BUF_31_013: equ 0x0248
BUF_31_014: equ 0x0249
BUF_31_027: equ 0x024A
BUF_31_028: equ 0x024B
BUF_31_029: equ 0x024C
BUF_31_030: equ 0x024D
BUF_31_031: equ 0x024E
BUF_31_040: equ 0x024F
BUF_31_041: equ 0x0250
BUF_31_042: equ 0x0251
BUF_31_043: equ 0x0252
BUF_31_044: equ 0x0253
BUF_31_046: equ 0x0254
BUF_31_048: equ 0x0255
BUF_31_049: equ 0x0256
BUF_31_050: equ 0x0257
BUF_31_051: equ 0x0258
BUF_31_052: equ 0x0259
BUF_31_053: equ 0x025A
BUF_31_054: equ 0x025B
BUF_57_010: equ 0x025C
BUF_57_011: equ 0x025D
BUF_57_012: equ 0x025E
BUF_57_013: equ 0x025F
BUF_57_014: equ 0x0260
BUF_57_015: equ 0x0261
BUF_57_016: equ 0x0262
BUF_57_027: equ 0x0263
BUF_57_028: equ 0x0264
BUF_57_029: equ 0x0265
BUF_57_030: equ 0x0266
BUF_57_031: equ 0x0267
BUF_57_032: equ 0x0268
BUF_57_033: equ 0x0269
BUF_57_034: equ 0x026A
BUF_57_035: equ 0x026B
BUF_57_036: equ 0x026C
BUF_57_037: equ 0x026D
BUF_57_038: equ 0x026E
BUF_57_039: equ 0x026F
BUF_57_040: equ 0x0270
BUF_57_041: equ 0x0271
BUF_57_042: equ 0x0272
BUF_57_043: equ 0x0273
BUF_57_044: equ 0x0274
BUF_57_045: equ 0x0275
BUF_57_046: equ 0x0276
BUF_57_047: equ 0x0277
BUF_57_048: equ 0x0278
BUF_57_049: equ 0x0279
BUF_57_050: equ 0x027A
BUF_57_051: equ 0x027B
BUF_57_052: equ 0x027C
BUF_57_053: equ 0x027D
BUF_57_054: equ 0x027E
BUF_58_049: equ 0x027F
BUF_58_054: equ 0x0280
BUF_59_049: equ 0x0281
BUF_59_054: equ 0x0282

; Import .rgba bitmap files and load them into VDP buffers
load_panels:

	ld hl,F15_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_004
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_004
	ld bc,17
	ld de,37
	ld ix,629
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_005
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_005
	ld bc,17
	ld de,37
	ld ix,629
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_023
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_023
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_024
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_024
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_018
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_018
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_019
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_019
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_017
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_017
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_020
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_020
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_021
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_021
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_026
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_026
	ld bc,36
	ld de,45
	ld ix,1620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_024
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_024
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_022
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_022
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_025
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_025
	ld bc,37
	ld de,47
	ld ix,1739
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_025
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_025
	ld bc,37
	ld de,47
	ld ix,1739
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_023
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_023
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_023
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_023
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_024
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_024
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_021
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_021
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_022
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_022
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_025
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_025
	ld bc,37
	ld de,47
	ld ix,1739
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_018
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_018
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_019
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_019
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_020
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_020
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_025
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_025
	ld bc,37
	ld de,47
	ld ix,1739
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_023
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_023
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_021
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_021
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_026
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_026
	ld bc,36
	ld de,45
	ld ix,1620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_017
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_017
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_018
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_018
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_019
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_019
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_018
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_018
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_020
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_020
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_022
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_022
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_026
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_026
	ld bc,36
	ld de,45
	ld ix,1620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_044
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_044
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_031
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_031
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_047
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_047
	ld bc,65
	ld de,107
	ld ix,6955
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_045
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_045
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_017
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_017
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_014
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_014
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_012
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_012
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_016
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_016
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_017
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_017
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_020
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_020
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_010
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_010
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_026
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_026
	ld bc,36
	ld de,45
	ld ix,1620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_011
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_011
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_024
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_024
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_034
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_034
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_013
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_013
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_022
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_022
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_019
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_019
	ld bc,6
	ld de,47
	ld ix,282
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_029
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_029
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_033
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_033
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_027
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_027
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_028
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_028
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_036
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_036
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_030
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_030
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_021
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_021
	ld bc,17
	ld de,47
	ld ix,799
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_042
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_042
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_038
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_038
	ld bc,47
	ld de,65
	ld ix,3055
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_040
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_040
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_041
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_041
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_043
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_043
	ld bc,65
	ld de,65
	ld ix,4225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_023
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_023
	ld bc,26
	ld de,47
	ld ix,1222
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_039
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_039
	ld bc,46
	ld de,63
	ld ix,2898
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_051
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_051
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_032
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_032
	ld bc,47
	ld de,47
	ld ix,2209
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_049
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_049
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_050
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_050
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_048
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_048
	ld bc,64
	ld de,105
	ld ix,6720
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_025
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_025
	ld bc,37
	ld de,47
	ld ix,1739
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_037
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_037
	ld bc,28
	ld de,65
	ld ix,1820
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_018
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_018
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_052
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_052
	ld bc,108
	ld de,160
	ld ix,17280
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_015
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_015
	ld bc,37
	ld de,37
	ld ix,1369
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_054
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_054
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_053
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_053
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_046
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_046
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_035
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_035
	ld bc,10
	ld de,65
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_003
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_003
	ld bc,10
	ld de,37
	ld ix,370
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_006
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_006
	ld bc,23
	ld de,37
	ld ix,851
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ret

F10_003: db "panels/10_003.rgba",0
F10_004: db "panels/10_004.rgba",0
F10_010: db "panels/10_010.rgba",0
F10_011: db "panels/10_011.rgba",0
F10_012: db "panels/10_012.rgba",0
F10_013: db "panels/10_013.rgba",0
F10_014: db "panels/10_014.rgba",0
F10_015: db "panels/10_015.rgba",0
F10_016: db "panels/10_016.rgba",0
F10_017: db "panels/10_017.rgba",0
F10_018: db "panels/10_018.rgba",0
F10_019: db "panels/10_019.rgba",0
F10_020: db "panels/10_020.rgba",0
F10_021: db "panels/10_021.rgba",0
F10_022: db "panels/10_022.rgba",0
F10_023: db "panels/10_023.rgba",0
F10_024: db "panels/10_024.rgba",0
F10_025: db "panels/10_025.rgba",0
F10_026: db "panels/10_026.rgba",0
F10_027: db "panels/10_027.rgba",0
F10_028: db "panels/10_028.rgba",0
F10_029: db "panels/10_029.rgba",0
F10_030: db "panels/10_030.rgba",0
F10_031: db "panels/10_031.rgba",0
F10_032: db "panels/10_032.rgba",0
F10_033: db "panels/10_033.rgba",0
F10_034: db "panels/10_034.rgba",0
F10_035: db "panels/10_035.rgba",0
F10_036: db "panels/10_036.rgba",0
F10_037: db "panels/10_037.rgba",0
F10_038: db "panels/10_038.rgba",0
F10_039: db "panels/10_039.rgba",0
F10_040: db "panels/10_040.rgba",0
F10_041: db "panels/10_041.rgba",0
F10_042: db "panels/10_042.rgba",0
F10_043: db "panels/10_043.rgba",0
F10_044: db "panels/10_044.rgba",0
F10_045: db "panels/10_045.rgba",0
F10_046: db "panels/10_046.rgba",0
F10_047: db "panels/10_047.rgba",0
F10_048: db "panels/10_048.rgba",0
F10_049: db "panels/10_049.rgba",0
F10_050: db "panels/10_050.rgba",0
F10_051: db "panels/10_051.rgba",0
F10_052: db "panels/10_052.rgba",0
F10_053: db "panels/10_053.rgba",0
F10_054: db "panels/10_054.rgba",0
F11_010: db "panels/11_010.rgba",0
F11_011: db "panels/11_011.rgba",0
F11_012: db "panels/11_012.rgba",0
F11_013: db "panels/11_013.rgba",0
F11_015: db "panels/11_015.rgba",0
F11_027: db "panels/11_027.rgba",0
F11_028: db "panels/11_028.rgba",0
F11_029: db "panels/11_029.rgba",0
F11_030: db "panels/11_030.rgba",0
F11_032: db "panels/11_032.rgba",0
F11_035: db "panels/11_035.rgba",0
F11_037: db "panels/11_037.rgba",0
F11_039: db "panels/11_039.rgba",0
F11_040: db "panels/11_040.rgba",0
F11_042: db "panels/11_042.rgba",0
F11_043: db "panels/11_043.rgba",0
F11_046: db "panels/11_046.rgba",0
F11_048: db "panels/11_048.rgba",0
F11_049: db "panels/11_049.rgba",0
F11_050: db "panels/11_050.rgba",0
F11_051: db "panels/11_051.rgba",0
F11_052: db "panels/11_052.rgba",0
F11_053: db "panels/11_053.rgba",0
F11_054: db "panels/11_054.rgba",0
F12_010: db "panels/12_010.rgba",0
F12_011: db "panels/12_011.rgba",0
F12_012: db "panels/12_012.rgba",0
F12_013: db "panels/12_013.rgba",0
F12_014: db "panels/12_014.rgba",0
F12_016: db "panels/12_016.rgba",0
F12_018: db "panels/12_018.rgba",0
F12_023: db "panels/12_023.rgba",0
F12_025: db "panels/12_025.rgba",0
F12_027: db "panels/12_027.rgba",0
F12_028: db "panels/12_028.rgba",0
F12_029: db "panels/12_029.rgba",0
F12_030: db "panels/12_030.rgba",0
F12_031: db "panels/12_031.rgba",0
F12_033: db "panels/12_033.rgba",0
F12_034: db "panels/12_034.rgba",0
F12_036: db "panels/12_036.rgba",0
F12_038: db "panels/12_038.rgba",0
F12_040: db "panels/12_040.rgba",0
F12_041: db "panels/12_041.rgba",0
F12_042: db "panels/12_042.rgba",0
F12_043: db "panels/12_043.rgba",0
F12_044: db "panels/12_044.rgba",0
F12_045: db "panels/12_045.rgba",0
F12_046: db "panels/12_046.rgba",0
F12_047: db "panels/12_047.rgba",0
F12_048: db "panels/12_048.rgba",0
F12_049: db "panels/12_049.rgba",0
F12_050: db "panels/12_050.rgba",0
F12_051: db "panels/12_051.rgba",0
F12_052: db "panels/12_052.rgba",0
F12_053: db "panels/12_053.rgba",0
F12_054: db "panels/12_054.rgba",0
F13_010: db "panels/13_010.rgba",0
F13_011: db "panels/13_011.rgba",0
F13_012: db "panels/13_012.rgba",0
F13_014: db "panels/13_014.rgba",0
F13_016: db "panels/13_016.rgba",0
F13_027: db "panels/13_027.rgba",0
F13_028: db "panels/13_028.rgba",0
F13_029: db "panels/13_029.rgba",0
F13_031: db "panels/13_031.rgba",0
F13_033: db "panels/13_033.rgba",0
F13_034: db "panels/13_034.rgba",0
F13_036: db "panels/13_036.rgba",0
F13_038: db "panels/13_038.rgba",0
F13_040: db "panels/13_040.rgba",0
F13_041: db "panels/13_041.rgba",0
F13_044: db "panels/13_044.rgba",0
F13_045: db "panels/13_045.rgba",0
F13_047: db "panels/13_047.rgba",0
F13_049: db "panels/13_049.rgba",0
F13_050: db "panels/13_050.rgba",0
F13_051: db "panels/13_051.rgba",0
F13_052: db "panels/13_052.rgba",0
F13_053: db "panels/13_053.rgba",0
F13_054: db "panels/13_054.rgba",0
F14_005: db "panels/14_005.rgba",0
F14_010: db "panels/14_010.rgba",0
F14_011: db "panels/14_011.rgba",0
F14_012: db "panels/14_012.rgba",0
F14_013: db "panels/14_013.rgba",0
F14_014: db "panels/14_014.rgba",0
F14_015: db "panels/14_015.rgba",0
F14_016: db "panels/14_016.rgba",0
F14_017: db "panels/14_017.rgba",0
F14_018: db "panels/14_018.rgba",0
F14_019: db "panels/14_019.rgba",0
F14_020: db "panels/14_020.rgba",0
F14_021: db "panels/14_021.rgba",0
F14_022: db "panels/14_022.rgba",0
F14_023: db "panels/14_023.rgba",0
F14_024: db "panels/14_024.rgba",0
F14_025: db "panels/14_025.rgba",0
F14_026: db "panels/14_026.rgba",0
F14_027: db "panels/14_027.rgba",0
F14_028: db "panels/14_028.rgba",0
F14_029: db "panels/14_029.rgba",0
F14_030: db "panels/14_030.rgba",0
F14_031: db "panels/14_031.rgba",0
F14_032: db "panels/14_032.rgba",0
F14_033: db "panels/14_033.rgba",0
F14_034: db "panels/14_034.rgba",0
F14_035: db "panels/14_035.rgba",0
F14_036: db "panels/14_036.rgba",0
F14_037: db "panels/14_037.rgba",0
F14_038: db "panels/14_038.rgba",0
F14_039: db "panels/14_039.rgba",0
F14_040: db "panels/14_040.rgba",0
F14_041: db "panels/14_041.rgba",0
F14_042: db "panels/14_042.rgba",0
F14_043: db "panels/14_043.rgba",0
F14_044: db "panels/14_044.rgba",0
F14_045: db "panels/14_045.rgba",0
F14_046: db "panels/14_046.rgba",0
F14_047: db "panels/14_047.rgba",0
F14_048: db "panels/14_048.rgba",0
F14_049: db "panels/14_049.rgba",0
F14_050: db "panels/14_050.rgba",0
F14_051: db "panels/14_051.rgba",0
F14_052: db "panels/14_052.rgba",0
F14_053: db "panels/14_053.rgba",0
F14_054: db "panels/14_054.rgba",0
F15_010: db "panels/15_010.rgba",0
F15_011: db "panels/15_011.rgba",0
F15_012: db "panels/15_012.rgba",0
F15_013: db "panels/15_013.rgba",0
F15_014: db "panels/15_014.rgba",0
F15_015: db "panels/15_015.rgba",0
F15_016: db "panels/15_016.rgba",0
F15_017: db "panels/15_017.rgba",0
F15_018: db "panels/15_018.rgba",0
F15_019: db "panels/15_019.rgba",0
F15_020: db "panels/15_020.rgba",0
F15_021: db "panels/15_021.rgba",0
F15_022: db "panels/15_022.rgba",0
F15_023: db "panels/15_023.rgba",0
F15_024: db "panels/15_024.rgba",0
F15_025: db "panels/15_025.rgba",0
F15_026: db "panels/15_026.rgba",0
F15_027: db "panels/15_027.rgba",0
F15_028: db "panels/15_028.rgba",0
F15_029: db "panels/15_029.rgba",0
F15_030: db "panels/15_030.rgba",0
F15_031: db "panels/15_031.rgba",0
F15_032: db "panels/15_032.rgba",0
F15_033: db "panels/15_033.rgba",0
F15_034: db "panels/15_034.rgba",0
F15_035: db "panels/15_035.rgba",0
F15_036: db "panels/15_036.rgba",0
F15_037: db "panels/15_037.rgba",0
F15_038: db "panels/15_038.rgba",0
F15_039: db "panels/15_039.rgba",0
F15_040: db "panels/15_040.rgba",0
F15_041: db "panels/15_041.rgba",0
F15_042: db "panels/15_042.rgba",0
F15_043: db "panels/15_043.rgba",0
F15_044: db "panels/15_044.rgba",0
F15_045: db "panels/15_045.rgba",0
F15_046: db "panels/15_046.rgba",0
F15_047: db "panels/15_047.rgba",0
F15_048: db "panels/15_048.rgba",0
F15_049: db "panels/15_049.rgba",0
F15_050: db "panels/15_050.rgba",0
F15_051: db "panels/15_051.rgba",0
F15_052: db "panels/15_052.rgba",0
F15_053: db "panels/15_053.rgba",0
F15_054: db "panels/15_054.rgba",0
F16_010: db "panels/16_010.rgba",0
F16_011: db "panels/16_011.rgba",0
F16_012: db "panels/16_012.rgba",0
F16_013: db "panels/16_013.rgba",0
F16_014: db "panels/16_014.rgba",0
F16_015: db "panels/16_015.rgba",0
F16_016: db "panels/16_016.rgba",0
F16_027: db "panels/16_027.rgba",0
F16_028: db "panels/16_028.rgba",0
F16_029: db "panels/16_029.rgba",0
F16_030: db "panels/16_030.rgba",0
F16_031: db "panels/16_031.rgba",0
F16_032: db "panels/16_032.rgba",0
F16_033: db "panels/16_033.rgba",0
F16_034: db "panels/16_034.rgba",0
F16_035: db "panels/16_035.rgba",0
F16_036: db "panels/16_036.rgba",0
F16_037: db "panels/16_037.rgba",0
F16_038: db "panels/16_038.rgba",0
F16_039: db "panels/16_039.rgba",0
F16_040: db "panels/16_040.rgba",0
F16_041: db "panels/16_041.rgba",0
F16_042: db "panels/16_042.rgba",0
F16_043: db "panels/16_043.rgba",0
F16_044: db "panels/16_044.rgba",0
F16_045: db "panels/16_045.rgba",0
F16_046: db "panels/16_046.rgba",0
F16_047: db "panels/16_047.rgba",0
F16_048: db "panels/16_048.rgba",0
F16_049: db "panels/16_049.rgba",0
F16_050: db "panels/16_050.rgba",0
F16_051: db "panels/16_051.rgba",0
F16_052: db "panels/16_052.rgba",0
F16_053: db "panels/16_053.rgba",0
F16_054: db "panels/16_054.rgba",0
F17_006: db "panels/17_006.rgba",0
F17_010: db "panels/17_010.rgba",0
F17_011: db "panels/17_011.rgba",0
F17_012: db "panels/17_012.rgba",0
F17_013: db "panels/17_013.rgba",0
F17_014: db "panels/17_014.rgba",0
F17_015: db "panels/17_015.rgba",0
F17_016: db "panels/17_016.rgba",0
F17_017: db "panels/17_017.rgba",0
F17_018: db "panels/17_018.rgba",0
F17_019: db "panels/17_019.rgba",0
F17_020: db "panels/17_020.rgba",0
F17_021: db "panels/17_021.rgba",0
F17_022: db "panels/17_022.rgba",0
F17_023: db "panels/17_023.rgba",0
F17_024: db "panels/17_024.rgba",0
F17_025: db "panels/17_025.rgba",0
F17_026: db "panels/17_026.rgba",0
F17_027: db "panels/17_027.rgba",0
F17_028: db "panels/17_028.rgba",0
F17_029: db "panels/17_029.rgba",0
F17_030: db "panels/17_030.rgba",0
F17_031: db "panels/17_031.rgba",0
F17_032: db "panels/17_032.rgba",0
F17_033: db "panels/17_033.rgba",0
F17_034: db "panels/17_034.rgba",0
F17_035: db "panels/17_035.rgba",0
F17_036: db "panels/17_036.rgba",0
F17_037: db "panels/17_037.rgba",0
F17_038: db "panels/17_038.rgba",0
F17_039: db "panels/17_039.rgba",0
F17_040: db "panels/17_040.rgba",0
F17_041: db "panels/17_041.rgba",0
F17_042: db "panels/17_042.rgba",0
F17_043: db "panels/17_043.rgba",0
F17_044: db "panels/17_044.rgba",0
F17_045: db "panels/17_045.rgba",0
F17_046: db "panels/17_046.rgba",0
F17_047: db "panels/17_047.rgba",0
F17_048: db "panels/17_048.rgba",0
F17_049: db "panels/17_049.rgba",0
F17_050: db "panels/17_050.rgba",0
F17_051: db "panels/17_051.rgba",0
F17_052: db "panels/17_052.rgba",0
F17_053: db "panels/17_053.rgba",0
F17_054: db "panels/17_054.rgba",0
F30_010: db "panels/30_010.rgba",0
F30_011: db "panels/30_011.rgba",0
F30_012: db "panels/30_012.rgba",0
F30_013: db "panels/30_013.rgba",0
F30_015: db "panels/30_015.rgba",0
F30_027: db "panels/30_027.rgba",0
F30_028: db "panels/30_028.rgba",0
F30_029: db "panels/30_029.rgba",0
F30_030: db "panels/30_030.rgba",0
F30_032: db "panels/30_032.rgba",0
F30_035: db "panels/30_035.rgba",0
F30_037: db "panels/30_037.rgba",0
F30_039: db "panels/30_039.rgba",0
F30_040: db "panels/30_040.rgba",0
F30_041: db "panels/30_041.rgba",0
F30_042: db "panels/30_042.rgba",0
F30_043: db "panels/30_043.rgba",0
F30_046: db "panels/30_046.rgba",0
F30_048: db "panels/30_048.rgba",0
F30_049: db "panels/30_049.rgba",0
F30_050: db "panels/30_050.rgba",0
F30_051: db "panels/30_051.rgba",0
F30_052: db "panels/30_052.rgba",0
F30_053: db "panels/30_053.rgba",0
F30_054: db "panels/30_054.rgba",0
F31_010: db "panels/31_010.rgba",0
F31_011: db "panels/31_011.rgba",0
F31_012: db "panels/31_012.rgba",0
F31_013: db "panels/31_013.rgba",0
F31_014: db "panels/31_014.rgba",0
F31_027: db "panels/31_027.rgba",0
F31_028: db "panels/31_028.rgba",0
F31_029: db "panels/31_029.rgba",0
F31_030: db "panels/31_030.rgba",0
F31_031: db "panels/31_031.rgba",0
F31_040: db "panels/31_040.rgba",0
F31_041: db "panels/31_041.rgba",0
F31_042: db "panels/31_042.rgba",0
F31_043: db "panels/31_043.rgba",0
F31_044: db "panels/31_044.rgba",0
F31_046: db "panels/31_046.rgba",0
F31_048: db "panels/31_048.rgba",0
F31_049: db "panels/31_049.rgba",0
F31_050: db "panels/31_050.rgba",0
F31_051: db "panels/31_051.rgba",0
F31_052: db "panels/31_052.rgba",0
F31_053: db "panels/31_053.rgba",0
F31_054: db "panels/31_054.rgba",0
F57_010: db "panels/57_010.rgba",0
F57_011: db "panels/57_011.rgba",0
F57_012: db "panels/57_012.rgba",0
F57_013: db "panels/57_013.rgba",0
F57_014: db "panels/57_014.rgba",0
F57_015: db "panels/57_015.rgba",0
F57_016: db "panels/57_016.rgba",0
F57_027: db "panels/57_027.rgba",0
F57_028: db "panels/57_028.rgba",0
F57_029: db "panels/57_029.rgba",0
F57_030: db "panels/57_030.rgba",0
F57_031: db "panels/57_031.rgba",0
F57_032: db "panels/57_032.rgba",0
F57_033: db "panels/57_033.rgba",0
F57_034: db "panels/57_034.rgba",0
F57_035: db "panels/57_035.rgba",0
F57_036: db "panels/57_036.rgba",0
F57_037: db "panels/57_037.rgba",0
F57_038: db "panels/57_038.rgba",0
F57_039: db "panels/57_039.rgba",0
F57_040: db "panels/57_040.rgba",0
F57_041: db "panels/57_041.rgba",0
F57_042: db "panels/57_042.rgba",0
F57_043: db "panels/57_043.rgba",0
F57_044: db "panels/57_044.rgba",0
F57_045: db "panels/57_045.rgba",0
F57_046: db "panels/57_046.rgba",0
F57_047: db "panels/57_047.rgba",0
F57_048: db "panels/57_048.rgba",0
F57_049: db "panels/57_049.rgba",0
F57_050: db "panels/57_050.rgba",0
F57_051: db "panels/57_051.rgba",0
F57_052: db "panels/57_052.rgba",0
F57_053: db "panels/57_053.rgba",0
F57_054: db "panels/57_054.rgba",0
F58_049: db "panels/58_049.rgba",0
F58_054: db "panels/58_054.rgba",0
F59_049: db "panels/59_049.rgba",0
F59_054: db "panels/59_054.rgba",0
