; Bitmap indices:
BUF_10_00: equ 0x0100
BUF_10_01: equ 0x0101
BUF_10_02: equ 0x0102
BUF_10_03: equ 0x0103
BUF_10_04: equ 0x0104
BUF_10_05: equ 0x0105
BUF_10_06: equ 0x0106
BUF_10_07: equ 0x0107
BUF_10_08: equ 0x0108
BUF_10_09: equ 0x0109
BUF_10_14: equ 0x010A
BUF_10_19: equ 0x010B
BUF_10_20: equ 0x010C
BUF_10_21: equ 0x010D
BUF_10_22: equ 0x010E
BUF_10_23: equ 0x010F
BUF_10_24: equ 0x0110
BUF_10_25: equ 0x0111
BUF_10_26: equ 0x0112
BUF_10_30: equ 0x0113
BUF_10_34: equ 0x0114
BUF_10_35: equ 0x0115
BUF_10_36: equ 0x0116
BUF_10_37: equ 0x0117
BUF_10_38: equ 0x0118
BUF_10_39: equ 0x0119
BUF_10_42: equ 0x011A
BUF_10_45: equ 0x011B
BUF_10_46: equ 0x011C
BUF_10_47: equ 0x011D
BUF_10_48: equ 0x011E
BUF_10_50: equ 0x011F
BUF_10_52: equ 0x0120
BUF_10_53: equ 0x0121
BUF_10_54: equ 0x0122
BUF_11_00: equ 0x0123
BUF_11_01: equ 0x0124
BUF_11_02: equ 0x0125
BUF_11_03: equ 0x0126
BUF_11_04: equ 0x0127
BUF_11_05: equ 0x0128
BUF_11_06: equ 0x0129
BUF_11_07: equ 0x012A
BUF_11_08: equ 0x012B
BUF_11_09: equ 0x012C
BUF_11_14: equ 0x012D
BUF_11_19: equ 0x012E
BUF_11_20: equ 0x012F
BUF_11_21: equ 0x0130
BUF_11_22: equ 0x0131
BUF_11_23: equ 0x0132
BUF_11_24: equ 0x0133
BUF_11_25: equ 0x0134
BUF_11_26: equ 0x0135
BUF_11_30: equ 0x0136
BUF_11_34: equ 0x0137
BUF_11_35: equ 0x0138
BUF_11_36: equ 0x0139
BUF_11_37: equ 0x013A
BUF_11_38: equ 0x013B
BUF_11_39: equ 0x013C
BUF_11_42: equ 0x013D
BUF_11_45: equ 0x013E
BUF_11_46: equ 0x013F
BUF_11_47: equ 0x0140
BUF_11_48: equ 0x0141
BUF_11_50: equ 0x0142
BUF_11_52: equ 0x0143
BUF_11_53: equ 0x0144
BUF_11_54: equ 0x0145
BUF_12_00: equ 0x0146
BUF_12_01: equ 0x0147
BUF_12_02: equ 0x0148
BUF_12_03: equ 0x0149
BUF_12_04: equ 0x014A
BUF_12_05: equ 0x014B
BUF_12_06: equ 0x014C
BUF_12_07: equ 0x014D
BUF_12_08: equ 0x014E
BUF_12_09: equ 0x014F
BUF_12_14: equ 0x0150
BUF_12_19: equ 0x0151
BUF_12_20: equ 0x0152
BUF_12_21: equ 0x0153
BUF_12_22: equ 0x0154
BUF_12_23: equ 0x0155
BUF_12_24: equ 0x0156
BUF_12_25: equ 0x0157
BUF_12_26: equ 0x0158
BUF_12_30: equ 0x0159
BUF_12_34: equ 0x015A
BUF_12_35: equ 0x015B
BUF_12_36: equ 0x015C
BUF_12_37: equ 0x015D
BUF_12_38: equ 0x015E
BUF_12_39: equ 0x015F
BUF_12_42: equ 0x0160
BUF_12_45: equ 0x0161
BUF_12_46: equ 0x0162
BUF_12_47: equ 0x0163
BUF_12_48: equ 0x0164
BUF_12_50: equ 0x0165
BUF_12_52: equ 0x0166
BUF_12_53: equ 0x0167
BUF_12_54: equ 0x0168
BUF_13_00: equ 0x0169
BUF_13_01: equ 0x016A
BUF_13_02: equ 0x016B
BUF_13_03: equ 0x016C
BUF_13_04: equ 0x016D
BUF_13_05: equ 0x016E
BUF_13_06: equ 0x016F
BUF_13_07: equ 0x0170
BUF_13_08: equ 0x0171
BUF_13_09: equ 0x0172
BUF_13_14: equ 0x0173
BUF_13_19: equ 0x0174
BUF_13_20: equ 0x0175
BUF_13_21: equ 0x0176
BUF_13_22: equ 0x0177
BUF_13_23: equ 0x0178
BUF_13_24: equ 0x0179
BUF_13_25: equ 0x017A
BUF_13_26: equ 0x017B
BUF_13_30: equ 0x017C
BUF_13_34: equ 0x017D
BUF_13_35: equ 0x017E
BUF_13_36: equ 0x017F
BUF_13_37: equ 0x0180
BUF_13_38: equ 0x0181
BUF_13_39: equ 0x0182
BUF_13_42: equ 0x0183
BUF_13_45: equ 0x0184
BUF_13_46: equ 0x0185
BUF_13_47: equ 0x0186
BUF_13_48: equ 0x0187
BUF_13_50: equ 0x0188
BUF_13_52: equ 0x0189
BUF_13_53: equ 0x018A
BUF_13_54: equ 0x018B
BUF_14_00: equ 0x018C
BUF_14_01: equ 0x018D
BUF_14_02: equ 0x018E
BUF_14_03: equ 0x018F
BUF_14_04: equ 0x0190
BUF_14_05: equ 0x0191
BUF_14_06: equ 0x0192
BUF_14_07: equ 0x0193
BUF_14_08: equ 0x0194
BUF_14_09: equ 0x0195
BUF_14_14: equ 0x0196
BUF_14_19: equ 0x0197
BUF_14_20: equ 0x0198
BUF_14_21: equ 0x0199
BUF_14_22: equ 0x019A
BUF_14_23: equ 0x019B
BUF_14_24: equ 0x019C
BUF_14_25: equ 0x019D
BUF_14_26: equ 0x019E
BUF_14_30: equ 0x019F
BUF_14_34: equ 0x01A0
BUF_14_35: equ 0x01A1
BUF_14_36: equ 0x01A2
BUF_14_37: equ 0x01A3
BUF_14_38: equ 0x01A4
BUF_14_39: equ 0x01A5
BUF_14_42: equ 0x01A6
BUF_14_45: equ 0x01A7
BUF_14_46: equ 0x01A8
BUF_14_47: equ 0x01A9
BUF_14_48: equ 0x01AA
BUF_14_50: equ 0x01AB
BUF_14_52: equ 0x01AC
BUF_14_53: equ 0x01AD
BUF_14_54: equ 0x01AE
BUF_15_00: equ 0x01AF
BUF_15_01: equ 0x01B0
BUF_15_02: equ 0x01B1
BUF_15_03: equ 0x01B2
BUF_15_04: equ 0x01B3
BUF_15_05: equ 0x01B4
BUF_15_06: equ 0x01B5
BUF_15_07: equ 0x01B6
BUF_15_08: equ 0x01B7
BUF_15_09: equ 0x01B8
BUF_15_14: equ 0x01B9
BUF_15_19: equ 0x01BA
BUF_15_20: equ 0x01BB
BUF_15_21: equ 0x01BC
BUF_15_22: equ 0x01BD
BUF_15_23: equ 0x01BE
BUF_15_24: equ 0x01BF
BUF_15_25: equ 0x01C0
BUF_15_26: equ 0x01C1
BUF_15_30: equ 0x01C2
BUF_15_34: equ 0x01C3
BUF_15_35: equ 0x01C4
BUF_15_36: equ 0x01C5
BUF_15_37: equ 0x01C6
BUF_15_38: equ 0x01C7
BUF_15_39: equ 0x01C8
BUF_15_42: equ 0x01C9
BUF_15_45: equ 0x01CA
BUF_15_46: equ 0x01CB
BUF_15_47: equ 0x01CC
BUF_15_48: equ 0x01CD
BUF_15_50: equ 0x01CE
BUF_15_52: equ 0x01CF
BUF_15_53: equ 0x01D0
BUF_15_54: equ 0x01D1
BUF_16_00: equ 0x01D2
BUF_16_01: equ 0x01D3
BUF_16_02: equ 0x01D4
BUF_16_03: equ 0x01D5
BUF_16_04: equ 0x01D6
BUF_16_05: equ 0x01D7
BUF_16_06: equ 0x01D8
BUF_16_07: equ 0x01D9
BUF_16_08: equ 0x01DA
BUF_16_09: equ 0x01DB
BUF_16_14: equ 0x01DC
BUF_16_19: equ 0x01DD
BUF_16_20: equ 0x01DE
BUF_16_21: equ 0x01DF
BUF_16_22: equ 0x01E0
BUF_16_23: equ 0x01E1
BUF_16_24: equ 0x01E2
BUF_16_25: equ 0x01E3
BUF_16_26: equ 0x01E4
BUF_16_30: equ 0x01E5
BUF_16_34: equ 0x01E6
BUF_16_35: equ 0x01E7
BUF_16_36: equ 0x01E8
BUF_16_37: equ 0x01E9
BUF_16_38: equ 0x01EA
BUF_16_39: equ 0x01EB
BUF_16_42: equ 0x01EC
BUF_16_45: equ 0x01ED
BUF_16_46: equ 0x01EE
BUF_16_47: equ 0x01EF
BUF_16_48: equ 0x01F0
BUF_16_50: equ 0x01F1
BUF_16_52: equ 0x01F2
BUF_16_53: equ 0x01F3
BUF_16_54: equ 0x01F4
BUF_17_00: equ 0x01F5
BUF_17_01: equ 0x01F6
BUF_17_02: equ 0x01F7
BUF_17_03: equ 0x01F8
BUF_17_04: equ 0x01F9
BUF_17_05: equ 0x01FA
BUF_17_06: equ 0x01FB
BUF_17_07: equ 0x01FC
BUF_17_08: equ 0x01FD
BUF_17_09: equ 0x01FE
BUF_17_14: equ 0x01FF
BUF_17_19: equ 0x0200
BUF_17_20: equ 0x0201
BUF_17_21: equ 0x0202
BUF_17_22: equ 0x0203
BUF_17_23: equ 0x0204
BUF_17_24: equ 0x0205
BUF_17_25: equ 0x0206
BUF_17_26: equ 0x0207
BUF_17_30: equ 0x0208
BUF_17_34: equ 0x0209
BUF_17_35: equ 0x020A
BUF_17_36: equ 0x020B
BUF_17_37: equ 0x020C
BUF_17_38: equ 0x020D
BUF_17_39: equ 0x020E
BUF_17_42: equ 0x020F
BUF_17_45: equ 0x0210
BUF_17_46: equ 0x0211
BUF_17_47: equ 0x0212
BUF_17_48: equ 0x0213
BUF_17_50: equ 0x0214
BUF_17_52: equ 0x0215
BUF_17_53: equ 0x0216
BUF_17_54: equ 0x0217
BUF_30_00: equ 0x0218
BUF_30_01: equ 0x0219
BUF_30_02: equ 0x021A
BUF_30_03: equ 0x021B
BUF_30_04: equ 0x021C
BUF_30_05: equ 0x021D
BUF_30_06: equ 0x021E
BUF_30_07: equ 0x021F
BUF_30_08: equ 0x0220
BUF_30_09: equ 0x0221
BUF_30_14: equ 0x0222
BUF_30_19: equ 0x0223
BUF_30_20: equ 0x0224
BUF_30_21: equ 0x0225
BUF_30_22: equ 0x0226
BUF_30_23: equ 0x0227
BUF_30_24: equ 0x0228
BUF_30_25: equ 0x0229
BUF_30_26: equ 0x022A
BUF_30_30: equ 0x022B
BUF_30_34: equ 0x022C
BUF_30_35: equ 0x022D
BUF_30_36: equ 0x022E
BUF_30_37: equ 0x022F
BUF_30_38: equ 0x0230
BUF_30_39: equ 0x0231
BUF_30_42: equ 0x0232
BUF_30_45: equ 0x0233
BUF_30_46: equ 0x0234
BUF_30_47: equ 0x0235
BUF_30_48: equ 0x0236
BUF_30_50: equ 0x0237
BUF_30_52: equ 0x0238
BUF_30_53: equ 0x0239
BUF_30_54: equ 0x023A
BUF_31_00: equ 0x023B
BUF_31_01: equ 0x023C
BUF_31_02: equ 0x023D
BUF_31_03: equ 0x023E
BUF_31_04: equ 0x023F
BUF_31_05: equ 0x0240
BUF_31_06: equ 0x0241
BUF_31_07: equ 0x0242
BUF_31_08: equ 0x0243
BUF_31_09: equ 0x0244
BUF_31_14: equ 0x0245
BUF_31_19: equ 0x0246
BUF_31_20: equ 0x0247
BUF_31_21: equ 0x0248
BUF_31_22: equ 0x0249
BUF_31_23: equ 0x024A
BUF_31_24: equ 0x024B
BUF_31_25: equ 0x024C
BUF_31_26: equ 0x024D
BUF_31_30: equ 0x024E
BUF_31_34: equ 0x024F
BUF_31_35: equ 0x0250
BUF_31_36: equ 0x0251
BUF_31_37: equ 0x0252
BUF_31_38: equ 0x0253
BUF_31_39: equ 0x0254
BUF_31_42: equ 0x0255
BUF_31_45: equ 0x0256
BUF_31_46: equ 0x0257
BUF_31_47: equ 0x0258
BUF_31_48: equ 0x0259
BUF_31_50: equ 0x025A
BUF_31_52: equ 0x025B
BUF_31_53: equ 0x025C
BUF_31_54: equ 0x025D
BUF_32_00: equ 0x025E
BUF_32_01: equ 0x025F
BUF_32_02: equ 0x0260
BUF_32_03: equ 0x0261
BUF_32_04: equ 0x0262
BUF_32_05: equ 0x0263
BUF_32_06: equ 0x0264
BUF_32_07: equ 0x0265
BUF_32_08: equ 0x0266
BUF_32_09: equ 0x0267
BUF_32_14: equ 0x0268
BUF_32_19: equ 0x0269
BUF_32_20: equ 0x026A
BUF_32_21: equ 0x026B
BUF_32_22: equ 0x026C
BUF_32_23: equ 0x026D
BUF_32_24: equ 0x026E
BUF_32_25: equ 0x026F
BUF_32_26: equ 0x0270
BUF_32_30: equ 0x0271
BUF_32_34: equ 0x0272
BUF_32_35: equ 0x0273
BUF_32_36: equ 0x0274
BUF_32_37: equ 0x0275
BUF_32_38: equ 0x0276
BUF_32_39: equ 0x0277
BUF_32_42: equ 0x0278
BUF_32_45: equ 0x0279
BUF_32_46: equ 0x027A
BUF_32_47: equ 0x027B
BUF_32_48: equ 0x027C
BUF_32_50: equ 0x027D
BUF_32_52: equ 0x027E
BUF_32_53: equ 0x027F
BUF_32_54: equ 0x0280

; Import .rgba bitmap files and load them into VDP buffers
load_panels:

	ld hl,F10_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F30_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_30_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F31_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_31_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_00
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_00
	ld bc,29
	ld de,36
	ld ix,1044
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_01
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_01
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_02
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_02
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_03
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_03
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_04
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_04
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_05
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_05
	ld bc,3
	ld de,36
	ld ix,108
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_06
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_06
	ld bc,9
	ld de,36
	ld ix,324
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_07
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_07
	ld bc,16
	ld de,36
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_08
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_08
	ld bc,22
	ld de,36
	ld ix,792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_09
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_09
	ld bc,28
	ld de,34
	ld ix,952
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_14
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_14
	ld bc,36
	ld de,36
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_19
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_19
	ld bc,36
	ld de,46
	ld ix,1656
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_20
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_20
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_21
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_21
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_22
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_22
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_23
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_23
	ld bc,5
	ld de,46
	ld ix,230
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_24
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_24
	ld bc,16
	ld de,46
	ld ix,736
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_25
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_25
	ld bc,25
	ld de,46
	ld ix,1150
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_26
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_26
	ld bc,35
	ld de,44
	ld ix,1540
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_30
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_30
	ld bc,46
	ld de,46
	ld ix,2116
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_34
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_34
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_35
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_35
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_36
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_36
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_37
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_37
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_38
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_38
	ld bc,27
	ld de,64
	ld ix,1728
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_39
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_39
	ld bc,45
	ld de,62
	ld ix,2790
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_42
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_42
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_45
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_45
	ld bc,64
	ld de,106
	ld ix,6784
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_46
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_46
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_47
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_47
	ld bc,21
	ld de,106
	ld ix,2226
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_48
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_48
	ld bc,63
	ld de,104
	ld ix,6552
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_50
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_50
	ld bc,106
	ld de,106
	ld ix,11236
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_52
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_52
	ld bc,107
	ld de,159
	ld ix,17013
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_53
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_53
	ld bc,106
	ld de,159
	ld ix,16854
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F32_54
	ld de,filedata
	ld bc,76800
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_32_54
	ld bc,319
	ld de,159
	ld ix,50721
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ret
F10_00: db "panels/10_00.rgba",0
F10_01: db "panels/10_01.rgba",0
F10_02: db "panels/10_02.rgba",0
F10_03: db "panels/10_03.rgba",0
F10_04: db "panels/10_04.rgba",0
F10_05: db "panels/10_05.rgba",0
F10_06: db "panels/10_06.rgba",0
F10_07: db "panels/10_07.rgba",0
F10_08: db "panels/10_08.rgba",0
F10_09: db "panels/10_09.rgba",0
F10_14: db "panels/10_14.rgba",0
F10_19: db "panels/10_19.rgba",0
F10_20: db "panels/10_20.rgba",0
F10_21: db "panels/10_21.rgba",0
F10_22: db "panels/10_22.rgba",0
F10_23: db "panels/10_23.rgba",0
F10_24: db "panels/10_24.rgba",0
F10_25: db "panels/10_25.rgba",0
F10_26: db "panels/10_26.rgba",0
F10_30: db "panels/10_30.rgba",0
F10_34: db "panels/10_34.rgba",0
F10_35: db "panels/10_35.rgba",0
F10_36: db "panels/10_36.rgba",0
F10_37: db "panels/10_37.rgba",0
F10_38: db "panels/10_38.rgba",0
F10_39: db "panels/10_39.rgba",0
F10_42: db "panels/10_42.rgba",0
F10_45: db "panels/10_45.rgba",0
F10_46: db "panels/10_46.rgba",0
F10_47: db "panels/10_47.rgba",0
F10_48: db "panels/10_48.rgba",0
F10_50: db "panels/10_50.rgba",0
F10_52: db "panels/10_52.rgba",0
F10_53: db "panels/10_53.rgba",0
F10_54: db "panels/10_54.rgba",0
F11_00: db "panels/11_00.rgba",0
F11_01: db "panels/11_01.rgba",0
F11_02: db "panels/11_02.rgba",0
F11_03: db "panels/11_03.rgba",0
F11_04: db "panels/11_04.rgba",0
F11_05: db "panels/11_05.rgba",0
F11_06: db "panels/11_06.rgba",0
F11_07: db "panels/11_07.rgba",0
F11_08: db "panels/11_08.rgba",0
F11_09: db "panels/11_09.rgba",0
F11_14: db "panels/11_14.rgba",0
F11_19: db "panels/11_19.rgba",0
F11_20: db "panels/11_20.rgba",0
F11_21: db "panels/11_21.rgba",0
F11_22: db "panels/11_22.rgba",0
F11_23: db "panels/11_23.rgba",0
F11_24: db "panels/11_24.rgba",0
F11_25: db "panels/11_25.rgba",0
F11_26: db "panels/11_26.rgba",0
F11_30: db "panels/11_30.rgba",0
F11_34: db "panels/11_34.rgba",0
F11_35: db "panels/11_35.rgba",0
F11_36: db "panels/11_36.rgba",0
F11_37: db "panels/11_37.rgba",0
F11_38: db "panels/11_38.rgba",0
F11_39: db "panels/11_39.rgba",0
F11_42: db "panels/11_42.rgba",0
F11_45: db "panels/11_45.rgba",0
F11_46: db "panels/11_46.rgba",0
F11_47: db "panels/11_47.rgba",0
F11_48: db "panels/11_48.rgba",0
F11_50: db "panels/11_50.rgba",0
F11_52: db "panels/11_52.rgba",0
F11_53: db "panels/11_53.rgba",0
F11_54: db "panels/11_54.rgba",0
F12_00: db "panels/12_00.rgba",0
F12_01: db "panels/12_01.rgba",0
F12_02: db "panels/12_02.rgba",0
F12_03: db "panels/12_03.rgba",0
F12_04: db "panels/12_04.rgba",0
F12_05: db "panels/12_05.rgba",0
F12_06: db "panels/12_06.rgba",0
F12_07: db "panels/12_07.rgba",0
F12_08: db "panels/12_08.rgba",0
F12_09: db "panels/12_09.rgba",0
F12_14: db "panels/12_14.rgba",0
F12_19: db "panels/12_19.rgba",0
F12_20: db "panels/12_20.rgba",0
F12_21: db "panels/12_21.rgba",0
F12_22: db "panels/12_22.rgba",0
F12_23: db "panels/12_23.rgba",0
F12_24: db "panels/12_24.rgba",0
F12_25: db "panels/12_25.rgba",0
F12_26: db "panels/12_26.rgba",0
F12_30: db "panels/12_30.rgba",0
F12_34: db "panels/12_34.rgba",0
F12_35: db "panels/12_35.rgba",0
F12_36: db "panels/12_36.rgba",0
F12_37: db "panels/12_37.rgba",0
F12_38: db "panels/12_38.rgba",0
F12_39: db "panels/12_39.rgba",0
F12_42: db "panels/12_42.rgba",0
F12_45: db "panels/12_45.rgba",0
F12_46: db "panels/12_46.rgba",0
F12_47: db "panels/12_47.rgba",0
F12_48: db "panels/12_48.rgba",0
F12_50: db "panels/12_50.rgba",0
F12_52: db "panels/12_52.rgba",0
F12_53: db "panels/12_53.rgba",0
F12_54: db "panels/12_54.rgba",0
F13_00: db "panels/13_00.rgba",0
F13_01: db "panels/13_01.rgba",0
F13_02: db "panels/13_02.rgba",0
F13_03: db "panels/13_03.rgba",0
F13_04: db "panels/13_04.rgba",0
F13_05: db "panels/13_05.rgba",0
F13_06: db "panels/13_06.rgba",0
F13_07: db "panels/13_07.rgba",0
F13_08: db "panels/13_08.rgba",0
F13_09: db "panels/13_09.rgba",0
F13_14: db "panels/13_14.rgba",0
F13_19: db "panels/13_19.rgba",0
F13_20: db "panels/13_20.rgba",0
F13_21: db "panels/13_21.rgba",0
F13_22: db "panels/13_22.rgba",0
F13_23: db "panels/13_23.rgba",0
F13_24: db "panels/13_24.rgba",0
F13_25: db "panels/13_25.rgba",0
F13_26: db "panels/13_26.rgba",0
F13_30: db "panels/13_30.rgba",0
F13_34: db "panels/13_34.rgba",0
F13_35: db "panels/13_35.rgba",0
F13_36: db "panels/13_36.rgba",0
F13_37: db "panels/13_37.rgba",0
F13_38: db "panels/13_38.rgba",0
F13_39: db "panels/13_39.rgba",0
F13_42: db "panels/13_42.rgba",0
F13_45: db "panels/13_45.rgba",0
F13_46: db "panels/13_46.rgba",0
F13_47: db "panels/13_47.rgba",0
F13_48: db "panels/13_48.rgba",0
F13_50: db "panels/13_50.rgba",0
F13_52: db "panels/13_52.rgba",0
F13_53: db "panels/13_53.rgba",0
F13_54: db "panels/13_54.rgba",0
F14_00: db "panels/14_00.rgba",0
F14_01: db "panels/14_01.rgba",0
F14_02: db "panels/14_02.rgba",0
F14_03: db "panels/14_03.rgba",0
F14_04: db "panels/14_04.rgba",0
F14_05: db "panels/14_05.rgba",0
F14_06: db "panels/14_06.rgba",0
F14_07: db "panels/14_07.rgba",0
F14_08: db "panels/14_08.rgba",0
F14_09: db "panels/14_09.rgba",0
F14_14: db "panels/14_14.rgba",0
F14_19: db "panels/14_19.rgba",0
F14_20: db "panels/14_20.rgba",0
F14_21: db "panels/14_21.rgba",0
F14_22: db "panels/14_22.rgba",0
F14_23: db "panels/14_23.rgba",0
F14_24: db "panels/14_24.rgba",0
F14_25: db "panels/14_25.rgba",0
F14_26: db "panels/14_26.rgba",0
F14_30: db "panels/14_30.rgba",0
F14_34: db "panels/14_34.rgba",0
F14_35: db "panels/14_35.rgba",0
F14_36: db "panels/14_36.rgba",0
F14_37: db "panels/14_37.rgba",0
F14_38: db "panels/14_38.rgba",0
F14_39: db "panels/14_39.rgba",0
F14_42: db "panels/14_42.rgba",0
F14_45: db "panels/14_45.rgba",0
F14_46: db "panels/14_46.rgba",0
F14_47: db "panels/14_47.rgba",0
F14_48: db "panels/14_48.rgba",0
F14_50: db "panels/14_50.rgba",0
F14_52: db "panels/14_52.rgba",0
F14_53: db "panels/14_53.rgba",0
F14_54: db "panels/14_54.rgba",0
F15_00: db "panels/15_00.rgba",0
F15_01: db "panels/15_01.rgba",0
F15_02: db "panels/15_02.rgba",0
F15_03: db "panels/15_03.rgba",0
F15_04: db "panels/15_04.rgba",0
F15_05: db "panels/15_05.rgba",0
F15_06: db "panels/15_06.rgba",0
F15_07: db "panels/15_07.rgba",0
F15_08: db "panels/15_08.rgba",0
F15_09: db "panels/15_09.rgba",0
F15_14: db "panels/15_14.rgba",0
F15_19: db "panels/15_19.rgba",0
F15_20: db "panels/15_20.rgba",0
F15_21: db "panels/15_21.rgba",0
F15_22: db "panels/15_22.rgba",0
F15_23: db "panels/15_23.rgba",0
F15_24: db "panels/15_24.rgba",0
F15_25: db "panels/15_25.rgba",0
F15_26: db "panels/15_26.rgba",0
F15_30: db "panels/15_30.rgba",0
F15_34: db "panels/15_34.rgba",0
F15_35: db "panels/15_35.rgba",0
F15_36: db "panels/15_36.rgba",0
F15_37: db "panels/15_37.rgba",0
F15_38: db "panels/15_38.rgba",0
F15_39: db "panels/15_39.rgba",0
F15_42: db "panels/15_42.rgba",0
F15_45: db "panels/15_45.rgba",0
F15_46: db "panels/15_46.rgba",0
F15_47: db "panels/15_47.rgba",0
F15_48: db "panels/15_48.rgba",0
F15_50: db "panels/15_50.rgba",0
F15_52: db "panels/15_52.rgba",0
F15_53: db "panels/15_53.rgba",0
F15_54: db "panels/15_54.rgba",0
F16_00: db "panels/16_00.rgba",0
F16_01: db "panels/16_01.rgba",0
F16_02: db "panels/16_02.rgba",0
F16_03: db "panels/16_03.rgba",0
F16_04: db "panels/16_04.rgba",0
F16_05: db "panels/16_05.rgba",0
F16_06: db "panels/16_06.rgba",0
F16_07: db "panels/16_07.rgba",0
F16_08: db "panels/16_08.rgba",0
F16_09: db "panels/16_09.rgba",0
F16_14: db "panels/16_14.rgba",0
F16_19: db "panels/16_19.rgba",0
F16_20: db "panels/16_20.rgba",0
F16_21: db "panels/16_21.rgba",0
F16_22: db "panels/16_22.rgba",0
F16_23: db "panels/16_23.rgba",0
F16_24: db "panels/16_24.rgba",0
F16_25: db "panels/16_25.rgba",0
F16_26: db "panels/16_26.rgba",0
F16_30: db "panels/16_30.rgba",0
F16_34: db "panels/16_34.rgba",0
F16_35: db "panels/16_35.rgba",0
F16_36: db "panels/16_36.rgba",0
F16_37: db "panels/16_37.rgba",0
F16_38: db "panels/16_38.rgba",0
F16_39: db "panels/16_39.rgba",0
F16_42: db "panels/16_42.rgba",0
F16_45: db "panels/16_45.rgba",0
F16_46: db "panels/16_46.rgba",0
F16_47: db "panels/16_47.rgba",0
F16_48: db "panels/16_48.rgba",0
F16_50: db "panels/16_50.rgba",0
F16_52: db "panels/16_52.rgba",0
F16_53: db "panels/16_53.rgba",0
F16_54: db "panels/16_54.rgba",0
F17_00: db "panels/17_00.rgba",0
F17_01: db "panels/17_01.rgba",0
F17_02: db "panels/17_02.rgba",0
F17_03: db "panels/17_03.rgba",0
F17_04: db "panels/17_04.rgba",0
F17_05: db "panels/17_05.rgba",0
F17_06: db "panels/17_06.rgba",0
F17_07: db "panels/17_07.rgba",0
F17_08: db "panels/17_08.rgba",0
F17_09: db "panels/17_09.rgba",0
F17_14: db "panels/17_14.rgba",0
F17_19: db "panels/17_19.rgba",0
F17_20: db "panels/17_20.rgba",0
F17_21: db "panels/17_21.rgba",0
F17_22: db "panels/17_22.rgba",0
F17_23: db "panels/17_23.rgba",0
F17_24: db "panels/17_24.rgba",0
F17_25: db "panels/17_25.rgba",0
F17_26: db "panels/17_26.rgba",0
F17_30: db "panels/17_30.rgba",0
F17_34: db "panels/17_34.rgba",0
F17_35: db "panels/17_35.rgba",0
F17_36: db "panels/17_36.rgba",0
F17_37: db "panels/17_37.rgba",0
F17_38: db "panels/17_38.rgba",0
F17_39: db "panels/17_39.rgba",0
F17_42: db "panels/17_42.rgba",0
F17_45: db "panels/17_45.rgba",0
F17_46: db "panels/17_46.rgba",0
F17_47: db "panels/17_47.rgba",0
F17_48: db "panels/17_48.rgba",0
F17_50: db "panels/17_50.rgba",0
F17_52: db "panels/17_52.rgba",0
F17_53: db "panels/17_53.rgba",0
F17_54: db "panels/17_54.rgba",0
F30_00: db "panels/30_00.rgba",0
F30_01: db "panels/30_01.rgba",0
F30_02: db "panels/30_02.rgba",0
F30_03: db "panels/30_03.rgba",0
F30_04: db "panels/30_04.rgba",0
F30_05: db "panels/30_05.rgba",0
F30_06: db "panels/30_06.rgba",0
F30_07: db "panels/30_07.rgba",0
F30_08: db "panels/30_08.rgba",0
F30_09: db "panels/30_09.rgba",0
F30_14: db "panels/30_14.rgba",0
F30_19: db "panels/30_19.rgba",0
F30_20: db "panels/30_20.rgba",0
F30_21: db "panels/30_21.rgba",0
F30_22: db "panels/30_22.rgba",0
F30_23: db "panels/30_23.rgba",0
F30_24: db "panels/30_24.rgba",0
F30_25: db "panels/30_25.rgba",0
F30_26: db "panels/30_26.rgba",0
F30_30: db "panels/30_30.rgba",0
F30_34: db "panels/30_34.rgba",0
F30_35: db "panels/30_35.rgba",0
F30_36: db "panels/30_36.rgba",0
F30_37: db "panels/30_37.rgba",0
F30_38: db "panels/30_38.rgba",0
F30_39: db "panels/30_39.rgba",0
F30_42: db "panels/30_42.rgba",0
F30_45: db "panels/30_45.rgba",0
F30_46: db "panels/30_46.rgba",0
F30_47: db "panels/30_47.rgba",0
F30_48: db "panels/30_48.rgba",0
F30_50: db "panels/30_50.rgba",0
F30_52: db "panels/30_52.rgba",0
F30_53: db "panels/30_53.rgba",0
F30_54: db "panels/30_54.rgba",0
F31_00: db "panels/31_00.rgba",0
F31_01: db "panels/31_01.rgba",0
F31_02: db "panels/31_02.rgba",0
F31_03: db "panels/31_03.rgba",0
F31_04: db "panels/31_04.rgba",0
F31_05: db "panels/31_05.rgba",0
F31_06: db "panels/31_06.rgba",0
F31_07: db "panels/31_07.rgba",0
F31_08: db "panels/31_08.rgba",0
F31_09: db "panels/31_09.rgba",0
F31_14: db "panels/31_14.rgba",0
F31_19: db "panels/31_19.rgba",0
F31_20: db "panels/31_20.rgba",0
F31_21: db "panels/31_21.rgba",0
F31_22: db "panels/31_22.rgba",0
F31_23: db "panels/31_23.rgba",0
F31_24: db "panels/31_24.rgba",0
F31_25: db "panels/31_25.rgba",0
F31_26: db "panels/31_26.rgba",0
F31_30: db "panels/31_30.rgba",0
F31_34: db "panels/31_34.rgba",0
F31_35: db "panels/31_35.rgba",0
F31_36: db "panels/31_36.rgba",0
F31_37: db "panels/31_37.rgba",0
F31_38: db "panels/31_38.rgba",0
F31_39: db "panels/31_39.rgba",0
F31_42: db "panels/31_42.rgba",0
F31_45: db "panels/31_45.rgba",0
F31_46: db "panels/31_46.rgba",0
F31_47: db "panels/31_47.rgba",0
F31_48: db "panels/31_48.rgba",0
F31_50: db "panels/31_50.rgba",0
F31_52: db "panels/31_52.rgba",0
F31_53: db "panels/31_53.rgba",0
F31_54: db "panels/31_54.rgba",0
F32_00: db "panels/32_00.rgba",0
F32_01: db "panels/32_01.rgba",0
F32_02: db "panels/32_02.rgba",0
F32_03: db "panels/32_03.rgba",0
F32_04: db "panels/32_04.rgba",0
F32_05: db "panels/32_05.rgba",0
F32_06: db "panels/32_06.rgba",0
F32_07: db "panels/32_07.rgba",0
F32_08: db "panels/32_08.rgba",0
F32_09: db "panels/32_09.rgba",0
F32_14: db "panels/32_14.rgba",0
F32_19: db "panels/32_19.rgba",0
F32_20: db "panels/32_20.rgba",0
F32_21: db "panels/32_21.rgba",0
F32_22: db "panels/32_22.rgba",0
F32_23: db "panels/32_23.rgba",0
F32_24: db "panels/32_24.rgba",0
F32_25: db "panels/32_25.rgba",0
F32_26: db "panels/32_26.rgba",0
F32_30: db "panels/32_30.rgba",0
F32_34: db "panels/32_34.rgba",0
F32_35: db "panels/32_35.rgba",0
F32_36: db "panels/32_36.rgba",0
F32_37: db "panels/32_37.rgba",0
F32_38: db "panels/32_38.rgba",0
F32_39: db "panels/32_39.rgba",0
F32_42: db "panels/32_42.rgba",0
F32_45: db "panels/32_45.rgba",0
F32_46: db "panels/32_46.rgba",0
F32_47: db "panels/32_47.rgba",0
F32_48: db "panels/32_48.rgba",0
F32_50: db "panels/32_50.rgba",0
F32_52: db "panels/32_52.rgba",0
F32_53: db "panels/32_53.rgba",0
F32_54: db "panels/32_54.rgba",0

	ret
