; Bitmap indices:
BUF_10_004: equ 0x0100
BUF_10_009: equ 0x0101
BUF_10_010: equ 0x0102
BUF_10_011: equ 0x0103
BUF_10_012: equ 0x0104
BUF_10_013: equ 0x0105
BUF_10_014: equ 0x0106
BUF_10_015: equ 0x0107
BUF_10_016: equ 0x0108
BUF_10_020: equ 0x0109
BUF_10_024: equ 0x010A
BUF_10_025: equ 0x010B
BUF_10_026: equ 0x010C
BUF_10_027: equ 0x010D
BUF_10_028: equ 0x010E
BUF_10_029: equ 0x010F
BUF_10_032: equ 0x0110
BUF_10_035: equ 0x0111
BUF_10_036: equ 0x0112
BUF_10_037: equ 0x0113
BUF_10_038: equ 0x0114
BUF_10_040: equ 0x0115
BUF_10_042: equ 0x0116
BUF_10_043: equ 0x0117
BUF_10_044: equ 0x0118
BUF_11_004: equ 0x0119
BUF_11_009: equ 0x011A
BUF_11_010: equ 0x011B
BUF_11_011: equ 0x011C
BUF_11_012: equ 0x011D
BUF_11_013: equ 0x011E
BUF_11_014: equ 0x011F
BUF_11_015: equ 0x0120
BUF_11_016: equ 0x0121
BUF_11_020: equ 0x0122
BUF_11_024: equ 0x0123
BUF_11_025: equ 0x0124
BUF_11_026: equ 0x0125
BUF_11_027: equ 0x0126
BUF_11_028: equ 0x0127
BUF_11_029: equ 0x0128
BUF_11_032: equ 0x0129
BUF_11_035: equ 0x012A
BUF_11_036: equ 0x012B
BUF_11_037: equ 0x012C
BUF_11_038: equ 0x012D
BUF_11_040: equ 0x012E
BUF_11_042: equ 0x012F
BUF_11_043: equ 0x0130
BUF_11_044: equ 0x0131
BUF_12_004: equ 0x0132
BUF_12_009: equ 0x0133
BUF_12_010: equ 0x0134
BUF_12_011: equ 0x0135
BUF_12_012: equ 0x0136
BUF_12_013: equ 0x0137
BUF_12_014: equ 0x0138
BUF_12_015: equ 0x0139
BUF_12_016: equ 0x013A
BUF_12_020: equ 0x013B
BUF_12_024: equ 0x013C
BUF_12_025: equ 0x013D
BUF_12_026: equ 0x013E
BUF_12_027: equ 0x013F
BUF_12_028: equ 0x0140
BUF_12_029: equ 0x0141
BUF_12_032: equ 0x0142
BUF_12_035: equ 0x0143
BUF_12_036: equ 0x0144
BUF_12_037: equ 0x0145
BUF_12_038: equ 0x0146
BUF_12_040: equ 0x0147
BUF_12_042: equ 0x0148
BUF_12_043: equ 0x0149
BUF_12_044: equ 0x014A
BUF_13_004: equ 0x014B
BUF_13_009: equ 0x014C
BUF_13_010: equ 0x014D
BUF_13_011: equ 0x014E
BUF_13_012: equ 0x014F
BUF_13_013: equ 0x0150
BUF_13_014: equ 0x0151
BUF_13_015: equ 0x0152
BUF_13_016: equ 0x0153
BUF_13_020: equ 0x0154
BUF_13_024: equ 0x0155
BUF_13_025: equ 0x0156
BUF_13_026: equ 0x0157
BUF_13_027: equ 0x0158
BUF_13_028: equ 0x0159
BUF_13_029: equ 0x015A
BUF_13_032: equ 0x015B
BUF_13_035: equ 0x015C
BUF_13_036: equ 0x015D
BUF_13_037: equ 0x015E
BUF_13_038: equ 0x015F
BUF_13_040: equ 0x0160
BUF_13_042: equ 0x0161
BUF_13_043: equ 0x0162
BUF_13_044: equ 0x0163
BUF_14_004: equ 0x0164
BUF_14_009: equ 0x0165
BUF_14_010: equ 0x0166
BUF_14_011: equ 0x0167
BUF_14_012: equ 0x0168
BUF_14_013: equ 0x0169
BUF_14_014: equ 0x016A
BUF_14_015: equ 0x016B
BUF_14_016: equ 0x016C
BUF_14_020: equ 0x016D
BUF_14_024: equ 0x016E
BUF_14_025: equ 0x016F
BUF_14_026: equ 0x0170
BUF_14_027: equ 0x0171
BUF_14_028: equ 0x0172
BUF_14_029: equ 0x0173
BUF_14_032: equ 0x0174
BUF_14_035: equ 0x0175
BUF_14_036: equ 0x0176
BUF_14_037: equ 0x0177
BUF_14_038: equ 0x0178
BUF_14_040: equ 0x0179
BUF_14_042: equ 0x017A
BUF_14_043: equ 0x017B
BUF_14_044: equ 0x017C
BUF_15_004: equ 0x017D
BUF_15_009: equ 0x017E
BUF_15_010: equ 0x017F
BUF_15_011: equ 0x0180
BUF_15_012: equ 0x0181
BUF_15_013: equ 0x0182
BUF_15_014: equ 0x0183
BUF_15_015: equ 0x0184
BUF_15_016: equ 0x0185
BUF_15_020: equ 0x0186
BUF_15_024: equ 0x0187
BUF_15_025: equ 0x0188
BUF_15_026: equ 0x0189
BUF_15_027: equ 0x018A
BUF_15_028: equ 0x018B
BUF_15_029: equ 0x018C
BUF_15_032: equ 0x018D
BUF_15_035: equ 0x018E
BUF_15_036: equ 0x018F
BUF_15_037: equ 0x0190
BUF_15_038: equ 0x0191
BUF_15_040: equ 0x0192
BUF_15_042: equ 0x0193
BUF_15_043: equ 0x0194
BUF_15_044: equ 0x0195
BUF_16_004: equ 0x0196
BUF_16_009: equ 0x0197
BUF_16_010: equ 0x0198
BUF_16_011: equ 0x0199
BUF_16_012: equ 0x019A
BUF_16_013: equ 0x019B
BUF_16_014: equ 0x019C
BUF_16_015: equ 0x019D
BUF_16_016: equ 0x019E
BUF_16_020: equ 0x019F
BUF_16_024: equ 0x01A0
BUF_16_025: equ 0x01A1
BUF_16_026: equ 0x01A2
BUF_16_027: equ 0x01A3
BUF_16_028: equ 0x01A4
BUF_16_029: equ 0x01A5
BUF_16_032: equ 0x01A6
BUF_16_035: equ 0x01A7
BUF_16_036: equ 0x01A8
BUF_16_037: equ 0x01A9
BUF_16_038: equ 0x01AA
BUF_16_040: equ 0x01AB
BUF_16_042: equ 0x01AC
BUF_16_043: equ 0x01AD
BUF_16_044: equ 0x01AE
BUF_17_004: equ 0x01AF
BUF_17_009: equ 0x01B0
BUF_17_010: equ 0x01B1
BUF_17_011: equ 0x01B2
BUF_17_012: equ 0x01B3
BUF_17_013: equ 0x01B4
BUF_17_014: equ 0x01B5
BUF_17_015: equ 0x01B6
BUF_17_016: equ 0x01B7
BUF_17_020: equ 0x01B8
BUF_17_024: equ 0x01B9
BUF_17_025: equ 0x01BA
BUF_17_026: equ 0x01BB
BUF_17_027: equ 0x01BC
BUF_17_028: equ 0x01BD
BUF_17_029: equ 0x01BE
BUF_17_032: equ 0x01BF
BUF_17_035: equ 0x01C0
BUF_17_036: equ 0x01C1
BUF_17_037: equ 0x01C2
BUF_17_038: equ 0x01C3
BUF_17_040: equ 0x01C4
BUF_17_042: equ 0x01C5
BUF_17_043: equ 0x01C6
BUF_17_044: equ 0x01C7
BUF_57_004: equ 0x01C8
BUF_57_009: equ 0x01C9
BUF_57_010: equ 0x01CA
BUF_57_011: equ 0x01CB
BUF_57_012: equ 0x01CC
BUF_57_013: equ 0x01CD
BUF_57_014: equ 0x01CE
BUF_57_015: equ 0x01CF
BUF_57_016: equ 0x01D0
BUF_57_020: equ 0x01D1
BUF_57_024: equ 0x01D2
BUF_57_025: equ 0x01D3
BUF_57_026: equ 0x01D4
BUF_57_027: equ 0x01D5
BUF_57_028: equ 0x01D6
BUF_57_029: equ 0x01D7
BUF_57_032: equ 0x01D8
BUF_57_035: equ 0x01D9
BUF_57_036: equ 0x01DA
BUF_57_037: equ 0x01DB
BUF_57_038: equ 0x01DC
BUF_57_040: equ 0x01DD
BUF_57_042: equ 0x01DE
BUF_57_043: equ 0x01DF
BUF_57_044: equ 0x01E0
BUF_58_004: equ 0x01E1
BUF_58_009: equ 0x01E2
BUF_58_010: equ 0x01E3
BUF_58_011: equ 0x01E4
BUF_58_012: equ 0x01E5
BUF_58_013: equ 0x01E6
BUF_58_014: equ 0x01E7
BUF_58_015: equ 0x01E8
BUF_58_016: equ 0x01E9
BUF_58_020: equ 0x01EA
BUF_58_024: equ 0x01EB
BUF_58_025: equ 0x01EC
BUF_58_026: equ 0x01ED
BUF_58_027: equ 0x01EE
BUF_58_028: equ 0x01EF
BUF_58_029: equ 0x01F0
BUF_58_032: equ 0x01F1
BUF_58_035: equ 0x01F2
BUF_58_036: equ 0x01F3
BUF_58_037: equ 0x01F4
BUF_58_038: equ 0x01F5
BUF_58_040: equ 0x01F6
BUF_58_042: equ 0x01F7
BUF_58_043: equ 0x01F8
BUF_58_044: equ 0x01F9
BUF_59_004: equ 0x01FA
BUF_59_009: equ 0x01FB
BUF_59_010: equ 0x01FC
BUF_59_011: equ 0x01FD
BUF_59_012: equ 0x01FE
BUF_59_013: equ 0x01FF
BUF_59_014: equ 0x0200
BUF_59_015: equ 0x0201
BUF_59_016: equ 0x0202
BUF_59_020: equ 0x0203
BUF_59_024: equ 0x0204
BUF_59_025: equ 0x0205
BUF_59_026: equ 0x0206
BUF_59_027: equ 0x0207
BUF_59_028: equ 0x0208
BUF_59_029: equ 0x0209
BUF_59_032: equ 0x020A
BUF_59_035: equ 0x020B
BUF_59_036: equ 0x020C
BUF_59_037: equ 0x020D
BUF_59_038: equ 0x020E
BUF_59_040: equ 0x020F
BUF_59_042: equ 0x0210
BUF_59_043: equ 0x0211
BUF_59_044: equ 0x0212

; Import .rgba bitmap files and load them into VDP buffers
load_panels:

	ld hl,F10_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F10_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_10_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F11_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_11_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F12_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_12_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F13_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_13_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F14_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_14_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F15_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_15_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F16_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_16_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F17_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_17_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F57_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_57_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F58_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_58_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_004
	ld bc,35
	ld de,35
	ld ix,1225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_009
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_009
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_010
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_010
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_011
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_011
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_012
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_012
	ld bc,5
	ld de,45
	ld ix,225
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_013
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_013
	ld bc,5
	ld de,43
	ld ix,215
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_014
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_014
	ld bc,15
	ld de,45
	ld ix,675
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_015
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_015
	ld bc,25
	ld de,45
	ld ix,1125
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_016
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_016
	ld bc,35
	ld de,45
	ld ix,1575
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_020
	ld bc,45
	ld de,45
	ld ix,2025
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_024
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_024
	ld bc,46
	ld de,64
	ld ix,2944
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_025
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_025
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_026
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_026
	ld bc,9
	ld de,64
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_027
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_027
	ld bc,10
	ld de,62
	ld ix,620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_028
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_028
	ld bc,28
	ld de,64
	ld ix,1792
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_029
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_029
	ld bc,47
	ld de,64
	ld ix,3008
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_032
	ld bc,64
	ld de,64
	ld ix,4096
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_035
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_035
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_036
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_036
	ld bc,22
	ld de,107
	ld ix,2354
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_037
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_037
	ld bc,21
	ld de,105
	ld ix,2205
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_038
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_038
	ld bc,63
	ld de,107
	ld ix,6741
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_040
	ld bc,107
	ld de,107
	ld ix,11449
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_042
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_042
	ld bc,106
	ld de,160
	ld ix,16960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_043
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_043
	ld bc,107
	ld de,160
	ld ix,17120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F59_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_59_044
	ld bc,320
	ld de,160
	ld ix,51200
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ret

F10_004: db "panels/10_004.rgba",0
F10_009: db "panels/10_009.rgba",0
F10_010: db "panels/10_010.rgba",0
F10_011: db "panels/10_011.rgba",0
F10_012: db "panels/10_012.rgba",0
F10_013: db "panels/10_013.rgba",0
F10_014: db "panels/10_014.rgba",0
F10_015: db "panels/10_015.rgba",0
F10_016: db "panels/10_016.rgba",0
F10_020: db "panels/10_020.rgba",0
F10_024: db "panels/10_024.rgba",0
F10_025: db "panels/10_025.rgba",0
F10_026: db "panels/10_026.rgba",0
F10_027: db "panels/10_027.rgba",0
F10_028: db "panels/10_028.rgba",0
F10_029: db "panels/10_029.rgba",0
F10_032: db "panels/10_032.rgba",0
F10_035: db "panels/10_035.rgba",0
F10_036: db "panels/10_036.rgba",0
F10_037: db "panels/10_037.rgba",0
F10_038: db "panels/10_038.rgba",0
F10_040: db "panels/10_040.rgba",0
F10_042: db "panels/10_042.rgba",0
F10_043: db "panels/10_043.rgba",0
F10_044: db "panels/10_044.rgba",0
F11_004: db "panels/11_004.rgba",0
F11_009: db "panels/11_009.rgba",0
F11_010: db "panels/11_010.rgba",0
F11_011: db "panels/11_011.rgba",0
F11_012: db "panels/11_012.rgba",0
F11_013: db "panels/11_013.rgba",0
F11_014: db "panels/11_014.rgba",0
F11_015: db "panels/11_015.rgba",0
F11_016: db "panels/11_016.rgba",0
F11_020: db "panels/11_020.rgba",0
F11_024: db "panels/11_024.rgba",0
F11_025: db "panels/11_025.rgba",0
F11_026: db "panels/11_026.rgba",0
F11_027: db "panels/11_027.rgba",0
F11_028: db "panels/11_028.rgba",0
F11_029: db "panels/11_029.rgba",0
F11_032: db "panels/11_032.rgba",0
F11_035: db "panels/11_035.rgba",0
F11_036: db "panels/11_036.rgba",0
F11_037: db "panels/11_037.rgba",0
F11_038: db "panels/11_038.rgba",0
F11_040: db "panels/11_040.rgba",0
F11_042: db "panels/11_042.rgba",0
F11_043: db "panels/11_043.rgba",0
F11_044: db "panels/11_044.rgba",0
F12_004: db "panels/12_004.rgba",0
F12_009: db "panels/12_009.rgba",0
F12_010: db "panels/12_010.rgba",0
F12_011: db "panels/12_011.rgba",0
F12_012: db "panels/12_012.rgba",0
F12_013: db "panels/12_013.rgba",0
F12_014: db "panels/12_014.rgba",0
F12_015: db "panels/12_015.rgba",0
F12_016: db "panels/12_016.rgba",0
F12_020: db "panels/12_020.rgba",0
F12_024: db "panels/12_024.rgba",0
F12_025: db "panels/12_025.rgba",0
F12_026: db "panels/12_026.rgba",0
F12_027: db "panels/12_027.rgba",0
F12_028: db "panels/12_028.rgba",0
F12_029: db "panels/12_029.rgba",0
F12_032: db "panels/12_032.rgba",0
F12_035: db "panels/12_035.rgba",0
F12_036: db "panels/12_036.rgba",0
F12_037: db "panels/12_037.rgba",0
F12_038: db "panels/12_038.rgba",0
F12_040: db "panels/12_040.rgba",0
F12_042: db "panels/12_042.rgba",0
F12_043: db "panels/12_043.rgba",0
F12_044: db "panels/12_044.rgba",0
F13_004: db "panels/13_004.rgba",0
F13_009: db "panels/13_009.rgba",0
F13_010: db "panels/13_010.rgba",0
F13_011: db "panels/13_011.rgba",0
F13_012: db "panels/13_012.rgba",0
F13_013: db "panels/13_013.rgba",0
F13_014: db "panels/13_014.rgba",0
F13_015: db "panels/13_015.rgba",0
F13_016: db "panels/13_016.rgba",0
F13_020: db "panels/13_020.rgba",0
F13_024: db "panels/13_024.rgba",0
F13_025: db "panels/13_025.rgba",0
F13_026: db "panels/13_026.rgba",0
F13_027: db "panels/13_027.rgba",0
F13_028: db "panels/13_028.rgba",0
F13_029: db "panels/13_029.rgba",0
F13_032: db "panels/13_032.rgba",0
F13_035: db "panels/13_035.rgba",0
F13_036: db "panels/13_036.rgba",0
F13_037: db "panels/13_037.rgba",0
F13_038: db "panels/13_038.rgba",0
F13_040: db "panels/13_040.rgba",0
F13_042: db "panels/13_042.rgba",0
F13_043: db "panels/13_043.rgba",0
F13_044: db "panels/13_044.rgba",0
F14_004: db "panels/14_004.rgba",0
F14_009: db "panels/14_009.rgba",0
F14_010: db "panels/14_010.rgba",0
F14_011: db "panels/14_011.rgba",0
F14_012: db "panels/14_012.rgba",0
F14_013: db "panels/14_013.rgba",0
F14_014: db "panels/14_014.rgba",0
F14_015: db "panels/14_015.rgba",0
F14_016: db "panels/14_016.rgba",0
F14_020: db "panels/14_020.rgba",0
F14_024: db "panels/14_024.rgba",0
F14_025: db "panels/14_025.rgba",0
F14_026: db "panels/14_026.rgba",0
F14_027: db "panels/14_027.rgba",0
F14_028: db "panels/14_028.rgba",0
F14_029: db "panels/14_029.rgba",0
F14_032: db "panels/14_032.rgba",0
F14_035: db "panels/14_035.rgba",0
F14_036: db "panels/14_036.rgba",0
F14_037: db "panels/14_037.rgba",0
F14_038: db "panels/14_038.rgba",0
F14_040: db "panels/14_040.rgba",0
F14_042: db "panels/14_042.rgba",0
F14_043: db "panels/14_043.rgba",0
F14_044: db "panels/14_044.rgba",0
F15_004: db "panels/15_004.rgba",0
F15_009: db "panels/15_009.rgba",0
F15_010: db "panels/15_010.rgba",0
F15_011: db "panels/15_011.rgba",0
F15_012: db "panels/15_012.rgba",0
F15_013: db "panels/15_013.rgba",0
F15_014: db "panels/15_014.rgba",0
F15_015: db "panels/15_015.rgba",0
F15_016: db "panels/15_016.rgba",0
F15_020: db "panels/15_020.rgba",0
F15_024: db "panels/15_024.rgba",0
F15_025: db "panels/15_025.rgba",0
F15_026: db "panels/15_026.rgba",0
F15_027: db "panels/15_027.rgba",0
F15_028: db "panels/15_028.rgba",0
F15_029: db "panels/15_029.rgba",0
F15_032: db "panels/15_032.rgba",0
F15_035: db "panels/15_035.rgba",0
F15_036: db "panels/15_036.rgba",0
F15_037: db "panels/15_037.rgba",0
F15_038: db "panels/15_038.rgba",0
F15_040: db "panels/15_040.rgba",0
F15_042: db "panels/15_042.rgba",0
F15_043: db "panels/15_043.rgba",0
F15_044: db "panels/15_044.rgba",0
F16_004: db "panels/16_004.rgba",0
F16_009: db "panels/16_009.rgba",0
F16_010: db "panels/16_010.rgba",0
F16_011: db "panels/16_011.rgba",0
F16_012: db "panels/16_012.rgba",0
F16_013: db "panels/16_013.rgba",0
F16_014: db "panels/16_014.rgba",0
F16_015: db "panels/16_015.rgba",0
F16_016: db "panels/16_016.rgba",0
F16_020: db "panels/16_020.rgba",0
F16_024: db "panels/16_024.rgba",0
F16_025: db "panels/16_025.rgba",0
F16_026: db "panels/16_026.rgba",0
F16_027: db "panels/16_027.rgba",0
F16_028: db "panels/16_028.rgba",0
F16_029: db "panels/16_029.rgba",0
F16_032: db "panels/16_032.rgba",0
F16_035: db "panels/16_035.rgba",0
F16_036: db "panels/16_036.rgba",0
F16_037: db "panels/16_037.rgba",0
F16_038: db "panels/16_038.rgba",0
F16_040: db "panels/16_040.rgba",0
F16_042: db "panels/16_042.rgba",0
F16_043: db "panels/16_043.rgba",0
F16_044: db "panels/16_044.rgba",0
F17_004: db "panels/17_004.rgba",0
F17_009: db "panels/17_009.rgba",0
F17_010: db "panels/17_010.rgba",0
F17_011: db "panels/17_011.rgba",0
F17_012: db "panels/17_012.rgba",0
F17_013: db "panels/17_013.rgba",0
F17_014: db "panels/17_014.rgba",0
F17_015: db "panels/17_015.rgba",0
F17_016: db "panels/17_016.rgba",0
F17_020: db "panels/17_020.rgba",0
F17_024: db "panels/17_024.rgba",0
F17_025: db "panels/17_025.rgba",0
F17_026: db "panels/17_026.rgba",0
F17_027: db "panels/17_027.rgba",0
F17_028: db "panels/17_028.rgba",0
F17_029: db "panels/17_029.rgba",0
F17_032: db "panels/17_032.rgba",0
F17_035: db "panels/17_035.rgba",0
F17_036: db "panels/17_036.rgba",0
F17_037: db "panels/17_037.rgba",0
F17_038: db "panels/17_038.rgba",0
F17_040: db "panels/17_040.rgba",0
F17_042: db "panels/17_042.rgba",0
F17_043: db "panels/17_043.rgba",0
F17_044: db "panels/17_044.rgba",0
F57_004: db "panels/57_004.rgba",0
F57_009: db "panels/57_009.rgba",0
F57_010: db "panels/57_010.rgba",0
F57_011: db "panels/57_011.rgba",0
F57_012: db "panels/57_012.rgba",0
F57_013: db "panels/57_013.rgba",0
F57_014: db "panels/57_014.rgba",0
F57_015: db "panels/57_015.rgba",0
F57_016: db "panels/57_016.rgba",0
F57_020: db "panels/57_020.rgba",0
F57_024: db "panels/57_024.rgba",0
F57_025: db "panels/57_025.rgba",0
F57_026: db "panels/57_026.rgba",0
F57_027: db "panels/57_027.rgba",0
F57_028: db "panels/57_028.rgba",0
F57_029: db "panels/57_029.rgba",0
F57_032: db "panels/57_032.rgba",0
F57_035: db "panels/57_035.rgba",0
F57_036: db "panels/57_036.rgba",0
F57_037: db "panels/57_037.rgba",0
F57_038: db "panels/57_038.rgba",0
F57_040: db "panels/57_040.rgba",0
F57_042: db "panels/57_042.rgba",0
F57_043: db "panels/57_043.rgba",0
F57_044: db "panels/57_044.rgba",0
F58_004: db "panels/58_004.rgba",0
F58_009: db "panels/58_009.rgba",0
F58_010: db "panels/58_010.rgba",0
F58_011: db "panels/58_011.rgba",0
F58_012: db "panels/58_012.rgba",0
F58_013: db "panels/58_013.rgba",0
F58_014: db "panels/58_014.rgba",0
F58_015: db "panels/58_015.rgba",0
F58_016: db "panels/58_016.rgba",0
F58_020: db "panels/58_020.rgba",0
F58_024: db "panels/58_024.rgba",0
F58_025: db "panels/58_025.rgba",0
F58_026: db "panels/58_026.rgba",0
F58_027: db "panels/58_027.rgba",0
F58_028: db "panels/58_028.rgba",0
F58_029: db "panels/58_029.rgba",0
F58_032: db "panels/58_032.rgba",0
F58_035: db "panels/58_035.rgba",0
F58_036: db "panels/58_036.rgba",0
F58_037: db "panels/58_037.rgba",0
F58_038: db "panels/58_038.rgba",0
F58_040: db "panels/58_040.rgba",0
F58_042: db "panels/58_042.rgba",0
F58_043: db "panels/58_043.rgba",0
F58_044: db "panels/58_044.rgba",0
F59_004: db "panels/59_004.rgba",0
F59_009: db "panels/59_009.rgba",0
F59_010: db "panels/59_010.rgba",0
F59_011: db "panels/59_011.rgba",0
F59_012: db "panels/59_012.rgba",0
F59_013: db "panels/59_013.rgba",0
F59_014: db "panels/59_014.rgba",0
F59_015: db "panels/59_015.rgba",0
F59_016: db "panels/59_016.rgba",0
F59_020: db "panels/59_020.rgba",0
F59_024: db "panels/59_024.rgba",0
F59_025: db "panels/59_025.rgba",0
F59_026: db "panels/59_026.rgba",0
F59_027: db "panels/59_027.rgba",0
F59_028: db "panels/59_028.rgba",0
F59_029: db "panels/59_029.rgba",0
F59_032: db "panels/59_032.rgba",0
F59_035: db "panels/59_035.rgba",0
F59_036: db "panels/59_036.rgba",0
F59_037: db "panels/59_037.rgba",0
F59_038: db "panels/59_038.rgba",0
F59_040: db "panels/59_040.rgba",0
F59_042: db "panels/59_042.rgba",0
F59_043: db "panels/59_043.rgba",0
F59_044: db "panels/59_044.rgba",0
; Bitmap indices:
BUF_20_004: equ 0x0213
BUF_20_020: equ 0x0214
BUF_20_032: equ 0x0215
BUF_20_040: equ 0x0216
BUF_20_044: equ 0x0217
BUF_21_004: equ 0x0218
BUF_21_020: equ 0x0219
BUF_21_032: equ 0x021A
BUF_21_040: equ 0x021B
BUF_21_044: equ 0x021C
BUF_22_004: equ 0x021D
BUF_22_020: equ 0x021E
BUF_22_032: equ 0x021F
BUF_22_040: equ 0x0220
BUF_22_044: equ 0x0221
BUF_23_004: equ 0x0222
BUF_23_020: equ 0x0223
BUF_23_032: equ 0x0224
BUF_23_040: equ 0x0225
BUF_23_044: equ 0x0226
BUF_24_004: equ 0x0227
BUF_24_020: equ 0x0228
BUF_24_032: equ 0x0229
BUF_24_040: equ 0x022A
BUF_24_044: equ 0x022B
BUF_40_004: equ 0x022C
BUF_40_020: equ 0x022D
BUF_40_032: equ 0x022E
BUF_40_040: equ 0x022F
BUF_40_044: equ 0x0230
BUF_41_004: equ 0x0231
BUF_41_020: equ 0x0232
BUF_41_032: equ 0x0233
BUF_41_040: equ 0x0234
BUF_41_044: equ 0x0235
BUF_42_004: equ 0x0236
BUF_42_020: equ 0x0237
BUF_42_032: equ 0x0238
BUF_42_040: equ 0x0239
BUF_42_044: equ 0x023A
BUF_43_004: equ 0x023B
BUF_43_020: equ 0x023C
BUF_43_032: equ 0x023D
BUF_43_040: equ 0x023E
BUF_43_044: equ 0x023F
BUF_44_004: equ 0x0240
BUF_44_020: equ 0x0241
BUF_44_032: equ 0x0242
BUF_44_040: equ 0x0243
BUF_44_044: equ 0x0244
BUF_45_004: equ 0x0245
BUF_45_020: equ 0x0246
BUF_45_032: equ 0x0247
BUF_45_040: equ 0x0248
BUF_45_044: equ 0x0249
BUF_46_004: equ 0x024A
BUF_46_020: equ 0x024B
BUF_46_032: equ 0x024C
BUF_46_040: equ 0x024D
BUF_46_044: equ 0x024E
BUF_47_004: equ 0x024F
BUF_47_020: equ 0x0250
BUF_47_032: equ 0x0251
BUF_47_040: equ 0x0252
BUF_47_044: equ 0x0253
BUF_48_004: equ 0x0254
BUF_48_020: equ 0x0255
BUF_48_032: equ 0x0256
BUF_48_040: equ 0x0257
BUF_48_044: equ 0x0258
BUF_49_004: equ 0x0259
BUF_49_020: equ 0x025A
BUF_49_032: equ 0x025B
BUF_49_040: equ 0x025C
BUF_49_044: equ 0x025D
BUF_50_004: equ 0x025E
BUF_50_020: equ 0x025F
BUF_50_032: equ 0x0260
BUF_50_040: equ 0x0261
BUF_50_044: equ 0x0262
BUF_51_004: equ 0x0263
BUF_51_020: equ 0x0264
BUF_51_032: equ 0x0265
BUF_51_040: equ 0x0266
BUF_51_044: equ 0x0267
BUF_52_004: equ 0x0268
BUF_52_020: equ 0x0269
BUF_52_032: equ 0x026A
BUF_52_040: equ 0x026B
BUF_52_044: equ 0x026C

; Import .rgba bitmap files and load them into VDP buffers
load_sprites:

	ld hl,F20_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_20_004
	ld bc,19
	ld de,21
	ld ix,399
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F20_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_20_020
	ld bc,25
	ld de,26
	ld ix,650
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F20_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_20_032
	ld bc,36
	ld de,39
	ld ix,1404
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F20_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_20_040
	ld bc,60
	ld de,65
	ld ix,3900
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F20_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_20_044
	ld bc,120
	ld de,115
	ld ix,13800
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F21_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_21_004
	ld bc,10
	ld de,11
	ld ix,110
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F21_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_21_020
	ld bc,13
	ld de,15
	ld ix,195
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F21_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_21_032
	ld bc,20
	ld de,22
	ld ix,440
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F21_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_21_040
	ld bc,34
	ld de,36
	ld ix,1224
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F21_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_21_044
	ld bc,100
	ld de,30
	ld ix,3000
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F22_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_22_004
	ld bc,16
	ld de,11
	ld ix,176
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F22_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_22_020
	ld bc,21
	ld de,15
	ld ix,315
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F22_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_22_032
	ld bc,30
	ld de,22
	ld ix,660
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F22_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_22_040
	ld bc,50
	ld de,36
	ld ix,1800
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F22_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_22_044
	ld bc,150
	ld de,30
	ld ix,4500
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F23_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_23_004
	ld bc,20
	ld de,9
	ld ix,180
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F23_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_23_020
	ld bc,25
	ld de,12
	ld ix,300
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F23_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_23_032
	ld bc,36
	ld de,16
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F23_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_23_040
	ld bc,60
	ld de,27
	ld ix,1620
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F23_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_23_044
	ld bc,1
	ld de,1
	ld ix,1
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F24_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_24_004
	ld bc,10
	ld de,11
	ld ix,110
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F24_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_24_020
	ld bc,13
	ld de,15
	ld ix,195
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F24_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_24_032
	ld bc,20
	ld de,22
	ld ix,440
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F24_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_24_040
	ld bc,34
	ld de,36
	ld ix,1224
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F24_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_24_044
	ld bc,100
	ld de,30
	ld ix,3000
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F40_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_40_004
	ld bc,17
	ld de,9
	ld ix,153
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F40_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_40_020
	ld bc,22
	ld de,12
	ld ix,264
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F40_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_40_032
	ld bc,32
	ld de,18
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F40_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_40_040
	ld bc,53
	ld de,29
	ld ix,1537
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F40_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_40_044
	ld bc,90
	ld de,10
	ld ix,900
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F41_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_41_004
	ld bc,17
	ld de,15
	ld ix,255
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F41_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_41_020
	ld bc,22
	ld de,20
	ld ix,440
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F41_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_41_032
	ld bc,32
	ld de,30
	ld ix,960
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F41_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_41_040
	ld bc,53
	ld de,49
	ld ix,2597
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F41_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_41_044
	ld bc,130
	ld de,70
	ld ix,9100
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F42_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_42_004
	ld bc,14
	ld de,12
	ld ix,168
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F42_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_42_020
	ld bc,19
	ld de,16
	ld ix,304
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F42_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_42_032
	ld bc,28
	ld de,24
	ld ix,672
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F42_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_42_040
	ld bc,46
	ld de,39
	ld ix,1794
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F42_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_42_044
	ld bc,100
	ld de,40
	ld ix,4000
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F43_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_43_004
	ld bc,17
	ld de,6
	ld ix,102
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F43_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_43_020
	ld bc,22
	ld de,8
	ld ix,176
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F43_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_43_032
	ld bc,32
	ld de,12
	ld ix,384
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F43_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_43_040
	ld bc,53
	ld de,19
	ld ix,1007
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F43_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_43_044
	ld bc,1
	ld de,1
	ld ix,1
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F44_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_44_004
	ld bc,13
	ld de,10
	ld ix,130
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F44_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_44_020
	ld bc,17
	ld de,13
	ld ix,221
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F44_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_44_032
	ld bc,26
	ld de,20
	ld ix,520
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F44_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_44_040
	ld bc,43
	ld de,33
	ld ix,1419
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F44_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_44_044
	ld bc,90
	ld de,20
	ld ix,1800
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F45_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_45_004
	ld bc,17
	ld de,11
	ld ix,187
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F45_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_45_020
	ld bc,22
	ld de,15
	ld ix,330
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F45_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_45_032
	ld bc,32
	ld de,22
	ld ix,704
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F45_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_45_040
	ld bc,53
	ld de,36
	ld ix,1908
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F45_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_45_044
	ld bc,130
	ld de,30
	ld ix,3900
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F46_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_46_004
	ld bc,17
	ld de,9
	ld ix,153
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F46_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_46_020
	ld bc,22
	ld de,12
	ld ix,264
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F46_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_46_032
	ld bc,32
	ld de,18
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F46_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_46_040
	ld bc,53
	ld de,29
	ld ix,1537
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F46_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_46_044
	ld bc,90
	ld de,10
	ld ix,900
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F47_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_47_004
	ld bc,17
	ld de,9
	ld ix,153
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F47_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_47_020
	ld bc,22
	ld de,12
	ld ix,264
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F47_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_47_032
	ld bc,32
	ld de,18
	ld ix,576
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F47_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_47_040
	ld bc,53
	ld de,30
	ld ix,1590
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F47_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_47_044
	ld bc,30
	ld de,20
	ld ix,600
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F48_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_48_004
	ld bc,13
	ld de,6
	ld ix,78
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F48_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_48_020
	ld bc,18
	ld de,8
	ld ix,144
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F48_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_48_032
	ld bc,26
	ld de,12
	ld ix,312
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F48_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_48_040
	ld bc,43
	ld de,19
	ld ix,817
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F48_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_48_044
	ld bc,1
	ld de,1
	ld ix,1
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F49_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_49_004
	ld bc,14
	ld de,6
	ld ix,84
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F49_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_49_020
	ld bc,19
	ld de,9
	ld ix,171
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F49_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_49_032
	ld bc,28
	ld de,12
	ld ix,336
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F49_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_49_040
	ld bc,46
	ld de,20
	ld ix,920
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F49_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_49_044
	ld bc,1
	ld de,1
	ld ix,1
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F50_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_50_004
	ld bc,9
	ld de,13
	ld ix,117
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F50_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_50_020
	ld bc,12
	ld de,17
	ld ix,204
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F50_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_50_032
	ld bc,18
	ld de,26
	ld ix,468
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F50_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_50_040
	ld bc,30
	ld de,43
	ld ix,1290
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F50_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_50_044
	ld bc,70
	ld de,50
	ld ix,3500
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F51_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_51_004
	ld bc,18
	ld de,26
	ld ix,468
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F51_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_51_020
	ld bc,23
	ld de,33
	ld ix,759
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F51_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_51_032
	ld bc,33
	ld de,48
	ld ix,1584
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F51_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_51_040
	ld bc,55
	ld de,80
	ld ix,4400
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F51_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_51_044
	ld bc,165
	ld de,160
	ld ix,26400
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F52_004
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_52_004
	ld bc,15
	ld de,26
	ld ix,390
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F52_020
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_52_020
	ld bc,19
	ld de,33
	ld ix,627
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F52_032
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_52_032
	ld bc,27
	ld de,48
	ld ix,1296
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F52_040
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_52_040
	ld bc,45
	ld de,80
	ld ix,3600
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,F52_044
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_52_044
	ld bc,135
	ld de,160
	ld ix,21600
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ret

F20_004: db "panels/20_004.rgba",0
F20_020: db "panels/20_020.rgba",0
F20_032: db "panels/20_032.rgba",0
F20_040: db "panels/20_040.rgba",0
F20_044: db "panels/20_044.rgba",0
F21_004: db "panels/21_004.rgba",0
F21_020: db "panels/21_020.rgba",0
F21_032: db "panels/21_032.rgba",0
F21_040: db "panels/21_040.rgba",0
F21_044: db "panels/21_044.rgba",0
F22_004: db "panels/22_004.rgba",0
F22_020: db "panels/22_020.rgba",0
F22_032: db "panels/22_032.rgba",0
F22_040: db "panels/22_040.rgba",0
F22_044: db "panels/22_044.rgba",0
F23_004: db "panels/23_004.rgba",0
F23_020: db "panels/23_020.rgba",0
F23_032: db "panels/23_032.rgba",0
F23_040: db "panels/23_040.rgba",0
F23_044: db "panels/23_044.rgba",0
F24_004: db "panels/24_004.rgba",0
F24_020: db "panels/24_020.rgba",0
F24_032: db "panels/24_032.rgba",0
F24_040: db "panels/24_040.rgba",0
F24_044: db "panels/24_044.rgba",0
F40_004: db "panels/40_004.rgba",0
F40_020: db "panels/40_020.rgba",0
F40_032: db "panels/40_032.rgba",0
F40_040: db "panels/40_040.rgba",0
F40_044: db "panels/40_044.rgba",0
F41_004: db "panels/41_004.rgba",0
F41_020: db "panels/41_020.rgba",0
F41_032: db "panels/41_032.rgba",0
F41_040: db "panels/41_040.rgba",0
F41_044: db "panels/41_044.rgba",0
F42_004: db "panels/42_004.rgba",0
F42_020: db "panels/42_020.rgba",0
F42_032: db "panels/42_032.rgba",0
F42_040: db "panels/42_040.rgba",0
F42_044: db "panels/42_044.rgba",0
F43_004: db "panels/43_004.rgba",0
F43_020: db "panels/43_020.rgba",0
F43_032: db "panels/43_032.rgba",0
F43_040: db "panels/43_040.rgba",0
F43_044: db "panels/43_044.rgba",0
F44_004: db "panels/44_004.rgba",0
F44_020: db "panels/44_020.rgba",0
F44_032: db "panels/44_032.rgba",0
F44_040: db "panels/44_040.rgba",0
F44_044: db "panels/44_044.rgba",0
F45_004: db "panels/45_004.rgba",0
F45_020: db "panels/45_020.rgba",0
F45_032: db "panels/45_032.rgba",0
F45_040: db "panels/45_040.rgba",0
F45_044: db "panels/45_044.rgba",0
F46_004: db "panels/46_004.rgba",0
F46_020: db "panels/46_020.rgba",0
F46_032: db "panels/46_032.rgba",0
F46_040: db "panels/46_040.rgba",0
F46_044: db "panels/46_044.rgba",0
F47_004: db "panels/47_004.rgba",0
F47_020: db "panels/47_020.rgba",0
F47_032: db "panels/47_032.rgba",0
F47_040: db "panels/47_040.rgba",0
F47_044: db "panels/47_044.rgba",0
F48_004: db "panels/48_004.rgba",0
F48_020: db "panels/48_020.rgba",0
F48_032: db "panels/48_032.rgba",0
F48_040: db "panels/48_040.rgba",0
F48_044: db "panels/48_044.rgba",0
F49_004: db "panels/49_004.rgba",0
F49_020: db "panels/49_020.rgba",0
F49_032: db "panels/49_032.rgba",0
F49_040: db "panels/49_040.rgba",0
F49_044: db "panels/49_044.rgba",0
F50_004: db "panels/50_004.rgba",0
F50_020: db "panels/50_020.rgba",0
F50_032: db "panels/50_032.rgba",0
F50_040: db "panels/50_040.rgba",0
F50_044: db "panels/50_044.rgba",0
F51_004: db "panels/51_004.rgba",0
F51_020: db "panels/51_020.rgba",0
F51_032: db "panels/51_032.rgba",0
F51_040: db "panels/51_040.rgba",0
F51_044: db "panels/51_044.rgba",0
F52_004: db "panels/52_004.rgba",0
F52_020: db "panels/52_020.rgba",0
F52_032: db "panels/52_032.rgba",0
F52_040: db "panels/52_040.rgba",0
F52_044: db "panels/52_044.rgba",0
; Bitmap indices:
BUF_DW_6: equ 0x026D
BUF_DW_7: equ 0x026E
BUF_DW_8: equ 0x026F
BUF_DW_9: equ 0x0270
BUF_DW_10: equ 0x0271
BUF_DW_11: equ 0x0272
BUF_DW_12: equ 0x0273
BUF_DW_13: equ 0x0274
BUF_DW_14: equ 0x0275

; Import .rgba bitmap files and load them into VDP buffers
load_dws:

	ld hl,Fdw_6
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_6
	ld bc,320
	ld de,30
	ld ix,9600
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_7
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_7
	ld bc,320
	ld de,24
	ld ix,7680
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_8
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_8
	ld bc,320
	ld de,22
	ld ix,7040
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_9
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_9
	ld bc,320
	ld de,18
	ld ix,5760
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_10
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_10
	ld bc,320
	ld de,16
	ld ix,5120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_11
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_11
	ld bc,320
	ld de,16
	ld ix,5120
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_12
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_12
	ld bc,320
	ld de,14
	ld ix,4480
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_13
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_13
	ld bc,320
	ld de,12
	ld ix,3840
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ld hl,Fdw_14
	ld de,filedata
	ld bc,102400
	ld a,mos_load
	RST.LIL 08h
	ld hl,BUF_DW_14
	ld bc,320
	ld de,12
	ld ix,3840
	call vdu_load_bmp2_from_file
	LD A, '.'
	RST.LIL 10h

	ret

Fdw_6: db "dws/dw_6.rgba",0
Fdw_7: db "dws/dw_7.rgba",0
Fdw_8: db "dws/dw_8.rgba",0
Fdw_9: db "dws/dw_9.rgba",0
Fdw_10: db "dws/dw_10.rgba",0
Fdw_11: db "dws/dw_11.rgba",0
Fdw_12: db "dws/dw_12.rgba",0
Fdw_13: db "dws/dw_13.rgba",0
Fdw_14: db "dws/dw_14.rgba",0
