    .assume adl=1   
    .org 0x040000    

    jp start       

    .align 64      
    .db "MOS"       
    .db 00h         
    .db 01h

	include "src/asm/mos_api.asm" ; wants to be first include b/c it has macros
	include "src/asm/macros.inc"
	include "src/asm/vdu_sound.asm" ; also has macros
	include "src/asm/autogenerated.asm"
	include "src/asm/fonts_bmp.asm"
	include "src/asm/maps.asm"
	include "src/asm/render.asm"
	include "src/asm/ui.asm"
	include "src/asm/sprites.asm"
	include "src/asm/vars.asm"
	include "src/asm/vdu.asm"
    include "src/asm/functions.asm"
	include "src/asm/player.asm"
	include "src/asm/maths.asm"
	include "src/asm/img_load.asm"
	include "src/asm/timer.asm"
	include "src/asm/agnb_api.inc"


start:              
    push af
    push bc
    push de
    push ix
    push iy

	call init ; Initialization code
    jr z,@initialized
; Initialization failed after changing VDP/application state. Restore the same
; MOS-facing state used by a normal game exit before returning to the caller.
    call app_cleanup
    jp exit
@initialized:
    call main ; Call the main function

exit:

    pop iy 
    pop ix
    pop de
    pop bc
    pop af
    ld hl,0

    ret 

application_version: db "0.2.0.alpha",0
welcome_message: asciz "Welcome to Agon Wolf3D"
press_any_key: asciz "Press any key to continue.\r\n"
ui_agnb_filename: asciz "ui.agnb"
font_agnb_filename: asciz "font.agnb"
images_agnb_filename: asciz "images.agnb"
sfx_agnb_filename: asciz "sfx.agnb"
is_emulator: db 0

init:
; clear all buffers
    call vdu_clear_all_buffers

; start generic stopwatch to time setup loop 
; so we can determine if we're running on emulator or hardware
	call stopwatch_set

; initialize global timestamp
    ld hl,(ix+sysvar_time) ; ix was set by stopwatch_start
    ld (timestamp_now),hl

; enable additional audio channels
	call vdu_enable_channels

; Load UI bitmaps in the user's current screen mode. Each completed image
; prints one console breadcrumb; nothing is plotted during this phase.
	call printInline
	asciz "Loading UI"
	ld de,ui_agnb_filename
	ld hl,img_load_agnb_breadcrumb
	call agnb_load_images_with_callback
	jr z,@ui_loaded
	jp @agnb_startup_error
@ui_loaded:
	call printNewLine

; Load the original game's proportional glyph bitmaps before the animated
; world-image splash uses them. Metrics remain in font_itc_honda.
	call printInline
	asciz "Loading font"
	ld de,font_agnb_filename
	ld hl,img_load_agnb_breadcrumb
	call agnb_load_images_with_callback
	jr z,@font_loaded
	jp @agnb_startup_error
@font_loaded:
	call printNewLine

; Switch to the game's display only after the bootstrap UI load is complete.
    ld a,8+128 ; 320x240x64 double-buffered
    call vdu_set_screen_mode
    xor a
    call vdu_set_scaling

; set the cursor off
	call cursor_off

; set text background color
	ld a,4 + 128
	call vdu_colour_text

; set text foreground color
	ld a,47 ; aaaaff lavenderish
	call vdu_colour_text

; set gfx bg color
	xor a ; plotting mode 0
	ld c,4 ; dark blue
	call vdu_gcol_bg
	call vdu_clg

; set the cursor off again since we changed screen modes
	call cursor_off

; VDU 28, left, bottom, right, top: Set text viewport **
; MIND THE LITTLE-ENDIANESS
; inputs: c=left,b=bottom,e=right,d=top
	ld c,0 ; left
	ld d,20 ; top
	ld e,39 ; right
	ld b,29; bottom
	call vdu_set_txt_viewport

; initialize image load routine
	call img_load_init

; load cube/panel, sprite, and distance-wall images
    ld hl,0
    ld (cur_file_idx),hl
	ld de,images_agnb_filename
	ld hl,img_load_agnb_progress
	call agnb_load_images_with_callback
	jr z,@images_loaded

; Fail startup without entering the game if the image container is invalid or
; unavailable. Preserve the loader error while presenting it to the user.
@agnb_startup_error:
    push af
    call vdu_cls
    call printInline
    asciz "AGNB image load failed: "
    pop af
    call printHex8
    call printNewLine
    call printInline
    asciz "Press any key to return to MOS\r\n"
    call vdu_flip
    call waitKeypress
    ld a,(agnb_last_error)
    or a
    ret

@images_loaded:

; load and finalize all sound effects from the AGNB 0.2 audio container
	ld hl,0
	ld (cur_file_idx),hl
	ld de,sfx_agnb_filename
	ld hl,img_load_agnb_audio_progress
	call agnb_load_audio_with_callback
	jr nz,@agnb_startup_error

; self modify vdu_play_sfx to enable sound
	xor a
	ld (vdu_play_sfx_disable),a

; use loading time to determine if we're running on emulator or hardware
	call stopwatch_get ; hl = elapsed time in 120ths of a second
	ld de,8000 ; emulator loads in about 2,400 ticks, hardware about 15,000
	xor a ; clear carry, default is running on hardware
	ld (is_emulator),a
	sbc hl,de
	jp m,@on_emulator
	call vdu_home_cursor
	call printInline
	asciz "Running on hardware.\r\n"
	jp @test_done

@on_emulator:
; print emulator message
	ld a,1
	ld (is_emulator),a
	call vdu_home_cursor
	call printInline
	asciz "Running on emulator.\r\n"

@test_done:
; print final loading time
	call printInline
	asciz "Loading time:"
	call stopwatch_get ; hl = elapsed time in 120ths of a second
	call printDec
	call printNewLine

; print loading complete message and wait for user keypress
	ld hl,press_any_key
	call printString
	call vdu_flip 
	call waitKeypress

; initialization done
    xor a
	ret

main_loop_tmr: ds 6
framerate: equ 30

new_game:
; initialize map variables and load map file
	ld hl,room_flags
	xor a
	ld b,10
@room_flags_loop:
	ld (hl),a
	inc hl
	djnz @room_flags_loop
; map_init:
	ld (cur_floor),a
	ld (cur_room),a
; load room file
	call map_load
; initialize sprite data
	call map_init_sprites
; initialize player position
	call plyr_init

	ret

main:
	call new_game

; main:
; ; set map variables and load initial map file
; 	call map_init
; ; initialize player position
; 	call plyr_init


main_loop:
; update global timestamp
    call timestamp_tick

; move enemies
	call sprites_see_plyr ; 220-285  prt ticks

; get player input and update sprite position
	; 0-1 prt ticks
	call plyr_input ; ix points to cell defs/status, a is target cell current obj_id

; render the updated scene
	call render_scene ; 6-12 prt ticks
; full loop 12-16 prt ticks

; flip the screen
	call vdu_flip

@wait:
	ld iy,main_loop_tmr
	call tmr_get
	jp z,@continue
	jp m,@continue
	jp @wait
@continue:

; reset main loop timer
	ld iy,main_loop_tmr
	ld hl,120/framerate
	call tmr_set

; check for escape key and quit if pressed
	MOSCALL mos_getkbmap
; 113 Escape
    bit 0,(ix+14)
	jr nz,main_end
@Escape:
	jr main_loop

main_end:
	; call do_outro

; Normal and failed-startup exits share one cleanup path.
app_cleanup:
    call vdu_clear_all_buffers
	call vdu_disable_channels

; restore screen to something normalish
	xor a
	call vdu_set_screen_mode
	call cursor_on
	ret

; files.asm must go here so that filedata doesn't stomp on program data
	include "src/asm/files.asm"
