; Map masks for floor 0, room 1
; Generated by build_91c_asm_map_masks.py
; Do not edit this file

	.org 0xB7E000 ; base of on-chip high speed SRAM

cell_status:
; high to low byte: obj_id, img_idx, map_type_status; sprite_id
; map_type_status bit mask = is_door,is_wall,is_trigger,is_blocking,is_start,is_to_room,render_type_masks
	dl 0x0E0450 ; cell 000 x,y (0,0) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x341143 ; cell 001 x,y (1,0) sprite normal SS GUARD 
	db 0x00 ; SS GUARD
	dl 0x1DFF01 ; cell 002 x,y (2,0) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 003 x,y (3,0) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 004 x,y (4,0) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 005 x,y (5,0) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 006 x,y (6,0) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1D0903 ; cell 007 x,y (7,0) sprite normal KEYCARD 
	db 0x01 ; KEYCARD
	dl 0x1DFF01 ; cell 008 x,y (8,0) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x331043 ; cell 009 x,y (9,0) sprite normal GERMAN TROOPER 
	db 0x02 ; GERMAN TROOPER
	dl 0x0D0350 ; cell 010 x,y (10,0) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 011 x,y (11,0) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1E0834 ; cell 012 x,y (12,0) cube to room DOOR TO ROOM 0 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 013 x,y (13,0) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 014 x,y (14,0) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 015 x,y (15,0) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x200834 ; cell 016 x,y (0,1) cube to room DOOR TO ROOM 2 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 017 x,y (1,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 018 x,y (2,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0303 ; cell 019 x,y (3,1) sprite normal OVERHEAD LIGHT 
	db 0x03 ; OVERHEAD LIGHT
	dl 0x1DFF01 ; cell 020 x,y (4,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 021 x,y (5,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 022 x,y (6,1) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 023 x,y (7,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 024 x,y (8,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 025 x,y (9,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 026 x,y (10,1) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 027 x,y (11,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 028 x,y (12,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 029 x,y (13,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 030 x,y (14,1) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 031 x,y (15,1) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 032 x,y (0,2) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x341143 ; cell 033 x,y (1,2) sprite normal SS GUARD 
	db 0x04 ; SS GUARD
	dl 0x1DFF01 ; cell 034 x,y (2,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 035 x,y (3,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 036 x,y (4,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 037 x,y (5,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 038 x,y (6,2) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 039 x,y (7,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 040 x,y (8,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 041 x,y (9,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0F0550 ; cell 042 x,y (10,2) cube normal HANGING FLAG 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 043 x,y (11,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 044 x,y (12,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 045 x,y (13,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 046 x,y (14,2) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 047 x,y (15,2) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 048 x,y (0,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 049 x,y (1,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 050 x,y (2,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 051 x,y (3,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 052 x,y (4,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 053 x,y (5,3) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 054 x,y (6,3) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 055 x,y (7,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 056 x,y (8,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 057 x,y (9,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 058 x,y (10,3) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 059 x,y (11,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 060 x,y (12,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 061 x,y (13,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 062 x,y (14,3) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 063 x,y (15,3) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 064 x,y (0,4) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 065 x,y (1,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 066 x,y (2,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0803 ; cell 067 x,y (3,4) sprite normal PLATE OF FOOD 
	db 0x05 ; PLATE OF FOOD
	dl 0x1DFF01 ; cell 068 x,y (4,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0903 ; cell 069 x,y (5,4) sprite normal KEYCARD 
	db 0x06 ; KEYCARD
	dl 0x0E0450 ; cell 070 x,y (6,4) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1D0503 ; cell 071 x,y (7,4) sprite normal HEALTH PACK 
	db 0x07 ; HEALTH PACK
	dl 0x1DFF01 ; cell 072 x,y (8,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 073 x,y (9,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 074 x,y (10,4) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 075 x,y (11,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 076 x,y (12,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0303 ; cell 077 x,y (13,4) sprite normal OVERHEAD LIGHT 
	db 0x08 ; OVERHEAD LIGHT
	dl 0x1DFF01 ; cell 078 x,y (14,4) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 079 x,y (15,4) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 080 x,y (0,5) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 081 x,y (1,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 082 x,y (2,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x160243 ; cell 083 x,y (3,5) sprite normal TABLE 
	db 0x09 ; TABLE
	dl 0x1DFF01 ; cell 084 x,y (4,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 085 x,y (5,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 086 x,y (6,5) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0C0250 ; cell 087 x,y (7,5) cube normal STONE ARCH BIRD 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 088 x,y (8,5) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x0C0250 ; cell 089 x,y (9,5) cube normal STONE ARCH BIRD 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 090 x,y (10,5) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 091 x,y (11,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 092 x,y (12,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 093 x,y (13,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 094 x,y (14,5) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 095 x,y (15,5) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 096 x,y (0,6) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 097 x,y (1,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 098 x,y (2,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0303 ; cell 099 x,y (3,6) sprite normal OVERHEAD LIGHT 
	db 0x0A ; OVERHEAD LIGHT
	dl 0x1DFF01 ; cell 100 x,y (4,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 101 x,y (5,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 102 x,y (6,6) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 103 x,y (7,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 104 x,y (8,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 105 x,y (9,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 106 x,y (10,6) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 107 x,y (11,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 108 x,y (12,6) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x320F43 ; cell 109 x,y (13,6) sprite normal DOG 
	db 0x0B ; DOG
	dl 0x331043 ; cell 110 x,y (14,6) sprite normal GERMAN TROOPER 
	db 0x0C ; GERMAN TROOPER
	dl 0x0A0050 ; cell 111 x,y (15,6) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 112 x,y (0,7) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 113 x,y (1,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 114 x,y (2,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 115 x,y (3,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 116 x,y (4,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 117 x,y (5,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 118 x,y (6,7) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 119 x,y (7,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 120 x,y (8,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 121 x,y (9,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 122 x,y (10,7) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 123 x,y (11,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 124 x,y (12,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 125 x,y (13,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 126 x,y (14,7) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 127 x,y (15,7) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 128 x,y (0,8) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 129 x,y (1,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 130 x,y (2,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 131 x,y (3,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 132 x,y (4,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0E03 ; cell 133 x,y (5,8) sprite normal GOLD KEY 
	db 0x0D ; GOLD KEY
	dl 0x0E0450 ; cell 134 x,y (6,8) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x1D0703 ; cell 135 x,y (7,8) sprite normal GOLD CROSS 
	db 0x0E ; GOLD CROSS
	dl 0x1D0903 ; cell 136 x,y (8,8) sprite normal KEYCARD 
	db 0x0F ; KEYCARD
	dl 0x1D0603 ; cell 137 x,y (9,8) sprite normal GOLD CHALISE 
	db 0x10 ; GOLD CHALISE
	dl 0x0D0350 ; cell 138 x,y (10,8) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 139 x,y (11,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 140 x,y (12,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 141 x,y (13,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 142 x,y (14,8) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 143 x,y (15,8) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 144 x,y (0,9) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 145 x,y (1,9) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 146 x,y (2,9) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 147 x,y (3,9) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 148 x,y (4,9) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x0E0450 ; cell 149 x,y (5,9) cube normal WOOD WALL 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 150 x,y (6,9) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 151 x,y (7,9) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 152 x,y (8,9) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 153 x,y (9,9) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 154 x,y (10,9) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 155 x,y (11,9) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 156 x,y (12,9) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x0D0350 ; cell 157 x,y (13,9) cube normal DARK GREY WALL 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 158 x,y (14,9) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 159 x,y (15,9) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1D0903 ; cell 160 x,y (0,10) sprite normal KEYCARD 
	db 0x11 ; KEYCARD
	dl 0x1DFF01 ; cell 161 x,y (1,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 162 x,y (2,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 163 x,y (3,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 164 x,y (4,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x140043 ; cell 165 x,y (5,10) sprite normal LAMP 
	db 0x12 ; LAMP
	dl 0x0A0050 ; cell 166 x,y (6,10) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 167 x,y (7,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 168 x,y (8,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 169 x,y (9,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 170 x,y (10,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 171 x,y (11,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 172 x,y (12,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 173 x,y (13,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 174 x,y (14,10) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 175 x,y (15,10) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x341143 ; cell 176 x,y (0,11) sprite normal SS GUARD 
	db 0x13 ; SS GUARD
	dl 0x1DFF01 ; cell 177 x,y (1,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 178 x,y (2,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 179 x,y (3,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 180 x,y (4,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 181 x,y (5,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 182 x,y (6,11) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 183 x,y (7,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 184 x,y (8,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x331043 ; cell 185 x,y (9,11) sprite normal GERMAN TROOPER 
	db 0x14 ; GERMAN TROOPER
	dl 0x1DFF01 ; cell 186 x,y (10,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 187 x,y (11,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 188 x,y (12,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 189 x,y (13,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 190 x,y (14,11) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 191 x,y (15,11) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 192 x,y (0,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 193 x,y (1,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 194 x,y (2,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 195 x,y (3,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 196 x,y (4,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 197 x,y (5,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x390890 ; cell 198 x,y (6,12) cube normal REGULAR DOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 199 x,y (7,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 200 x,y (8,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0303 ; cell 201 x,y (9,12) sprite normal OVERHEAD LIGHT 
	db 0x15 ; OVERHEAD LIGHT
	dl 0x160243 ; cell 202 x,y (10,12) sprite normal TABLE 
	db 0x16 ; TABLE
	dl 0x1D0803 ; cell 203 x,y (11,12) sprite normal PLATE OF FOOD 
	db 0x17 ; PLATE OF FOOD
	dl 0x1DFF01 ; cell 204 x,y (12,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 205 x,y (13,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 206 x,y (14,12) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 207 x,y (15,12) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 208 x,y (0,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 209 x,y (1,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 210 x,y (2,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 211 x,y (3,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 212 x,y (4,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 213 x,y (5,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x110750 ; cell 214 x,y (6,13) cube normal BLUE WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 215 x,y (7,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 216 x,y (8,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 217 x,y (9,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 218 x,y (10,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 219 x,y (11,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 220 x,y (12,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 221 x,y (13,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 222 x,y (14,13) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 223 x,y (15,13) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1D0503 ; cell 224 x,y (0,14) sprite normal HEALTH PACK 
	db 0x18 ; HEALTH PACK
	dl 0x1DFF01 ; cell 225 x,y (1,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 226 x,y (2,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 227 x,y (3,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 228 x,y (4,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 229 x,y (5,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 230 x,y (6,14) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 231 x,y (7,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 232 x,y (8,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 233 x,y (9,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 234 x,y (10,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 235 x,y (11,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 236 x,y (12,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1DFF01 ; cell 237 x,y (13,14) floor normal GREY FLOOR 
	db 0xFF ; no sprite
	dl 0x1D0903 ; cell 238 x,y (14,14) sprite normal KEYCARD 
	db 0x19 ; KEYCARD
	dl 0x0A0050 ; cell 239 x,y (15,14) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 240 x,y (0,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 241 x,y (1,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 242 x,y (2,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 243 x,y (3,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 244 x,y (4,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 245 x,y (5,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 246 x,y (6,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 247 x,y (7,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 248 x,y (8,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 249 x,y (9,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 250 x,y (10,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 251 x,y (11,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 252 x,y (12,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 253 x,y (13,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 254 x,y (14,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite
	dl 0x0A0050 ; cell 255 x,y (15,15) cube outer LIGHT GREY WALL 
	db 0xFF ; no sprite

	.org 0xB7E400 ; cell_status + 256*4

; mind the little-endianess in the bit order here!
cell_views:
	dl 0x000000,0x000000 ; Cell 0, Orientation 0
	dl 0x000000,0x000000 ; Cell 0, Orientation 1
	dl 0x000000,0x000000 ; Cell 0, Orientation 2
	dl 0x000000,0x000000 ; Cell 0, Orientation 3
	dl 0x000000,0x800000 ; Cell 1, Orientation 0
	dl 0x848380,0xB8B923 ; Cell 1, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 1, Orientation 2
	dl 0x000000,0x800000 ; Cell 1, Orientation 3
	dl 0x000000,0x800000 ; Cell 2, Orientation 0
	dl 0x800000,0xB8B923 ; Cell 2, Orientation 1
	dl 0x000000,0x9E1E00 ; Cell 2, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 2, Orientation 3
	dl 0x000000,0x800000 ; Cell 3, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 3, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 3, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 3, Orientation 3
	dl 0x000000,0x800000 ; Cell 4, Orientation 0
	dl 0x000000,0xB80000 ; Cell 4, Orientation 1
	dl 0x000000,0x9C7C00 ; Cell 4, Orientation 2
	dl 0xE00000,0xCD0E48 ; Cell 4, Orientation 3
	dl 0x000000,0x800000 ; Cell 5, Orientation 0
	dl 0x000000,0x800000 ; Cell 5, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 5, Orientation 2
	dl 0xE120E0,0xCD0E48 ; Cell 5, Orientation 3
	dl 0x000000,0x000000 ; Cell 6, Orientation 0
	dl 0x000000,0x000000 ; Cell 6, Orientation 1
	dl 0x000000,0x000000 ; Cell 6, Orientation 2
	dl 0x000000,0x000000 ; Cell 6, Orientation 3
	dl 0x000000,0x800000 ; Cell 7, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 7, Orientation 1
	dl 0xE120E0,0xCD0E48 ; Cell 7, Orientation 2
	dl 0x000000,0x800000 ; Cell 7, Orientation 3
	dl 0x000000,0x800000 ; Cell 8, Orientation 0
	dl 0x000000,0xB80000 ; Cell 8, Orientation 1
	dl 0xC241C0,0x9E5C91 ; Cell 8, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 8, Orientation 3
	dl 0x000000,0x800000 ; Cell 9, Orientation 0
	dl 0x000000,0x800000 ; Cell 9, Orientation 1
	dl 0x848380,0xB8B923 ; Cell 9, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 9, Orientation 3
	dl 0x000000,0x000000 ; Cell 10, Orientation 0
	dl 0x000000,0x000000 ; Cell 10, Orientation 1
	dl 0x000000,0x000000 ; Cell 10, Orientation 2
	dl 0x000000,0x000000 ; Cell 10, Orientation 3
	dl 0x000000,0x000000 ; Cell 11, Orientation 0
	dl 0x000000,0x000000 ; Cell 11, Orientation 1
	dl 0x000000,0x000000 ; Cell 11, Orientation 2
	dl 0x000000,0x000000 ; Cell 11, Orientation 3
	dl 0x000000,0x800000 ; Cell 12, Orientation 0
	dl 0x000000,0x800000 ; Cell 12, Orientation 1
	dl 0xE221E0,0x9E1E89 ; Cell 12, Orientation 2
	dl 0x000000,0x800000 ; Cell 12, Orientation 3
	dl 0x000000,0x000000 ; Cell 13, Orientation 0
	dl 0x000000,0x000000 ; Cell 13, Orientation 1
	dl 0x000000,0x000000 ; Cell 13, Orientation 2
	dl 0x000000,0x000000 ; Cell 13, Orientation 3
	dl 0x000000,0x000000 ; Cell 14, Orientation 0
	dl 0x000000,0x000000 ; Cell 14, Orientation 1
	dl 0x000000,0x000000 ; Cell 14, Orientation 2
	dl 0x000000,0x000000 ; Cell 14, Orientation 3
	dl 0x000000,0x000000 ; Cell 15, Orientation 0
	dl 0x000000,0x000000 ; Cell 15, Orientation 1
	dl 0x000000,0x000000 ; Cell 15, Orientation 2
	dl 0x000000,0x000000 ; Cell 15, Orientation 3
	dl 0x000000,0x800000 ; Cell 16, Orientation 0
	dl 0xC241C0,0x9E5C91 ; Cell 16, Orientation 1
	dl 0x000000,0x800000 ; Cell 16, Orientation 2
	dl 0x000000,0x800000 ; Cell 16, Orientation 3
	dl 0x000000,0xB80000 ; Cell 17, Orientation 0
	dl 0xC241C0,0x9E5C91 ; Cell 17, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 17, Orientation 2
	dl 0x000000,0x800000 ; Cell 17, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 18, Orientation 0
	dl 0xC00000,0x9E5C91 ; Cell 18, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 18, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 18, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 19, Orientation 0
	dl 0x000000,0x9E5C00 ; Cell 19, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 19, Orientation 2
	dl 0x000000,0x9E5C00 ; Cell 19, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 20, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 20, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 20, Orientation 2
	dl 0xC00000,0x9E5C91 ; Cell 20, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 21, Orientation 0
	dl 0x000000,0x800000 ; Cell 21, Orientation 1
	dl 0x000000,0xB80000 ; Cell 21, Orientation 2
	dl 0xC241C0,0x9E5C91 ; Cell 21, Orientation 3
	dl 0x000000,0x000000 ; Cell 22, Orientation 0
	dl 0x000000,0x000000 ; Cell 22, Orientation 1
	dl 0x000000,0x000000 ; Cell 22, Orientation 2
	dl 0x000000,0x000000 ; Cell 22, Orientation 3
	dl 0x000000,0xB80000 ; Cell 23, Orientation 0
	dl 0x000000,0x9C7C00 ; Cell 23, Orientation 1
	dl 0xE00000,0xCD0E48 ; Cell 23, Orientation 2
	dl 0x000000,0x800000 ; Cell 23, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 24, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 24, Orientation 1
	dl 0xC00000,0x9E5C91 ; Cell 24, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 24, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 25, Orientation 0
	dl 0x000000,0x800000 ; Cell 25, Orientation 1
	dl 0x800000,0xB8B923 ; Cell 25, Orientation 2
	dl 0x000000,0x9E1E00 ; Cell 25, Orientation 3
	dl 0x000000,0x000000 ; Cell 26, Orientation 0
	dl 0x000000,0x000000 ; Cell 26, Orientation 1
	dl 0x000000,0x000000 ; Cell 26, Orientation 2
	dl 0x000000,0x000000 ; Cell 26, Orientation 3
	dl 0x000000,0x800000 ; Cell 27, Orientation 0
	dl 0x800000,0xB8B827 ; Cell 27, Orientation 1
	dl 0xF110F2,0xCD0E40 ; Cell 27, Orientation 2
	dl 0x000000,0x800000 ; Cell 27, Orientation 3
	dl 0x000000,0x800000 ; Cell 28, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 28, Orientation 1
	dl 0xE221E0,0x9E1E89 ; Cell 28, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 28, Orientation 3
	dl 0x000000,0x800000 ; Cell 29, Orientation 0
	dl 0x000000,0xB80000 ; Cell 29, Orientation 1
	dl 0xC443C0,0x9C7D13 ; Cell 29, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 29, Orientation 3
	dl 0x000000,0x800000 ; Cell 30, Orientation 0
	dl 0x000000,0x800000 ; Cell 30, Orientation 1
	dl 0x888780,0xB8B827 ; Cell 30, Orientation 2
	dl 0xF00000,0xCD0E40 ; Cell 30, Orientation 3
	dl 0x000000,0x000000 ; Cell 31, Orientation 0
	dl 0x000000,0x000000 ; Cell 31, Orientation 1
	dl 0x000000,0x000000 ; Cell 31, Orientation 2
	dl 0x000000,0x000000 ; Cell 31, Orientation 3
	dl 0x000000,0x000000 ; Cell 32, Orientation 0
	dl 0x000000,0x000000 ; Cell 32, Orientation 1
	dl 0x000000,0x000000 ; Cell 32, Orientation 2
	dl 0x000000,0x000000 ; Cell 32, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 33, Orientation 0
	dl 0xE120E0,0xCD0E48 ; Cell 33, Orientation 1
	dl 0x000000,0x800000 ; Cell 33, Orientation 2
	dl 0x000000,0x800000 ; Cell 33, Orientation 3
	dl 0x000000,0x9C7C00 ; Cell 34, Orientation 0
	dl 0xE00000,0xCD0E48 ; Cell 34, Orientation 1
	dl 0x000000,0x800000 ; Cell 34, Orientation 2
	dl 0x000000,0xB80000 ; Cell 34, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 35, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 35, Orientation 1
	dl 0x000000,0x800000 ; Cell 35, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 35, Orientation 3
	dl 0x000000,0x9E1E00 ; Cell 36, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 36, Orientation 1
	dl 0x000000,0x800000 ; Cell 36, Orientation 2
	dl 0x800000,0xB8B923 ; Cell 36, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 37, Orientation 0
	dl 0x000000,0x800000 ; Cell 37, Orientation 1
	dl 0x000000,0x800000 ; Cell 37, Orientation 2
	dl 0x848380,0xB8B923 ; Cell 37, Orientation 3
	dl 0x000000,0x800000 ; Cell 38, Orientation 0
	dl 0xE00000,0x9C3F0B ; Cell 38, Orientation 1
	dl 0x000000,0x800000 ; Cell 38, Orientation 2
	dl 0x848380,0xB8B923 ; Cell 38, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 39, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 39, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 39, Orientation 2
	dl 0x000000,0x800000 ; Cell 39, Orientation 3
	dl 0x000000,0x9E5C00 ; Cell 40, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 40, Orientation 1
	dl 0x000000,0x9E5C00 ; Cell 40, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 40, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 41, Orientation 0
	dl 0x000000,0x800000 ; Cell 41, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 41, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 41, Orientation 3
	dl 0x000000,0x000000 ; Cell 42, Orientation 0
	dl 0x000000,0x000000 ; Cell 42, Orientation 1
	dl 0x000000,0x000000 ; Cell 42, Orientation 2
	dl 0x000000,0x000000 ; Cell 42, Orientation 3
	dl 0x000000,0xB80000 ; Cell 43, Orientation 0
	dl 0xC00000,0x9C7C17 ; Cell 43, Orientation 1
	dl 0xF110F2,0xCD0E40 ; Cell 43, Orientation 2
	dl 0x000000,0x800000 ; Cell 43, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 44, Orientation 0
	dl 0x000000,0x9C7C00 ; Cell 44, Orientation 1
	dl 0xE221E0,0x9E1E89 ; Cell 44, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 44, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 45, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 45, Orientation 1
	dl 0xC443C0,0x9C7D13 ; Cell 45, Orientation 2
	dl 0x000000,0x9E1E00 ; Cell 45, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 46, Orientation 0
	dl 0x000000,0x800000 ; Cell 46, Orientation 1
	dl 0x888780,0xB8B827 ; Cell 46, Orientation 2
	dl 0xF00000,0x9E1E81 ; Cell 46, Orientation 3
	dl 0x000000,0x000000 ; Cell 47, Orientation 0
	dl 0x000000,0x000000 ; Cell 47, Orientation 1
	dl 0x000000,0x000000 ; Cell 47, Orientation 2
	dl 0x000000,0x000000 ; Cell 47, Orientation 3
	dl 0x000000,0x000000 ; Cell 48, Orientation 0
	dl 0x000000,0x000000 ; Cell 48, Orientation 1
	dl 0x000000,0x000000 ; Cell 48, Orientation 2
	dl 0x000000,0x000000 ; Cell 48, Orientation 3
	dl 0x000000,0x000000 ; Cell 49, Orientation 0
	dl 0x000000,0x000000 ; Cell 49, Orientation 1
	dl 0x000000,0x000000 ; Cell 49, Orientation 2
	dl 0x000000,0x000000 ; Cell 49, Orientation 3
	dl 0x000000,0x000000 ; Cell 50, Orientation 0
	dl 0x000000,0x000000 ; Cell 50, Orientation 1
	dl 0x000000,0x000000 ; Cell 50, Orientation 2
	dl 0x000000,0x000000 ; Cell 50, Orientation 3
	dl 0x000000,0x000000 ; Cell 51, Orientation 0
	dl 0x000000,0x000000 ; Cell 51, Orientation 1
	dl 0x000000,0x000000 ; Cell 51, Orientation 2
	dl 0x000000,0x000000 ; Cell 51, Orientation 3
	dl 0x000000,0x000000 ; Cell 52, Orientation 0
	dl 0x000000,0x000000 ; Cell 52, Orientation 1
	dl 0x000000,0x000000 ; Cell 52, Orientation 2
	dl 0x000000,0x000000 ; Cell 52, Orientation 3
	dl 0x000000,0x000000 ; Cell 53, Orientation 0
	dl 0x000000,0x000000 ; Cell 53, Orientation 1
	dl 0x000000,0x000000 ; Cell 53, Orientation 2
	dl 0x000000,0x000000 ; Cell 53, Orientation 3
	dl 0x000000,0x000000 ; Cell 54, Orientation 0
	dl 0x000000,0x000000 ; Cell 54, Orientation 1
	dl 0x000000,0x000000 ; Cell 54, Orientation 2
	dl 0x000000,0x000000 ; Cell 54, Orientation 3
	dl 0x800000,0xB8B923 ; Cell 55, Orientation 0
	dl 0x000000,0x9E1E00 ; Cell 55, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 55, Orientation 2
	dl 0x000000,0x800000 ; Cell 55, Orientation 3
	dl 0xC00000,0x9E5C91 ; Cell 56, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 56, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 56, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 56, Orientation 3
	dl 0xE00000,0xCD0E48 ; Cell 57, Orientation 0
	dl 0x000000,0x800000 ; Cell 57, Orientation 1
	dl 0x000000,0xB80000 ; Cell 57, Orientation 2
	dl 0x000000,0x9C7C00 ; Cell 57, Orientation 3
	dl 0x000000,0x000000 ; Cell 58, Orientation 0
	dl 0x000000,0x000000 ; Cell 58, Orientation 1
	dl 0x000000,0x000000 ; Cell 58, Orientation 2
	dl 0x000000,0x000000 ; Cell 58, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 59, Orientation 0
	dl 0xE00000,0x9C3E0F ; Cell 59, Orientation 1
	dl 0xF110F2,0xCD0E40 ; Cell 59, Orientation 2
	dl 0x000000,0x800000 ; Cell 59, Orientation 3
	dl 0x000000,0x9C7C00 ; Cell 60, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 60, Orientation 1
	dl 0xE221E0,0x9E1E89 ; Cell 60, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 60, Orientation 3
	dl 0x000000,0x9E1E00 ; Cell 61, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 61, Orientation 1
	dl 0xC443C0,0x9C7D13 ; Cell 61, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 61, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 62, Orientation 0
	dl 0x000000,0x800000 ; Cell 62, Orientation 1
	dl 0x888780,0xB8B827 ; Cell 62, Orientation 2
	dl 0xF00000,0x9C3F03 ; Cell 62, Orientation 3
	dl 0x000000,0x000000 ; Cell 63, Orientation 0
	dl 0x000000,0x000000 ; Cell 63, Orientation 1
	dl 0x000000,0x000000 ; Cell 63, Orientation 2
	dl 0x000000,0x000000 ; Cell 63, Orientation 3
	dl 0x000000,0x000000 ; Cell 64, Orientation 0
	dl 0x000000,0x000000 ; Cell 64, Orientation 1
	dl 0x000000,0x000000 ; Cell 64, Orientation 2
	dl 0x000000,0x000000 ; Cell 64, Orientation 3
	dl 0x000000,0x800000 ; Cell 65, Orientation 0
	dl 0x808F80,0xB8B827 ; Cell 65, Orientation 1
	dl 0xF100F8,0xCD0E40 ; Cell 65, Orientation 2
	dl 0x000000,0x800000 ; Cell 65, Orientation 3
	dl 0x000000,0x800000 ; Cell 66, Orientation 0
	dl 0x800000,0xB8B827 ; Cell 66, Orientation 1
	dl 0xF211F0,0x9E1E81 ; Cell 66, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 66, Orientation 3
	dl 0x000000,0x800000 ; Cell 67, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 67, Orientation 1
	dl 0xE423E0,0x9C3F0B ; Cell 67, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 67, Orientation 3
	dl 0x000000,0x800000 ; Cell 68, Orientation 0
	dl 0x000000,0xB80000 ; Cell 68, Orientation 1
	dl 0xC847C0,0x9C7C17 ; Cell 68, Orientation 2
	dl 0xF00000,0xCD0E40 ; Cell 68, Orientation 3
	dl 0x000000,0x800000 ; Cell 69, Orientation 0
	dl 0x000000,0x800000 ; Cell 69, Orientation 1
	dl 0x808F80,0xB8B827 ; Cell 69, Orientation 2
	dl 0xF100F8,0xCD0E40 ; Cell 69, Orientation 3
	dl 0x000000,0x000000 ; Cell 70, Orientation 0
	dl 0x000000,0x000000 ; Cell 70, Orientation 1
	dl 0x000000,0x000000 ; Cell 70, Orientation 2
	dl 0x000000,0x000000 ; Cell 70, Orientation 3
	dl 0x848380,0xB8B923 ; Cell 71, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 71, Orientation 1
	dl 0x000000,0x800000 ; Cell 71, Orientation 2
	dl 0x000000,0x800000 ; Cell 71, Orientation 3
	dl 0xC241C0,0x9E5C91 ; Cell 72, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 72, Orientation 1
	dl 0x000000,0x800000 ; Cell 72, Orientation 2
	dl 0x000000,0xB80000 ; Cell 72, Orientation 3
	dl 0xE120E0,0xCD0E48 ; Cell 73, Orientation 0
	dl 0x000000,0x800000 ; Cell 73, Orientation 1
	dl 0x000000,0x800000 ; Cell 73, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 73, Orientation 3
	dl 0x000000,0x000000 ; Cell 74, Orientation 0
	dl 0x000000,0x000000 ; Cell 74, Orientation 1
	dl 0x000000,0x000000 ; Cell 74, Orientation 2
	dl 0x000000,0x000000 ; Cell 74, Orientation 3
	dl 0x800000,0xB8B827 ; Cell 75, Orientation 0
	dl 0xF00000,0x9C3E07 ; Cell 75, Orientation 1
	dl 0xF110F0,0xCD0E40 ; Cell 75, Orientation 2
	dl 0x000000,0x800000 ; Cell 75, Orientation 3
	dl 0xC00000,0x9C7D13 ; Cell 76, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 76, Orientation 1
	dl 0xE221E0,0x9E1E89 ; Cell 76, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 76, Orientation 3
	dl 0xE00000,0x9E1E89 ; Cell 77, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 77, Orientation 1
	dl 0xC443C0,0x9C7D13 ; Cell 77, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 77, Orientation 3
	dl 0xF00000,0xCD0E40 ; Cell 78, Orientation 0
	dl 0x000000,0x800000 ; Cell 78, Orientation 1
	dl 0x888780,0xB8B827 ; Cell 78, Orientation 2
	dl 0xF00000,0x9C3E07 ; Cell 78, Orientation 3
	dl 0x000000,0x000000 ; Cell 79, Orientation 0
	dl 0x000000,0x000000 ; Cell 79, Orientation 1
	dl 0x000000,0x000000 ; Cell 79, Orientation 2
	dl 0x000000,0x000000 ; Cell 79, Orientation 3
	dl 0x000000,0x000000 ; Cell 80, Orientation 0
	dl 0x000000,0x000000 ; Cell 80, Orientation 1
	dl 0x000000,0x000000 ; Cell 80, Orientation 2
	dl 0x000000,0x000000 ; Cell 80, Orientation 3
	dl 0x000000,0xB80000 ; Cell 81, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 81, Orientation 1
	dl 0xF00000,0xCD0E40 ; Cell 81, Orientation 2
	dl 0x000000,0x800000 ; Cell 81, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 82, Orientation 0
	dl 0xC00000,0x9C7C17 ; Cell 82, Orientation 1
	dl 0xF00000,0x9E1E81 ; Cell 82, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 82, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 83, Orientation 0
	dl 0x000000,0x9C7C00 ; Cell 83, Orientation 1
	dl 0xE00000,0x9C3F0B ; Cell 83, Orientation 2
	dl 0x000000,0x9E1E00 ; Cell 83, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 84, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 84, Orientation 1
	dl 0xC00000,0x9C7C17 ; Cell 84, Orientation 2
	dl 0xF00000,0x9E1E81 ; Cell 84, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 85, Orientation 0
	dl 0x000000,0x800000 ; Cell 85, Orientation 1
	dl 0x800000,0xB8B827 ; Cell 85, Orientation 2
	dl 0xF211F0,0x9E1E81 ; Cell 85, Orientation 3
	dl 0x000000,0x000000 ; Cell 86, Orientation 0
	dl 0x000000,0x000000 ; Cell 86, Orientation 1
	dl 0x000000,0x000000 ; Cell 86, Orientation 2
	dl 0x000000,0x000000 ; Cell 86, Orientation 3
	dl 0x000000,0x000000 ; Cell 87, Orientation 0
	dl 0x000000,0x000000 ; Cell 87, Orientation 1
	dl 0x000000,0x000000 ; Cell 87, Orientation 2
	dl 0x000000,0x000000 ; Cell 87, Orientation 3
	dl 0xC241C0,0x9E5C91 ; Cell 88, Orientation 0
	dl 0x000000,0x800000 ; Cell 88, Orientation 1
	dl 0xC00000,0x9E5C91 ; Cell 88, Orientation 2
	dl 0x000000,0x800000 ; Cell 88, Orientation 3
	dl 0x000000,0x000000 ; Cell 89, Orientation 0
	dl 0x000000,0x000000 ; Cell 89, Orientation 1
	dl 0x000000,0x000000 ; Cell 89, Orientation 2
	dl 0x000000,0x000000 ; Cell 89, Orientation 3
	dl 0x000000,0x000000 ; Cell 90, Orientation 0
	dl 0x000000,0x000000 ; Cell 90, Orientation 1
	dl 0x000000,0x000000 ; Cell 90, Orientation 2
	dl 0x000000,0x000000 ; Cell 90, Orientation 3
	dl 0x888780,0xB8B827 ; Cell 91, Orientation 0
	dl 0xF00000,0x9C3E07 ; Cell 91, Orientation 1
	dl 0xF00000,0xCD0E40 ; Cell 91, Orientation 2
	dl 0x000000,0x800000 ; Cell 91, Orientation 3
	dl 0xC443C0,0x9C7D13 ; Cell 92, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 92, Orientation 1
	dl 0xE00000,0x9E1E89 ; Cell 92, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 92, Orientation 3
	dl 0xE221E0,0x9E1E89 ; Cell 93, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 93, Orientation 1
	dl 0xC00000,0x9C7D13 ; Cell 93, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 93, Orientation 3
	dl 0xF110F0,0xCD0E40 ; Cell 94, Orientation 0
	dl 0x000000,0x800000 ; Cell 94, Orientation 1
	dl 0x800000,0xB8B827 ; Cell 94, Orientation 2
	dl 0xF00000,0x9C3E07 ; Cell 94, Orientation 3
	dl 0x000000,0x000000 ; Cell 95, Orientation 0
	dl 0x000000,0x000000 ; Cell 95, Orientation 1
	dl 0x000000,0x000000 ; Cell 95, Orientation 2
	dl 0x000000,0x000000 ; Cell 95, Orientation 3
	dl 0x000000,0x000000 ; Cell 96, Orientation 0
	dl 0x000000,0x000000 ; Cell 96, Orientation 1
	dl 0x000000,0x000000 ; Cell 96, Orientation 2
	dl 0x000000,0x000000 ; Cell 96, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 97, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 97, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 97, Orientation 2
	dl 0x000000,0x800000 ; Cell 97, Orientation 3
	dl 0x000000,0x9C7C00 ; Cell 98, Orientation 0
	dl 0xE00000,0x9C3F0B ; Cell 98, Orientation 1
	dl 0x000000,0x9E1E00 ; Cell 98, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 98, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 99, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 99, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 99, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 99, Orientation 3
	dl 0x000000,0x9E1E00 ; Cell 100, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 100, Orientation 1
	dl 0x000000,0x9C7C00 ; Cell 100, Orientation 2
	dl 0xE00000,0x9C3F0B ; Cell 100, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 101, Orientation 0
	dl 0x000000,0x800000 ; Cell 101, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 101, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 101, Orientation 3
	dl 0x000000,0x000000 ; Cell 102, Orientation 0
	dl 0x000000,0x000000 ; Cell 102, Orientation 1
	dl 0x000000,0x000000 ; Cell 102, Orientation 2
	dl 0x000000,0x000000 ; Cell 102, Orientation 3
	dl 0x000000,0x800000 ; Cell 103, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 103, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 103, Orientation 2
	dl 0x000000,0x800000 ; Cell 103, Orientation 3
	dl 0x000000,0x800000 ; Cell 104, Orientation 0
	dl 0x000000,0xB80000 ; Cell 104, Orientation 1
	dl 0x000000,0x9E5C00 ; Cell 104, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 104, Orientation 3
	dl 0x000000,0x800000 ; Cell 105, Orientation 0
	dl 0x000000,0x800000 ; Cell 105, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 105, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 105, Orientation 3
	dl 0x000000,0x000000 ; Cell 106, Orientation 0
	dl 0x000000,0x000000 ; Cell 106, Orientation 1
	dl 0x000000,0x000000 ; Cell 106, Orientation 2
	dl 0x000000,0x000000 ; Cell 106, Orientation 3
	dl 0x888780,0xB8B827 ; Cell 107, Orientation 0
	dl 0xF00000,0x9C3F03 ; Cell 107, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 107, Orientation 2
	dl 0x000000,0x800000 ; Cell 107, Orientation 3
	dl 0xC443C0,0x9C7D13 ; Cell 108, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 108, Orientation 1
	dl 0x000000,0x9E1E00 ; Cell 108, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 108, Orientation 3
	dl 0xE221E0,0x9E1E89 ; Cell 109, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 109, Orientation 1
	dl 0x000000,0x9C7C00 ; Cell 109, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 109, Orientation 3
	dl 0xF110F2,0xCD0E40 ; Cell 110, Orientation 0
	dl 0x000000,0x800000 ; Cell 110, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 110, Orientation 2
	dl 0xE00000,0x9C3E0F ; Cell 110, Orientation 3
	dl 0x000000,0x000000 ; Cell 111, Orientation 0
	dl 0x000000,0x000000 ; Cell 111, Orientation 1
	dl 0x000000,0x000000 ; Cell 111, Orientation 2
	dl 0x000000,0x000000 ; Cell 111, Orientation 3
	dl 0x000000,0x000000 ; Cell 112, Orientation 0
	dl 0x000000,0x000000 ; Cell 112, Orientation 1
	dl 0x000000,0x000000 ; Cell 112, Orientation 2
	dl 0x000000,0x000000 ; Cell 112, Orientation 3
	dl 0x800000,0xB8B827 ; Cell 113, Orientation 0
	dl 0xF211F0,0x9E1E81 ; Cell 113, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 113, Orientation 2
	dl 0x000000,0x800000 ; Cell 113, Orientation 3
	dl 0xC00000,0x9C7C17 ; Cell 114, Orientation 0
	dl 0xF00000,0x9E1E81 ; Cell 114, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 114, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 114, Orientation 3
	dl 0xE00000,0x9C3F0B ; Cell 115, Orientation 0
	dl 0x000000,0x9E1E00 ; Cell 115, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 115, Orientation 2
	dl 0x000000,0x9C7C00 ; Cell 115, Orientation 3
	dl 0xF00000,0x9E1E81 ; Cell 116, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 116, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 116, Orientation 2
	dl 0xC00000,0x9C7C17 ; Cell 116, Orientation 3
	dl 0xF00000,0xCD0E40 ; Cell 117, Orientation 0
	dl 0x000000,0x800000 ; Cell 117, Orientation 1
	dl 0x000000,0xB80000 ; Cell 117, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 117, Orientation 3
	dl 0x000000,0x800000 ; Cell 118, Orientation 0
	dl 0xC00000,0x9E5C91 ; Cell 118, Orientation 1
	dl 0x000000,0x800000 ; Cell 118, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 118, Orientation 3
	dl 0x000000,0xB80000 ; Cell 119, Orientation 0
	dl 0x000000,0x9E5C00 ; Cell 119, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 119, Orientation 2
	dl 0x000000,0x800000 ; Cell 119, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 120, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 120, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 120, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 120, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 121, Orientation 0
	dl 0x000000,0x800000 ; Cell 121, Orientation 1
	dl 0x000000,0xB80000 ; Cell 121, Orientation 2
	dl 0x000000,0x9E5C00 ; Cell 121, Orientation 3
	dl 0x000000,0x000000 ; Cell 122, Orientation 0
	dl 0x000000,0x000000 ; Cell 122, Orientation 1
	dl 0x000000,0x000000 ; Cell 122, Orientation 2
	dl 0x000000,0x000000 ; Cell 122, Orientation 3
	dl 0x888780,0xB8B827 ; Cell 123, Orientation 0
	dl 0xF00000,0x9E1E81 ; Cell 123, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 123, Orientation 2
	dl 0x000000,0x800000 ; Cell 123, Orientation 3
	dl 0xC443C0,0x9C7D13 ; Cell 124, Orientation 0
	dl 0x000000,0x9E1E00 ; Cell 124, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 124, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 124, Orientation 3
	dl 0xE221E0,0x9E1E89 ; Cell 125, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 125, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 125, Orientation 2
	dl 0x000000,0x9C7C00 ; Cell 125, Orientation 3
	dl 0xF110F2,0xCD0E40 ; Cell 126, Orientation 0
	dl 0x000000,0x800000 ; Cell 126, Orientation 1
	dl 0x000000,0xB80000 ; Cell 126, Orientation 2
	dl 0xC00000,0x9C7C17 ; Cell 126, Orientation 3
	dl 0x000000,0x000000 ; Cell 127, Orientation 0
	dl 0x000000,0x000000 ; Cell 127, Orientation 1
	dl 0x000000,0x000000 ; Cell 127, Orientation 2
	dl 0x000000,0x000000 ; Cell 127, Orientation 3
	dl 0x000000,0x000000 ; Cell 128, Orientation 0
	dl 0x000000,0x000000 ; Cell 128, Orientation 1
	dl 0x000000,0x000000 ; Cell 128, Orientation 2
	dl 0x000000,0x000000 ; Cell 128, Orientation 3
	dl 0x808F80,0xB8B827 ; Cell 129, Orientation 0
	dl 0xF100F8,0xCD0E40 ; Cell 129, Orientation 1
	dl 0x000000,0x800000 ; Cell 129, Orientation 2
	dl 0x000000,0x800000 ; Cell 129, Orientation 3
	dl 0xC847C0,0x9C7C17 ; Cell 130, Orientation 0
	dl 0xF00000,0xCD0E40 ; Cell 130, Orientation 1
	dl 0x000000,0x800000 ; Cell 130, Orientation 2
	dl 0x000000,0xB80000 ; Cell 130, Orientation 3
	dl 0xE423E0,0x9C3F0B ; Cell 131, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 131, Orientation 1
	dl 0x000000,0x800000 ; Cell 131, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 131, Orientation 3
	dl 0xF211F0,0x9E1E81 ; Cell 132, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 132, Orientation 1
	dl 0x000000,0x800000 ; Cell 132, Orientation 2
	dl 0x800000,0xB8B827 ; Cell 132, Orientation 3
	dl 0xF100F8,0xCD0E40 ; Cell 133, Orientation 0
	dl 0x000000,0x800000 ; Cell 133, Orientation 1
	dl 0x000000,0x800000 ; Cell 133, Orientation 2
	dl 0x808F80,0xB8B827 ; Cell 133, Orientation 3
	dl 0x000000,0x000000 ; Cell 134, Orientation 0
	dl 0x000000,0x000000 ; Cell 134, Orientation 1
	dl 0x000000,0x000000 ; Cell 134, Orientation 2
	dl 0x000000,0x000000 ; Cell 134, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 135, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 135, Orientation 1
	dl 0x000000,0x800000 ; Cell 135, Orientation 2
	dl 0x000000,0x800000 ; Cell 135, Orientation 3
	dl 0x000000,0x9E5C00 ; Cell 136, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 136, Orientation 1
	dl 0x000000,0x800000 ; Cell 136, Orientation 2
	dl 0x000000,0xB80000 ; Cell 136, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 137, Orientation 0
	dl 0x000000,0x800000 ; Cell 137, Orientation 1
	dl 0x000000,0x800000 ; Cell 137, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 137, Orientation 3
	dl 0x000000,0x000000 ; Cell 138, Orientation 0
	dl 0x000000,0x000000 ; Cell 138, Orientation 1
	dl 0x000000,0x000000 ; Cell 138, Orientation 2
	dl 0x000000,0x000000 ; Cell 138, Orientation 3
	dl 0x888780,0xB8B827 ; Cell 139, Orientation 0
	dl 0xF00000,0xCD0E40 ; Cell 139, Orientation 1
	dl 0x000000,0x800000 ; Cell 139, Orientation 2
	dl 0x000000,0x800000 ; Cell 139, Orientation 3
	dl 0xC443C0,0x9C7D13 ; Cell 140, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 140, Orientation 1
	dl 0x000000,0x800000 ; Cell 140, Orientation 2
	dl 0x000000,0xB80000 ; Cell 140, Orientation 3
	dl 0xE221E0,0x9E1E89 ; Cell 141, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 141, Orientation 1
	dl 0x000000,0x800000 ; Cell 141, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 141, Orientation 3
	dl 0xF110F2,0xCD0E40 ; Cell 142, Orientation 0
	dl 0x000000,0x800000 ; Cell 142, Orientation 1
	dl 0x000000,0x800000 ; Cell 142, Orientation 2
	dl 0x800000,0xB8B827 ; Cell 142, Orientation 3
	dl 0x000000,0x000000 ; Cell 143, Orientation 0
	dl 0x000000,0x000000 ; Cell 143, Orientation 1
	dl 0x000000,0x000000 ; Cell 143, Orientation 2
	dl 0x000000,0x000000 ; Cell 143, Orientation 3
	dl 0x000000,0x000000 ; Cell 144, Orientation 0
	dl 0x000000,0x000000 ; Cell 144, Orientation 1
	dl 0x000000,0x000000 ; Cell 144, Orientation 2
	dl 0x000000,0x000000 ; Cell 144, Orientation 3
	dl 0x000000,0x000000 ; Cell 145, Orientation 0
	dl 0x000000,0x000000 ; Cell 145, Orientation 1
	dl 0x000000,0x000000 ; Cell 145, Orientation 2
	dl 0x000000,0x000000 ; Cell 145, Orientation 3
	dl 0x000000,0x000000 ; Cell 146, Orientation 0
	dl 0x000000,0x000000 ; Cell 146, Orientation 1
	dl 0x000000,0x000000 ; Cell 146, Orientation 2
	dl 0x000000,0x000000 ; Cell 146, Orientation 3
	dl 0xE423E0,0x9C3F0B ; Cell 147, Orientation 0
	dl 0x000000,0x800000 ; Cell 147, Orientation 1
	dl 0xE827E0,0x9C3E0F ; Cell 147, Orientation 2
	dl 0x000000,0x800000 ; Cell 147, Orientation 3
	dl 0x000000,0x000000 ; Cell 148, Orientation 0
	dl 0x000000,0x000000 ; Cell 148, Orientation 1
	dl 0x000000,0x000000 ; Cell 148, Orientation 2
	dl 0x000000,0x000000 ; Cell 148, Orientation 3
	dl 0x000000,0x000000 ; Cell 149, Orientation 0
	dl 0x000000,0x000000 ; Cell 149, Orientation 1
	dl 0x000000,0x000000 ; Cell 149, Orientation 2
	dl 0x000000,0x000000 ; Cell 149, Orientation 3
	dl 0x000000,0x000000 ; Cell 150, Orientation 0
	dl 0x000000,0x000000 ; Cell 150, Orientation 1
	dl 0x000000,0x000000 ; Cell 150, Orientation 2
	dl 0x000000,0x000000 ; Cell 150, Orientation 3
	dl 0x000000,0x000000 ; Cell 151, Orientation 0
	dl 0x000000,0x000000 ; Cell 151, Orientation 1
	dl 0x000000,0x000000 ; Cell 151, Orientation 2
	dl 0x000000,0x000000 ; Cell 151, Orientation 3
	dl 0x000000,0x000000 ; Cell 152, Orientation 0
	dl 0x000000,0x000000 ; Cell 152, Orientation 1
	dl 0x000000,0x000000 ; Cell 152, Orientation 2
	dl 0x000000,0x000000 ; Cell 152, Orientation 3
	dl 0x000000,0x000000 ; Cell 153, Orientation 0
	dl 0x000000,0x000000 ; Cell 153, Orientation 1
	dl 0x000000,0x000000 ; Cell 153, Orientation 2
	dl 0x000000,0x000000 ; Cell 153, Orientation 3
	dl 0x000000,0x000000 ; Cell 154, Orientation 0
	dl 0x000000,0x000000 ; Cell 154, Orientation 1
	dl 0x000000,0x000000 ; Cell 154, Orientation 2
	dl 0x000000,0x000000 ; Cell 154, Orientation 3
	dl 0x000000,0x000000 ; Cell 155, Orientation 0
	dl 0x000000,0x000000 ; Cell 155, Orientation 1
	dl 0x000000,0x000000 ; Cell 155, Orientation 2
	dl 0x000000,0x000000 ; Cell 155, Orientation 3
	dl 0xC443C0,0x9C7D13 ; Cell 156, Orientation 0
	dl 0x000000,0x800000 ; Cell 156, Orientation 1
	dl 0xE02FE0,0x9C3E0F ; Cell 156, Orientation 2
	dl 0x000000,0x800000 ; Cell 156, Orientation 3
	dl 0x000000,0x000000 ; Cell 157, Orientation 0
	dl 0x000000,0x000000 ; Cell 157, Orientation 1
	dl 0x000000,0x000000 ; Cell 157, Orientation 2
	dl 0x000000,0x000000 ; Cell 157, Orientation 3
	dl 0x000000,0x000000 ; Cell 158, Orientation 0
	dl 0x000000,0x000000 ; Cell 158, Orientation 1
	dl 0x000000,0x000000 ; Cell 158, Orientation 2
	dl 0x000000,0x000000 ; Cell 158, Orientation 3
	dl 0x000000,0x000000 ; Cell 159, Orientation 0
	dl 0x000000,0x000000 ; Cell 159, Orientation 1
	dl 0x000000,0x000000 ; Cell 159, Orientation 2
	dl 0x000000,0x000000 ; Cell 159, Orientation 3
	dl 0x000000,0x800000 ; Cell 160, Orientation 0
	dl 0x808F84,0xB8B827 ; Cell 160, Orientation 1
	dl 0xF100F8,0xCD0E40 ; Cell 160, Orientation 2
	dl 0x000000,0x800000 ; Cell 160, Orientation 3
	dl 0x000000,0x800000 ; Cell 161, Orientation 0
	dl 0x808F80,0xB8B827 ; Cell 161, Orientation 1
	dl 0xF201F8,0x9E1E81 ; Cell 161, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 161, Orientation 3
	dl 0x000000,0x800000 ; Cell 162, Orientation 0
	dl 0x800000,0xB8B827 ; Cell 162, Orientation 1
	dl 0xF413F0,0x9C3F03 ; Cell 162, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 162, Orientation 3
	dl 0x000000,0x800000 ; Cell 163, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 163, Orientation 1
	dl 0xE827E0,0x9C3E0F ; Cell 163, Orientation 2
	dl 0xF00000,0xCD0E40 ; Cell 163, Orientation 3
	dl 0x000000,0x800000 ; Cell 164, Orientation 0
	dl 0x000000,0xB80000 ; Cell 164, Orientation 1
	dl 0xC04FC0,0x9C7C17 ; Cell 164, Orientation 2
	dl 0xF100F8,0xCD0E40 ; Cell 164, Orientation 3
	dl 0x000000,0x800000 ; Cell 165, Orientation 0
	dl 0x000000,0x800000 ; Cell 165, Orientation 1
	dl 0x808F80,0xB8B827 ; Cell 165, Orientation 2
	dl 0xF100F9,0xCD0E40 ; Cell 165, Orientation 3
	dl 0x000000,0x000000 ; Cell 166, Orientation 0
	dl 0x000000,0x000000 ; Cell 166, Orientation 1
	dl 0x000000,0x000000 ; Cell 166, Orientation 2
	dl 0x000000,0x000000 ; Cell 166, Orientation 3
	dl 0x000000,0x800000 ; Cell 167, Orientation 0
	dl 0x808F84,0xB8B827 ; Cell 167, Orientation 1
	dl 0xF100F8,0xCD0E40 ; Cell 167, Orientation 2
	dl 0x000000,0x800000 ; Cell 167, Orientation 3
	dl 0x000000,0x800000 ; Cell 168, Orientation 0
	dl 0x808F84,0xB8B827 ; Cell 168, Orientation 1
	dl 0xF201F8,0x9E1E81 ; Cell 168, Orientation 2
	dl 0x000000,0xCC0000 ; Cell 168, Orientation 3
	dl 0x000000,0x800000 ; Cell 169, Orientation 0
	dl 0x808F84,0xB8B827 ; Cell 169, Orientation 1
	dl 0xF403F8,0x9C3F03 ; Cell 169, Orientation 2
	dl 0x000000,0xCD0E00 ; Cell 169, Orientation 3
	dl 0x000000,0x800000 ; Cell 170, Orientation 0
	dl 0x808F80,0xB8B827 ; Cell 170, Orientation 1
	dl 0xF807F8,0x9C3E07 ; Cell 170, Orientation 2
	dl 0xF00000,0xCD0E40 ; Cell 170, Orientation 3
	dl 0x000000,0x800000 ; Cell 171, Orientation 0
	dl 0x800000,0xB8B827 ; Cell 171, Orientation 1
	dl 0xF01FF0,0x9C3E07 ; Cell 171, Orientation 2
	dl 0xF100F8,0xCD0E40 ; Cell 171, Orientation 3
	dl 0x000000,0x800000 ; Cell 172, Orientation 0
	dl 0x000000,0xB8B800 ; Cell 172, Orientation 1
	dl 0xE02FE0,0x9C3E0F ; Cell 172, Orientation 2
	dl 0xF100F9,0xCD0E40 ; Cell 172, Orientation 3
	dl 0x000000,0x800000 ; Cell 173, Orientation 0
	dl 0x000000,0xB80000 ; Cell 173, Orientation 1
	dl 0xC04FC0,0x9C7C17 ; Cell 173, Orientation 2
	dl 0xF100F9,0xCD0E40 ; Cell 173, Orientation 3
	dl 0x000000,0x800000 ; Cell 174, Orientation 0
	dl 0x000000,0x800000 ; Cell 174, Orientation 1
	dl 0x808F80,0xB8B827 ; Cell 174, Orientation 2
	dl 0xF100F9,0xCD0E40 ; Cell 174, Orientation 3
	dl 0x000000,0x000000 ; Cell 175, Orientation 0
	dl 0x000000,0x000000 ; Cell 175, Orientation 1
	dl 0x000000,0x000000 ; Cell 175, Orientation 2
	dl 0x000000,0x000000 ; Cell 175, Orientation 3
	dl 0x000000,0xB80000 ; Cell 176, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 176, Orientation 1
	dl 0xF00000,0xCD0E40 ; Cell 176, Orientation 2
	dl 0x000000,0x800000 ; Cell 176, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 177, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 177, Orientation 1
	dl 0xF00000,0x9E1E81 ; Cell 177, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 177, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 178, Orientation 0
	dl 0xC00000,0x9C7C17 ; Cell 178, Orientation 1
	dl 0xF00000,0x9C3F03 ; Cell 178, Orientation 2
	dl 0x000000,0x9E1E00 ; Cell 178, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 179, Orientation 0
	dl 0x000000,0x9C7C00 ; Cell 179, Orientation 1
	dl 0xE00000,0x9C3E0F ; Cell 179, Orientation 2
	dl 0xF00000,0x9E1E81 ; Cell 179, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 180, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 180, Orientation 1
	dl 0xC00000,0x9C7C17 ; Cell 180, Orientation 2
	dl 0xF211F0,0x9E1E81 ; Cell 180, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 181, Orientation 0
	dl 0x000000,0x800000 ; Cell 181, Orientation 1
	dl 0x800000,0xB8B827 ; Cell 181, Orientation 2
	dl 0xF211F2,0x9E1E81 ; Cell 181, Orientation 3
	dl 0x000000,0x000000 ; Cell 182, Orientation 0
	dl 0x000000,0x000000 ; Cell 182, Orientation 1
	dl 0x000000,0x000000 ; Cell 182, Orientation 2
	dl 0x000000,0x000000 ; Cell 182, Orientation 3
	dl 0x000000,0xB80000 ; Cell 183, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 183, Orientation 1
	dl 0xF00000,0xCD0E40 ; Cell 183, Orientation 2
	dl 0x000000,0x800000 ; Cell 183, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 184, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 184, Orientation 1
	dl 0xF00000,0x9E1E81 ; Cell 184, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 184, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 185, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 185, Orientation 1
	dl 0xF00000,0x9C3F03 ; Cell 185, Orientation 2
	dl 0x000000,0x9E1E00 ; Cell 185, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 186, Orientation 0
	dl 0xC847C0,0x9C7C17 ; Cell 186, Orientation 1
	dl 0xF00000,0x9C3E07 ; Cell 186, Orientation 2
	dl 0xF00000,0x9E1E81 ; Cell 186, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 187, Orientation 0
	dl 0xC00000,0x9C7C17 ; Cell 187, Orientation 1
	dl 0xF00000,0x9C3E07 ; Cell 187, Orientation 2
	dl 0xF211F0,0x9E1E81 ; Cell 187, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 188, Orientation 0
	dl 0x000000,0x9C7C00 ; Cell 188, Orientation 1
	dl 0xE00000,0x9C3E0F ; Cell 188, Orientation 2
	dl 0xF211F2,0x9E1E81 ; Cell 188, Orientation 3
	dl 0x000000,0x9C0000 ; Cell 189, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 189, Orientation 1
	dl 0xC00000,0x9C7C17 ; Cell 189, Orientation 2
	dl 0xF211F2,0x9E1E81 ; Cell 189, Orientation 3
	dl 0x000000,0xCC0000 ; Cell 190, Orientation 0
	dl 0x000000,0x800000 ; Cell 190, Orientation 1
	dl 0x800000,0xB8B827 ; Cell 190, Orientation 2
	dl 0xF211F2,0x9E1E81 ; Cell 190, Orientation 3
	dl 0x000000,0x000000 ; Cell 191, Orientation 0
	dl 0x000000,0x000000 ; Cell 191, Orientation 1
	dl 0x000000,0x000000 ; Cell 191, Orientation 2
	dl 0x000000,0x000000 ; Cell 191, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 192, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 192, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 192, Orientation 2
	dl 0x000000,0x800000 ; Cell 192, Orientation 3
	dl 0x000000,0x9C7C00 ; Cell 193, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 193, Orientation 1
	dl 0x000000,0x9E1E00 ; Cell 193, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 193, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 194, Orientation 0
	dl 0xE00000,0x9C3F0B ; Cell 194, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 194, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 194, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 195, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 195, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 195, Orientation 2
	dl 0xE00000,0x9C3F0B ; Cell 195, Orientation 3
	dl 0x000000,0x9E1E00 ; Cell 196, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 196, Orientation 1
	dl 0x000000,0x9C7C00 ; Cell 196, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 196, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 197, Orientation 0
	dl 0x000000,0x800000 ; Cell 197, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 197, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 197, Orientation 3
	dl 0x000000,0x800000 ; Cell 198, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 198, Orientation 1
	dl 0x000000,0x800000 ; Cell 198, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 198, Orientation 3
	dl 0x000000,0xB8B800 ; Cell 199, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 199, Orientation 1
	dl 0x000000,0xCD0E00 ; Cell 199, Orientation 2
	dl 0x000000,0x800000 ; Cell 199, Orientation 3
	dl 0x000000,0x9C7C00 ; Cell 200, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 200, Orientation 1
	dl 0x000000,0x9E1E00 ; Cell 200, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 200, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 201, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 201, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 201, Orientation 2
	dl 0x000000,0x9C3E00 ; Cell 201, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 202, Orientation 0
	dl 0xE423E0,0x9C3F0B ; Cell 202, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 202, Orientation 2
	dl 0xE00000,0x9C3F0B ; Cell 202, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 203, Orientation 0
	dl 0xE00000,0x9C3F0B ; Cell 203, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 203, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 203, Orientation 3
	dl 0x000000,0x9C3E00 ; Cell 204, Orientation 0
	dl 0x000000,0x9C3E00 ; Cell 204, Orientation 1
	dl 0x000000,0x9C3E00 ; Cell 204, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 204, Orientation 3
	dl 0x000000,0x9E1E00 ; Cell 205, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 205, Orientation 1
	dl 0x000000,0x9C7C00 ; Cell 205, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 205, Orientation 3
	dl 0x000000,0xCD0E00 ; Cell 206, Orientation 0
	dl 0x000000,0x800000 ; Cell 206, Orientation 1
	dl 0x000000,0xB8B800 ; Cell 206, Orientation 2
	dl 0xE423E0,0x9C3F0B ; Cell 206, Orientation 3
	dl 0x000000,0x000000 ; Cell 207, Orientation 0
	dl 0x000000,0x000000 ; Cell 207, Orientation 1
	dl 0x000000,0x000000 ; Cell 207, Orientation 2
	dl 0x000000,0x000000 ; Cell 207, Orientation 3
	dl 0x800000,0xB8B827 ; Cell 208, Orientation 0
	dl 0xF211F2,0x9E1E81 ; Cell 208, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 208, Orientation 2
	dl 0x000000,0x800000 ; Cell 208, Orientation 3
	dl 0xC00000,0x9C7C17 ; Cell 209, Orientation 0
	dl 0xF211F0,0x9E1E81 ; Cell 209, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 209, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 209, Orientation 3
	dl 0xE00000,0x9C3E0F ; Cell 210, Orientation 0
	dl 0xF00000,0x9E1E81 ; Cell 210, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 210, Orientation 2
	dl 0x000000,0x9C7C00 ; Cell 210, Orientation 3
	dl 0xF00000,0x9C3F03 ; Cell 211, Orientation 0
	dl 0x000000,0x9E1E00 ; Cell 211, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 211, Orientation 2
	dl 0xC00000,0x9C7C17 ; Cell 211, Orientation 3
	dl 0xF00000,0x9E1E81 ; Cell 212, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 212, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 212, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 212, Orientation 3
	dl 0xF00000,0xCD0E40 ; Cell 213, Orientation 0
	dl 0x000000,0x800000 ; Cell 213, Orientation 1
	dl 0x000000,0xB80000 ; Cell 213, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 213, Orientation 3
	dl 0x000000,0x000000 ; Cell 214, Orientation 0
	dl 0x000000,0x000000 ; Cell 214, Orientation 1
	dl 0x000000,0x000000 ; Cell 214, Orientation 2
	dl 0x000000,0x000000 ; Cell 214, Orientation 3
	dl 0x800000,0xB8B827 ; Cell 215, Orientation 0
	dl 0xF211F2,0x9E1E81 ; Cell 215, Orientation 1
	dl 0x000000,0xCC0000 ; Cell 215, Orientation 2
	dl 0x000000,0x800000 ; Cell 215, Orientation 3
	dl 0xC00000,0x9C7C17 ; Cell 216, Orientation 0
	dl 0xF211F2,0x9E1E81 ; Cell 216, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 216, Orientation 2
	dl 0x000000,0x9C0000 ; Cell 216, Orientation 3
	dl 0xE00000,0x9C3E0F ; Cell 217, Orientation 0
	dl 0xF211F2,0x9E1E81 ; Cell 217, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 217, Orientation 2
	dl 0x000000,0x9C7C00 ; Cell 217, Orientation 3
	dl 0xF00000,0x9C3E07 ; Cell 218, Orientation 0
	dl 0xF211F0,0x9E1E81 ; Cell 218, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 218, Orientation 2
	dl 0xC00000,0x9C7C17 ; Cell 218, Orientation 3
	dl 0xF00000,0x9C3E07 ; Cell 219, Orientation 0
	dl 0xF00000,0x9E1E81 ; Cell 219, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 219, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 219, Orientation 3
	dl 0xF00000,0x9C3F03 ; Cell 220, Orientation 0
	dl 0x000000,0x9E1E00 ; Cell 220, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 220, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 220, Orientation 3
	dl 0xF00000,0x9E1E81 ; Cell 221, Orientation 0
	dl 0x000000,0x9C0000 ; Cell 221, Orientation 1
	dl 0x000000,0x9C0000 ; Cell 221, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 221, Orientation 3
	dl 0xF00000,0xCD0E40 ; Cell 222, Orientation 0
	dl 0x000000,0x800000 ; Cell 222, Orientation 1
	dl 0x000000,0xB80000 ; Cell 222, Orientation 2
	dl 0xC847C0,0x9C7C17 ; Cell 222, Orientation 3
	dl 0x000000,0x000000 ; Cell 223, Orientation 0
	dl 0x000000,0x000000 ; Cell 223, Orientation 1
	dl 0x000000,0x000000 ; Cell 223, Orientation 2
	dl 0x000000,0x000000 ; Cell 223, Orientation 3
	dl 0x808F80,0xB8B827 ; Cell 224, Orientation 0
	dl 0xF100F9,0xCD0E40 ; Cell 224, Orientation 1
	dl 0x000000,0x800000 ; Cell 224, Orientation 2
	dl 0x000000,0x800000 ; Cell 224, Orientation 3
	dl 0xC04FC0,0x9C7C17 ; Cell 225, Orientation 0
	dl 0xF100F8,0xCD0E40 ; Cell 225, Orientation 1
	dl 0x000000,0x800000 ; Cell 225, Orientation 2
	dl 0x000000,0xB80000 ; Cell 225, Orientation 3
	dl 0xE827E0,0x9C3E0F ; Cell 226, Orientation 0
	dl 0xF00000,0xCD0E40 ; Cell 226, Orientation 1
	dl 0x000000,0x800000 ; Cell 226, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 226, Orientation 3
	dl 0xF413F0,0x9C3F03 ; Cell 227, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 227, Orientation 1
	dl 0x000000,0x800000 ; Cell 227, Orientation 2
	dl 0x800000,0xB8B827 ; Cell 227, Orientation 3
	dl 0xF201F8,0x9E1E81 ; Cell 228, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 228, Orientation 1
	dl 0x000000,0x800000 ; Cell 228, Orientation 2
	dl 0x808F80,0xB8B827 ; Cell 228, Orientation 3
	dl 0xF100F8,0xCD0E40 ; Cell 229, Orientation 0
	dl 0x000000,0x800000 ; Cell 229, Orientation 1
	dl 0x000000,0x800000 ; Cell 229, Orientation 2
	dl 0x808F84,0xB8B827 ; Cell 229, Orientation 3
	dl 0x000000,0x000000 ; Cell 230, Orientation 0
	dl 0x000000,0x000000 ; Cell 230, Orientation 1
	dl 0x000000,0x000000 ; Cell 230, Orientation 2
	dl 0x000000,0x000000 ; Cell 230, Orientation 3
	dl 0x808F80,0xB8B827 ; Cell 231, Orientation 0
	dl 0xF100F9,0xCD0E40 ; Cell 231, Orientation 1
	dl 0x000000,0x800000 ; Cell 231, Orientation 2
	dl 0x000000,0x800000 ; Cell 231, Orientation 3
	dl 0xC04FC0,0x9C7C17 ; Cell 232, Orientation 0
	dl 0xF100F9,0xCD0E40 ; Cell 232, Orientation 1
	dl 0x000000,0x800000 ; Cell 232, Orientation 2
	dl 0x000000,0xB80000 ; Cell 232, Orientation 3
	dl 0xE02FE0,0x9C3E0F ; Cell 233, Orientation 0
	dl 0xF100F9,0xCD0E40 ; Cell 233, Orientation 1
	dl 0x000000,0x800000 ; Cell 233, Orientation 2
	dl 0x000000,0xB8B800 ; Cell 233, Orientation 3
	dl 0xF01FF0,0x9C3E07 ; Cell 234, Orientation 0
	dl 0xF100F8,0xCD0E40 ; Cell 234, Orientation 1
	dl 0x000000,0x800000 ; Cell 234, Orientation 2
	dl 0x800000,0xB8B827 ; Cell 234, Orientation 3
	dl 0xF807F8,0x9C3E07 ; Cell 235, Orientation 0
	dl 0xF00000,0xCD0E40 ; Cell 235, Orientation 1
	dl 0x000000,0x800000 ; Cell 235, Orientation 2
	dl 0x808F80,0xB8B827 ; Cell 235, Orientation 3
	dl 0xF403F8,0x9C3F03 ; Cell 236, Orientation 0
	dl 0x000000,0xCD0E00 ; Cell 236, Orientation 1
	dl 0x000000,0x800000 ; Cell 236, Orientation 2
	dl 0x808F84,0xB8B827 ; Cell 236, Orientation 3
	dl 0xF201F8,0x9E1E81 ; Cell 237, Orientation 0
	dl 0x000000,0xCC0000 ; Cell 237, Orientation 1
	dl 0x000000,0x800000 ; Cell 237, Orientation 2
	dl 0x808F84,0xB8B827 ; Cell 237, Orientation 3
	dl 0xF100F8,0xCD0E40 ; Cell 238, Orientation 0
	dl 0x000000,0x800000 ; Cell 238, Orientation 1
	dl 0x000000,0x800000 ; Cell 238, Orientation 2
	dl 0x808F84,0xB8B827 ; Cell 238, Orientation 3
	dl 0x000000,0x000000 ; Cell 239, Orientation 0
	dl 0x000000,0x000000 ; Cell 239, Orientation 1
	dl 0x000000,0x000000 ; Cell 239, Orientation 2
	dl 0x000000,0x000000 ; Cell 239, Orientation 3
	dl 0x000000,0x000000 ; Cell 240, Orientation 0
	dl 0x000000,0x000000 ; Cell 240, Orientation 1
	dl 0x000000,0x000000 ; Cell 240, Orientation 2
	dl 0x000000,0x000000 ; Cell 240, Orientation 3
	dl 0x000000,0x000000 ; Cell 241, Orientation 0
	dl 0x000000,0x000000 ; Cell 241, Orientation 1
	dl 0x000000,0x000000 ; Cell 241, Orientation 2
	dl 0x000000,0x000000 ; Cell 241, Orientation 3
	dl 0x000000,0x000000 ; Cell 242, Orientation 0
	dl 0x000000,0x000000 ; Cell 242, Orientation 1
	dl 0x000000,0x000000 ; Cell 242, Orientation 2
	dl 0x000000,0x000000 ; Cell 242, Orientation 3
	dl 0x000000,0x000000 ; Cell 243, Orientation 0
	dl 0x000000,0x000000 ; Cell 243, Orientation 1
	dl 0x000000,0x000000 ; Cell 243, Orientation 2
	dl 0x000000,0x000000 ; Cell 243, Orientation 3
	dl 0x000000,0x000000 ; Cell 244, Orientation 0
	dl 0x000000,0x000000 ; Cell 244, Orientation 1
	dl 0x000000,0x000000 ; Cell 244, Orientation 2
	dl 0x000000,0x000000 ; Cell 244, Orientation 3
	dl 0x000000,0x000000 ; Cell 245, Orientation 0
	dl 0x000000,0x000000 ; Cell 245, Orientation 1
	dl 0x000000,0x000000 ; Cell 245, Orientation 2
	dl 0x000000,0x000000 ; Cell 245, Orientation 3
	dl 0x000000,0x000000 ; Cell 246, Orientation 0
	dl 0x000000,0x000000 ; Cell 246, Orientation 1
	dl 0x000000,0x000000 ; Cell 246, Orientation 2
	dl 0x000000,0x000000 ; Cell 246, Orientation 3
	dl 0x000000,0x000000 ; Cell 247, Orientation 0
	dl 0x000000,0x000000 ; Cell 247, Orientation 1
	dl 0x000000,0x000000 ; Cell 247, Orientation 2
	dl 0x000000,0x000000 ; Cell 247, Orientation 3
	dl 0x000000,0x000000 ; Cell 248, Orientation 0
	dl 0x000000,0x000000 ; Cell 248, Orientation 1
	dl 0x000000,0x000000 ; Cell 248, Orientation 2
	dl 0x000000,0x000000 ; Cell 248, Orientation 3
	dl 0x000000,0x000000 ; Cell 249, Orientation 0
	dl 0x000000,0x000000 ; Cell 249, Orientation 1
	dl 0x000000,0x000000 ; Cell 249, Orientation 2
	dl 0x000000,0x000000 ; Cell 249, Orientation 3
	dl 0x000000,0x000000 ; Cell 250, Orientation 0
	dl 0x000000,0x000000 ; Cell 250, Orientation 1
	dl 0x000000,0x000000 ; Cell 250, Orientation 2
	dl 0x000000,0x000000 ; Cell 250, Orientation 3
	dl 0x000000,0x000000 ; Cell 251, Orientation 0
	dl 0x000000,0x000000 ; Cell 251, Orientation 1
	dl 0x000000,0x000000 ; Cell 251, Orientation 2
	dl 0x000000,0x000000 ; Cell 251, Orientation 3
	dl 0x000000,0x000000 ; Cell 252, Orientation 0
	dl 0x000000,0x000000 ; Cell 252, Orientation 1
	dl 0x000000,0x000000 ; Cell 252, Orientation 2
	dl 0x000000,0x000000 ; Cell 252, Orientation 3
	dl 0x000000,0x000000 ; Cell 253, Orientation 0
	dl 0x000000,0x000000 ; Cell 253, Orientation 1
	dl 0x000000,0x000000 ; Cell 253, Orientation 2
	dl 0x000000,0x000000 ; Cell 253, Orientation 3
	dl 0x000000,0x000000 ; Cell 254, Orientation 0
	dl 0x000000,0x000000 ; Cell 254, Orientation 1
	dl 0x000000,0x000000 ; Cell 254, Orientation 2
	dl 0x000000,0x000000 ; Cell 254, Orientation 3
	dl 0x000000,0x000000 ; Cell 255, Orientation 0
	dl 0x000000,0x000000 ; Cell 255, Orientation 1
	dl 0x000000,0x000000 ; Cell 255, Orientation 2
	dl 0x000000,0x000000 ; Cell 255, Orientation 3

sprite_table_base: blkb 1024,255 ; so that sprite_id and sprite_obj default to no sprite
sprite_table_limit:
